BONNIE 1513
MeasureAuthoringTool/bonnie pull request #1004
Opened 2018-05-31 16:19 UTC by mayerm94

Add method and qdm_status to datatypes that required them, but did not have them
See model info file and QDM spec for proof that these attributes are required on the modified datatypes https://github.com/cqframework/clinical_quality_language/blob/master/Src/java/qdm/src/main/resources/gov/healthit/qdm/qdm-modelinfo-5.3.xml

Pull requests into Bonnie require the following. Submitter and reviewer should :white_check_mark: when done. For items that are not-applicable, note it's not-applicable ("N/A") and :white_check_mark:.

**Submitter:**
- [ ] This pull request describes why these changes were made.
- [ ] This PR is into the correct branch.
- [ ] JIRA ticket for this PR: https://jira.mitre.org/browse/BONNIE-1513
- [ ] JIRA ticket links to this PR
- [x] Code diff has been done and been reviewed (it **does not** contain: additional white space, not applicable code changes, debug statements, etc.)
- [x] If UI changes have been made, google WAVE plug-in has been executed to ensure no 508 issues were introduced. NA
- [ ] Tests are included and test edge cases NA
- [ ] Tests have been run locally and pass (remember to update Gemfile when applicable)
- [ ] Test fixtures updated and documented as necessary ( see [internal wiki](https://gitlab.mitre.org/bonnie/internal-documentation/wikis/testing#test-fixtures) )
- [ ] Code coverage has not gone down and all code touched or added is covered. 
     * In rare situations, this may not be possible or applicable to a PR. In those situations:
         1. Note why this could not be done or is not applicable here: 
         2. Add TODOs in the code noting that it requires a test
         3. Add a JIRA task to add the test and link it here: 

Branch | Back End Coverage | Front End Coverage
-- | -- | --
master | [Paste Output Here] | [Paste Screenshot Here]
[New Branch] | [Paste Output Here] | [Paste Screenshot Here]

- [ ] Automated regression test(s) pass

If JIRA tests were used to supplement or replace automated tests:
- [ ] JIRA test links:
- [ ] Justification for using JIRA tests:
- [ ] JIRA tests have been added to sprint

**Reviewer 1:**

Name:
- [ ] Code is maintainable and reusable, reuses existing code and infrastructure where appropriate, and accomplishes the task’s purpose
- [ ] The tests appropriately test the new code, including edge cases
- [ ] You have tried to break the code

If JIRA tests were used to supplement or replace automated tests:
- [ ] JIRA tests have been run and pass
- [ ] You agree with the justification for use of JIRA tests or have provided input on why you disagree

**Reviewer 2:**

Name:
- [ ] Code is maintainable and reusable, reuses existing code and infrastructure where appropriate, and accomplishes the task’s purpose
- [ ] The tests appropriately test the new code, including edge cases
- [ ] You have tried to break the code

If JIRA tests were used to supplement or replace automated tests:
- [ ] JIRA tests have been run and pass
- [ ] You agree with the justification for use of JIRA tests or have provided input on why you disagree

2018-06-01 22:34 UTC, c-monkey submitted a review, later dismissed
Codes appear as appropriate and this PR works with the other 2 Bonnie 1513 PRs (cql_qdm_patientapi and hds)

2018-06-05 11:24 UTC, hossenlopp requested changes

2018-06-05 11:24 UTC, hossenlopp commented on Gemfile
> +  gem 'health-data-standards', :git => 'https://github.com/projectcypress/health-data-standards.git', :branch => 'master_bonnie'
Should not have any spaces before `gem`.

2018-06-05 11:24 UTC, hossenlopp commented on Gemfile.lock
> +    uuid (2.3.9)
This shouldn't have been updated.

2018-06-05 11:50 UTC, mayerm94 commented on Gemfile
> +  gem 'health-data-standards', :git => 'https://github.com/projectcypress/health-data-standards.git', :branch => 'master_bonnie'
I know --intend on fixing when the cql_qdm_patientapi hash is updated once the 1513 PR is merged in that repo

2018-06-05 16:09 UTC, hossenlopp commented on Gemfile.lock
> +    uuid (2.3.8)
This line change should be reverted.

2018-06-06 13:59 UTC, hossenlopp submitted a review, later dismissed
JIRA test pass. Looks good.

2018-06-06 14:15 UTC, jbradl11 submitted a review, later dismissed
Looks good. Nice Jira Test!

2018-06-06 17:58 UTC, hossenlopp approved these changes

2018-06-06 18:00 UTC, jbradl11 approved these changes
Changes still look good.

2018-06-07 12:46 UTC, merged