Mat api cql
MeasureAuthoringTool/bonnie pull request #1012
Opened 2018-06-13 11:18 UTC by jbradl11

Pull requests into Bonnie require the following. Submitter and reviewer should :white_check_mark: when done. For items that are not-applicable, note it's not-applicable ("N/A") and :white_check_mark:.

Porting over QDM MAT API functionality into Bonnie v2.3 branch. The functionality includes, authentication, user information, and providing a dummy excel export document. 

**Submitter:**
- [x] This pull request describes why these changes were made.
- [x] This PR is into the correct branch.
- [x] JIRA ticket for this PR: https://jira.mitre.org/browse/BONNIE-1528
- [ ] JIRA ticket links to this PR
- [x] Code diff has been done and been reviewed (it **does not** contain: additional white space, not applicable code changes, debug statements, etc.)
- [x] If UI changes have been made, google WAVE plug-in has been executed to ensure no 508 issues were introduced.
- [x] Tests are included and test edge cases
- [x] Tests have been run locally and pass (remember to update Gemfile when applicable)
- [x] Test fixtures updated and documented as necessary ( see [internal wiki](https://gitlab.mitre.org/bonnie/internal-documentation/wikis/testing#test-fixtures) )
- [x] Code coverage has not gone down and all code touched or added is covered. 
     * In rare situations, this may not be possible or applicable to a PR. In those situations:
         1. Note why this could not be done or is not applicable here: A few of the added config files bring down this number below 89.13%. I am open to suggestions. 
         2. Add TODOs in the code noting that it requires a test
         3. Add a JIRA task to add the test and link it here:  No jira test would be valid for this situation.

Branch | Back End Coverage | Front End Coverage
-- | -- | --
bonnie-v2.3 |  1738 / 1950 LOC (89.13%) | ![image](https://user-images.githubusercontent.com/1568999/41348032-6dd3e84e-6ed9-11e8-8011-96922db516e2.png)
mat_api_cql | 1897 / 2153 LOC (88.11%) | ![image](https://user-images.githubusercontent.com/1568999/41347734-9783be0e-6ed8-11e8-9f60-a152e3a3aa08.png)

- [ ] Automated regression test(s) pass

If JIRA tests were used to supplement or replace automated tests:
- [x] JIRA test links: N/A
- [x] Justification for using JIRA tests: N/A
- [x] JIRA tests have been added to sprint: N/A

**Reviewer 1:**

Name:
- [ ] Code is maintainable and reusable, reuses existing code and infrastructure where appropriate, and accomplishes the task’s purpose
- [ ] The tests appropriately test the new code, including edge cases
- [ ] You have tried to break the code

If JIRA tests were used to supplement or replace automated tests:
- [ ] JIRA tests have been run and pass
- [ ] You agree with the justification for use of JIRA tests or have provided input on why you disagree

**Reviewer 2:**

Name:
- [ ] Code is maintainable and reusable, reuses existing code and infrastructure where appropriate, and accomplishes the task’s purpose
- [ ] The tests appropriately test the new code, including edge cases
- [ ] You have tried to break the code

If JIRA tests were used to supplement or replace automated tests:
- [ ] JIRA tests have been run and pass
- [ ] You agree with the justification for use of JIRA tests or have provided input on why you disagree

2018-06-14 14:34 UTC, hossenlopp requested changes
A few small changes suggested and comments. There was some code from the MAT API QDM branch that shouldn't be removed, just temporarily disabled/commented out. I hope those comments went through, because I put them on your clean up commits specifically.

2018-06-14 14:34 UTC, hossenlopp commented on app/controllers/api_v1/measures_controller.rb
> -  def_param_group :measure_upload do
This shouldn't be removed. It still is useful code for uploading measures which we still need. It does need to be updated for the VSAC profile/release options changes. Perhaps just comment this out for now until we have time to revisit measure uploads.

2018-06-14 14:34 UTC, hossenlopp commented on app/controllers/api_v1/measures_controller.rb
> -  def load_measure(params, is_update)
This is alright to be thrown out. We should re-write this for CQL measures or find a way to make it share code with the regular MeasuresController.

2018-06-14 14:34 UTC, hossenlopp commented on config/initializers/webmock.rb
> +if defined?(WebMock)
Hmm. I wonder if this is actually needed.

2018-06-14 14:34 UTC, hossenlopp commented on config/mongoid.yml
> +    raise_not_found_error: true
It still seems odd to me that this is needed...

2018-06-14 15:04 UTC, jbradl11 commented on app/controllers/api_v1/measures_controller.rb
> -  def_param_group :measure_upload do
I am alright with bringing this code back in. I mainly wanted to rip out all unused code, but I am comfortable including this and just commenting it out for now with a TODO.

2018-06-14 15:07 UTC, jbradl11 commented on config/mongoid.yml
> +    raise_not_found_error: true
Good catch. I believe it defaults to `true` even when this is removed. I will remove this.

2018-06-19 16:36 UTC, hossenlopp submitted a review, later dismissed

2018-06-19 17:04 UTC, mayerm94 submitted a review, later dismissed

2018-06-19 17:40 UTC, hossenlopp requested changes

2018-06-19 17:40 UTC, hossenlopp commented on config/initializers/doorkeeper.rb
> +  grant_flows %w([authorization_code])
This needs to be changed to:
```
 grant_flows %w(authorization_code)
```

2018-06-19 18:35 UTC, hossenlopp commented on app/controllers/api_v1/measures_controller.rb
> +      @api_v1_measures = CqlMeasure.by_user(current_resource_owner)
Suggest making the response here smaller by removing `skippable_fields` line and adding to this line to make it get only the fields in MEASURE_WHITELIST defined above in the file.
```
@api_v1_measures = CqlMeasure.by_user(current_resource_owner).only(MEASURE_WHITELIST)
```

2018-06-19 18:37 UTC, hossenlopp requested changes
Request making the index response simpler.

2018-06-19 18:37 UTC, hossenlopp commented on app/controllers/api_v1/measures_controller.rb
> +      @api_v1_measures = CqlMeasure.by_user(current_resource_owner)
Suggest making the response here smaller by removing `skippable_fields` line and adding to this line to make it get only the fields in MEASURE_WHITELIST defined above in the file.
```
@api_v1_measures = CqlMeasure.by_user(current_resource_owner).only(MEASURE_WHITELIST)
```

2018-06-19 18:37 UTC, hossenlopp commented on app/controllers/api_v1/measures_controller.rb
> +              skippable_fields.each { |f| h.delete(f) }
If using my suggestion above. Remove this line too. Also `.delete` may be destructive to the measure....

2018-06-22 16:44 UTC, hossenlopp commented
Give this the sprockets update and I'd say it is good to go. We can handle the application deletion issue later.

2018-06-22 16:51 UTC, hossenlopp approved these changes

2018-06-22 17:00 UTC, mayerm94 approved these changes
Tested all endpoints --they work. Looks good

2018-06-25 12:19 UTC, edeyoung commented
checks failing due to sprockets vulnerability. will be updating base branch at a later date. merging.

2018-06-25 12:20 UTC, edeyoung commented
@jbradl11 @hossenlopp  can the commit history be cleaned up? Not sure I want to squash merge everything, but there's a lot of extraneous commits.

2018-06-25 12:26 UTC, merged