Bonnie 1536
MeasureAuthoringTool/bonnie pull request #1015
Opened 2018-06-18 15:28 UTC by mayerm94

Adds cqm-converter into bonnie so HDS patients can be converted into QDM patients

Pull requests into Bonnie require the following. Submitter and reviewer should :white_check_mark: when done. For items that are not-applicable, note it's not-applicable ("N/A") and :white_check_mark:.

**Submitter:**
- [x] This pull request describes why these changes were made.
- [x] This PR is into the correct branch.
- [ ] JIRA ticket for this PR:
- [ ] JIRA ticket links to this PR
- [ ] Code diff has been done and been reviewed (it **does not** contain: additional white space, not applicable code changes, debug statements, etc.)
- [ ] If UI changes have been made, google WAVE plug-in has been executed to ensure no 508 issues were introduced.
- [ ] Tests are included and test edge cases
- [ ] Tests have been run locally and pass (remember to update Gemfile when applicable)
- [ ] Test fixtures updated and documented as necessary ( see [internal wiki](https://gitlab.mitre.org/bonnie/internal-documentation/wikis/testing#test-fixtures) )
- [ ] Code coverage has not gone down and all code touched or added is covered. 
     * In rare situations, this may not be possible or applicable to a PR. In those situations:
         1. Note why this could not be done or is not applicable here: 
         2. Add TODOs in the code noting that it requires a test
         3. Add a JIRA task to add the test and link it here: 

Branch | Back End Coverage | Front End Coverage
-- | -- | --
master | [Paste Output Here] | [Paste Screenshot Here]
[New Branch] | [Paste Output Here] | [Paste Screenshot Here]

- [ ] Automated regression test(s) pass

If JIRA tests were used to supplement or replace automated tests:
- [ ] JIRA test links:
- [ ] Justification for using JIRA tests:
- [ ] JIRA tests have been added to sprint

**Reviewer 1:**

Name:
- [ ] Code is maintainable and reusable, reuses existing code and infrastructure where appropriate, and accomplishes the task’s purpose
- [ ] The tests appropriately test the new code, including edge cases
- [ ] You have tried to break the code

If JIRA tests were used to supplement or replace automated tests:
- [ ] JIRA tests have been run and pass
- [ ] You agree with the justification for use of JIRA tests or have provided input on why you disagree

**Reviewer 2:**

Name:
- [ ] Code is maintainable and reusable, reuses existing code and infrastructure where appropriate, and accomplishes the task’s purpose
- [ ] The tests appropriately test the new code, including edge cases
- [ ] You have tried to break the code

If JIRA tests were used to supplement or replace automated tests:
- [ ] JIRA tests have been run and pass
- [ ] You agree with the justification for use of JIRA tests or have provided input on why you disagree

2018-06-18 15:37 UTC, holmesie requested changes

2018-06-18 15:37 UTC, holmesie commented on app/controllers/measures_controller.rb
> +  hds_record_converter = CQM::Converter::HDSRecord.new
This should be something like:
`@@hds_record_converter ||= CQM::Converter::HDSRecord.new`

2018-06-18 15:37 UTC, holmesie commented on config/initializers/cqm_converter.rb
> +::CQMConverter = CQM::Converter::HDSRecord.new
I'm seeing that you have two initialized converters; this one and the one in the measures controller. You probably only want one.

2018-06-18 15:49 UTC, mayerm94 commented on config/initializers/cqm_converter.rb
> +::CQMConverter = CQM::Converter::HDSRecord.new
The one in the measures controller was mistakenly committed, it has since been deleted

2018-06-18 19:17 UTC, holmesie requested changes

2018-06-18 19:17 UTC, holmesie commented on app/helpers/patient_helper.rb
> +  def self.convert_patient_models(hds_records)
I feel like this entire module/helper function is unnecessary. Why not just do the conversion in place where you need it?
The following one-liner is equivalent to this entire block:
`qdm_records = hds_records.collect { | hds_record | CQMConverter.to_qdm(hds_record) }`

2018-06-19 10:17 UTC, mayerm94 commented on app/helpers/patient_helper.rb
> +  def self.convert_patient_models(hds_records)
This is pulled out into a helper function for testability and because we are going to need the ability to do this in a few places. The places I can think of where it will be needed right now are for the MAT_API, backend calculations and I am sure we will have a rake task at some point that will need this.

2018-06-20 14:57 UTC, edeyoung commented on app/helpers/patient_helper.rb
> +  def self.convert_patient_models(hds_records)
what about a compromise - keep as own function for reusability and testability, but update with more concise language.

2018-06-20 15:47 UTC, mayerm94 commented on app/helpers/patient_helper.rb
> +  def self.convert_patient_models(hds_records)
The one-liner may be concise, but it's not as clear. --I doubt that I am the only one who had to/will have to look at the ruby docs to see what exactly `.collect`  does. I will concede and change it in order to get this PR through since this is essentially a matter of preference

2018-06-20 18:47 UTC, holmesie commented on app/helpers/patient_helper.rb
> +  def self.convert_patient_models(hds_records)
Works for me 👍

Apologies if my original suggestion required you to have to go and look things up in an API 😕, I think `map` is an even better choice!

2018-06-22 13:55 UTC, holmesie approved these changes
Looks great! 🤠

2018-06-22 13:57 UTC, merged