Sde display expansion boxes
MeasureAuthoringTool/bonnie pull request #1018
Opened 2018-06-19 19:55 UTC by losborne

This PR adds the UI elements to show results for define statements.

Pull requests into Bonnie require the following. Submitter and reviewer should :white_check_mark: when done. For items that are not-applicable, note it's not-applicable ("N/A") and :white_check_mark:.

**Submitter:**
- [x] This pull request describes why these changes were made.
- [x] This PR is into the correct branch.
- [x] JIRA ticket for this PR: https://jira.mitre.org/browse/BONNIE-1449
- [ ] JIRA ticket links to this PR
- [x] Code diff has been done and been reviewed (it **does not** contain: additional white space, not applicable code changes, debug statements, etc.)
- [ ] If UI changes have been made, google WAVE plug-in has been executed to ensure no 508 issues were introduced.
- [x] Tests are included and test edge cases
- [ ] Tests have been run locally and pass (remember to update Gemfile when applicable)
- [x] Test fixtures updated and documented as necessary ( see [internal wiki](https://gitlab.mitre.org/bonnie/internal-documentation/wikis/testing#test-fixtures) )
- [x] Code coverage has not gone down and all code touched or added is covered. 

Branch | Back End Coverage | Front End Coverage
-- | -- | --
bonnie-v2.2 | 1738 / 1950 LOC (89.13%) covered | Statements   : 58.94% ( 7134/12104 ) <br>Branches     : 42.79% ( 1935/4522 ) <br>Functions    : 49.19% ( 1178/2395 ) <br>Lines        : 56.81% ( 6408/11279 )
sde_display_expansion_boxes | 1738 / 1950 LOC (89.13%) covered. | Statements   : 59.28% ( 7236/12206 )<br>Branches     : 42.9% ( 1945/4534 )<br>Functions    : 49.69% ( 1202/2419 )<br>Lines        : 57.13% ( 6492/11363 )

- [ ] Automated regression test(s) pass

If JIRA tests were used to supplement or replace automated tests:
- [x] JIRA test links: N/A
- [x] Justification for using JIRA tests: N/A
- [x] JIRA tests have been added to sprint N/A

**Reviewer 1:**

Name:
- [ ] Code is maintainable and reusable, reuses existing code and infrastructure where appropriate, and accomplishes the task’s purpose
- [ ] The tests appropriately test the new code, including edge cases
- [ ] You have tried to break the code

If JIRA tests were used to supplement or replace automated tests:
- [ ] JIRA tests have been run and pass
- [ ] You agree with the justification for use of JIRA tests or have provided input on why you disagree

**Reviewer 2:**

Name:
- [ ] Code is maintainable and reusable, reuses existing code and infrastructure where appropriate, and accomplishes the task’s purpose
- [ ] The tests appropriately test the new code, including edge cases
- [ ] You have tried to break the code

If JIRA tests were used to supplement or replace automated tests:
- [ ] JIRA tests have been run and pass
- [ ] You agree with the justification for use of JIRA tests or have provided input on why you disagree

2018-06-20 18:52 UTC, hossenlopp requested changes
These should not show up for functions. I think there should be more space after the button before the next define.

2018-06-22 17:15 UTC, hossenlopp commented
Quantites still look odd with the `:` between the value and the unit.

2018-06-25 16:57 UTC, jbradl11 commented on app/assets/javascripts/helpers/cql_results_helpers.js.coffee
> +      if indentLevel >= 3
What case is this `if` block covering?

2018-06-25 17:03 UTC, jbradl11 commented
The horizontal scroll bars have changed on the patient builder page. I think this is a side effect of css changes. 

![image](https://user-images.githubusercontent.com/1568999/41864319-8dd75f48-7877-11e8-8ea7-74b17c9878a8.png)

2018-06-25 19:00 UTC, losborne commented on app/assets/javascripts/helpers/cql_results_helpers.js.coffee
> +      if indentLevel >= 3
Good question.  Originally, this was needed to keep the final `}` from having any indentation.  It seems to no longer be needed with the current state of this function.  Will remove and just leave `prettyResult = prettyResult + "#{currentIndentation}}"`

2018-06-25 21:02 UTC, hossenlopp approved these changes

2018-06-26 17:43 UTC, jbradl11 approved these changes
Changes look good. Cool feature.

2018-06-27 13:00 UTC, merged