Bonnie 1552
MeasureAuthoringTool/bonnie pull request #1023
Opened 2018-06-25 14:51 UTC by daco101

This PR adds a key (or legend) page to the excel export, and changes false(undefined) to false(function) when appropriate (also in the excel file).

https://jira.mitre.org/browse/BONNIE-1552

Pull requests into Bonnie require the following. Submitter and reviewer should :white_check_mark: when done. For items that are not-applicable, note it's not-applicable ("N/A") and :white_check_mark:.

**Submitter:**
- [:white_check_mark: ] This pull request describes why these changes were made.
- [:white_check_mark: ] This PR is into the correct branch.
- [ :white_check_mark:] JIRA ticket for this PR:
- [ ] JIRA ticket links to this PR
- [:white_check_mark:] Code diff has been done and been reviewed (it **does not** contain: additional white space, not applicable code changes, debug statements, etc.)
- [N/A:white_check_mark: ] If UI changes have been made, google WAVE plug-in has been executed to ensure no 508 issues were introduced.
- [:white_check_mark:] Tests are included and test edge cases
- [:white_check_mark: ] Tests have been run locally and pass (remember to update Gemfile when applicable)
- ["N/A":white_check_mark:] Test fixtures updated and documented as necessary ( see [internal wiki](https://gitlab.mitre.org/bonnie/internal-documentation/wikis/testing#test-fixtures) )
- [:white_check_mark: ] Code coverage has not gone down and all code touched or added is covered. 
     * In rare situations, this may not be possible or applicable to a PR. In those situations:
         1. Note why this could not be done or is not applicable here: 
         2. Add TODOs in the code noting that it requires a test
         3. Add a JIRA task to add the test and link it here: 

Branch | Back End Coverage | Front End Coverage
bonnie-v2.2 | 1752 / 1964 LOC (89.21%) covered | Statements   : 58.98% ( 7144/12112 )
Branches     : 42.9% ( 1944/4531 )
Functions    : 49.19% ( 1178/2395 )
Lines        : 56.86% ( 6418/11287 )

- [:white_check_mark: ] Automated regression test(s) pass

If JIRA tests were used to supplement or replace automated tests:
- [ ] JIRA test links:
- [ ] Justification for using JIRA tests:
- [ ] JIRA tests have been added to sprint

**Reviewer 1:**

Name:
- [ ] Code is maintainable and reusable, reuses existing code and infrastructure where appropriate, and accomplishes the task’s purpose
- [ ] The tests appropriately test the new code, including edge cases
- [ ] You have tried to break the code

If JIRA tests were used to supplement or replace automated tests:
- [ ] JIRA tests have been run and pass
- [ ] You agree with the justification for use of JIRA tests or have provided input on why you disagree

**Reviewer 2:**

Name:
- [ ] Code is maintainable and reusable, reuses existing code and infrastructure where appropriate, and accomplishes the task’s purpose
- [ ] The tests appropriately test the new code, including edge cases
- [ ] You have tried to break the code

If JIRA tests were used to supplement or replace automated tests:
- [ ] JIRA tests have been run and pass
- [ ] You agree with the justification for use of JIRA tests or have provided input on why you disagree

2018-06-25 17:06 UTC, c-monkey approved these changes
Tests pass, results look good.

2018-06-25 17:07 UTC, c-monkey requested changes
We need to fix your rubocop errors. Ask me if you want help.

2018-06-25 18:03 UTC, daco101 commented
Ok should be good now.

2018-06-25 18:10 UTC, c-monkey approved these changes

2018-06-26 18:12 UTC, mayerm94 commented on lib/patient_export.rb
> +            ["Code","Code: system: code","Code: SNOMED-CT: 8715000"],
Check that the capitalization of theses is correct, for example I see in an excel export "Code" is actually "CODE"

2018-06-27 13:56 UTC, daco101 commented on lib/patient_export.rb
> +            ["Code","Code: system: code","Code: SNOMED-CT: 8715000"],
Looks like there are two places that print out something like "Code: system code". The reason that there are capitalized codes in the excel export is because they are list items that have already been formatted by a function in the cql_qdm_patientapi. I suggest leaving as "Code" since it matches the format in the bonnie codebase.

2018-06-27 18:30 UTC, c-monkey approved these changes
Excel export looks good to me

2018-06-27 18:32 UTC, mayerm94 approved these changes

2018-06-27 19:30 UTC, merged