Bonnie v2.3 restful calculation call
MeasureAuthoringTool/bonnie pull request #1028
Opened 2018-07-03 18:57 UTC by daco101

This PR sets up the rest call and tests it (against the current calculation server which just echoes). The function will be modified once the cql calculation engine server is up and running. 
It also tweaks the test_helper so it can insert arrays (i.e. of value sets) into mongo.

Pull requests into Bonnie require the following. Submitter and reviewer should :white_check_mark: when done. For items that are not-applicable, note it's not-applicable ("N/A") and :white_check_mark:.

**Submitter:**
- [ ] This pull request describes why these changes were made.
- [ ] This PR is into the correct branch.
- [ ] JIRA ticket for this PR: https://jira.mitre.org/browse/BONNIE-1577
- [ ] JIRA ticket links to this PR
- [ ] Code diff has been done and been reviewed (it **does not** contain: additional white space, not applicable code changes, debug statements, etc.)
- [ ] If UI changes have been made, google WAVE plug-in has been executed to ensure no 508 issues were introduced.
- [ ] Tests are included and test edge cases
- [ ] Tests have been run locally and pass (remember to update Gemfile when applicable)
- [ ] Test fixtures updated and documented as necessary ( see [internal wiki](https://gitlab.mitre.org/bonnie/internal-documentation/wikis/testing#test-fixtures) )
- [ ] Code coverage has not gone down and all code touched or added is covered. 
     * In rare situations, this may not be possible or applicable to a PR. In those situations:
         1. Note why this could not be done or is not applicable here: 
         2. Add TODOs in the code noting that it requires a test
         3. Add a JIRA task to add the test and link it here: 

Branch | Back End Coverage | Front End Coverage
-- | -- | --
bonnie-v2.3-backend-calculation | 1903 / 2134 LOC (89.18%) covered| Statements   : 59.44% ( 7280/12247 )<br>Branches     : 43.43% ( 1979/4557 )<br>Functions    : 49.81% ( 1207/2423 )<br>Lines        : 57.31% ( 6536/11404 )
bonnie-v2.3-restful-calculation-call | 1911 / 2139 LOC (89.34%) covered | Statements   : 59.44% ( 7280/12247 ) <br> Branches     : 43.43% ( 1979/4557 ) <br> Functions    : 49.81% ( 1207/2423 ) <br> Lines        : 57.31% ( 6536/11404 )

- [ ] Automated regression test(s) pass N/A

If JIRA tests were used to supplement or replace automated tests:
- [ ] JIRA test links:
- [ ] Justification for using JIRA tests:
- [ ] JIRA tests have been added to sprint

**Reviewer 1:**

Name:
- [ ] Code is maintainable and reusable, reuses existing code and infrastructure where appropriate, and accomplishes the task’s purpose
- [ ] The tests appropriately test the new code, including edge cases
- [ ] You have tried to break the code

If JIRA tests were used to supplement or replace automated tests:
- [ ] JIRA tests have been run and pass
- [ ] You agree with the justification for use of JIRA tests or have provided input on why you disagree

**Reviewer 2:**

Name:
- [ ] Code is maintainable and reusable, reuses existing code and infrastructure where appropriate, and accomplishes the task’s purpose
- [ ] The tests appropriately test the new code, including edge cases
- [ ] You have tried to break the code

If JIRA tests were used to supplement or replace automated tests:
- [ ] JIRA tests have been run and pass
- [ ] You agree with the justification for use of JIRA tests or have provided input on why you disagree

2018-07-05 19:10 UTC, hossenlopp requested changes
Just one last change to fix test ordering issues.

2018-07-05 19:10 UTC, hossenlopp commented on test/unit/backend_calc_test.rb
> +      assert_equal patients.first['first'], r['patients'].first['givenNames'][0]
This one still has ordering issues but for some reason checking for count of the arrays fix the ordering issue. Just add this before this line and it should work for people on mongo 3.4.4.
```
assert_equal patients.count, r['patients'].count
```

2018-07-05 19:31 UTC, hossenlopp commented on test/unit/backend_calc_test.rb
> +      assert_equal patients.first['first'], r['patients'].first['givenNames'][0]
Nevermind. This doesn't work.

2018-07-05 20:37 UTC, hossenlopp commented on test/unit/backend_calc_test.rb
> +      assert_equal patients.first['first'], r['patients'].first['givenNames'][0]
Got a different suggestion. This grabs all the names and sorts them before checking the lists.
```
assert_equal (patients.collect { |p| p.first }).sort, (r['patients'].collect { |p| p['givenNames'][0] }).sort
assert_equal (patients.collect { |p| p.last }).sort, (r['patients'].collect { |p| p['familyName'] }).sort
```

2018-07-06 12:38 UTC, hossenlopp approved these changes
The error checking situations aren't tested, but that will be much easier to do once the service is running with calculation stuff intact to throw errors.

2018-07-06 12:40 UTC, hossenlopp commented
Approving with travis failure due to nokogiri vulnerability that we will solve on master.

2018-07-06 12:49 UTC, hossenlopp requested changes
Just add a test to make sure timeouts to the service are handled gracefully.

2018-07-06 15:07 UTC, hossenlopp approved these changes

2018-07-06 17:03 UTC, jbradl11 approved these changes
Code looks good! Approving, knowing we will fix vulnerability in the base branch.

2018-07-06 17:03 UTC, merged