Excel export results conversion
MeasureAuthoringTool/bonnie pull request #1030
Opened 2018-07-10 19:18 UTC by losborne

NOTE: This PR is for an initial review only--there is still some work left in getting the tests figured out.  There may be some issues with the backend calculator causing discrepancies.  

excel_export_helper.rb work should be more or less stable and ready for review.  Tests are set up and cases can be reviewed, but are not complete.

```
Pull requests into Bonnie require the following. Submitter and reviewer should :white_check_mark: when done. For items that are not-applicable, note it's not-applicable ("N/A") and :white_check_mark:.

**Submitter:**
- [ ] This pull request describes why these changes were made.
- [ ] This PR is into the correct branch.
- [ ] JIRA ticket for this PR:
- [ ] JIRA ticket links to this PR
- [ ] Code diff has been done and been reviewed (it **does not** contain: additional white space, not applicable code changes, debug statements, etc.)
- [ ] If UI changes have been made, google WAVE plug-in has been executed to ensure no 508 issues were introduced.
- [ ] Tests are included and test edge cases
- [ ] Tests have been run locally and pass (remember to update Gemfile when applicable)
- [ ] Test fixtures updated and documented as necessary ( see [internal wiki](https://gitlab.mitre.org/bonnie/internal-documentation/wikis/testing#test-fixtures) )
- [ ] Code coverage has not gone down and all code touched or added is covered. 
     * In rare situations, this may not be possible or applicable to a PR. In those situations:
         1. Note why this could not be done or is not applicable here: 
         2. Add TODOs in the code noting that it requires a test
         3. Add a JIRA task to add the test and link it here: 

Branch | Back End Coverage | Front End Coverage
-- | -- | --
master | [Paste Output Here] | [Paste Screenshot Here]
[New Branch] | [Paste Output Here] | [Paste Screenshot Here]

- [ ] Automated regression test(s) pass

If JIRA tests were used to supplement or replace automated tests:
- [ ] JIRA test links:
- [ ] Justification for using JIRA tests:
- [ ] JIRA tests have been added to sprint

**Reviewer 1:**

Name:
- [ ] Code is maintainable and reusable, reuses existing code and infrastructure where appropriate, and accomplishes the task’s purpose
- [ ] The tests appropriately test the new code, including edge cases
- [ ] You have tried to break the code

If JIRA tests were used to supplement or replace automated tests:
- [ ] JIRA tests have been run and pass
- [ ] You agree with the justification for use of JIRA tests or have provided input on why you disagree

**Reviewer 2:**

Name:
- [ ] Code is maintainable and reusable, reuses existing code and infrastructure where appropriate, and accomplishes the task’s purpose
- [ ] The tests appropriately test the new code, including edge cases
- [ ] You have tried to break the code

If JIRA tests were used to supplement or replace automated tests:
- [ ] JIRA tests have been run and pass
- [ ] You agree with the justification for use of JIRA tests or have provided input on why you disagree
```

2018-07-10 20:47 UTC, edeyoung commented on app/controllers/api_v1/measures_controller.rb
> +      # statement_details = ExcelExportHelper.get_statement_details_from_measure(@api_v1_measure)
what's the status on all the commented code? looks like 168 will be removed. are the others going to be uncommented or removed?

2018-07-10 21:07 UTC, edeyoung reviewed
initial set of comments. need to review tests

2018-07-10 21:07 UTC, edeyoung commented on app/controllers/api_v1/measures_controller.rb
> +          # send_data excel_package.to_stream.read, type: :xlsx, status: http_status, filename: ERB::Util.url_encode(filename)
same question re status of comments

2018-07-10 21:07 UTC, edeyoung commented on app/helpers/excel_export_helper.rb
> +        result[population['id']]['extendedData']['population_relevance'].each_key do |pop_crit|
consider renaming to `population_criteria` or `pop_criteria`

2018-07-10 21:07 UTC, edeyoung commented on app/helpers/excel_export_helper.rb
> +          if pop_crit == 'values'
can you add a comment for why this is a separate case? what is special about it being `'values'`?

2018-07-10 21:07 UTC, edeyoung commented on app/helpers/excel_export_helper.rb
> +  def self.convert_results_for_excel_export(results, measure, patients)
add method comment

2018-07-10 21:07 UTC, edeyoung commented on app/helpers/excel_export_helper.rb
> +  private_class_method def self.remove_extra(results)
add method comment (same w all other methods)

2018-07-10 21:07 UTC, edeyoung commented on app/helpers/excel_export_helper.rb
> +  private_class_method def self.remove_extra(results)
is there a better name for this? `remove_redundant_results`? then add in the method description that defaults to use `pretty` if it exists?

2018-07-10 21:07 UTC, edeyoung commented on app/helpers/excel_export_helper.rb
> +      criteria.push 'index'
add comment explaining this is just to match the front-end. maybe also a "TODO" to investigate removing it entirely...

2018-07-10 21:07 UTC, edeyoung commented on app/helpers/excel_export_helper.rb
> +    statement_details.with_indifferent_access
general question: you have `with_indifferent_access` for all of the base hashes that get returned. should this also be on the embedded hashes (`lib_statements` here)?

also, what about making the hash indifferent at creation time rather than on return? (`lib_statements = ActiveSupport::HashWithIndifferentAccess.new`)

2018-07-10 21:07 UTC, edeyoung commented on test/fixtures/excel_export_helper/README.md
> +in cqm-execution/spec/models/calculator_spec.js on branch bonnie_backend_execution_results_stub
great README!!!

2018-07-10 21:22 UTC, losborne commented on app/controllers/api_v1/measures_controller.rb
> +      # statement_details = ExcelExportHelper.get_statement_details_from_measure(@api_v1_measure)
168 can be used once the results from the calculator are right for testing until the route is implemented then will be removed.

The other lines will be uncommented once `BonnieBackendCalculator.calculate` is returning the real results.

Lines 177 and 178 will be replaced by 180-182 to return the real excel export instead of the dummy.

2018-07-10 21:23 UTC, losborne commented on app/controllers/api_v1/measures_controller.rb
> +          # send_data excel_package.to_stream.read, type: :xlsx, status: http_status, filename: ERB::Util.url_encode(filename)
Lines 177 and 178 will be replaced by 180-182 to return the real excel export instead of the dummy.

2018-07-11 22:06 UTC, losborne commented
CI failing is only because of
```
Name: nokogiri
Version: 1.8.2
Advisory: CVE-2018-8048
Criticality: Unknown
URL: https://github.com/sparklemotion/nokogiri/pull/1746
Title: Revert libxml2 behavior in Nokogiri gem that could cause XSS
Solution: upgrade to >= 1.8.3
Vulnerabilities found!
```

2018-07-11 23:35 UTC, edeyoung requested changes
see comments - minor

2018-07-11 23:35 UTC, edeyoung commented on test/unit/helpers/excel_export_helper_test.rb
> +    cid_to_measure_id_map = { 'c320': '5a58e9b6942c6d4bb26bb2f6', 'c468': '5a593d66942c6d0773593d97', 'c495': '5a593ff0942c6d0773593dff', 'c523': '5a5940ba942c6d0c717eeece'}
this information is used in two places (also lines 39-42). thoughts on making this part of the `setup` statement and reusing it in both these functions?

2018-07-11 23:35 UTC, edeyoung commented on app/helpers/excel_export_helper.rb
> +                                        results[lib_key][statement_key]['final']
not covered in testing. how hard to cover?

![image](https://user-images.githubusercontent.com/11574199/42604092-efd7f09e-853e-11e8-98aa-5f1b66b3fad5.png)

2018-07-11 23:35 UTC, edeyoung commented on test/unit/helpers/excel_export_helper_test.rb
> +    @calc_results = JSON.parse(File.read(File.join(Rails.root, 'test', 'fixtures', 'excel_export_helper', 'calc_results.json')))
add comment that these are the results from the front end calculation processing to compare with the back end calculation processing

2018-07-11 23:35 UTC, edeyoung commented on test/unit/helpers/excel_export_helper_test.rb
> +    # TODO: how to test this--load excel fixture and look at rows? might be different order
who owns this todo? if it's for another task, would be good to note in whichever jira task that is. based on the comments, it sounds like this isn't intended to be resolved in this PR.

2018-07-11 23:35 UTC, edeyoung commented on test/unit/helpers/excel_export_helper_test.rb
> +      assert_equal calc_result[1]['c320'], converted_result[1]['5a58e9b6942c6d4bb26bb2f6']
would the dereferencing here be clearer if you used the population mapping on lines 63-66? have this in the `setup` and then iterate over the mapping here instead of doing the zip? because when i first looked at this, i was like, "are we missing important information in `calc_result[0]`? what is `calc_result[0]`? if you did something with the population cid->index mappings, i think that would make this more explicit.

2018-07-11 23:40 UTC, edeyoung commented
this stuff brings us to 89.97% test coverage... just .03% until green!

2018-07-12 00:48 UTC, jbradl11 commented on app/helpers/excel_export_helper.rb
> +module ExcelExportHelper
I like the structure of this file a lot. Two comments. I would group the two 'private' functions together at the bottom of the module. And its typically Ruby convention to have the comments right above the function name.

2018-07-12 00:49 UTC, jbradl11 commented on test/unit/helpers/excel_export_helper_test.rb
> +    # TODO: Use CMS134v6 for more tests with a measure without multiple pops/strats
Should we add this test now?

2018-07-12 10:42 UTC, jbradl11 commented
General question, has this been tested on a measure with patients failing to be converted due to UCUM unit issues?

2018-07-12 12:15 UTC, losborne commented
@jbradl11 This hasn't been tested with such a measure.  Are there any in `cqm-execution` that exhibit that failure? Or in bonnie that could be added to `cqm-execution` so I can generate another fixture for that?

2018-07-12 13:20 UTC, losborne commented on app/helpers/excel_export_helper.rb
> +                                        results[lib_key][statement_key]['final']
Good catch--added a couple new fixtures and a new test to cover it.

2018-07-12 13:30 UTC, losborne commented on test/unit/helpers/excel_export_helper_test.rb
> +      assert_equal calc_result[1]['c320'], converted_result[1]['5a58e9b6942c6d4bb26bb2f6']
Good point.  I found a cleaner way to loop over them.

2018-07-12 13:39 UTC, losborne commented on test/unit/helpers/excel_export_helper_test.rb
> +    # TODO: Use CMS134v6 for more tests with a measure without multiple pops/strats
I think it may make sense to wait until the BackendCalculator can be called directly from the unit tests for this tests, rather than making a new set of fixtures from `cqm-execution`.

2018-07-13 13:18 UTC, edeyoung commented on test/unit/helpers/excel_export_helper_test.rb
> +    @simple_patients = Record.by_user(@user).where({:measure_ids.in => [@simple_measure.hqmf_set_id]})
minor minor comment - the organization of this is a bit confusing - `simple` things interspersed w the rest. consider grouping these variables together. Maybe add the comment on line 20 to the initial access of the simple measures. e.g.,

```
users_set = File.join('users', 'base_set')

# measure w stratifications which present the most edge cases
measures_set = File.join('cql_measures', 'core_measures', 'CMS32v7')
records_set = File.join('records','core_measures', 'CMS32v7')

# simple measure w a patient that fails due to invalid ucum units
simple_measures_set = File.join('cql_measures', 'core_measures', 'CMS134v6')
simple_records_set = File.join('records','core_measures', 'CMS134v6')

collection_fixtures(measures_set, users_set, records_set, simple_measures_set, simple_records_set)
```

2018-07-13 13:18 UTC, edeyoung commented on test/unit/helpers/excel_export_helper_test.rb
> +    # modify the backend results keys to match the keys of our patients. The results stub's keys
again - an optional formatting recommendation - add a space above line 28

2018-07-13 13:19 UTC, edeyoung approved these changes
have minor formatting comments that don't necessarily need to be implemented. approve.

2018-07-13 20:41 UTC, jbradl11 approved these changes

2018-07-13 20:42 UTC, merged