Excel key fix
MeasureAuthoringTool/bonnie pull request #1031
Opened 2018-07-11 14:41 UTC by daco101

This PR slightly modifies the "pretty result" function to match the style from the qdm_patientapi, improves the excel "key" sheet, and adds a maximum column width to the excel export.

Pull requests into Bonnie require the following. Submitter and reviewer should :white_check_mark: when done. For items that are not-applicable, note it's not-applicable ("N/A") and :white_check_mark:.

**Submitter:**
- [x] This pull request describes why these changes were made.
- [x] This PR is into the correct branch.
- [ ] JIRA ticket for this PR:
- [ ] JIRA ticket links to this PR
- [x] Code diff has been done and been reviewed (it **does not** contain: additional white space, not applicable code changes, debug statements, etc.)
- [x] If UI changes have been made, google WAVE plug-in has been executed to ensure no 508 issues were introduced. N/A
- [x] Tests are included and test edge cases
- [x] Tests have been run locally and pass (remember to update Gemfile when applicable)
- [x] Test fixtures updated and documented as necessary ( see [internal wiki](https://gitlab.mitre.org/bonnie/internal-documentation/wikis/testing#test-fixtures) )
- [x] Code coverage has not gone down and all code touched or added is covered. 
     * In rare situations, this may not be possible or applicable to a PR. In those situations:
         1. Note why this could not be done or is not applicable here: 
         2. Add TODOs in the code noting that it requires a test
         3. Add a JIRA task to add the test and link it here: 

Branch | Back End Coverage | Front End Coverage
-- | -- | --
master | 1753 / 1965 LOC (89.21%) covered | Statements   : 59.44% ( 7280/12247 )<br>Branches     : 43.43% ( 1979/4557 )<br>Functions    : 49.81% ( 1207/2423 )<br>Lines        : 57.31% ( 6536/11404 )
excel_key_fix | 1759 / 1971 LOC (89.24%) covered | Statements   : 59.44% ( 7280/12247 )<br>Branches     : 43.43% ( 1979/4557 )<br>Functions    : 49.81% ( 1207/2423 )<br>Lines        : 57.31% ( 6536/11404 )

- [x] Automated regression test(s) pass

If JIRA tests were used to supplement or replace automated tests:
- [x] JIRA test links: N/A
- [x] Justification for using JIRA tests: N/A
- [x] JIRA tests have been added to sprint N/A

**Reviewer 1:**

Name:
- [ ] Code is maintainable and reusable, reuses existing code and infrastructure where appropriate, and accomplishes the task’s purpose
- [ ] The tests appropriately test the new code, including edge cases
- [ ] You have tried to break the code

If JIRA tests were used to supplement or replace automated tests:
- [ ] JIRA tests have been run and pass
- [ ] You agree with the justification for use of JIRA tests or have provided input on why you disagree

**Reviewer 2:**

Name:
- [ ] Code is maintainable and reusable, reuses existing code and infrastructure where appropriate, and accomplishes the task’s purpose
- [ ] The tests appropriately test the new code, including edge cases
- [ ] You have tried to break the code

If JIRA tests were used to supplement or replace automated tests:
- [ ] JIRA tests have been run and pass
- [ ] You agree with the justification for use of JIRA tests or have provided input on why you disagree

2018-07-11 19:07 UTC, edeyoung commented
noticed this:

![image](https://user-images.githubusercontent.com/11574199/42594046-0ab86f10-851c-11e8-8c24-4dab5c3fdae1.png)


"FUNCTION" sometimes used, other times "Not Calculated" is used. This should always be "FUNCTION" (up for hearing disagreement here, but I believe this should always be "FUNCTION" - I think otherwise this is confusing)

2018-07-11 19:22 UTC, edeyoung requested changes
I think the key looks good and all changes in this PR look good! however - there's the FUNCTION issue. would be convenient to resolve that here as well.

2018-07-11 19:42 UTC, daco101 commented
I will defer to your judgement and change it to Function.

2018-07-12 13:40 UTC, edeyoung commented on lib/patient_export.rb
> +                      statement_results[statement_to_column[statement]] = "FUNCTION"
this should only be done if the statement is a function. it looks like it's being blanket assigned to "FUNCTION" vs only when the statement itself is a function. I have not yet tested this - have you confirmed that this only occurs for "FUNCTION"s?

Can a test be added to explicitly confirm this?

2018-07-12 13:48 UTC, edeyoung commented on lib/patient_export.rb
> +                      statement_results[statement_to_column[statement]] = "FUNCTION"
yes - this just replaces all unhits w function, which shouldn't happen w definition statements. see screen shot below.

![image](https://user-images.githubusercontent.com/11574199/42637252-a89309e2-85b8-11e8-985f-432c8a7ae0a9.png)

I think that you need to modify the actual results that are returned - figure out where "FUNCTION" is being added to those results and see if that can replace "UNHIT" for function related statements.

2018-07-12 13:51 UTC, losborne commented on lib/patient_export.rb
> +                      statement_results[statement_to_column[statement]] = "FUNCTION"
```
  @buildStatementAndClauseResults: (measure, rawClauseResults, statementRelevance, doPretty = false) ->
...

2018-07-12 21:04 UTC, c-monkey requested changes

2018-07-12 21:04 UTC, c-monkey commented on app/assets/javascripts/helpers/cql_results_helpers.js.coffee
> +            statementResults[lib][statementName].pretty = "FUNCTION" if doPretty
The comment at the top of the function says `final` is always set to one of 'NA', 'UNHIT', 'TRUE', 'FALSE'. From my digging, I think this is not an issue because client code checks for 'TRUE' or 'FALSE' explicitly, i.e. `app/assets/javascripts/views/logic/cql_clause_view.js.coffee` function `showRationale`.

Regardless, we should probably be setting .final to 'UNHIT'

2018-07-12 21:04 UTC, c-monkey commented on lib/patient_export.rb
> +        ##ADD THE KEY SHEET TO THE BEGINNING OF THE DOCUMENT
Two things:
- Now that we have key-sheet specific styles, I think the block above (defining styles, not the error sheet) should be moved to be after this key block
- Perhaps the key-sheet shouldn't be added if there are no patients. The error sheet is the first one so I don't think this is problematic, but maybe omitting the key would make the error more clear.

2018-07-13 12:34 UTC, daco101 commented on app/assets/javascripts/helpers/cql_results_helpers.js.coffee
> +            statementResults[lib][statementName].pretty = "FUNCTION" if doPretty
Makes sense, i'm adding the .final assignment.

Regarding the unit tests not hitting the assignment, the new jira test covers this.

2018-07-13 13:29 UTC, daco101 commented on lib/patient_export.rb
> +        ##ADD THE KEY SHEET TO THE BEGINNING OF THE DOCUMENT
Sounds good, moved the block and skipped the key sheet in case of errors.

2018-07-13 13:35 UTC, daco101 commented
Latest commit should address comments by @c-monkey

2018-07-13 14:12 UTC, edeyoung requested changes
See minor comment. Not rejecting due to that comment. Rejecting due to JIRA test.

In JIRA test step (7) it asks you to go to the second tab. In step (8) it asks you to confirm that "FUNCTION" present in all cells in an particular column. **However**, "FUNCTION" was always present in that particular column. Make sure that the test is looking at a column where this once failed.

2018-07-13 14:12 UTC, edeyoung commented on lib/patient_export.rb
> +            ["QDM Data Criteria","QDM Datatype: Value Set\nSTART: MM/DD/YYYY h:mm AM/PM\nSTOP: MM/DD/YYYY h:mm AM/PM\nCODE: system code\n* only the first code on the data criteria is shown","Medicati
recommend adding second footnote:

```
* STOP entry is optional
* only the first code on the data criteria is shown

2018-07-13 16:20 UTC, c-monkey commented on app/assets/javascripts/helpers/cql_results_helpers.js.coffee
> +            statementResults[lib][statementName].pretty = "FUNCTION" if doPretty
I agree that the JIRA test covers this line. And for time considerations I'll consent to us not adding a unit test.

2018-07-13 16:55 UTC, c-monkey approved these changes
Coverage is good except for the 1 line we've noted that's in the JIRA test. Regression tests have no changes.

Changes between the few measures I checked exporting from Bonnie production vs. this PR branch have resolved all issues Lizzie identified in the slack thread as well as feedback in this PR.

2018-07-13 16:57 UTC, c-monkey commented
The Travis failure is:
```
ruby-advisory-db: 317 advisories
Name: nokogiri
Version: 1.8.2
Advisory: CVE-2018-8048
Criticality: Unknown
URL: https://github.com/sparklemotion/nokogiri/pull/1746
Title: Revert libxml2 behavior in Nokogiri gem that could cause XSS
Solution: upgrade to >= 1.8.3
Vulnerabilities found!
The command "bundle exec bundle-audit check --update" exited with 1.
```

2018-07-13 17:33 UTC, edeyoung approved these changes

2018-07-13 17:35 UTC, merged