Use calc svc
MeasureAuthoringTool/bonnie pull request #1037
Opened 2018-07-17 12:30 UTC by daco101

This PR adds the calculation engine endpoint for the backend calculator.

Pull requests into Bonnie require the following. Submitter and reviewer should :white_check_mark: when done. For items that are not-applicable, note it's not-applicable ("N/A") and :white_check_mark:.

**Submitter:**
- [x] This pull request describes why these changes were made.
- [x] This PR is into the correct branch.
- [ ] JIRA ticket for this PR:
- [ ] JIRA ticket links to this PR
- [ ] Code diff has been done and been reviewed (it **does not** contain: additional white space, not applicable code changes, debug statements, etc.)
- [ ] If UI changes have been made, google WAVE plug-in has been executed to ensure no 508 issues were introduced.
- [x] Tests are included and test edge cases
- [x] Tests have been run locally and pass (remember to update Gemfile when applicable)
- [x] Test fixtures updated and documented as necessary ( see [internal wiki](https://gitlab.mitre.org/bonnie/internal-documentation/wikis/testing#test-fixtures) )
- [ ] Code coverage has not gone down and all code touched or added is covered. 
     * In rare situations, this may not be possible or applicable to a PR. In those situations:
         1. Note why this could not be done or is not applicable here: 
         2. Add TODOs in the code noting that it requires a test
         3. Add a JIRA task to add the test and link it here: 

Branch | Back End Coverage | Front End Coverage
-- | -- | --
master | [Paste Output Here] | [Paste Screenshot Here]
use_calc_svc | 2139 / 2395 LOC (89.31%) covered. | Statements   : 59.44% ( 7280/12247 )<br>Branches     : 43.43% ( 1979/4557 )<br>Functions    : 49.81% ( 1207/2423 )<br>Lines        : 57.31% ( 6536/11404 )

- [ ] Automated regression test(s) pass

If JIRA tests were used to supplement or replace automated tests:
- [ ] JIRA test links:
- [ ] Justification for using JIRA tests:
- [ ] JIRA tests have been added to sprint

**Reviewer 1:**

Name:
- [ ] Code is maintainable and reusable, reuses existing code and infrastructure where appropriate, and accomplishes the task’s purpose
- [ ] The tests appropriately test the new code, including edge cases
- [ ] You have tried to break the code

If JIRA tests were used to supplement or replace automated tests:
- [ ] JIRA tests have been run and pass
- [ ] You agree with the justification for use of JIRA tests or have provided input on why you disagree

**Reviewer 2:**

Name:
- [ ] Code is maintainable and reusable, reuses existing code and infrastructure where appropriate, and accomplishes the task’s purpose
- [ ] The tests appropriately test the new code, including edge cases
- [ ] You have tried to break the code

If JIRA tests were used to supplement or replace automated tests:
- [ ] JIRA tests have been run and pass
- [ ] You agree with the justification for use of JIRA tests or have provided input on why you disagree

2018-07-17 13:15 UTC, daco101 commented
I see coverage has gone down - I will look into this

2018-07-17 15:00 UTC, lukoktonos requested changes

2018-07-17 15:00 UTC, losborne commented on app/controllers/api_v1/measures_controller.rb
> +    XLSX_CONTENT_TYPES = ["application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", "xlsx"].freeze # only the first is official
I believe this is redundant as `:xlsx` is registered in `config/initializers_mime_types.rb` to be `application/vnd.openxmlformats-officedocument.spreadsheetml.sheet`.  Was it not giving the right request header with that?

```
config/initializers/mime_types.rb
6:Mime::Type.register 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet', :xlsx
```

2018-07-17 15:00 UTC, losborne commented on test/functional/api_v1/measures_controller_test.rb
> +      associate_measures_with_patients(CqlMeasure.all, Record.all)
There's an extra space at the end of this line

2018-07-17 15:00 UTC, losborne commented on test/functional/api_v1/measures_controller_test_backend_calc.rb
> +    # StubToken simulates an OAuth2 token... we're not actually
I think it would make sense to pull this out into `test_helper.rb`, since it is being used a 2nd time (first would be in `test/functional/api_v1/measures_controller_test.rb).

2018-07-17 15:23 UTC, losborne commented on app/controllers/api_v1/measures_controller.rb
>      def calculated_results
The individual parts of this are tested, but the actual route from the measures_controller isn't covered

2018-07-17 15:24 UTC, losborne commented on test/functional/api_v1/measures_controller_test.rb
> -    test "should get calculated_results as xlsx for api_v1_measure" do
I think it would be better to adjust the assert rather than removing this test.

2018-07-17 18:14 UTC, lukoktonos submitted a review, later dismissed
Looks good!

2018-07-18 18:29 UTC, jbradl11 commented on app/controllers/api_v1/measures_controller.rb
> +      calculated_results = BonnieBackendCalculator.calculate(@api_v1_measure, @api_v1_patients, @api_v1_value_sets, @calculator_options)
Looks like we need better error handling for this function in general, but this new code should probably go into the begin/rescue block above.

2018-07-18 18:31 UTC, jbradl11 commented on app/controllers/api_v1/measures_controller.rb
> +        render json: calculated_results
You should return the status here `status: http_status` along with the calculated_results

2018-07-18 18:37 UTC, jbradl11 commented on app/controllers/api_v1/measures_controller.rb
>          if http_status != 404
It looks like we could get into a situation where `request.headers['Accept']  ==   Mime::Type.lookup_by_extension(:xlsx)` but `http_status == 404`.

2018-07-18 19:05 UTC, jbradl11 commented
Looks like 3 tests are failing and need to be updated.

2018-07-25 19:03 UTC, lukoktonos approved these changes
Looks good, once again!  Good job solving the doubly-running rake tests mystery as well.

2018-07-26 20:53 UTC, jbradl11 commented on app/controllers/api_v1/measures_controller.rb
> +      calculated_results = BonnieBackendCalculator.calculate(@api_v1_measure, @api_v1_patients, @api_v1_value_sets, @calculator_options)
This should be wrapped in a begin/rescue block. If the node service is down or errors out, we should return a `status: :internal_server_error`

2018-07-30 18:20 UTC, jbradl11 approved these changes

2018-07-30 18:20 UTC, merged