rake tasks for comparing Excel files
MeasureAuthoringTool/bonnie pull request #1038
Opened 2018-07-18 13:26 UTC by c-monkey

Comparing either two directories or two individual Excel files for differences. When comparing either way, any differences are outputted to `FIRST-diffs` and `SECOND-diffs` files which are best reviewed by an external diff tool.

Example usage:
```
bundle exec rake bonnie:compare_excel_files FIRST=foo/bar@example.com-7C443B9B-1AD1-4467-B527-DEFC445701FF.xlsx SECOND=baz/bar@example.com-7C443B9B-1AD1-4467-B527-DEFC445701FF.xlsx
```
Compare two directories:
```
bundle exec rake bonnie:compare_excel_exports FIRST=frontend/ SECOND=backend/ 
```

Pull requests into Bonnie require the following. Submitter and reviewer should :white_check_mark: when done. For items that are not-applicable, note it's not-applicable ("N/A") and :white_check_mark:.

**Submitter:**
- [X] This pull request describes why these changes were made.
- [X] This PR is into the correct branch.
- [X] JIRA ticket for this PR: https://jira.mitre.org/browse/BONNIE-1540
- [x] JIRA ticket links to this PR
- [X] Code diff has been done and been reviewed (it **does not** contain: additional white space, not applicable code changes, debug statements, etc.)
- [X] If UI changes have been made, google WAVE plug-in has been executed to ensure no 508 issues were introduced.
- [X] Tests are included and test edge cases N/A
- [X] Tests have been run locally and pass (remember to update Gemfile when applicable)
- [X] Test fixtures updated and documented as necessary ( see [internal wiki](https://gitlab.mitre.org/bonnie/internal-documentation/wikis/testing#test-fixtures) )
- [X] Code coverage has not gone down and all code touched or added is covered. 
     * In rare situations, this may not be possible or applicable to a PR. In those situations:
         1. Note why this could not be done or is not applicable here: 
         2. Add TODOs in the code noting that it requires a test
         3. Add a JIRA task to add the test and link it here: 

Branch | Back End Coverage | Front End Coverage
-- | -- | --
master | [Paste Output Here] | [Paste Screenshot Here]
[New Branch] | [Paste Output Here] | [Paste Screenshot Here]

- [X] Automated regression test(s) pass

If JIRA tests were used to supplement or replace automated tests:
- [X] JIRA test links: N/A
- [X] Justification for using JIRA tests: N/A
- [X] JIRA tests have been added to sprint N/A

**Reviewer 1:**

Name: @losborne
- [x] Code is maintainable and reusable, reuses existing code and infrastructure where appropriate, and accomplishes the task’s purpose
- [x] The tests appropriately test the new code, including edge cases
- [x] You have tried to break the code

**Reviewer 2:**

Name: @mayerm94
- [x] Code is maintainable and reusable, reuses existing code and infrastructure where appropriate, and accomplishes the task’s purpose
- [x] The tests appropriately test the new code, including edge cases
- [x] You have tried to break the code

2018-07-20 20:08 UTC, lukoktonos requested changes
Comparison is working great--just a comment on usability and a couple of minor textual suggestions.

2018-07-20 20:08 UTC, losborne commented on lib/tasks/bonnie_run_once.rake
> +        puts "   The two Excel files have different columns!"
This should have `.red` at the end

2018-07-20 20:08 UTC, losborne commented on lib/tasks/bonnie_run_once.rake
> +              puts "      Back end: " + sorted_backend_rows[idx].to_s
The Back end results and Front end results are inter-mingled, which makes doing any sort of diff difficult.

A couple of ideas that would make this output more usable (choose any or none of them depending on the level of effort you feel they would take, but the output needs to be more usable somehow):
- If we print out patient-by-patient, add a header row with the patient's name, followed by a colorized diff, similar to `git diff` (with patients instead of files).
- Save all restuls, then print all backend results out followed by all frontend results.  This could be thrown into a diff tool to generate a more readable diff.  Even better might be making a backend results and frontend results file, for cases when the diff is too large to easily copy.
- Go into a finer granularity.  Right now it prints out an entire row if 1 element is different in the row. Printing some way to tell which row (patient name) and which column is different along with the single item difference might be more usable.

2018-07-20 20:08 UTC, losborne commented on lib/tasks/bonnie_run_once.rake
> +        return
I think having some indicator of success here would be nice--like a green text printout with the filename or maybe just a green dot.

2018-07-24 13:36 UTC, losborne commented on lib/tasks/bonnie_run_once.rake
> +        # skip patients who have no name (bug with equals sign says Luke)
Please update this comment and the identical one below to be:
```
# skip patients who have no name (BONNIE-1612)
```

2018-07-24 13:44 UTC, c-monkey commented on lib/tasks/bonnie_run_once.rake
> +        # skip patients who have no name (bug with equals sign says Luke)
thanks! done

2018-07-24 13:46 UTC, lukoktonos approved these changes
Looks good!

2018-07-26 19:26 UTC, mayerm94 approved these changes
Rake task works. --Had to update bonnie_bundler reference to 'bonnie-v2.3-backend-calculation', but that's fine since that is what is referenced in the use_calc_svc branch

2018-07-27 20:36 UTC, jbradl11 commented
This is failing rubocop and tests.

2018-07-30 17:43 UTC, merged