Bonnie 1580 result datetime milliseconds fix
MeasureAuthoringTool/bonnie pull request #1042
Opened 2018-08-01 14:42 UTC by c-monkey

Fixes a unit conversion bug where DateTime results in data criteria and in components are represented as seconds rather than milliseconds for CQL times.

Pull requests into Bonnie require the following. Submitter and reviewer should :white_check_mark: when done. For items that are not-applicable, note it's not-applicable ("N/A") and :white_check_mark:.

**Submitter:**
- [X] This pull request describes why these changes were made.
- [X] This PR is into the correct branch.
- [X] JIRA ticket for this PR: https://jira.mitre.org/browse/BONNIE-1580
- [ ] JIRA ticket links to this PR
- [X] Code diff has been done and been reviewed (it **does not** contain: additional white space, not applicable code changes, debug statements, etc.)
- [X] If UI changes have been made, google WAVE plug-in has been executed to ensure no 508 issues were introduced. N/A
- [X] Tests are included and test edge cases
- [X] Tests have been run locally and pass (remember to update Gemfile when applicable)
- [X] Test fixtures updated and documented as necessary ( see [internal wiki](https://gitlab.mitre.org/bonnie/internal-documentation/wikis/testing#test-fixtures) )
- [X] Code coverage has not gone down and all code touched or added is covered. 
     * In rare situations, this may not be possible or applicable to a PR. In those situations:
         1. Note why this could not be done or is not applicable here: 
         2. Add TODOs in the code noting that it requires a test
         3. Add a JIRA task to add the test and link it here: 

Branch | Back End Coverage | Front End Coverage
-- | -- | --
master | [Paste Output Here] | [Paste Screenshot Here]
[New Branch] | [Paste Output Here] | [Paste Screenshot Here]

- [ ] Automated regression test(s) pass

If JIRA tests were used to supplement or replace automated tests:
- [ ] ~~JIRA test links~~
- [ ] ~~Justification for using JIRA tests~~
- [ ] ~~JIRA tests have been added to sprint~~

**Reviewer 1:**

Name:
- [ ] Code is maintainable and reusable, reuses existing code and infrastructure where appropriate, and accomplishes the task’s purpose
- [ ] The tests appropriately test the new code, including edge cases
- [ ] You have tried to break the code

**Reviewer 2:**

Name:
- [ ] Code is maintainable and reusable, reuses existing code and infrastructure where appropriate, and accomplishes the task’s purpose
- [ ] The tests appropriately test the new code, including edge cases
- [ ] You have tried to break the code

2018-08-01 15:13 UTC, c-monkey commented
Note, this fixes https://oncprojectracking.healthit.gov/support/browse/BONNIE-485. To test you need to modify the Assessment RESULT value to be a dateTime.

2018-08-01 16:37 UTC, edeyoung requested changes
see comments

2018-08-01 16:37 UTC, edeyoung commented on lib/measures/patient_builder.rb
> +          time = HQMF::Range.from_json('low' => {'value' => result_value['value']/1000, 'unit' => 'UnixTime'})
add comments explaining this change

2018-08-01 16:37 UTC, edeyoung commented on test/functional/patient_builder_test.rb
> +    record = Record.where(last: 'NoNumerator').first
why are two records tested? does numerator vs no numerator change things? if so, recommend leaving a comment.

2018-08-01 17:22 UTC, c-monkey commented on test/functional/patient_builder_test.rb
> +    record = Record.where(last: 'NoNumerator').first
This only changes things calculated in the front-end. I removed the redundant test cases. The JIRA test demonstrates how the newly converted times work correctly with the logic.

2018-08-01 18:13 UTC, edeyoung approved these changes

2018-08-02 17:36 UTC, mayerm94 requested changes
I think there may be a problem with serializing the result datetime out of the database. When I open CMS879, the patient 'Numerator Test' is not a part of the IPP, if I delete the Result DateTime and add it back in (same date), the patient then passes. NOTE: I can only replicate this with a fresh DB snapshot, once I modify the result date, save and re-open it works fine.

2018-08-02 17:47 UTC, c-monkey commented
This is because the fixtures are created on the bonnie.healthit.gov website which doesn't have the new code.

I guess after deployed we should update the results and replace the fixture. To update, just, change the patient's name and change focus, then change it back. Whatever is required to do the materialize.

2018-08-02 18:16 UTC, mayerm94 approved these changes

2018-08-07 20:02 UTC, merged