Sort keys in objects for prettyResult and update gemfile with id changes
MeasureAuthoringTool/bonnie pull request #1062
Opened 2018-08-24 18:38 UTC by hossenlopp

Pull requests into Bonnie require the following. Submitter and reviewer should :white_check_mark: when done. For items that are not-applicable, note it's not-applicable ("N/A") and :white_check_mark:.

**Submitter:**
- [ ] This pull request describes why these changes were made.
- [ ] This PR is into the correct branch.
- [ ] JIRA ticket for this PR:
- [ ] JIRA ticket links to this PR
- [ ] Code diff has been done and been reviewed (it **does not** contain: additional white space, not applicable code changes, debug statements, etc.)
- [ ] If UI changes have been made, google WAVE plug-in has been executed to ensure no 508 issues were introduced.
- [ ] Tests are included and test edge cases
- [ ] Tests have been run locally and pass (remember to update Gemfile when applicable)
- [ ] Test fixtures updated and documented as necessary ( see [internal wiki](https://gitlab.mitre.org/bonnie/internal-documentation/wikis/testing#test-fixtures) )
- [ ] Code coverage has not gone down and all code touched or added is covered. 
     * In rare situations, this may not be possible or applicable to a PR. In those situations:
         1. Note why this could not be done or is not applicable here: 
         2. Add TODOs in the code noting that it requires a test
         3. Add a JIRA task to add the test and link it here: 

Branch | Back End Coverage | Front End Coverage
-- | -- | --
master | [Paste Output Here] | [Paste Screenshot Here]
[New Branch] | [Paste Output Here] | [Paste Screenshot Here]

- [ ] Automated regression test(s) pass

If JIRA tests were used to supplement or replace automated tests:
- [ ] JIRA test links:
- [ ] Justification for using JIRA tests:
- [ ] JIRA tests have been added to sprint

**Reviewer 1:**

Name:
- [ ] Code is maintainable and reusable, reuses existing code and infrastructure where appropriate, and accomplishes the task’s purpose
- [ ] The tests appropriately test the new code, including edge cases
- [ ] You have tried to break the code

If JIRA tests were used to supplement or replace automated tests:
- [ ] JIRA tests have been run and pass
- [ ] You agree with the justification for use of JIRA tests or have provided input on why you disagree

**Reviewer 2:**

Name:
- [ ] Code is maintainable and reusable, reuses existing code and infrastructure where appropriate, and accomplishes the task’s purpose
- [ ] The tests appropriately test the new code, including edge cases
- [ ] You have tried to break the code

If JIRA tests were used to supplement or replace automated tests:
- [ ] JIRA tests have been run and pass
- [ ] You agree with the justification for use of JIRA tests or have provided input on why you disagree

2018-08-27 13:42 UTC, losborne commented on spec/javascripts/helper_specs/cql_results_helpers_spec.js.coffee
>        prettyNestedObject = """
Since this test is now checking both for indentation and sorting, I would update the test description.  It would also be good to make the doubleNested keys out of order to show that those are sorted as well.

2018-08-27 14:03 UTC, daco101 requested changes

2018-08-27 14:03 UTC, daco101 commented on app/assets/javascripts/helpers/cql_results_helpers.js.coffee
> +      sortedKeys = Object.keys(result).sort()
It looks like coffeescript "for key, value of object" will include the object's own properties as well as inherited ones, but "Object.keys(object)" only includes the object's own properties. Not sure if we even want to include inherited properties in the pretty result though.

2018-08-27 17:33 UTC, hossenlopp commented on app/assets/javascripts/helpers/cql_results_helpers.js.coffee
> +      sortedKeys = Object.keys(result).sort()
The old code was using both the `for key, value of result` for iteration and `Object.keys` in determining (potentially unsuccessfully) the last key... so picking one and sticking with it is an improvement. At least in the front end, any objects that end up here will not have a prototype hierarchy. These are either CQL Tuples which are just plain objects or CQL_QDM basetypes.

2018-08-27 22:03 UTC, hossenlopp commented
Travis failure is from bundler-audit. Will not be resolved in this PR.

2018-08-28 13:00 UTC, lukoktonos approved these changes

2018-08-28 17:09 UTC, daco101 commented on app/assets/javascripts/helpers/cql_results_helpers.js.coffee
> +      sortedKeys = Object.keys(result).sort()
Makes sense to me.

2018-08-28 17:09 UTC, daco101 approved these changes

2018-08-28 17:39 UTC, merged