Composite measures patient sharing and excel export
MeasureAuthoringTool/bonnie pull request #1093
Opened 2018-10-26 21:15 UTC by daco101

This PR adds support for sharing patients across all children of a composite measure, and fixes excel exports for shared patients.

Pull requests into Bonnie require the following. Submitter and reviewer should :white_check_mark: when done. For items that are not-applicable, note it's not-applicable ("N/A") and :white_check_mark:.

**Submitter:**
- [x] This pull request describes why these changes were made.
- [x] This PR is into the correct branch.
- [x] JIRA ticket for this PR: https://jira.mitre.org/browse/BONNIE-1755, https://jira.mitre.org/browse/BONNIE-1754
- [x] JIRA ticket links to this PR
- [ ] Code diff has been done and been reviewed (it **does not** contain: additional white space, not applicable code changes, debug statements, etc.)
- [x] NA If UI changes have been made, google WAVE plug-in has been executed to ensure no 508 issues were introduced.
- [x] Tests are included and test edge cases
- [ ] Tests have been run locally and pass (remember to update Gemfile when applicable)
- [ ] Test fixtures updated and documented as necessary ( see [internal wiki](https://gitlab.mitre.org/bonnie/internal-documentation/wikis/testing#test-fixtures) )
- [ ] Code coverage has not gone down and all code touched or added is covered. 
     * In rare situations, this may not be possible or applicable to a PR. In those situations:
         1. Note why this could not be done or is not applicable here: 
         2. Add TODOs in the code noting that it requires a test
         3. Add a JIRA task to add the test and link it here: 

Branch | Back End Coverage | Front End Coverage
-- | -- | --
master | [Paste Output Here] | [Paste Screenshot Here]
[New Branch] | [Paste Output Here] | [Paste Screenshot Here]

- [ ] Automated regression test(s) pass

If JIRA tests were used to supplement or replace automated tests:
- [ ] JIRA test links:
- [ ] Justification for using JIRA tests:
- [ ] JIRA tests have been added to sprint

**Reviewer 1:**

Name:
- [ ] Code is maintainable and reusable, reuses existing code and infrastructure where appropriate, and accomplishes the task’s purpose
- [ ] The tests appropriately test the new code, including edge cases
- [ ] You have tried to break the code

If JIRA tests were used to supplement or replace automated tests:
- [ ] JIRA tests have been run and pass
- [ ] You agree with the justification for use of JIRA tests or have provided input on why you disagree

**Reviewer 2:**

Name:
- [ ] Code is maintainable and reusable, reuses existing code and infrastructure where appropriate, and accomplishes the task’s purpose
- [ ] The tests appropriately test the new code, including edge cases
- [ ] You have tried to break the code

If JIRA tests were used to supplement or replace automated tests:
- [ ] JIRA tests have been run and pass
- [ ] You agree with the justification for use of JIRA tests or have provided input on why you disagree

2018-10-29 12:56 UTC, lukoktonos requested changes
Will need rebase once `composite_measures` and `composite_measures_dashboard` are passing.

2018-10-29 12:56 UTC, losborne commented on app/controllers/api_v1/measures_controller.rb
> +        excel_package = PatientExport.export_excel_cql_file(converted_results, patient_details, population_details, statement_details, @api_v1_measure.hqmf_set_id)
`@api_v1_measure.hqmf_set_id` is accessible as `hqmf_set_id`

2018-10-29 12:56 UTC, losborne commented on app/controllers/api_v1/measures_controller.rb
> +        # require 'pry'; binding.pry
This should go away after rebase(s), as it was taken out of the composite_measures branch, I believe.

2018-10-29 12:56 UTC, losborne commented on app/controllers/patients_controller.rb
> +    # if the patient has any existing measure ids that correspond to child composite measures, all sibling measure ids will be added
I think 'child composite measures' should be 'component measures'

2018-10-29 12:56 UTC, losborne commented on app/controllers/patients_controller.rb
> +      parent_measure = CqlMeasure.only(:components).where(hqmf_set_id: parent_measure_id).first
This logic assumes that all composite measures with a given hqmf_set_id will have the same component measures.  What if two different accounts have different versions of the composite measure that have different components?

2018-10-29 12:56 UTC, losborne commented on test/functional/api_v1/measures_controller_backend_calc_test.rb
> +    test "should calculate result excel sheet with correct expected values for shared patient in composite measure" do
composite -> component

2018-10-29 12:56 UTC, losborne commented on test/test_helper.rb
> +        # end
extra `# end`

2018-10-31 10:50 UTC, jbradl11 commented on app/controllers/patients_controller.rb
> +      next if measure_id.nil? || measure_id.length <= 36 || measure_id[36] != '&'
Does the standard say this is the expected length? What situation are you guarding against with the `measure_id.length <= 36`?

2018-10-31 10:59 UTC, jbradl11 commented on app/controllers/patients_controller.rb
> +      parent_measure_ids << measure_id[0..35]
If the length isn't guaranteed, I think you could do something like

` parent_measure_ids << measure_id.split('&').first`

2018-10-31 11:08 UTC, jbradl11 commented on lib/patient_export.rb
> +              evs = patient_details[patient_key]["expected_values"].detect { |ev| ev["measure_id"]==measure_hqmf_set_id && ev["population_index"]==pop_index }
I recommend changing the variable name `evs` to something a little more intuitive.

2018-11-01 19:01 UTC, lukoktonos requested changes

2018-11-01 19:01 UTC, lukoktonos commented on app/assets/javascripts/router.js.coffee.erb
> +
Some extra whitespace added here

2018-11-01 19:01 UTC, lukoktonos commented on app/assets/javascripts/templates/breadcrumb.hbs
> +      <li>{{#link "measures/{{this.hqmf_set_id}}" expand-tokens=true}}<i class='fa fa-fw fa-tasks' aria-hidden='true'></i> {{this.cms_id}} {{/link}}</li>
should be able to do just `hqmf_set_id` and `cms_id` without the `this.`

2018-11-01 19:01 UTC, lukoktonos commented on app/assets/javascripts/templates/patient_builder/patient_builder.hbs
> +          <label for="{{#if expired}}deathdate{{else}}expired{{/if}}" class="control-label">{{#if expired}}Date of
Are these and similar whitespace changes in this file done automatically by your IDE?  I'm not necessarily opposed to shorter lines, but in this case it doesn't seem right to break in the middle of the text.

2018-11-01 19:01 UTC, lukoktonos commented on app/assets/javascripts/views/breadcrumb.js.coffee
> +      measureHierarchy: (m.toJSON() for m in measureHierarchy)
Would use `measure` rather than `m`

2018-11-01 19:01 UTC, lukoktonos commented on app/assets/javascripts/views/breadcrumb.js.coffee
> +      measureHierarchy: (m.toJSON() for m in measureHierarchy)
Same as above, prefer `measure` to `m` here.

2018-11-01 19:01 UTC, lukoktonos commented on app/assets/javascripts/views/breadcrumb.js.coffee
> +      measureHierarchy: (m.toJSON() for m in measureHierarchy)
Same as above

2018-11-01 19:01 UTC, lukoktonos commented on app/assets/javascripts/views/patient_builder/patient_builder.js.coffee
> +    unless @measure.get('component')
I think `if...else` is easier to read for this since they are checking the same thing

2018-11-02 13:21 UTC, daco101 commented on app/assets/javascripts/templates/breadcrumb.hbs
> +      <li>{{#link "measures/{{this.hqmf_set_id}}" expand-tokens=true}}<i class='fa fa-fw fa-tasks' aria-hidden='true'></i> {{this.cms_id}} {{/link}}</li>
Do you think we have a style norm against doing it this way? I prefer being explicit, or else there is no way of knowing whether you are expecting hqmf_set_id to be part of a measure object, or if you are looking for something higher up the context chain.

2018-11-02 13:32 UTC, daco101 commented on app/assets/javascripts/views/patient_builder/patient_builder.js.coffee
> +    unless @measure.get('component')
Yah, I thought about this but decided against it since I thought the logic for whether or not to show the value set warning was conceptually separate from whether to show the composite sharing message, let me know if you feel strongly.

2018-11-02 13:59 UTC, losborne commented on app/assets/javascripts/views/patient_builder/patient_builder.js.coffee
> +    unless @measure.get('component')
That's fine, just a style choice

2018-11-02 14:01 UTC, losborne commented on app/assets/javascripts/templates/breadcrumb.hbs
> +      <li>{{#link "measures/{{this.hqmf_set_id}}" expand-tokens=true}}<i class='fa fa-fw fa-tasks' aria-hidden='true'></i> {{this.cms_id}} {{/link}}</li>
That's works for me

2018-11-02 15:10 UTC, daco101 commented on app/assets/javascripts/templates/patient_builder/patient_builder.hbs
> +          <label for="{{#if expired}}deathdate{{else}}expired{{/if}}" class="control-label">{{#if expired}}Date of
Yes, sorry it was an IDE plugin.

2018-11-02 15:57 UTC, jbradl11 commented on app/controllers/patients_controller.rb
> +      # composite hqmf set ids are two ids with '&' in between
I believe you mean `component` not `composite`

2018-11-02 16:26 UTC, jbradl11 commented on app/assets/javascripts/views/patient_builder/composite_sharing_warning.js.coffee
> +# and @measure instance variables, which we just use to set up the appropriate context
Need to update these comments.

2018-11-02 16:40 UTC, jbradl11 commented on test/test_helper.rb
> +          Mongoid.default_client[collection_name].insert_one(fj)
What is going on here?

2018-11-07 14:23 UTC, closed without merging