Fixture generation for composite measures
MeasureAuthoringTool/bonnie pull request #1107
Opened 2018-11-19 13:15 UTC by daco101

This PR refactors some of the fixture generation task, and makes it so for composite measures, all components are exported and all of their valuesets are in the fixture. It also changes it so for the backend fixtures, all bson objects ids are turned into "$oids", and it updates the fixture import step to support this.

Style feedback is especially welcome on this PR since I am trying to follow some clean code guidelines.

Pull requests into Bonnie require the following. Submitter and reviewer should :white_check_mark: when done. For items that are not-applicable, note it's not-applicable ("N/A") and :white_check_mark:.

**Submitter:**
- [x] This pull request describes why these changes were made.
- [x] This PR is into the correct branch.
- [x] JIRA ticket for this PR: https://jira.mitre.org/browse/BONNIE-1809
- [ ] JIRA ticket links to this PR
- [x] Code diff has been done and been reviewed (it **does not** contain: additional white space, not applicable code changes, debug statements, etc.)
- [x] NA If UI changes have been made, google WAVE plug-in has been executed to ensure no 508 issues were introduced.
- [x] NA Tests are included and test edge cases
- [x] Tests have been run locally and pass (remember to update Gemfile when applicable)
- [x] NA Test fixtures updated and documented as necessary ( see [internal wiki](https://gitlab.mitre.org/bonnie/internal-documentation/wikis/testing#test-fixtures) )
- [ ] Code coverage has not gone down and all code touched or added is covered. 
     * In rare situations, this may not be possible or applicable to a PR. In those situations:
         1. Note why this could not be done or is not applicable here: 
         2. Add TODOs in the code noting that it requires a test
         3. Add a JIRA task to add the test and link it here: 

Branch | Back End Coverage | Front End Coverage
-- | -- | --
master | [Paste Output Here] | [Paste Screenshot Here]
[New Branch] | [Paste Output Here] | [Paste Screenshot Here]

- [x] NA Automated regression test(s) pass

If JIRA tests were used to supplement or replace automated tests:
- [x] NA JIRA test links:
- [x] NA Justification for using JIRA tests:
- [x] NA JIRA tests have been added to sprint

**Reviewer 1:**

Name:
- [ ] Code is maintainable and reusable, reuses existing code and infrastructure where appropriate, and accomplishes the task’s purpose
- [ ] The tests appropriately test the new code, including edge cases
- [ ] You have tried to break the code

If JIRA tests were used to supplement or replace automated tests:
- [ ] JIRA tests have been run and pass
- [ ] You agree with the justification for use of JIRA tests or have provided input on why you disagree

**Reviewer 2:**

Name:
- [ ] Code is maintainable and reusable, reuses existing code and infrastructure where appropriate, and accomplishes the task’s purpose
- [ ] The tests appropriately test the new code, including edge cases
- [ ] You have tried to break the code

If JIRA tests were used to supplement or replace automated tests:
- [ ] JIRA tests have been run and pass
- [ ] You agree with the justification for use of JIRA tests or have provided input on why you disagree

2018-11-21 12:26 UTC, hossenlopp commented on lib/tasks/fixture_exporter.rb
> +class FixtureExporter
This is fantastic having the fixture export stuff moved to its own file. But I think it should not be in `lib/tasks` since it isn't a Rake task itself. Perhaps just in `lib` or maybe `lib/util`.

2018-11-21 12:44 UTC, lukoktonos requested changes
Stylistic suggestions (optional) included along with a minor whitespace issue.

2018-11-21 12:44 UTC, losborne commented on lib/tasks/fixture_exporter.rb
> +          input[key] = { '$oid' => value.to_s}
Space missing: `{ '$oid' => value.to_s}` -> `{ '$oid' => value.to_s }`

2018-11-21 12:44 UTC, losborne commented on lib/tasks/fixture_exporter.rb
> +    relevant_vs_version = get_version_of_relevant_valuesets(measure)
I think `get_version_of_relevant_valuesets` should be `get_relevant_version_of_valuesets(measure)` or even `get_draft_version_of_valuesets(measure)`.

2018-11-21 12:44 UTC, losborne commented on lib/tasks/cql_testing.rake
> +                                              preserve_oids: true)
Rather than use the boolean `preserve_oids` to implement polymorphism, we can either preserve oids for both frontend and backend fixtures (and load them appropriately with a helper function for frontend ones like we do with backend ones, or else have a `FrontendFixtureExporter` and a `BackendFixtureExporter` that derive from `FixtureExporter` that behave appropriately.

2018-11-26 12:52 UTC, lukoktonos requested changes

2018-11-26 12:52 UTC, losborne commented on lib/util/fixture_exporter.rb
> +  def export_components(path)
With this moved here, the `def export_components(...)` in `lib/tasks/cql_testing.rake` can now be deleted.

2018-11-26 12:52 UTC, losborne commented on lib/util/fixture_exporter.rb
> +class FixtureExporter
This file is uncovered and causing the coverage to drop below the threshold. I think it's fine to ignore this file for coverage calculations, as it is for testing only.

2018-11-29 15:56 UTC, lukoktonos approved these changes

2018-11-29 16:05 UTC, hossenlopp approved these changes

2018-11-29 16:07 UTC, merged