Added persistent banner warning users about the retirement of bonnie-qdm
MeasureAuthoringTool/bonnie pull request #1168
Opened 2019-01-11 19:58 UTC by zlister

Pull requests into Bonnie require the following. Submitter and reviewer should :white_check_mark: when done. For items that are not-applicable, note it's not-applicable ("N/A") and :white_check_mark:.

**Submitter:**
- [x] This pull request describes why these changes were made.
- [x] This PR is into the correct branch.
- [ ] JIRA ticket for this PR:
- [ ] JIRA ticket links to this PR
- [ ] Code diff has been done and been reviewed (it **does not** contain: additional white space, not applicable code changes, debug statements, etc.)
- [ ] If UI changes have been made, google WAVE plug-in has been executed to ensure no 508 issues were introduced.
- [ ] Tests are included and test edge cases
- [ ] Tests have been run locally and pass (remember to update Gemfile when applicable)
- [ ] Test fixtures updated and documented as necessary ( see [internal wiki](https://gitlab.mitre.org/bonnie/internal-documentation/wikis/testing#test-fixtures) )
- [ ] Code coverage has not gone down and all code touched or added is covered. 
     * In rare situations, this may not be possible or applicable to a PR. In those situations:
         1. Note why this could not be done or is not applicable here: 
         2. Add TODOs in the code noting that it requires a test
         3. Add a JIRA task to add the test and link it here: 
- [ ] Automated regression test(s) pass

If JIRA tests were used to supplement or replace automated tests:
- [ ] JIRA test links:
- [ ] Justification for using JIRA tests:
- [ ] JIRA tests have been added to sprint

**Reviewer 1:**

Name:
- [ ] Code is maintainable and reusable, reuses existing code and infrastructure where appropriate, and accomplishes the task’s purpose
- [ ] The tests appropriately test the new code, including edge cases
- [ ] You have tried to break the code

If JIRA tests were used to supplement or replace automated tests:
- [ ] JIRA tests have been run and pass
- [ ] You agree with the justification for use of JIRA tests or have provided input on why you disagree

**Reviewer 2:**

Name:
- [ ] Code is maintainable and reusable, reuses existing code and infrastructure where appropriate, and accomplishes the task’s purpose
- [ ] The tests appropriately test the new code, including edge cases
- [ ] You have tried to break the code

If JIRA tests were used to supplement or replace automated tests:
- [ ] JIRA tests have been run and pass
- [ ] You agree with the justification for use of JIRA tests or have provided input on why you disagree

2019-01-14 01:22 UTC, jbradl11 commented
This is a good start. But it should also be visible on the Homepage and Login page. We should discuss the wording, color and size of the banner.

2019-01-14 21:38 UTC, zlister commented
<img width="1277" alt="screen shot 2019-01-14 at 4 10 23 pm" src="https://user-images.githubusercontent.com/5925802/51142798-db5c8200-181a-11e9-81be-9fd707760d02.png">

2019-01-14 21:41 UTC, zlister commented
[screencapture-localhost-3000-users-sign_in-2019-01-14-16_41_13.pdf](https://github.com/projecttacoma/bonnie/files/2757176/screencapture-localhost-3000-users-sign_in-2019-01-14-16_41_13.pdf)

2019-01-14 21:41 UTC, zlister commented
[screencapture-localhost-3000-users-sign_in-2019-01-14-16_41_13.pdf](https://github.com/projecttacoma/bonnie/files/2757180/screencapture-localhost-3000-users-sign_in-2019-01-14-16_41_13.pdf)

2019-01-15 13:19 UTC, lukoktonos requested changes
Currently the banner is duplicated on the Account Page, because the header is also rendered in devise.html.erb in that case:

![image](https://user-images.githubusercontent.com/14879344/51183133-5f0b8280-189e-11e9-9767-4b027a6f6fd8.png)

2019-01-15 13:19 UTC, losborne commented on app/views/layouts/devise.html.erb
> +    <div class="alert alert-danger"><p style="text-align: center;"><span style="font-size: 16pt;">
Since this `div` is duplicated from above, you should pull both of them into `qdm_retirement_banner.html.erb` or similar then `<%= render 'layouts/qdm_retirement_banner' %>` here and above.

2019-01-16 13:25 UTC, lukoktonos approved these changes

2019-01-16 13:28 UTC, jbradl11 approved these changes

2019-01-16 13:29 UTC, merged