Updated readme
MeasureAuthoringTool/bonnie pull request #1171
Opened 2019-01-17 18:21 UTC by jbradl11

Pull requests into Bonnie require the following. Submitter and reviewer should :white_check_mark: when done. For items that are not-applicable, note it's not-applicable ("N/A") and :white_check_mark:.

Updated README, added LICENSE and notice.md file

**Submitter:**
- [ ] This pull request describes why these changes were made.
- [ ] This PR is into the correct branch.
- [ ] JIRA ticket for this PR:
- [ ] JIRA ticket links to this PR
- [ ] Code diff has been done and been reviewed (it **does not** contain: additional white space, not applicable code changes, debug statements, etc.)
- [ ] If UI changes have been made, google WAVE plug-in has been executed to ensure no 508 issues were introduced.
- [ ] Tests are included and test edge cases
- [ ] Tests have been run locally and pass (remember to update Gemfile when applicable)
- [ ] Test fixtures updated and documented as necessary ( see [internal wiki](https://gitlab.mitre.org/bonnie/internal-documentation/wikis/testing#test-fixtures) )
- [ ] Code coverage has not gone down and all code touched or added is covered. 
     * In rare situations, this may not be possible or applicable to a PR. In those situations:
         1. Note why this could not be done or is not applicable here: 
         2. Add TODOs in the code noting that it requires a test
         3. Add a JIRA task to add the test and link it here: 
- [ ] Automated regression test(s) pass

If JIRA tests were used to supplement or replace automated tests:
- [ ] JIRA test links:
- [ ] Justification for using JIRA tests:
- [ ] JIRA tests have been added to sprint

**Reviewer 1:**

Name:
- [ ] Code is maintainable and reusable, reuses existing code and infrastructure where appropriate, and accomplishes the task’s purpose
- [ ] The tests appropriately test the new code, including edge cases
- [ ] You have tried to break the code

If JIRA tests were used to supplement or replace automated tests:
- [ ] JIRA tests have been run and pass
- [ ] You agree with the justification for use of JIRA tests or have provided input on why you disagree

**Reviewer 2:**

Name:
- [ ] Code is maintainable and reusable, reuses existing code and infrastructure where appropriate, and accomplishes the task’s purpose
- [ ] The tests appropriately test the new code, including edge cases
- [ ] You have tried to break the code

If JIRA tests were used to supplement or replace automated tests:
- [ ] JIRA tests have been run and pass
- [ ] You agree with the justification for use of JIRA tests or have provided input on why you disagree

2019-01-17 18:33 UTC, lukoktonos submitted a review, later dismissed

2019-01-17 18:33 UTC, losborne commented on README.md
> +[![Build Status](https://travis-ci.org/projecttacoma/bonnie.svg?branch=master)](https://travis-ci.org/projecttacoma/bonnie)
This should be travis-ci.com

2019-01-17 18:56 UTC, lukoktonos submitted a review, later dismissed

2019-01-28 13:45 UTC, edeyoung requested changes

2019-01-28 13:45 UTC, edeyoung commented on README.md
> +Bonnie is designed to support streamlined and efficient pre-testing of eCQMs, particularly those used in the Centers for Medicare & Medicaid Services (CMS) quality reporting programs.
i think bonnie deserves more description.
can you use the intro to the user guide?
what about qrda exporting? that covers another user base

2019-01-28 13:45 UTC, edeyoung commented on README.md
> +## Issues Reporting
```suggestion
## Reporting Issues
```

2019-02-04 16:52 UTC, edeyoung commented on README.md
> +Bonnie is designed to support streamlined and efficient pre-testing of eCQMs, particularly those used in the Centers for Medicare & Medicaid Services (CMS) quality reporting programs.
```suggestion
Bonnie is a software tool that allows electronic clinical quality measure (eCQM) developers to
test and verify the behavior of their eCQM logic. The main goal of the Bonnie application is to
reduce the number of defects in eCQMs by providing a robust and automated testing framework.
The Bonnie application allows measure developers to independently load measures that they
have constructed using the Measure Authoring Tool (MAT). Developers can then use the
measure metadata to build a synthetic patient test deck for the measure from the clinical elements
defined during the measure construction process. By using measure metadata as a basis for
building synthetic patients, developers can quickly and efficiently create a test deck for a
measure. The Bonnie application helps measure developers execute the measure logic against the
constructed patient test deck and evaluate whether the logic aligns with the intent of the measure. Additionally, Bonnie allows users to export their synthetic patient test deck in the Quality Reporting Document Architecture (QRDA) Category 1 data standard to enable them to more easily test their own systems. 

Bonnie has been designed to integrate with the nationally recognized data standards the Centers
for Medicare & Medicaid Services (CMS) quality reporting programs use for expressing eCQM
logic for machine-to-machine interoperability. This integration provides enormous value to the
eCQM program and federal policy leaders and stakeholders. The Bonnie tool verifies that the
new and evolving standards for eCQMs used in the CMS quality reporting programs are flexible
and can be implemented in software.
```

2019-02-04 16:53 UTC, edeyoung commented on README.md
> +Bonnie is designed to support streamlined and efficient pre-testing of eCQMs, particularly those used in the Centers for Medicare & Medicaid Services (CMS) quality reporting programs.
ewww... copy/pasted and didn't realize the returns were included. Will remove.

2019-02-21 19:00 UTC, edeyoung approved these changes

2019-02-21 20:52 UTC, lukoktonos approved these changes

2019-02-21 20:53 UTC, merged