Cqm parsers integration
MeasureAuthoringTool/bonnie pull request #1179
Opened 2019-02-15 20:56 UTC by daco101

wip
Pull requests into Bonnie require the following. Submitter and reviewer should :white_check_mark: when done. For items that are not-applicable, note it's not-applicable ("N/A") and :white_check_mark:.

**Submitter:**
- [ ] This pull request describes why these changes were made.
- [ ] This PR is into the correct branch.
- [ ] JIRA ticket for this PR:
- [ ] JIRA ticket links to this PR
- [ ] Code diff has been done and been reviewed (it **does not** contain: additional white space, not applicable code changes, debug statements, etc.)
- [ ] If UI changes have been made, google WAVE plug-in has been executed to ensure no 508 issues were introduced.
- [ ] Tests are included and test edge cases
- [ ] Tests have been run locally and pass (remember to update Gemfile when applicable)
- [ ] Test fixtures updated and documented as necessary ( see [internal wiki](https://gitlab.mitre.org/bonnie/internal-documentation/wikis/testing#test-fixtures) )
- [ ] Code coverage has not gone down and all code touched or added is covered. 
     * In rare situations, this may not be possible or applicable to a PR. In those situations:
         1. Note why this could not be done or is not applicable here: 
         2. Add TODOs in the code noting that it requires a test
         3. Add a JIRA task to add the test and link it here: 
- [ ] Automated regression test(s) pass

If JIRA tests were used to supplement or replace automated tests:
- [ ] JIRA test links:
- [ ] Justification for using JIRA tests:
- [ ] JIRA tests have been added to sprint

**Reviewer 1:**

Name:
- [ ] Code is maintainable and reusable, reuses existing code and infrastructure where appropriate, and accomplishes the task’s purpose
- [ ] The tests appropriately test the new code, including edge cases
- [ ] You have tried to break the code

If JIRA tests were used to supplement or replace automated tests:
- [ ] JIRA tests have been run and pass
- [ ] You agree with the justification for use of JIRA tests or have provided input on why you disagree

**Reviewer 2:**

Name:
- [ ] Code is maintainable and reusable, reuses existing code and infrastructure where appropriate, and accomplishes the task’s purpose
- [ ] The tests appropriately test the new code, including edge cases
- [ ] You have tried to break the code

If JIRA tests were used to supplement or replace automated tests:
- [ ] JIRA tests have been run and pass
- [ ] You agree with the justification for use of JIRA tests or have provided input on why you disagree

2019-03-01 18:13 UTC, lukoktonos requested changes

2019-03-01 18:13 UTC, lukoktonos commented on .rubocop_todo.yml
> +  Enabled: false
<3

2019-03-01 18:13 UTC, lukoktonos commented on app/controllers/api_v1/measures_controller.rb
> +        @api_v1_measure = CQM::Measure.by_user(current_resource_owner).where({:hqmf_set_id=> params[:id]}).min_by { |m| m[:updated_at] }
Nice!

2019-03-01 18:13 UTC, lukoktonos commented on app/controllers/api_v1/measures_controller.rb
> +        'calculate_sdes' => params[:calculate_sdes].nil? ? false : params[:calculate_sdes].to_s == 'true',
I think `params[:calculate_sdes].to_s == 'true'` is enough--it should return false if `params[:calculate_sdes]` is `nil`:
`nil.to_s` -> `''`, `'' == 'true'` -> `false`

2019-03-01 18:13 UTC, lukoktonos commented on app/controllers/measures_controller.rb
> +      # Throw error since component can't be deleted individually
Comment is redundant with error message below and can be removed imo

2019-03-01 18:13 UTC, lukoktonos commented on app/controllers/populations_controller.rb
> +    pop_or_strat = measure.population_sets.select { |ps| ps.population_set_id == params[:id] }.first || measure.all_stratifications.select { |strat| strat.stratification_id == params[:id] }.first
Why the `.first`s on this line? Wouldn't that fail to update ones that aren't first?

2019-03-01 18:13 UTC, lukoktonos commented on test/vcr_setup.rb
> +  st = uri[/(&ticket=.*)&|(&ticket=.*)$/,0]
`st` -> `service_ticket` (st is too close to string imo)

2019-03-01 18:13 UTC, lukoktonos commented on app/helpers/measure_helper.rb
> +    # what is this for?
remove comment

2019-03-01 18:13 UTC, losborne commented on app/helpers/measure_helper.rb
> +    # TODO: make sure this is good.
Is this still in investigation?

2019-03-01 18:13 UTC, losborne commented on app/helpers/measure_helper.rb
> +  def delete_for_update(existing, user)
`delete_for_update` -> `delete_component_measures_for_update`

2019-03-01 18:13 UTC, losborne commented on app/helpers/measure_helper.rb
> +    if error.respond_to?(:operator_error) && error.operator_error && defined? ExceptionNotifier::Notifier # rubocop:disable Style/GuardClause
Is this rubocop comment still needed with your changes in the rubocop file above?

2019-03-01 18:13 UTC, losborne commented on app/helpers/measure_helper.rb
> +      # params[:error_file] = filename  #TODO what is this
Is this TODO still under investigation?

2019-03-01 18:41 UTC, daco101 commented on app/helpers/measure_helper.rb
> +  def delete_for_update(existing, user)
this method deletes the measure and any components

2019-03-01 18:41 UTC, daco101 commented on app/helpers/measure_helper.rb
> +    # what is this for?
do you know what this is for? why do we manually maintain a list of measures on a user?

2019-03-01 18:42 UTC, daco101 commented on app/controllers/populations_controller.rb
> +    pop_or_strat = measure.population_sets.select { |ps| ps.population_set_id == params[:id] }.first || measure.all_stratifications.select { |strat| strat.stratification_id == params[:id] }.first
The ids should be unique, so we only expect to get one pop_or_strat.

2019-03-01 19:18 UTC, losborne commented on app/helpers/measure_helper.rb
> +    # what is this for?
It's the mongoid relationship between the user and the measures.  A User `has_many :cqm_measures`

2019-03-03 16:20 UTC, daco101 commented on app/helpers/measure_helper.rb
> +    # what is this for?
I've confirmed that we do not need to manually maintain this, mongoid will take care of it.

2019-03-04 13:17 UTC, losborne commented on app/helpers/measure_helper.rb
> +    # what is this for?
Interesting--so we can remove this then?

2019-03-04 20:22 UTC, hackrm commented on app/controllers/api_v1/measures_controller.rb
> +        'population_titles' => params[:population_titles]
Is there a reason why 'population_titles' is included in this _retrieve_measure_details()_ function but not in [this one](https://github.com/projecttacoma/bonnie/pull/1179/files#diff-9f6c25d2ea5170e4953a469c855a47d4R113) from app/controllers/measures_controller.rb?

2019-03-04 20:59 UTC, hossenlopp commented on app/controllers/api_v1/measures_controller.rb
> +        'population_titles' => params[:population_titles]
The API allows the API user to optionally provide the titles for the populations on upload. In the Bonnie frontend the measure upload does not ask for them. We ask the user after it uploads if they want to change the titles from a default.

2019-03-04 21:15 UTC, hackrm commented on app/controllers/api_v1/measures_controller.rb
> +        'population_titles' => params[:population_titles]
Thanks for the explanation!

2019-03-08 13:10 UTC, daco101 commented on app/helpers/measure_helper.rb
> +    if error.respond_to?(:operator_error) && error.operator_error && defined? ExceptionNotifier::Notifier # rubocop:disable Style/GuardClause
Yes, im open to suggestions though.

2019-03-08 13:10 UTC, daco101 commented on app/helpers/measure_helper.rb
> +      # params[:error_file] = filename  #TODO what is this
I just decided to delete the line. I can't see that it ever did anything.

2019-03-08 17:37 UTC, lukoktonos approved these changes
Looks good. Manual testing is showing consistent performance now with quite a significant speed up in measure upload.  Great work!

2019-03-08 20:27 UTC, hackrm commented
I know some tests are skipped for work that will be done in the future. If this hasn't been done already, would it be helpful add references to these skipped test to the description of those relevant tasks? That way the person completing the task knows to go back and update those specific tests.

2019-03-08 20:38 UTC, hackrm approved these changes
Besides the little tip I left earlier, it looks good to me!

2019-03-11 15:16 UTC, merged