Verification function for the convert measures rake task
MeasureAuthoringTool/bonnie pull request #1208
Opened 2019-04-19 12:05 UTC by hackrm

Pull requests into Bonnie require the following. Submitter and reviewer should :white_check_mark: when done. For items that are not-applicable, note it's not-applicable ("N/A") and :white_check_mark:.

**Submitter:**
- [ ] This pull request describes why these changes were made.
- [ ] This PR is into the correct branch.
- [ ] JIRA ticket for this PR:
- [ ] JIRA ticket links to this PR
- [ ] Code diff has been done and been reviewed (it **does not** contain: additional white space, not applicable code changes, debug statements, etc.)
- [ ] If UI changes have been made, google WAVE plug-in has been executed to ensure no 508 issues were introduced.
- [ ] Tests are included and test edge cases
- [ ] Tests have been run locally and pass (remember to update Gemfile when applicable)
- [ ] Test fixtures updated and documented as necessary ( see [internal wiki](https://gitlab.mitre.org/bonnie/internal-documentation/wikis/testing#test-fixtures) )
- [ ] Code coverage has not gone down and all code touched or added is covered. 
     * In rare situations, this may not be possible or applicable to a PR. In those situations:
         1. Note why this could not be done or is not applicable here: 
         2. Add TODOs in the code noting that it requires a test
         3. Add a JIRA task to add the test and link it here: 
- [ ] Automated regression test(s) pass

If JIRA tests were used to supplement or replace automated tests:
- [ ] JIRA test links:
- [ ] Justification for using JIRA tests:
- [ ] JIRA tests have been added to sprint

**Reviewer 1:**

Name:
- [ ] Code is maintainable and reusable, reuses existing code and infrastructure where appropriate, and accomplishes the task’s purpose
- [ ] The tests appropriately test the new code, including edge cases
- [ ] You have tried to break the code

If JIRA tests were used to supplement or replace automated tests:
- [ ] JIRA tests have been run and pass
- [ ] You agree with the justification for use of JIRA tests or have provided input on why you disagree

**Reviewer 2:**

Name:
- [ ] Code is maintainable and reusable, reuses existing code and infrastructure where appropriate, and accomplishes the task’s purpose
- [ ] The tests appropriately test the new code, including edge cases
- [ ] You have tried to break the code

If JIRA tests were used to supplement or replace automated tests:
- [ ] JIRA tests have been run and pass
- [ ] You agree with the justification for use of JIRA tests or have provided input on why you disagree

2019-04-19 12:22 UTC, hackrm commented on lib/tasks/cql.rake
> +          differences['value_sets'] = 'value sets' if (cqm_measure.value_sets.where(oid: cql_val_set[:oid], version: "").count < 1 && cqm_measure.value_sets.where(oid: cql_val_set[:oid], version: "N/
During the conversion, if a value_set_oid_version_object had an empty string version, it could either contain an empty string or "N/A" in the converted CQM measure, which is the reason for this if statement structure.

2019-04-19 14:05 UTC, hackrm commented
If you want to run the rake task and only convert one of the measures listed in the description, temporarily replace line 131 in cql.rake with one of the following: 
      bonnie_cql_measures = CqlMeasure.where(_id: BSON::ObjectId("5a97f802b848467fb6a92e3c"))
      bonnie_cql_measures = CqlMeasure.where(_id: BSON::ObjectId("5bfe3673b84846165cd1d1fe"))

2019-04-24 13:46 UTC, lukoktonos requested changes

2019-04-24 13:46 UTC, losborne commented on Gemfile.lock
> +  revision: 24d197e354bcfe6dcf94f47dbed50144b4dc1f8f
This commit is behind master, should update and possibly need to verify the changes contained in the most recent commit(s)

2019-04-24 13:46 UTC, losborne commented on lib/tasks/cql.rake
> +          unless diff.empty?
What about adding a success message if there are no errors found and a summary at the bottom?

Currently it looks like this:
```
**** Starting to convert measures! ****

**** Done converting ****
```

What about:
```
**** Starting to convert measures! ****
lwosborne@mitre.org CMS123 converted successfully (green text)
...
**** Done converting ****
     Successful Conversions: 42
     Unsuccessful Conversions: 2
```

2019-04-24 13:46 UTC, losborne commented on lib/tasks/cql.rake
> +      differences['user id'] = 'user_id' if Digest::MD5.hexdigest(cql_measure.user_id.to_json) != Digest::MD5.hexdigest(cqm_measure['user_id'].to_json)
Since we are only using each of these values once, doing a `Digest::MD5` increases the runtime rather than speeding things up.  If we were going to be re-using the strings for multiple comparisons, then it might be faster to convert once (O(n) for hashing) and compare multiple times (O(1) for hash comparison) rather than doing multiple string comparisons (O(n) for each string comparison).  As it is now, these `Digest::MD5`s seem like they can be removed to both simplify the code and speed it up slightly.

We also don't need the `to_json` for these either, we can just do
```
differences['hqmf id'] = 'hqmf_id' if cql_measure.hqmf_id != cqm_measure['hqmf_id']
```

Finally, instead of using a hash with identical key/values, you can just use an array to store `differences`.  The values are not used in the printout loop above:
```
            diff.each_key do |key|
              puts "--- #{key} --- Is different from CQL measure".light_blue
            end
```

So the final version can look something like:
```
differences = []
...
differences.push 'hqmf_id' if cql_measure.hqmf_id != cqm_measure['hqmf_id']
```

2019-04-24 20:14 UTC, hackrm commented on Gemfile.lock
> +  revision: 24d197e354bcfe6dcf94f47dbed50144b4dc1f8f
This has been addressed and will push the update by tomorrow. This PR is also a number of commits behind for it's cqm-models reference so that will be updated too.

2019-04-29 18:00 UTC, lukoktonos approved these changes
Looks good!

2019-05-10 15:16 UTC, jbradl11 approved these changes

2019-05-10 15:17 UTC, merged