Truncate results
MeasureAuthoringTool/bonnie pull request #1217
Opened 2019-05-09 13:24 UTC by mayerm94

Pull requests into Bonnie require the following. Submitter and reviewer should :white_check_mark: when done. For items that are not-applicable, note it's not-applicable ("N/A") and :white_check_mark:.

**Submitter:**
- [ ] This pull request describes why these changes were made.
- [ ] This PR is into the correct branch.
- [ ] JIRA ticket for this PR:
- [ ] JIRA ticket links to this PR
- [ ] Code diff has been done and been reviewed (it **does not** contain: additional white space, not applicable code changes, debug statements, etc.)
- [ ] If UI changes have been made, google WAVE plug-in has been executed to ensure no 508 issues were introduced.
- [ ] Tests are included and test edge cases
- [ ] Tests have been run locally and pass (remember to update Gemfile when applicable)
- [ ] Test fixtures updated and documented as necessary ( see [internal wiki](https://gitlab.mitre.org/bonnie/internal-documentation/wikis/testing#test-fixtures) )
- [ ] Code coverage has not gone down and all code touched or added is covered. 
     * In rare situations, this may not be possible or applicable to a PR. In those situations:
         1. Note why this could not be done or is not applicable here: 
         2. Add TODOs in the code noting that it requires a test
         3. Add a JIRA task to add the test and link it here: 
- [ ] Automated regression test(s) pass

If JIRA tests were used to supplement or replace automated tests:
- [ ] JIRA test links:
- [ ] Justification for using JIRA tests:
- [ ] JIRA tests have been added to sprint

**Reviewer 1:**

Name:
- [ ] Code is maintainable and reusable, reuses existing code and infrastructure where appropriate, and accomplishes the task’s purpose
- [ ] The tests appropriately test the new code, including edge cases
- [ ] You have tried to break the code

If JIRA tests were used to supplement or replace automated tests:
- [ ] JIRA tests have been run and pass
- [ ] You agree with the justification for use of JIRA tests or have provided input on why you disagree

**Reviewer 2:**

Name:
- [ ] Code is maintainable and reusable, reuses existing code and infrastructure where appropriate, and accomplishes the task’s purpose
- [ ] The tests appropriately test the new code, including edge cases
- [ ] You have tried to break the code

If JIRA tests were used to supplement or replace automated tests:
- [ ] JIRA tests have been run and pass
- [ ] You agree with the justification for use of JIRA tests or have provided input on why you disagree

2019-05-09 19:24 UTC, lukoktonos requested changes

2019-05-09 19:24 UTC, losborne commented on test/unit/helpers/excel_export_helper_test.rb
> +    assert true, truncated_string.length < 32700
This needs to be `assert_equal true, truncated_string.length < 32730`

2019-05-09 19:24 UTC, losborne commented on test/unit/helpers/excel_export_helper_test.rb
> +    assert true, (truncated_string.include? 'Entry Truncated To Fit Cell')
This needs to be `assert_equal true, (truncated_string.include? 'Entry Truncated To Fit Cell'`

2019-05-10 14:00 UTC, lukoktonos approved these changes

2019-05-10 14:05 UTC, losborne commented
rubocop failures are unrelated to this PR changes:

```
rlwosborne at MM232275-PC in ~/git/bonnie on excel_truncate*
$ rubocop lib/patient_export.rb 
Inspecting 1 file
.

1 file inspected, no offenses detected
lwosborne at MM232275-PC in ~/git/bonnie on excel_truncate*
$ rubocop test/unit/helpers/excel_export_helper_test.rb 
Inspecting 1 file
.

1 file inspected, no offenses detected
```

2019-05-10 15:37 UTC, hackrm approved these changes

2019-05-10 16:07 UTC, merged