Patient save backend
MeasureAuthoringTool/bonnie pull request #1219
Opened 2019-05-10 17:41 UTC by hackrm

Pull requests into Bonnie require the following. Submitter and reviewer should :white_check_mark: when done. For items that are not-applicable, note it's not-applicable ("N/A") and :white_check_mark:.

**Submitter:**
- [ ] This pull request describes why these changes were made.
- [ ] This PR is into the correct branch.
- [ ] JIRA ticket for this PR:
- [ ] JIRA ticket links to this PR
- [ ] Code diff has been done and been reviewed (it **does not** contain: additional white space, not applicable code changes, debug statements, etc.)
- [ ] If UI changes have been made, google WAVE plug-in has been executed to ensure no 508 issues were introduced.
- [ ] Tests are included and test edge cases
- [ ] Tests have been run locally and pass (remember to update Gemfile when applicable)
- [ ] Test fixtures updated and documented as necessary ( see [internal wiki](https://gitlab.mitre.org/bonnie/internal-documentation/wikis/testing#test-fixtures) )
- [ ] Code coverage has not gone down and all code touched or added is covered. 
     * In rare situations, this may not be possible or applicable to a PR. In those situations:
         1. Note why this could not be done or is not applicable here: 
         2. Add TODOs in the code noting that it requires a test
         3. Add a JIRA task to add the test and link it here: 
- [ ] Automated regression test(s) pass

If JIRA tests were used to supplement or replace automated tests:
- [ ] JIRA test links:
- [ ] Justification for using JIRA tests:
- [ ] JIRA tests have been added to sprint

**Reviewer 1:**

Name:
- [ ] Code is maintainable and reusable, reuses existing code and infrastructure where appropriate, and accomplishes the task’s purpose
- [ ] The tests appropriately test the new code, including edge cases
- [ ] You have tried to break the code

If JIRA tests were used to supplement or replace automated tests:
- [ ] JIRA tests have been run and pass
- [ ] You agree with the justification for use of JIRA tests or have provided input on why you disagree

**Reviewer 2:**

Name:
- [ ] Code is maintainable and reusable, reuses existing code and infrastructure where appropriate, and accomplishes the task’s purpose
- [ ] The tests appropriately test the new code, including edge cases
- [ ] You have tried to break the code

If JIRA tests were used to supplement or replace automated tests:
- [ ] JIRA tests have been run and pass
- [ ] You agree with the justification for use of JIRA tests or have provided input on why you disagree

2019-05-13 14:54 UTC, hackrm commented
The most important files for this specific PR are app/controllers/patients_controller.rb & test/functional/patients_controller_test.rb. A large amount of the diff is caused by the renaming of a fixture directory.

2019-05-13 19:37 UTC, lukoktonos requested changes
There are 7 additional backend test errors vs `cqm-integration` that need to be investigated as well.

2019-05-13 19:37 UTC, losborne commented on spec/javascripts/views/patient_builder_spec.js.coffee
> +    #@firstCriteria = @patientBuilder.model.get('source_data_criteria').first()
Can this just be removed instead of commented out?

2019-05-13 19:37 UTC, losborne commented on test/functional/patients_controller_test.rb
> +    r = CQM::Patient.first
`r` should be more descriptive, like `patient` or similar (here and in following tests)

2019-05-13 19:37 UTC, losborne commented on app/controllers/patients_controller.rb
> +    patient = CQM::Patient.by_user(current_user).find(params[:id]) # FIXME: will we have an ID attribute on server side?
FIXME comment  can be removed, no?

2019-05-14 00:33 UTC, jbradl11 commented on spec/javascripts/views/patient_builder_spec.js.coffee
> +      patients = new Thorax.Collections.Patients getJSONFixture('cqm_patients/CMS347/patients.json'), parse: true
If the fixture has been updated, should we no longer skip this test?

2019-05-14 00:35 UTC, jbradl11 commented on spec/javascripts/views/patient_builder_spec.js.coffee
>      jasmine.getJSONFixtures().clearCache()
Above (line 659) it looks like you removed `jasmine.getJSONFixtures().clearCache()`. Was that intentional?

2019-05-14 00:40 UTC, jbradl11 commented on test/functional/patients_controller_test.rb
> +    updated_patient['_id'] = patient.id.to_s
What is the difference between `id` and `_id`? What are those values?

2019-05-15 04:12 UTC, zlister commented on spec/javascripts/views/patient_builder_spec.js.coffee
> +    #@firstCriteria = @patientBuilder.model.get('source_data_criteria').first()
That is a part of some skipped tests lower down. I think it may need to be addressed and updated once everything settles

2019-05-15 04:31 UTC, zlister commented on spec/javascripts/views/patient_builder_spec.js.coffee
> +      patients = new Thorax.Collections.Patients getJSONFixture('cqm_patients/CMS347/patients.json'), parse: true
Will need to investigate this further. It seems to still fail when not skipped

2019-05-15 04:36 UTC, zlister commented on test/functional/patients_controller_test.rb
> +    updated_patient['_id'] = patient.id.to_s
`id` is used for the route for properly updating the correct patient. `_id` is used on calling the mongoid Document so that it can be retrieved and updated. Not really sure why they can't be the same but currently both are necessary.

2019-05-17 11:24 UTC, jbradl11 commented on spec/javascripts/production_tests/production_patient_builder_spec.js.coffee
> +      bonnie.valueSetsByMeasureId = getJSONFixture('cqm_measure_data/core_measures/CMS160/value_sets.json')
I didn't think `valueSetsByMeasureId` was needed anymore in Bonnie.

2019-05-17 14:19 UTC, losborne commented on spec/javascripts/views/patient_builder_spec.js.coffee
> +      patients = new Thorax.Collections.Patients getJSONFixture('cqm_patients/CMS347/patients.json'), parse: true
cqm_patients path needs to be updated, will do in a future task

2019-05-17 14:46 UTC, lukoktonos approved these changes

2019-05-17 14:58 UTC, jbradl11 approved these changes

2019-05-17 14:58 UTC, merged