Frontend patient saving
MeasureAuthoringTool/bonnie pull request #1239
Opened 2019-06-03 15:56 UTC by hackrm

Pull requests into Bonnie require the following. Submitter and reviewer should :white_check_mark: when done. For items that are not-applicable, note it's not-applicable ("N/A") and :white_check_mark:.

**Submitter:**
- [ ] This pull request describes why these changes were made.
- [ ] This PR is into the correct branch.
- [ ] JIRA ticket for this PR:
- [ ] JIRA ticket links to this PR
- [ ] Code diff has been done and been reviewed (it **does not** contain: additional white space, not applicable code changes, debug statements, etc.)
- [ ] If UI changes have been made, google WAVE plug-in has been executed to ensure no 508 issues were introduced.
- [ ] Tests are included and test edge cases
- [ ] Tests have been run locally and pass (remember to update Gemfile when applicable)
- [ ] Test fixtures updated and documented as necessary ( see [internal wiki](https://gitlab.mitre.org/bonnie/internal-documentation/wikis/testing#test-fixtures) )
- [ ] Code coverage has not gone down and all code touched or added is covered. 
     * In rare situations, this may not be possible or applicable to a PR. In those situations:
         1. Note why this could not be done or is not applicable here: 
         2. Add TODOs in the code noting that it requires a test
         3. Add a JIRA task to add the test and link it here: 
- [ ] Automated regression test(s) pass

If JIRA tests were used to supplement or replace automated tests:
- [ ] JIRA test links:
- [ ] Justification for using JIRA tests:
- [ ] JIRA tests have been added to sprint

**Reviewer 1:**

Name:
- [ ] Code is maintainable and reusable, reuses existing code and infrastructure where appropriate, and accomplishes the task’s purpose
- [ ] The tests appropriately test the new code, including edge cases
- [ ] You have tried to break the code

If JIRA tests were used to supplement or replace automated tests:
- [ ] JIRA tests have been run and pass
- [ ] You agree with the justification for use of JIRA tests or have provided input on why you disagree

**Reviewer 2:**

Name:
- [ ] Code is maintainable and reusable, reuses existing code and infrastructure where appropriate, and accomplishes the task’s purpose
- [ ] The tests appropriately test the new code, including edge cases
- [ ] You have tried to break the code

If JIRA tests were used to supplement or replace automated tests:
- [ ] JIRA tests have been run and pass
- [ ] You agree with the justification for use of JIRA tests or have provided input on why you disagree

2019-06-12 13:02 UTC, losborne commented on spec/javascripts/integration/population_state_spec.js.coffee
>      @measureToTest = loadMeasureWithValueSets 'cqm_measure_data/core_measures/CMS160/CMS160v6.json', 'cqm_measure_data/core_measures/CMS160/value_sets.json'
Add:

```
    bonnie.measures = new Thorax.Collections.Measures()
    bonnie.measures.add @measureToTest
```
Adding this should allow you to unskip `it "carries over changes between views", ->` and perhaps ` it "resets when user goes to measures route", -`.  I started making those changes but it looks like it needs the `expectedValues` work here to fully fix:

2019-06-12 14:38 UTC, hackrm commented on spec/javascripts/integration/population_state_spec.js.coffee
>      @measureToTest = loadMeasureWithValueSets 'cqm_measure_data/core_measures/CMS160/CMS160v6.json', 'cqm_measure_data/core_measures/CMS160/value_sets.json'
I tried adding those lines and still got errors for the tests you suggest I un-skip. Should I debug this to resolve the issue or should this fix have resolved all the issues for these tests without any additional work?

2019-06-12 14:41 UTC, hackrm commented on app/assets/javascripts/models/data_criteria.js.coffee
> -  toJSON: ->
This method was called during the patient saving process and is no longer needed since 'field_values' isn't an attribute of data_criteria any longer.

2019-06-12 14:44 UTC, hackrm commented on app/assets/javascripts/models/expected_value.js.coffee
> +    @parent = options?.parent
This provides the expected values collection access to the Patient which is needed in the changeExpectedValue() method.

2019-06-12 17:29 UTC, losborne commented on spec/javascripts/integration/population_state_spec.js.coffee
>      @measureToTest = loadMeasureWithValueSets 'cqm_measure_data/core_measures/CMS160/CMS160v6.json', 'cqm_measure_data/core_measures/CMS160/value_sets.json'
I'd say debug a bit to determine if the errors are expectedValue related or not.  If so, fix; if not, leave skipped

2019-06-12 17:40 UTC, jbradl11 commented on app/assets/javascripts/models/expected_value.js.coffee
> +    mongoose_expectedValue = (@collection.parent.get('cqmPatient').expectedValues.filter (val) -> val.population_index is expectedValue.get('population_index') && val.measure_id is expectedValue.get(
It looks like `Numex` and `Denex` are missing from this list.

2019-06-12 17:43 UTC, jbradl11 commented on app/assets/javascripts/views/patient_builder/patient_builder.js.coffee
>          # TODO ADD A PATIENT -> MEASURE ID RELATION IN CQM-MODELS
Is this TODO still valid or can it be deleted?

2019-06-12 18:00 UTC, lukoktonos requested changes

2019-06-12 18:00 UTC, lukoktonos commented on app/assets/javascripts/models/expected_value.js.coffee
> +    if expectedValue.has('MSRPOPLEX') then mongoose_expectedValue.MSRPOPLEX = expectedValue.get('MSMSRPOPLEXRPOPL')
```suggestion
    if expectedValue.has('MSRPOPLEX') then mongoose_expectedValue.MSRPOPLEX = expectedValue.get('MSRPOPLEX')
```

2019-06-12 18:00 UTC, lukoktonos commented on app/assets/javascripts/views/patient_builder/patient_builder.js.coffee
> +          continue if !measure_id?
This shouldn't be needed anymore--we got rid of the `nil` in `measure_ids`

2019-06-12 18:00 UTC, lukoktonos commented on app/assets/javascripts/models/expected_value.js.coffee
> +  changeExpectedValue: (expectedValue) ->
We should add some unit tests for this function.  I think it's only covered indirectly and not assertively.

2019-06-13 02:13 UTC, losborne commented
Saving does not seem to be working, when I modify expected values and click save it hangs on
![image](https://user-images.githubusercontent.com/14879344/59398751-517bfb00-8d5f-11e9-989e-03302cecbd11.png)

But then clicking cancel shows the changed state back on the measure page.  There is this error as well:
```
data_criteria.js?body=1:51 Uncaught TypeError: Cannot read property 'each' of undefined
    at SourceDataCriteria.Thorax.Models.SourceDataCriteria.SourceDataCriteria.toJSON (data_criteria.js?body=1:51)
    at backbone-min.js?body=1:1
    at Array.map (<anonymous>)
    at Function.w.map.w.collect (underscore-min.js?body=1:1)
    at SourceDataCriteria.Collection.<computed> [as map] (backbone-min.js?body=1:1)
    at SourceDataCriteria.toJSON (backbone-min.js?body=1:1)
    at JSON.stringify (<anonymous>)
    at Backbone.sync (backbone-min.js?body=1:1)
    at Patient.<anonymous> (application.js?body=1:17)
    at Patient.<anonymous> (underscore-min.js?body=1:1)
    at Patient.Thorax.sync (thorax.js?body=1:2769)
    at Patient.save (backbone-min.js?body=1:1)
    at PatientBuilder.Thorax.Views.PatientBuilder.PatientBuilder.save (patient_builder.js?body=1:347)
    at HTMLButtonElement.handleClick (thorax.js?body=1:2465)
    at HTMLDocument.dispatch (jquery.min.js?body=1:6)
    at HTMLDocument.y.handle (jquery.min.js?body=1:6)```

2019-06-17 23:46 UTC, jbradl11 commented on app/assets/javascripts/models/patient.js.coffee
> +      sourceElement.dataElementCodes[0] = new cqm.models.CQL.Code('21112-8', 'LOINC', undefined, 'Birth date')
We should discuss this line. Since I have been on the project, we have assumed that a patient must have a birthdate. Should that be the case?

2019-06-18 15:29 UTC, hackrm commented on spec/javascripts/views/patient_builder_spec.js.coffee
> +    it 'updates the values of the frontend mongoose model', ->
Here are the new tests I created to verify the new changeExpectedValue() method in expected_value.js.coffee behaves properly. If there are any suggestions on how to improve them, feel free to let me know.

2019-06-18 15:34 UTC, hackrm commented on app/assets/javascripts/models/expected_value.js.coffee
> +  changeExpectedValue: (expectedValue) ->
I was able to include some tests in my most recent commit.

2019-06-18 20:43 UTC, hackrm commented on spec/javascripts/integration/population_state_spec.js.coffee
>      @measureToTest = loadMeasureWithValueSets 'cqm_measure_data/core_measures/CMS160/CMS160v6.json', 'cqm_measure_data/core_measures/CMS160/value_sets.json'
I didn't get the time to debug this yet since I was dealing with some other issues on this PR. I see your un-skip tests PR has most of these tests passing now so is this all set?

2019-06-18 20:45 UTC, hackrm commented on app/assets/javascripts/models/patient.js.coffee
> +      sourceElement.dataElementCodes[0] = new cqm.models.CQL.Code('21112-8', 'LOINC', undefined, 'Birth date')
Just to document the decision here: After discussion with JB, Matt and Hoss during Retro, the decision was to not force a patient to have a birth date data element if the measure does not have one. The most recent commit handles this.

2019-06-18 21:00 UTC, losborne commented on spec/javascripts/integration/population_state_spec.js.coffee
>      @measureToTest = loadMeasureWithValueSets 'cqm_measure_data/core_measures/CMS160/CMS160v6.json', 'cqm_measure_data/core_measures/CMS160/value_sets.json'
Yes this is no longer an issue :thumbsup:

2019-06-19 21:16 UTC, hackrm commented on app/assets/javascripts/models/patient.js.coffee
> +      sourceElement.dataElementCodes[0] = new cqm.models.CQL.Code('21112-8', 'LOINC', undefined, 'Birth date')
Notice on this line: I did find at least one instance where there was a PatientCharacteristicBirthDate on a measure but no DataElementCode associated with it, so I included this portion of the logic again so a code will be created for it under this condition.

2019-06-24 19:27 UTC, lukoktonos approved these changes
Looks good

2019-06-24 19:46 UTC, jbradl11 approved these changes

2019-06-24 19:52 UTC, merged