patient builder timing attributes
MeasureAuthoringTool/bonnie pull request #1241
Opened 2019-06-07 19:34 UTC by hossenlopp

Pull requests into Bonnie require the following. Submitter and reviewer should :white_check_mark: when done. For items that are not-applicable, note it's not-applicable ("N/A") and :white_check_mark:.

**Submitter:**
- [x] This pull request describes why these changes were made.
- [x] This PR is into the correct branch.
- [ ] JIRA ticket for this PR:
- [ ] JIRA ticket links to this PR
- [ ] Code diff has been done and been reviewed (it **does not** contain: additional white space, not applicable code changes, debug statements, etc.)
- [x] If UI changes have been made, google WAVE plug-in has been executed to ensure no 508 issues were introduced.
- [x] Tests are included and test edge cases
- [x] Tests have been run locally and pass (remember to update Gemfile when applicable)
- [x] Test fixtures updated and documented as necessary ( see [internal wiki](https://gitlab.mitre.org/bonnie/internal-documentation/wikis/testing#test-fixtures) )
- [ ] Code coverage has not gone down and all code touched or added is covered. 
     * In rare situations, this may not be possible or applicable to a PR. In those situations:
         1. Note why this could not be done or is not applicable here: 
         2. Add TODOs in the code noting that it requires a test
         3. Add a JIRA task to add the test and link it here: 
- [x] Automated regression test(s) pass N/A

**Reviewer 1:**

Name: @jbradl11 
- [ ] Code is maintainable and reusable, reuses existing code and infrastructure where appropriate, and accomplishes the task’s purpose
- [ ] The tests appropriately test the new code, including edge cases
- [ ] You have tried to break the code

**Reviewer 2:**

Name:
- [ ] Code is maintainable and reusable, reuses existing code and infrastructure where appropriate, and accomplishes the task’s purpose
- [ ] The tests appropriately test the new code, including edge cases
- [ ] You have tried to break the code

2019-06-08 12:47 UTC, lukoktonos requested changes
The UI looks great and is pretty close to ready!  Found a few minor edge cases and made some in-line suggestions to get rid of some of the TODOs.

Since codecov didn't report for some reason, commented in-line where I noticed a couple small in coverage. Overall coverage is great and I'm not sure if those gaps actually matter or not or are testable, just thought I'd tag them.

Dragging one item onto another (`copyTimingAttributes`) has a few small issues:
1. authorDateTime selection does not copy over properly:
![2019-06-08 08 07 42](https://user-images.githubusercontent.com/14879344/59147057-a4069180-89c4-11e9-9831-66d39f4764bf.gif)

2. If start time is not selected, copying it re-selects it:
![2019-06-08 08 09 31](https://user-images.githubusercontent.com/14879344/59147064-d44e3000-89c4-11e9-99a9-510824f7ee04.gif)

3. If you drag a data element with different timing attributes onto another data element, the timing attributes that don't line up show up as unchecked (this may be OK, but just worth considering if we want to default as if they were dragged fresh rather than being unchecked in this case):
![2019-06-08 08 14 08](https://user-images.githubusercontent.com/14879344/59147122-98679a80-89c5-11e9-96ee-5ad147166d17.gif)

2019-06-08 12:47 UTC, lukoktonos commented on app/assets/javascripts/views/patient_builder/patient_builder.js.coffee
> +      debugger
```suggestion
```

2019-06-08 12:47 UTC, lukoktonos commented on app/assets/javascripts/views/patient_builder/patient_builder.js.coffee
> +    # TODO: use measurement period for this
```suggestion
```

2019-06-08 12:47 UTC, lukoktonos commented on app/assets/javascripts/views/patient_builder/patient_builder.js.coffee
> +    todayInMP.setYear(2012)
```suggestion
    todayInMP.setYear(@measure.getMeasurePeriodYear())
```

2019-06-08 12:47 UTC, lukoktonos commented on app/assets/javascripts/views/patient_builder/patient_builder.js.coffee
> +    todayInMP = new Date()
There's a small edge case if the user is developing on Feb 29th but the MP isn't a leap year.  We could just use Feb 28th in that case.

2019-06-08 12:47 UTC, losborne commented on app/assets/javascripts/models/data_criteria.js.coffee
> +  # TODO: Complete this or find a more appropiate location for this
I think this place makes sense for the map, but is the TODO still valid for completing this for this PR?

2019-06-08 12:47 UTC, losborne commented on app/assets/javascripts/views/patient_builder/data_criteria.js.coffee
> +    primaryTimingAttributeName = @model.getPrimaryTimingAttribute() || 'authorDatetime'
Is there a reason why we can't check/return `'authorDatetime'` from the `getPrimaryTimingAttribute` function itself rather than returning `undefined` and having the `|| 'authorDatetime'` here?

2019-06-08 12:47 UTC, losborne commented on app/assets/javascripts/views/patient_builder/inputs/datetime.js.coffee
> +    # TODO: use measurement period for this
```suggestion
```

2019-06-08 12:47 UTC, losborne commented on app/assets/javascripts/views/patient_builder/inputs/interval_datetime.js.coffee
> +    # TODO: use measurement period for this
```suggestion
```

2019-06-08 12:47 UTC, losborne commented on app/assets/javascripts/views/patient_builder/inputs/datetime.js.coffee
> +    todayInMP.setYear(2012)
```suggestion
    todayInMP.setYear(@parent.measure.getMeasurePeriodYear())
```

2019-06-08 12:47 UTC, losborne commented on app/assets/javascripts/views/patient_builder/inputs/interval_datetime.js.coffee
> +    todayInMP.setYear(2012)
```suggestion
    todayInMP.setYear(@parent.measure.getMeasurePeriodYear())
```

2019-06-08 12:47 UTC, losborne commented on app/assets/javascripts/views/patient_builder/inputs/datetime.js.coffee
> +    # if either before xor after was null trigger change
I think this is `or` rather than `xor`--does it need to be xor?

2019-06-08 12:47 UTC, losborne commented on app/assets/javascripts/models/data_criteria.js.coffee
> +      if @get('qdmDataElement').schema.path(timingAttr)?
Line not covered by tests

2019-06-08 12:47 UTC, losborne commented on app/assets/javascripts/models/data_criteria.js.coffee
> +  getAttributeType: (attributeName) ->
Not covered by tests (because it's used in the uncovered line above)

2019-06-08 12:47 UTC, losborne commented on app/assets/javascripts/views/patient_builder/inputs/datetime.js.coffee
> +  createDefault: ->
Function not covered by tests

2019-06-08 12:47 UTC, losborne commented on app/assets/javascripts/views/patient_builder/inputs/interval_datetime.js.coffee
> +  createDefault: ->
Function not covered by tests

2019-06-08 14:08 UTC, jbradl11 commented
This may have been a suggestion by me but I am seeing a label inconsistency. 
![image](https://user-images.githubusercontent.com/1568999/59148310-4dee1a00-89d5-11e9-8c05-897666208730.png)

But the collapse view shows a date range:
![image](https://user-images.githubusercontent.com/1568999/59148318-6100ea00-89d5-11e9-9972-47e9c6f83925.png)

2019-06-10 12:43 UTC, hossenlopp commented on app/assets/javascripts/models/data_criteria.js.coffee
> +  # TODO: Complete this or find a more appropiate location for this
We will want this map to be expanded to include the rest of the possible QDM data element attributes.

2019-06-10 12:46 UTC, hossenlopp commented on app/assets/javascripts/views/patient_builder/data_criteria.js.coffee
> +    primaryTimingAttributeName = @model.getPrimaryTimingAttribute() || 'authorDatetime'
I was thinking the same thing. I didn't want to rock the boat and change that... I'll give it a try and see what breaks. I think the ideal would be to use `getPrimaryTimingAttributes()[0]` to get the singular one that should be considered primary.

2019-06-10 12:50 UTC, hossenlopp commented on app/assets/javascripts/views/patient_builder/inputs/datetime.js.coffee
> +    todayInMP.setYear(2012)
I would rather this input field be able to work without requiring a reference to the measure. I'll add an optional field that it can be constructed with to define the default year.

2019-06-10 12:53 UTC, hossenlopp commented on app/assets/javascripts/views/patient_builder/inputs/datetime.js.coffee
> +    # if either before xor after was null trigger change
it does need to be xor. We only want to trigger a valueChanged event if it actually changed. Going from null to null is not a change. Line 69 takes care of the null to null situation by just leaving early. I didn't think there was an xor operator.

2019-06-10 15:12 UTC, hossenlopp commented on app/assets/javascripts/views/patient_builder/inputs/interval_datetime.js.coffee
> +  createDefault: ->
This is covered by the tests that uncheck and recheck either end. It uses this function to build the new default time to fill the field with. I presume you mean this should be tested specifically. I'll add tests.

2019-06-10 15:58 UTC, losborne commented on app/assets/javascripts/views/patient_builder/inputs/interval_datetime.js.coffee
> +  createDefault: ->
Ah--looks like it's just codecov being wrong:
![image](https://user-images.githubusercontent.com/14879344/59208449-1cad4f80-8b77-11e9-9318-d87db339349f.png)

2019-06-10 16:00 UTC, losborne commented on app/assets/javascripts/models/data_criteria.js.coffee
> +  # TODO: Complete this or find a more appropiate location for this
Will we want the map to be expanded for completing this PR?

2019-06-10 16:02 UTC, hossenlopp commented on app/assets/javascripts/models/data_criteria.js.coffee
> +  # TODO: Complete this or find a more appropiate location for this
Nah. I think that it should be expanded when the attribute inputs are worked on.

2019-06-10 16:04 UTC, hossenlopp commented on app/assets/javascripts/views/patient_builder/inputs/interval_datetime.js.coffee
> +  createDefault: ->
I'll still create the tests, also so the measurement period stuff can be tested.

2019-06-10 16:06 UTC, hossenlopp commented
> This may have been a suggestion by me but I am seeing a label inconsistency.
> ![image](https://user-images.githubusercontent.com/1568999/59148310-4dee1a00-89d5-11e9-8c05-897666208730.png)
> 
> But the collapse view shows a date range:
> ![image](https://user-images.githubusercontent.com/1568999/59148318-6100ea00-89d5-11e9-9972-47e9c6f83925.png)

This should just show the value for authorDatetime, right?

2019-06-11 22:11 UTC, hossenlopp commented on app/assets/javascripts/views/patient_builder/patient_builder.js.coffee
> +    todayInMP = new Date()
Resolved in Slack conversation. Tested in JS console, JS Date 'fails' safely by changing to Mar 1st when the year is changed. This behavior is ok.

2019-06-12 21:14 UTC, hossenlopp commented on app/assets/javascripts/views/patient_builder/inputs/datetime.js.coffee
> +  createDefault: ->
Tests have been added that check this.

2019-06-12 21:14 UTC, hossenlopp commented on app/assets/javascripts/views/patient_builder/inputs/interval_datetime.js.coffee
> +  createDefault: ->
Tests have been added that check this.

2019-06-12 21:46 UTC, hossenlopp commented on app/assets/javascripts/models/data_criteria.js.coffee
> +      if @get('qdmDataElement').schema.path(timingAttr)?
Tests were added that make use of this.

2019-06-12 21:46 UTC, hossenlopp commented on app/assets/javascripts/models/data_criteria.js.coffee
> +  getAttributeType: (attributeName) ->
Tests were added that make use of this.

2019-06-12 21:47 UTC, hossenlopp commented on app/assets/javascripts/views/patient_builder/inputs/datetime.js.coffee
> +    # TODO: use measurement period for this
Updated to use measurement year.

2019-06-12 21:47 UTC, hossenlopp commented on app/assets/javascripts/views/patient_builder/inputs/interval_datetime.js.coffee
> +    # TODO: use measurement period for this
Updated to use measurement year.

2019-06-12 21:48 UTC, hossenlopp commented on app/assets/javascripts/views/patient_builder/inputs/interval_datetime.js.coffee
> +    todayInMP.setYear(2012)
New implementation uses measurement year in the end.

2019-06-12 21:48 UTC, hossenlopp commented on app/assets/javascripts/views/patient_builder/inputs/datetime.js.coffee
> +    todayInMP.setYear(2012)
New implementation uses measurement year in the end.

2019-06-13 01:53 UTC, lukoktonos approved these changes
I think this is in a good state, approved

I did find some unusual behavior with invalid dates but I think the current behavior is reasonable (showing that the date is invalid)
![2019-06-12 21 49 16](https://user-images.githubusercontent.com/14879344/59397889-3491f880-8d5c-11e9-9165-e9c8956e1fa0.gif)

noticed the fa-icon for allergy is still a `?`, but that can be fixed in a later PR since it's not directly related:
![image](https://user-images.githubusercontent.com/14879344/59397982-7753d080-8d5c-11e9-947d-e34685fdfc5f.png)

2019-06-13 12:27 UTC, hossenlopp commented
The allergy icon fix should be trivial. I didn't notice it.

The `invalid date` issue is telling of a more severe issue that I thought was handled by the datepicker. It looks like 4/12/2012 wasn't saved to the data element. Good catch. I'll try to fix asap.

2019-06-13 14:36 UTC, lukoktonos approved these changes

2019-06-13 15:39 UTC, jbradl11 approved these changes

2019-06-17 13:41 UTC, lukoktonos approved these changes

2019-06-17 13:49 UTC, merged