Shift years
MeasureAuthoringTool/bonnie pull request #1242
Opened 2019-06-07 21:22 UTC by zlister

This PR is adding the `shift_years` function so that the dates on the patients will be adjusted according to the new measurement period.

- [ ] Update cqm-models in the Gemfile once merged

Pull requests into Bonnie require the following. Submitter and reviewer should :white_check_mark: when done. For items that are not-applicable, note it's not-applicable ("N/A") and :white_check_mark:.

**Submitter:**
- [ ] This pull request describes why these changes were made.
- [ ] This PR is into the correct branch.
- [ ] JIRA ticket for this PR:
- [ ] JIRA ticket links to this PR
- [ ] Code diff has been done and been reviewed (it **does not** contain: additional white space, not applicable code changes, debug statements, etc.)
- [ ] If UI changes have been made, google WAVE plug-in has been executed to ensure no 508 issues were introduced.
- [ ] Tests are included and test edge cases
- [ ] Tests have been run locally and pass (remember to update Gemfile when applicable)
- [ ] Test fixtures updated and documented as necessary ( see [internal wiki](https://gitlab.mitre.org/bonnie/internal-documentation/wikis/testing#test-fixtures) )
- [ ] Code coverage has not gone down and all code touched or added is covered. 
     * In rare situations, this may not be possible or applicable to a PR. In those situations:
         1. Note why this could not be done or is not applicable here: 
         2. Add TODOs in the code noting that it requires a test
         3. Add a JIRA task to add the test and link it here: 
- [ ] Automated regression test(s) pass

If JIRA tests were used to supplement or replace automated tests:
- [ ] JIRA test links:
- [ ] Justification for using JIRA tests:
- [ ] JIRA tests have been added to sprint

**Reviewer 1:**

Name:
- [ ] Code is maintainable and reusable, reuses existing code and infrastructure where appropriate, and accomplishes the task’s purpose
- [ ] The tests appropriately test the new code, including edge cases
- [ ] You have tried to break the code

If JIRA tests were used to supplement or replace automated tests:
- [ ] JIRA tests have been run and pass
- [ ] You agree with the justification for use of JIRA tests or have provided input on why you disagree

**Reviewer 2:**

Name:
- [ ] Code is maintainable and reusable, reuses existing code and infrastructure where appropriate, and accomplishes the task’s purpose
- [ ] The tests appropriately test the new code, including edge cases
- [ ] You have tried to break the code

If JIRA tests were used to supplement or replace automated tests:
- [ ] JIRA tests have been run and pass
- [ ] You agree with the justification for use of JIRA tests or have provided input on why you disagree

2019-06-08 11:48 UTC, lukoktonos requested changes

2019-06-08 11:48 UTC, losborne commented on app/controllers/measures_controller.rb
> +      patient.qdmPatient.dataElements.each do |data_element|
In addition to this loop, we should also update the birthDatetime of the qdmpatient (which is in the data elements array but also outside of it:

![image](https://user-images.githubusercontent.com/14879344/59146844-2ee58d00-89c1-11e9-94d6-1bb4c30b1a54.png)

2019-06-08 11:48 UTC, losborne commented on test/functional/measures_controller_test.rb
> +    assert_equal 1984, patient.qdmPatient.dataElements.first.relevantPeriod.low.year
Should add a test where the data element had a year other than 2012 originally and check that it has shifted appropriately by the correct number of years

One edge case that is unlikely but worth considering is if the shift in dates would produce an invalid CQL Year,
for example if a data element has year 0001 but then the MP is changed from 2012 to 2011.  We might want to throw an error in that case

2019-06-08 12:43 UTC, jbradl11 commented on app/controllers/measures_controller.rb
> +      patient.qdmPatient.dataElements.each do |data_element|
In addition to this, would a death Datetime be handled in a similar way?

2019-06-08 12:48 UTC, jbradl11 commented on lib/tasks/fixture_helper.rb
> +        end
Is there a possibility of an Array inside of an Array?

2019-06-08 12:49 UTC, losborne commented on app/controllers/measures_controller.rb
> +      patient.qdmPatient.dataElements.each do |data_element|
Yes, good point--the users said that they would want all dates on the patient shifted.

2019-06-10 15:50 UTC, zlister commented on app/controllers/measures_controller.rb
> +      patient.qdmPatient.dataElements.each do |data_element|
Is the death Datetime a data element? It might already be handled then

2019-06-12 17:58 UTC, zlister commented on lib/tasks/fixture_helper.rb
> +        end
I haven't seen one, usually it is an array of Hashes (an array containing other classes tend to be a Hash). I can add another check just so that it is covered in case though

2019-06-14 19:12 UTC, zlister commented on app/controllers/measures_controller.rb
> +      patient.qdmPatient.dataElements.each do |data_element|
`expiredDatetime` is a data_element

2019-06-15 12:44 UTC, lukoktonos reviewed
It looks like CQM Patients' QDM Patients have both a `dataElements` array as well as `extendedData.source_data_criteria`.  I'm not sure what the role of the latter is--should that even be on the qdm patient?  If so, I think we may need to adjust those dates as well, as they have start/end dates.

It does not look like the qdmpatient's birthdate is being updated with the change in measurementperiod.  (the one in dataElements is, but not the other one.  The date picker in the patient builder view doesnt show a different birthdate)

It would be better for the error upon failure to shift an element (due to <1 or >9999) to give some information about which element is causing the issue if possible:
```Element on Patient could not be shifted. Please make sure shift will keep all years between 1 and 9999```

I think it may make sense to hold off on merging this PR until the patient saving and patient builder timing section get in, because those allow for more comprehensive manual testing.

2019-06-17 19:47 UTC, losborne commented on Gemfile.lock
> +  revision: ef59618fa137ba6fa27c057b2a57cea4977ba0fa
`2688b71` is the most up-to-date, `ef59618f` is 1 commit behind now

2019-06-19 03:24 UTC, jbradl11 commented on lib/tasks/fixture_helper.rb
> +          vals.each { |vall| convert_times(vall) }
You should be able to just to do this
```
if val.is_a?(Hash)
  convert_times(val)
```
Since you have a base check for `Hash` this will be handled.

2019-06-19 03:25 UTC, jbradl11 commented on lib/tasks/fixture_helper.rb
> +          val.each do |value|
Similarly to the previous comment. Since you have a base check for `Array` you can just pass val back into the function.

2019-06-19 13:44 UTC, lukoktonos approved these changes
Looks good!

2019-06-19 13:46 UTC, jbradl11 approved these changes

2019-06-19 13:47 UTC, merged