Individual result mods 2.0
MeasureAuthoringTool/bonnie pull request #1245
Opened 2019-06-17 13:17 UTC by mayerm94

Follows changes made in https://github.com/projecttacoma/cqm-models/pull/113/files and https://github.com/projecttacoma/cqm-execution/pull/52/files
Pull requests into Bonnie require the following. Submitter and reviewer should :white_check_mark: when done. For items that are not-applicable, note it's not-applicable ("N/A") and :white_check_mark:.

❗️ BEFORE MERGE ❗️
- [ ] After https://github.com/projecttacoma/cqm-execution/pull/48 is merged, update Package.json and yarn.lock

**Submitter:**
- [x] This pull request describes why these changes were made.
- [x] This PR is into the correct branch.
- [x] JIRA ticket for this PR: https://jira.mitre.org/browse/CYPRESS-514
- [x] JIRA ticket links to this PR
- [x] Code diff has been done and been reviewed (it **does not** contain: additional white space, not applicable code changes, debug statements, etc.)
- [x] If UI changes have been made, google WAVE plug-in has been executed to ensure no 508 issues were introduced. NA
- [x] Tests are included and test edge cases
- [x] Tests have been run locally and pass (remember to update Gemfile when applicable)
- [x] Test fixtures updated and documented as necessary ( see [internal wiki](https://gitlab.mitre.org/bonnie/internal-documentation/wikis/testing#test-fixtures) )
- [ ] Code coverage has not gone down and all code touched or added is covered. 
     * In rare situations, this may not be possible or applicable to a PR. In those situations:
         1. Note why this could not be done or is not applicable here: 
         2. Add TODOs in the code noting that it requires a test
         3. Add a JIRA task to add the test and link it here: 
- [ ] Automated regression test(s) pass

If JIRA tests were used to supplement or replace automated tests:
- [ ] JIRA test links:
- [ ] Justification for using JIRA tests:
- [ ] JIRA tests have been added to sprint

**Reviewer 1:**

Name:
- [ ] Code is maintainable and reusable, reuses existing code and infrastructure where appropriate, and accomplishes the task’s purpose
- [ ] The tests appropriately test the new code, including edge cases
- [ ] You have tried to break the code

If JIRA tests were used to supplement or replace automated tests:
- [ ] JIRA tests have been run and pass
- [ ] You agree with the justification for use of JIRA tests or have provided input on why you disagree

**Reviewer 2:**

Name:
- [ ] Code is maintainable and reusable, reuses existing code and infrastructure where appropriate, and accomplishes the task’s purpose
- [ ] The tests appropriately test the new code, including edge cases
- [ ] You have tried to break the code

If JIRA tests were used to supplement or replace automated tests:
- [ ] JIRA tests have been run and pass
- [ ] You agree with the justification for use of JIRA tests or have provided input on why you disagree

2019-06-17 13:40 UTC, lukoktonos requested changes
Mostly looks good, just a couple small changes needed

Codecov red square is irrelevant for this PR (excel export will be fixed in a different task)

2019-06-17 13:40 UTC, losborne commented on spec/javascripts/integration/composite_measures_spec.js.coffee
> +  it 'calculate correctly for the composite measure 1', ->
This one is composite, the one below is component, so I don't think we need the 1/2

2019-06-17 13:40 UTC, losborne commented on config/mongoid.yml
> +      database: bonnie613
```suggestion
      database: bonnie_development
```

2019-06-17 13:40 UTC, losborne commented on app/assets/javascripts/cqm_calculator.js.coffee
> +      cqmResults = cqm.execution.Calculator.calculate(cqmMeasure, [cqmPatient.qdmPatient], cqmValueSets, { doPretty: true, includeClauseResults: true, requestDocument: false })
Should `requestDocument: false` be passed into the `calculate()` call below in `calculateAll` as well?

2019-06-17 14:11 UTC, mayerm94 commented on app/assets/javascripts/cqm_calculator.js.coffee
> +      cqmResults = cqm.execution.Calculator.calculate(cqmMeasure, [cqmPatient.qdmPatient], cqmValueSets, { doPretty: true, includeClauseResults: true, requestDocument: false })
requestDocument defaults to false, but i will add it in for consistency 👍

2019-06-18 21:24 UTC, hossenlopp requested changes

2019-06-18 21:24 UTC, hossenlopp commented on app/helpers/excel_export_helper.rb
> +          result[pop_set_or_strat[:id]]['population_relevance'].each_key do |population_criteria|
Fixtures need to be updated to have population_relevance not in extendedData.

2019-06-18 21:29 UTC, hossenlopp commented on Gemfile.lock
> +  revision: bbb76658ee3605e0f54b340b7097d62c5bca8d8b
Why did the hash of this change?

2019-06-18 21:30 UTC, hossenlopp commented on Gemfile.lock
> +  revision: 96c8b3058351650ff76f76a0ea301417bb41b9ea
Why did the hash of this change. It probably is a good thing for it to be updated anyways.

2019-06-18 21:32 UTC, mayerm94 commented on Gemfile.lock
> +  revision: bbb76658ee3605e0f54b340b7097d62c5bca8d8b
bundle update cqm-models

2019-06-19 00:00 UTC, mayerm94 commented on Gemfile.lock
> +  revision: 96c8b3058351650ff76f76a0ea301417bb41b9ea
bundle update cqm-models caused this i believe (weird because models doesn't depend on parsers) either way, should probably be updated

2019-06-19 14:05 UTC, hossenlopp requested changes

2019-06-19 14:05 UTC, hossenlopp commented on test/fixtures/excel_export_helper/CMS32/CMS32-results-stub.json
> +        "values": true
Wasn't `"values"` changed to `"observation_values"`?

2019-06-20 11:33 UTC, closed without merging