checker function for converting patients from Record to CQM::Patient
MeasureAuthoringTool/bonnie pull request #1262
Opened 2019-07-02 05:02 UTC by zlister

Pull requests into Bonnie require the following. Submitter and reviewer should :white_check_mark: when done. For items that are not-applicable, note it's not-applicable ("N/A") and :white_check_mark:.

**Submitter:**
- [ ] This pull request describes why these changes were made.
- [ ] This PR is into the correct branch.
- [ ] JIRA ticket for this PR: https://jira.mitre.org/browse/BONNIE-1964
- [ ] JIRA ticket links to this PR
- [ ] Code diff has been done and been reviewed (it **does not** contain: additional white space, not applicable code changes, debug statements, etc.)
- [ ] Tests are included and test edge cases
- [ ] Tests have been run locally and pass (remember to update Gemfile when applicable)

**Reviewer 1:**

Name:
- [ ] Code is maintainable and reusable, reuses existing code and infrastructure where appropriate, and accomplishes the task’s purpose
- [ ] The tests appropriately test the new code, including edge cases
- [ ] You have tried to break the code

If JIRA tests were used to supplement or replace automated tests:
- [ ] JIRA tests have been run and pass
- [ ] You agree with the justification for use of JIRA tests or have provided input on why you disagree

**Reviewer 2:**

Name:
- [ ] Code is maintainable and reusable, reuses existing code and infrastructure where appropriate, and accomplishes the task’s purpose
- [ ] The tests appropriately test the new code, including edge cases
- [ ] You have tried to break the code

If JIRA tests were used to supplement or replace automated tests:
- [ ] JIRA tests have been run and pass
- [ ] You agree with the justification for use of JIRA tests or have provided input on why you disagree

2019-07-03 13:13 UTC, losborne commented
Codecov report is buggy--actually it is +0.07 if you go to the codecov site.

2019-07-03 14:40 UTC, losborne commented on lib/tasks/cql.rake
> +              element = element.split(':')[0].delete(',')
One of the elements in the whitelist, `Diagnostic Study, Result'`, has a comma, so this removal would never match up with that.  I think we need to remove the comma from the whitelist element in order to hit that one, right?

2019-07-03 14:43 UTC, losborne commented on lib/tasks/cql.rake
> +        next unless sdc[:id] != 'MeasurePeriod'
I think `next unless ... !=` would be clearer as `next if ... ==`

2019-07-03 14:58 UTC, lukoktonos requested changes
In addition to comments here, discussed on slack about changing error printout for `dataElements` and posed the question about there being unexpected differences in our super tester accounts.

2019-07-03 15:03 UTC, zlister commented on lib/tasks/cql.rake
> +              element = element.split(':')[0].delete(',')
Yep, good catch.

2019-07-05 13:35 UTC, lukoktonos approved these changes

2019-07-05 14:30 UTC, jbradl11 requested changes
Looks good. Just need to update the Gemfile.

2019-07-08 14:20 UTC, jbradl11 approved these changes

2019-07-08 14:21 UTC, merged