Data Element Negation View
MeasureAuthoringTool/bonnie pull request #1264
Opened 2019-07-05 16:24 UTC by losborne

Pull requests into Bonnie require the following. Submitter and reviewer should :white_check_mark: when done. For items that are not-applicable, note it's not-applicable ("N/A") and :white_check_mark:.

**Submitter:**
- [ ] This pull request describes why these changes were made.
- [ ] This PR is into the correct branch.
- [ ] JIRA ticket for this PR:
- [ ] JIRA ticket links to this PR
- [ ] Code diff has been done and been reviewed (it **does not** contain: additional white space, not applicable code changes, debug statements, etc.)
- [ ] If UI changes have been made, google WAVE plug-in has been executed to ensure no 508 issues were introduced.
- [ ] Tests are included and test edge cases
- [ ] Tests have been run locally and pass (remember to update Gemfile when applicable)
- [ ] Test fixtures updated and documented as necessary ( see [internal wiki](https://gitlab.mitre.org/bonnie/internal-documentation/wikis/testing#test-fixtures) )
- [ ] Code coverage has not gone down and all code touched or added is covered. 
     * In rare situations, this may not be possible or applicable to a PR. In those situations:
         1. Note why this could not be done or is not applicable here: 
         2. Add TODOs in the code noting that it requires a test
         3. Add a JIRA task to add the test and link it here: 
- [ ] Automated regression test(s) pass

If JIRA tests were used to supplement or replace automated tests:
- [ ] JIRA test links:
- [ ] Justification for using JIRA tests:
- [ ] JIRA tests have been added to sprint

**Reviewer 1:**

Name:
- [ ] Code is maintainable and reusable, reuses existing code and infrastructure where appropriate, and accomplishes the task’s purpose
- [ ] The tests appropriately test the new code, including edge cases
- [ ] You have tried to break the code

If JIRA tests were used to supplement or replace automated tests:
- [ ] JIRA tests have been run and pass
- [ ] You agree with the justification for use of JIRA tests or have provided input on why you disagree

**Reviewer 2:**

Name:
- [ ] Code is maintainable and reusable, reuses existing code and infrastructure where appropriate, and accomplishes the task’s purpose
- [ ] The tests appropriately test the new code, including edge cases
- [ ] You have tried to break the code

If JIRA tests were used to supplement or replace automated tests:
- [ ] JIRA tests have been run and pass
- [ ] You agree with the justification for use of JIRA tests or have provided input on why you disagree

2019-07-07 22:30 UTC, jbradl11 requested changes
I am seeing an odd behavior following these steps:
- Select "Not Performed" 
- Select a code from the list
- Unclick "Not Performed"

The data element view collapses instead of just unclicking the data element.

2019-07-08 14:48 UTC, hossenlopp commented on app/assets/javascripts/templates/patient_builder/edit_criteria.hbs
> +          <label for="negationCodeListId_{{@cid}}" class="sr-only">Negation Code Set</label>
Since we are now letting them properly choose a code...
```suggestion
          <label for="negationCodeListId_{{@cid}}" class="sr-only">Negation Rationale Code</label>
```

2019-07-08 15:03 UTC, hossenlopp requested changes

2019-07-08 15:03 UTC, hossenlopp commented on app/assets/javascripts/views/patient_builder/data_criteria.js.coffee
> +    @cqmValueSets = @measure.get('cqmValueSets')
Why fetch this when it is only getting used once on line 103?

2019-07-08 15:03 UTC, hossenlopp commented on app/assets/javascripts/views/patient_builder/inputs/code.js.coffee
> +    @$('select[name="valueset"] > option:first').prop('selected', true)
I suggest adding a simple test for this.

2019-07-08 16:08 UTC, mayerm94 approved these changes
This is great

2019-07-08 16:26 UTC, hossenlopp approved these changes

2019-07-08 16:32 UTC, jbradl11 approved these changes

2019-07-08 16:32 UTC, merged