Model update rake task
MeasureAuthoringTool/bonnie pull request #1267
Opened 2019-07-09 19:05 UTC by zlister

Created rake task to convert models from QDM 5.4 to QDM 5.5. Also added checker function to make sure no unexpected data loss happens

Pull requests into Bonnie require the following. Submitter and reviewer should :white_check_mark: when done. For items that are not-applicable, note it's not-applicable ("N/A") and :white_check_mark:.

**Submitter:**
- [ ] This pull request describes why these changes were made.
- [ ] This PR is into the correct branch.
- [ ] JIRA ticket for this PR:
- [ ] JIRA ticket links to this PR
- [ ] Code diff has been done and been reviewed (it **does not** contain: additional white space, not applicable code changes, debug statements, etc.)
- [ ] If UI changes have been made, google WAVE plug-in has been executed to ensure no 508 issues were introduced.
- [ ] Tests are included and test edge cases
- [ ] Tests have been run locally and pass (remember to update Gemfile when applicable)
- [ ] Test fixtures updated and documented as necessary ( see [internal wiki](https://gitlab.mitre.org/bonnie/internal-documentation/wikis/testing#test-fixtures) )
- [ ] Code coverage has not gone down and all code touched or added is covered. 
     * In rare situations, this may not be possible or applicable to a PR. In those situations:
         1. Note why this could not be done or is not applicable here: 
         2. Add TODOs in the code noting that it requires a test
         3. Add a JIRA task to add the test and link it here: 
- [ ] Automated regression test(s) pass

If JIRA tests were used to supplement or replace automated tests:
- [ ] JIRA test links:
- [ ] Justification for using JIRA tests:
- [ ] JIRA tests have been added to sprint

**Reviewer 1:**

Name:
- [ ] Code is maintainable and reusable, reuses existing code and infrastructure where appropriate, and accomplishes the task’s purpose
- [ ] The tests appropriately test the new code, including edge cases
- [ ] You have tried to break the code

If JIRA tests were used to supplement or replace automated tests:
- [ ] JIRA tests have been run and pass
- [ ] You agree with the justification for use of JIRA tests or have provided input on why you disagree

**Reviewer 2:**

Name:
- [ ] Code is maintainable and reusable, reuses existing code and infrastructure where appropriate, and accomplishes the task’s purpose
- [ ] The tests appropriately test the new code, including edge cases
- [ ] You have tried to break the code

If JIRA tests were used to supplement or replace automated tests:
- [ ] JIRA tests have been run and pass
- [ ] You agree with the justification for use of JIRA tests or have provided input on why you disagree

2019-07-10 18:01 UTC, lukoktonos commented on lib/tasks/bonnie_run_once.rake
> +  task :convert_qdm_to_new_qdm => :environment do
Recommend renaming to `:convert_patients_qdm_5_4_to_5_5` or something else that indicates that _patients_ are being converted and qdm/new qdm refers to 5.4 and 5.5.

2019-07-10 18:01 UTC, lukoktonos commented on lib/tasks/bonnie_run_once.rake
> +            new_data_element.attributes['id'] = element.attributes['id']['value']
I think we need to add `nil` checks for `element.attributes['id']` and `element.attributes['id']['value']`--there are lots of this error printed out if you convert_patients and then run this rake task both using the new models branch:
```
#<QDM::PatientCharacteristicBirthdate:0x00007ff4c83e0110>
undefined method `[]' for nil:NilClass
```

2019-07-10 18:01 UTC, lukoktonos commented on lib/tasks/bonnie_run_once.rake
> +      ode = ''
Since `ode` is already a word I think it makes sense to just use `old_data_element` for readability

2019-07-10 20:03 UTC, zlister commented on lib/tasks/bonnie_run_once.rake
> +            new_data_element.attributes['id'] = element.attributes['id']['value']
This isn't a proper workflow, when you convert_patients with the new models branch, that is creating a 5.5 model patient. When running the rake task, you would be trying to convert a 5.5 model patient to a 5.5 model patient.

2019-07-12 12:41 UTC, mayerm94 requested changes
principal diagnosis doesn't appear to be getting a rank when put into the diagnoses array. The diagnoses transformations should have a unit test.

![image](https://user-images.githubusercontent.com/3967953/61128728-bc187780-a480-11e9-9ce2-a3e7ef46adc7.png)

2019-07-15 16:46 UTC, losborne commented on lib/tasks/bonnie_run_once.rake
> +        old_data_element.relatedTo.each do |related|
Ruby has a `each_with_index do |related, index|` so you don't have to keep track of the index manually

2019-07-16 10:46 UTC, lukoktonos requested changes
There are rubocop failures on Travis related to this file, yarn audit and rake test failures are unrelated

2019-07-16 16:18 UTC, lukoktonos approved these changes
Looks good

Failing travis  tests are unrelated to this PR as far as I can tell

2019-07-22 19:31 UTC, mayerm94 approved these changes
👍

2019-07-22 21:45 UTC, merged