Expired fix
MeasureAuthoringTool/bonnie pull request #1281
Opened 2019-07-19 01:44 UTC by jbradl11

Pull requests into Bonnie require the following. Submitter and reviewer should :white_check_mark: when done. For items that are not-applicable, note it's not-applicable ("N/A") and :white_check_mark:.

Fix Patient Characteristic Expired / Deathdate save / loading. For measures that have Patient Characteristic expired and for measures that don't.

Added a warning banner for measures that don't have Patient Characteristic Birthdate/Expired but use them on the patient.

**Submitter:**
- [x] This pull request describes why these changes were made.
- [x] This PR is into the correct branch.
- [ ] JIRA ticket for this PR:
- [ ] JIRA ticket links to this PR
- [x] Code diff has been done and been reviewed (it **does not** contain: additional white space, not applicable code changes, debug statements, etc.)
- [x] If UI changes have been made, google WAVE plug-in has been executed to ensure no 508 issues were introduced.
- [x] Tests are included and test edge cases
- [x] Tests have been run locally and pass (remember to update Gemfile when applicable)
- [x] Test fixtures updated and documented as necessary ( see [internal wiki](https://gitlab.mitre.org/bonnie/internal-documentation/wikis/testing#test-fixtures) )
- [x] Code coverage has not gone down and all code touched or added is covered. 
     * In rare situations, this may not be possible or applicable to a PR. In those situations:
         1. Note why this could not be done or is not applicable here: 
         2. Add TODOs in the code noting that it requires a test
         3. Add a JIRA task to add the test and link it here: 
- [x] Automated regression test(s) pass

If JIRA tests were used to supplement or replace automated tests:
- [ ] JIRA test links:
- [ ] Justification for using JIRA tests:
- [ ] JIRA tests have been added to sprint

**Reviewer 1:**

Name:
- [ ] Code is maintainable and reusable, reuses existing code and infrastructure where appropriate, and accomplishes the task’s purpose
- [ ] The tests appropriately test the new code, including edge cases
- [ ] You have tried to break the code

If JIRA tests were used to supplement or replace automated tests:
- [ ] JIRA tests have been run and pass
- [ ] You agree with the justification for use of JIRA tests or have provided input on why you disagree

**Reviewer 2:**

Name:
- [ ] Code is maintainable and reusable, reuses existing code and infrastructure where appropriate, and accomplishes the task’s purpose
- [ ] The tests appropriately test the new code, including edge cases
- [ ] You have tried to break the code

If JIRA tests were used to supplement or replace automated tests:
- [ ] JIRA tests have been run and pass
- [ ] You agree with the justification for use of JIRA tests or have provided input on why you disagree

2019-07-19 12:29 UTC, lukoktonos requested changes
Using the measure without the Patient Characteristic, Expired, the warning does show upon initial selection of birth date or death date. 👍 

Date of Death does not auto populate time like birth date:
<img width="237" alt="image" src="https://user-images.githubusercontent.com/14879344/61534807-951cf100-a9fe-11e9-971d-dfdea3dcfd57.png">

If none is entered on this measure or if one is typed in and you click 'save', saving fails and these errors are displayed:
<img width="699" alt="image" src="https://user-images.githubusercontent.com/14879344/61534836-a665fd80-a9fe-11e9-932a-e1e95ce1139e.png">
(the other warning about missing charactersitics is no longer displayed at this point)

Using a measure that has the patient characteristic, `--:-- --` is shown in the time placeholder, but then saving works and 12:00am is chosen and displayed if the patient is re-opened.

2019-07-19 12:29 UTC, lukoktonos commented on spec/javascripts/patient_builder_tests/patient_builder_spec.js.coffee
> +    @measure = loadMeasureWithValueSets 'cqm_measure_data/CMSv5555/CMSv5555.json', 'cqm_measure_data/CMSv5555/value_sets.json'
Since these are only used within this `it` block, it's better to not make them member variables (`measure` vs `@measure`, etc)

2019-07-19 12:29 UTC, losborne commented on spec/javascripts/patient_builder_tests/patient_builder_spec.js.coffee
> +    # TODO: don't rely on first() for this. What should the criteria be?
This line through line 63 (@patientDataElement) are seemingly unused and can be removed (also the similar ones up at the top of the file whence this setup was copied seem to no longer be used and can be removed as well.

2019-07-19 12:29 UTC, losborne commented on spec/javascripts/patient_builder_tests/patient_builder_spec.js.coffee
> +    @$el = @patientBuilder.$el
This one is not used in this test, but the one up at the top is used, so just remove from here.

2019-07-19 18:30 UTC, lukoktonos approved these changes
👍

2019-07-19 20:04 UTC, lukoktonos approved these changes
mouseover text works and passes the wave tool

2019-07-22 16:50 UTC, hackrm approved these changes
Was able to see the banner when running Bonnie with a measure known to have this issue.

2019-07-22 16:57 UTC, merged