Entities optional
MeasureAuthoringTool/bonnie pull request #1294
Opened 2019-07-29 14:25 UTC by losborne

Pull requests into Bonnie require the following. Submitter and reviewer should :white_check_mark: when done. For items that are not-applicable, note it's not-applicable ("N/A") and :white_check_mark:.

**Submitter:**
- [ ] This pull request describes why these changes were made.
- [ ] This PR is into the correct branch.
- [ ] JIRA ticket for this PR:
- [ ] JIRA ticket links to this PR
- [ ] Code diff has been done and been reviewed (it **does not** contain: additional white space, not applicable code changes, debug statements, etc.)
- [ ] If UI changes have been made, google WAVE plug-in has been executed to ensure no 508 issues were introduced.
- [ ] Tests are included and test edge cases
- [ ] Tests have been run locally and pass (remember to update Gemfile when applicable)
- [ ] Test fixtures updated and documented as necessary ( see [internal wiki](https://gitlab.mitre.org/bonnie/internal-documentation/wikis/testing#test-fixtures) )
- [ ] Code coverage has not gone down and all code touched or added is covered. 
     * In rare situations, this may not be possible or applicable to a PR. In those situations:
         1. Note why this could not be done or is not applicable here: 
         2. Add TODOs in the code noting that it requires a test
         3. Add a JIRA task to add the test and link it here: 
- [ ] Automated regression test(s) pass

If JIRA tests were used to supplement or replace automated tests:
- [ ] JIRA test links:
- [ ] Justification for using JIRA tests:
- [ ] JIRA tests have been added to sprint

**Reviewer 1:**

Name:
- [ ] Code is maintainable and reusable, reuses existing code and infrastructure where appropriate, and accomplishes the task’s purpose
- [ ] The tests appropriately test the new code, including edge cases
- [ ] You have tried to break the code

If JIRA tests were used to supplement or replace automated tests:
- [ ] JIRA tests have been run and pass
- [ ] You agree with the justification for use of JIRA tests or have provided input on why you disagree

**Reviewer 2:**

Name:
- [ ] Code is maintainable and reusable, reuses existing code and infrastructure where appropriate, and accomplishes the task’s purpose
- [ ] The tests appropriately test the new code, including edge cases
- [ ] You have tried to break the code

If JIRA tests were used to supplement or replace automated tests:
- [ ] JIRA tests have been run and pass
- [ ] You agree with the justification for use of JIRA tests or have provided input on why you disagree

2019-07-29 17:37 UTC, hossenlopp approved these changes

2019-07-30 15:29 UTC, jbradl11 requested changes
Identifier does not appear if only one of the two fields is filled in. This should either not allow the user to add Identifier or display just the one field (if QDM allows for that).
![image](https://user-images.githubusercontent.com/1568999/62142963-33da0500-b2bd-11e9-8aa9-abeed2ab093c.png)

2019-07-30 17:13 UTC, losborne commented
Updated to display identifier correctly, but will need to merge cqm-models and cqm-execution before merging

2019-08-02 14:50 UTC, hossenlopp commented
I think this has two undecided questions on how it should function:

1. Show nulls in attribute view or not? Currently is showing them. This is a change already made.
2. Unfilled identifier fields means: null OR identifier with null naming system and values? Currently the later.

Here is a screenshot that shows the null fields showing up and the Identifier {null, null}

<img width="496" alt="Screen Shot 2019-08-02 at 10 41 04 AM" src="https://user-images.githubusercontent.com/11613067/62378369-b0195600-b512-11e9-8468-2658802805d8.png">

My opinions on this... but @jbradl11 and @losborne are free to decide whats best:

1. Showing nulls makes it clear to the user what is there. More clutter, but better info.
2. I think they should be able to have an identifier field be null by just not filling out the fields.

2019-08-06 18:18 UTC, jbradl11 approved these changes

2019-08-06 18:19 UTC, merged