Measure History PR Dry Run
MeasureAuthoringTool/bonnie pull request #567
Opened 2016-08-22 21:56 UTC by hossenlopp

2016-08-23 13:52 UTC, DPC15038 commented on app/assets/javascripts/templates/patient_bank/patient_bank.hbs
> +    <a href="#measures/{{measure_id}}/history"><i class="fa fa-history"></i> </i>MEASURE UPLOAD HISTORY</a>
`{{measure_id}}` is null, so this link doesn't redirect to anywhere
Consider getting the hqmf_set_id within the context of /patient_bank/patient_bank_view.js.coffee

2016-08-23 13:56 UTC, DPC15038 commented on lib/ext/measure_upload_summary.rb
> +        case !patient.too_big
Using the case statement with `true` and `else` seems a little weird to me. Why not just use a normal `if - else`?

2016-08-23 14:18 UTC, hossenlopp commented on app/assets/javascripts/templates/patient_bank/patient_bank.hbs
> +    <a href="#measures/{{measure_id}}/history"><i class="fa fa-history"></i> </i>MEASURE UPLOAD HISTORY</a>
Good catch... I have no idea why this link is here. Wont have a need to go from patient bank to the measure history. I'll remove it.

2016-08-23 14:32 UTC, DPC15038 commented on app/assets/javascripts/views/measure_history_diff_view.js.coffee
> +      return
[return statements in coffeescript are implicit](http://coffeescript.org/#expressions)

2016-08-23 14:46 UTC, DPC15038 commented on app/assets/javascripts/views/measure_history_timeline_view.js.coffee
> +
Could this be refactored as

`if @upload_summaries.size() > 1 && @upload_summaries.at(0).has('measure_db_id_before')`
&emsp;`@hasHistory = true`
`else`
&emsp;`@hasHistory = false`

or even

`@hasHistory = @upload_summaries.size() > 1 && @upload_summaries.at(0).has('measure_db_id_before')`

2016-08-23 14:57 UTC, DPC15038 commented on app/assets/javascripts/views/measure_history_view.js.coffee
> +    console.log(population)
Remove `console.log` statements

2016-08-23 17:54 UTC, hossenlopp commented on lib/ext/measure_upload_summary.rb
> +        case !patient.too_big
Agreed. @mulcahyk, can you take a look at this?

2016-08-23 22:19 UTC, thecristen commented on app/assets/javascripts/models/xmeasure.js.coffee
> +    @set 'patients', new Thorax.Collections.Patients [], _fetched: true
Where do you use `isEmpty()`? This just seems a bit odd to me...

2016-08-23 22:32 UTC, thecristen commented on app/assets/javascripts/router.js.coffee
> +    archivedMeausures = measure.get('archived_measures')
Why is this variable name consistently misspelled? Intentional? 😰

2016-08-24 05:23 UTC, thecristen commented on app/assets/javascripts/templates/measure_history_diff.hbs
> +    <p>Select a historic measure to view diff.</p>
Might want to explain to a lay person what a "diff" is, or substitute with more common terminology.

2016-08-24 05:38 UTC, thecristen commented on app/assets/javascripts/templates/measure_upload_summary.hbs
> +        <table class="table-striped table-condensed ">
Forgot the (necessary for bootstrap) `table` class

2016-08-24 05:41 UTC, thecristen commented on app/assets/javascripts/views/measure_history_view.js.coffee
> +      minTime = 999999999999999
Does using 999999999999999 really make sense here?

2016-08-24 05:43 UTC, thecristen commented
Would you mind adding some screenshots of the new views?

2016-08-24 12:34 UTC, hossenlopp commented on app/assets/javascripts/router.js.coffee
> +    archivedMeausures = measure.get('archived_measures')
Which variable name?

2016-08-24 13:32 UTC, thecristen commented on app/assets/javascripts/router.js.coffee
> +    archivedMeausures = measure.get('archived_measures')
`archivedMeausures`

2016-08-24 13:38 UTC, DPC15038 commented
## **MEASURE LOGIC CHANGES**
![measure logic changes modal](https://cloud.githubusercontent.com/assets/17532163/17932422/f1805f22-69dd-11e6-97ce-b0b675e7ba30.png)
---
## **PATIENT BUILDER COMPARE BUTTON**
![patient builder - compare button](https://cloud.githubusercontent.com/assets/17532163/17932425/f182d982-69dd-11e6-99b9-bb9a71e0cae3.png)
---
## **PATIENT COMPARE MODAL**
![patient compare modal](https://cloud.githubusercontent.com/assets/17532163/17932423/f18099ba-69dd-11e6-8e7c-c82ef3395b9e.png)
---
## **MEASURE UPLOAD HISTORY**
![measure upload history](https://cloud.githubusercontent.com/assets/17532163/17932424/f1812c90-69dd-11e6-9264-892be6554168.png)
---
## **MEASURE UPLOAD SUMMARY MODAL**
![measure upload summary modal](https://cloud.githubusercontent.com/assets/17532163/17932426/f184d98a-69dd-11e6-8392-95ec1f3de943.png)

2016-08-24 17:28 UTC, DPC15038 commented on app/assets/javascripts/helpers.js.coffee
> +Handlebars.registerHelper 'dateFormat', (date, fmt) ->
I initially used this Helper file in my additions to the Patient Builder, before deciding not to use it, and reverting the file. Pete made several comments on it, which I'll copy here
![image](https://cloud.githubusercontent.com/assets/17532163/17940738/70101a2e-69fe-11e6-9fd8-1102d5f796d8.png)

2016-08-24 17:30 UTC, DPC15038 commented on app/assets/javascripts/helpers.js.coffee
> +  (block.fn(i) for i in [0...n]).join("")
I initially used this Helper file in my additions to the Patient Builder, before deciding not to use it, and reverting the file. Pete made several comments on it, which I'll copy here
![image](https://cloud.githubusercontent.com/assets/17532163/17940839/dfc32122-69fe-11e6-8973-39d2b3a67847.png)

2016-08-24 17:31 UTC, DPC15038 commented on app/assets/javascripts/helpers.js.coffee
> +
I initially used this Helper file in my additions to the Patient Builder, before deciding not to use it, and reverting the file. Pete made several comments on it, which I'll copy here
![image](https://cloud.githubusercontent.com/assets/17532163/17940883/0cdb260a-69ff-11e6-8eb8-d4cc25300ef0.png)

2016-08-24 18:34 UTC, thecristen commented on app/assets/javascripts/templates/measure_upload_summary_dialog.hbs
> +        <h5>Your measure has uploaded successfully!</h5>
Change the h5 to h2
And add the closing `</div>` for the modal-header!!

2016-08-24 18:36 UTC, thecristen commented on app/assets/javascripts/templates/measure_upload_summary.hbs
> +          <tr>
For all tables - the table rows containing headers need to be wrapped in `<thead>` and the rest of the rows collectively wrapped in a `<tbody>`

2016-08-24 18:41 UTC, thecristen commented on app/assets/stylesheets/measure_history.less
> +
Might want to clean out some of the commented out stuff and then take advantage of LESS by nesting, e.g. 

```less
th.history-patient-header {
  height: 55px;
  white-space: nowrap;
  border-top: none !important;

  > div {
    transform:
    /* Magic Numbers */
    translate(-3px, 15px)
    /* 45 is really 360 - 45 */
    rotate(315deg);
    width: 30px;

    > span {
    padding: 5px;
    }
  }
}
```

2016-08-24 18:44 UTC, thecristen commented on app/assets/stylesheets/measure_history.less
> +}
How will you handle longer patient names?

2016-08-24 18:46 UTC, thecristen commented on app/assets/stylesheets/measure_history.less
> +  color: #730800;
use a variable for these colors!

2016-08-24 18:48 UTC, thecristen commented on app/assets/stylesheets/measure_history.less
> +/* Style from diffy gem */
I'm guessing the styles from the diffy gem are not intended to be changed? Might want to separate it out to its own css file if that's the case

2016-08-24 20:32 UTC, hossenlopp commented on app/assets/javascripts/templates/measure_history_diff.hbs
> +    <p>Select a historic measure to view diff.</p>
Updated this to reflect what is actually happening. It shows momentary if it takes some time to load the diff "comparison" from the server.

2016-08-24 20:36 UTC, hossenlopp commented on app/assets/javascripts/views/measure_history_view.js.coffee
> +    console.log(population)
Removed these.

2016-08-24 20:37 UTC, hossenlopp commented on app/assets/javascripts/views/measure_history_timeline_view.js.coffee
> +
Committed improved explanation and logic for this.

2016-08-24 20:38 UTC, hossenlopp commented on app/assets/javascripts/views/measure_history_diff_view.js.coffee
> +      return
removed the return from the .get call back. I purposefully need to leave the function early with the first one.

2016-08-25 13:43 UTC, hossenlopp commented on app/assets/javascripts/router.js.coffee
> +    archivedMeausures = measure.get('archived_measures')
Good catch! Fixed in fd340dbb0d06240a77e96248a4d4ba2211db47a2.

2016-08-25 13:45 UTC, hossenlopp commented on app/assets/javascripts/views/measure_history_view.js.coffee
> +      minTime = 999999999999999
This code was removed in ed9c1936305ee4e8f7b92a25863a04ce92902671.

2016-08-25 13:52 UTC, thecristen commented
I feel like I need more context on the Patient Compare modal. It should at least tell me which patient I am looking at. Also, in this particular screenshot, how is "current state" any different from "after most recent upload"? Are they the same? Is my current state 5 changes after that most recent upload? There's no way to tell, and I think adding it would help..

2016-08-25 16:18 UTC, DPC15038 commented
@thecristen That's my bad for uploading a poor screenshot. This one better illustrates a difference of what's going on. However, with that said I do agree with the other things you are saying
![image](https://cloud.githubusercontent.com/assets/17532163/17977013/f48852fc-6abd-11e6-8e72-115f6002db5b.png)

2016-08-26 13:25 UTC, hossenlopp commented on app/assets/javascripts/templates/measure_upload_summary.hbs
> +        <table class="table-striped table-condensed ">
@DPC15038 added the table class in e5dcb8de0c47a0ceab16f9a66ff9a31f1be10e7c. Just commenting to mark as done.

2016-08-26 14:15 UTC, hossenlopp commented on app/assets/javascripts/templates/measure_upload_summary_dialog.hbs
> +        <h1 id="uploadSummaryTitle">Measure Upload Completed</h1>
modal-header should close after the h1 and be a sibling to the modal-body and modal-footer. I'll fix this.

2016-08-26 14:47 UTC, hossenlopp commented
The upload summary modal shows this when there were no changes with calculation.  I think this lack of data makes the modal awkward. @thecristen, should we show the two status circles when there are no changes to make it more consistent?
![screen shot 2016-08-26 at 10 43 43 am](https://cloud.githubusercontent.com/assets/11613067/18009409/1868f430-6b7a-11e6-9409-c8bb6facccbc.png)

2016-08-29 11:03 UTC, thecristen commented
@hossenlopp I totally agree it looks awkward! This'll probably be a bit harder to program, but I think it shouldn't show this modal at all if there are no patient calculation changes. In that case, it should just follow the current behavior (refresh to the dashboard page on successful upload).

2016-08-29 20:17 UTC, pkmitre commented on app/assets/javascripts/models/xmeasure.js.coffee
> +    @set 'patients', new Thorax.Collections.Patients [], _fetched: true
I think I wrote that comment, a long time ago; it should probably be expanded to be clear on what's going on. Basically, when you initialize a collection to the empty array in Thorax, calling isEmpty() on the collection can return false because Thorax thinks the collection has perhaps not been fetched from the server yet.

2016-08-30 16:33 UTC, mulcahyk commented on app/controllers/patients_controller.rb
> +  # wrap patientData in stratifications
Do we still need this?  It was from the prototype.

2016-08-30 16:34 UTC, mulcahyk commented on app/controllers/patients_controller.rb
> +  def calculate_value_results(actual, expected)
I think that we can remove this since the 'pass/fail' calculations have been centralized now.

2016-08-30 16:40 UTC, mulcahyk commented on app/controllers/patients_controller.rb
> +  #   {label: "Jack Sparrow", times: [{result:"pass", updateTime: 1451606400000},
I think we can say goodbye to Jack Sparrow and crew....

2016-09-06 16:18 UTC, mayerm94 commented on app/assets/javascripts/models/patient.js.coffee
Not relevant to this pull request, but printDate() uses getDay(), which returns the day of the week 0-Sunday, 1-Monday etc..... getDate() is the function that will return 0-31 corresponding with the date

2016-09-06 18:56 UTC, mayerm94 commented on app/assets/javascripts/views/patient_builder/patient_builder.js.coffee
> +    @calculateAllResults((calc_results) =>
The addition of this function appears to be causing the jasmine test for "PatientBuilderView setting basic attributes and saving tries to save the patient correctly" to fail.

2016-09-07 14:50 UTC, mayerm94 commented on app/assets/javascripts/views/patient_builder/patient_version_compare.js.coffee
> +      # @populationInBefore = true
This line can be removed

2016-09-07 14:51 UTC, mayerm94 commented on app/assets/javascripts/views/patient_builder/patient_version_compare.js.coffee
> +          # @fromEdit = true
This line can also be removed.... in addition to other commented out lines below that also appear uncommented elsewhere

2016-09-07 14:57 UTC, mayerm94 commented on app/controllers/measures_controller.rb
> +    #render :json => results
This commented out line can be removed

2016-09-08 10:31 UTC, mayerm94 commented on app/assets/javascripts/views/measure_history_timeline_view.js.coffee
> +    #$.get('/measures/history?id='+@model.attributes['hqmf_set_id'], @loadHistory)
Commented line can be removed

2016-09-08 10:34 UTC, mayerm94 commented on app/assets/javascripts/views/measure_history_timeline_view.js.coffee
> +      -> @$('#measure-diff-view-dialog').on 'hidden.bs.modal', @closeDiff
Weird style with the thin arrow here, should move thin arrow or whole line up

2016-09-08 11:27 UTC, mayerm94 commented on app/controllers/patients_controller.rb
> +              # puts key
These commented out puts can be removed

2016-09-08 11:31 UTC, mayerm94 commented on app/controllers/patients_controller.rb
> +    puts "The from is #{from}"
We probably don't want our logs filled with the output of this puts statement, suggest deletion

2016-09-08 11:33 UTC, mayerm94 commented on app/controllers/patients_controller.rb
> +    # binding.pry
This line should be deleted

2016-09-08 11:35 UTC, mayerm94 commented on app/controllers/patients_controller.rb
> +    blah = {}
Is 'blah' ever even used for anything?

2016-09-08 11:36 UTC, mayerm94 commented on app/controllers/patients_controller.rb
> +    meh = {}
Is 'meh' ever even used for anything?

2016-09-08 11:39 UTC, mayerm94 commented on app/controllers/patients_controller.rb
> +      # exps = to if field == 'expected_values'
These commented lines seem to be unnecessary

2016-09-08 11:42 UTC, mayerm94 commented on app/controllers/patients_controller.rb
> +    #       pv.map do |plk, plv| # for each logic population
Is anybody particularly attached to this block of commented out code?

2016-09-08 11:52 UTC, mayerm94 commented on config/mongoid.yml
> +      # database: bonnie_production-2016-03-24-23
Looks like someone blindly did a 'commit -a'. Delete this line

2016-09-08 11:58 UTC, mayerm94 commented on lib/ext/measure_upload_summary.rb
> +  #
Delete extraneous comment

2016-09-08 11:59 UTC, mayerm94 commented on lib/ext/measure_upload_summary.rb
> +        # diff_after_expected = (b_mups[:patients][patient][:expected].to_a - trim_after.to_a).to_h
Delete commented out code

2016-09-08 12:01 UTC, mayerm94 commented on lib/ext/record.rb
> +    # puts "\n\n\tcalc_results is #{calc_results.to_json.size}\n\n"
Remove commented debug line

2016-09-08 12:02 UTC, mayerm94 commented on lib/tasks/setup_history_tracks.rake
> +          # next if patient.id == "5509b61769702d5cfa100c00"
Delete this line

2016-09-08 12:03 UTC, mayerm94 commented on lib/tasks/setup_history_tracks.rake
> +      # Rake::Task['upgrade_add_hx_tracks:patients:clear_actuals'].invoke
Delete this

2016-09-08 12:05 UTC, mayerm94 commented on lib/tasks/setup_history_tracks.rake
> +       puts "Measure: #{measure.cms_id}\n\tPatient: #{patient.first} #{patient.last} (#{patient._id})\n\t\tPopulation Index: #{population_index}"
Do we need to log every single calculated patient?

2016-09-08 12:11 UTC, mayerm94 commented on lib/tasks/setup_history_tracks.rake
> +      puts "It took #{finish - start} seconds to run this."
1. Wouldn't this provide milliseconds, not seconds
2. Could we add context, "It took 3 seconds to calculate X patients"

2016-09-08 12:22 UTC, mayerm94 commented on test/functional/patients_controller_test.rb
> +    # patient.user = @user
Delete commented out lines from old version of test

2016-09-08 12:22 UTC, mayerm94 commented on test/functional/patients_controller_test.rb
> +    # patient.user = @user
Also delete them here

2016-09-08 12:23 UTC, mayerm94 commented on test/functional/patients_controller_test.rb
> +    # assert_equal "pass", r.history_tracks[2]['original']['calc_results'][0]['status']
Remove commented out assertions

2016-09-08 12:24 UTC, mayerm94 commented on test/functional/patients_controller_test.rb
> +@patient = {
Fix spacing

2016-09-08 12:28 UTC, mayerm94 commented on test/functional/patients_controller_test.rb
> +     'calc_results'=> [{"measure_id"=>@measure.hqmf_set_id, "population_index"=>0, "IPP"=>1, "DENOM"=>0, "NUMER"=>0, "rationale"=>'X' * (1024), "finalSpecifics"=>'Z' * (1024)}]}
Is it necessary to reset all of the fields of the patient when all that changed was calc_results?

2016-09-08 12:28 UTC, mayerm94 commented on test/functional/patients_controller_test.rb
> +    # binding.pry
Remove comment

2016-09-08 12:29 UTC, mayerm94 commented on test/functional/patients_controller_test.rb
> +@patient = {
Fix spacing

2016-09-08 12:29 UTC, mayerm94 commented on test/functional/patients_controller_test.rb
> +    # binding.pry
Remove comment

2016-09-08 12:29 UTC, edeyoung commented on app/controllers/patients_controller.rb
> +    meh = {}
variable names should always be descriptive. if `blah`, `meh`, and `me` are used, these need to be renamed. Ensure that all variable names in the following files are descriptive.

2016-09-08 12:31 UTC, edeyoung commented on app/controllers/patients_controller.rb
> +  def history_changes_results(field, from, to, acts, exps, fordot)
what do `exps`, `acts` and fordot` mean?

add context to `from` and `to`. `from` what? `to` what?

what is the `field` a field of?

A user should be able to read a method signature and know what to give to the function, especially if there are no comments.

Look at all of the methods in these files and ensure that the parameter names are sufficiently descriptive.

2016-09-08 12:34 UTC, edeyoung commented on app/controllers/patients_controller.rb
> +  def history_changes_singles(field, from, to)
add comment headers to all of the methods.

2016-09-08 22:11 UTC, mulcahyk commented on app/controllers/patients_controller.rb
> +  def history
I think that we can remove this function.  It was for tracking changes to fields at the patient level and we are no longer showing/reporting that level of detail.

2016-09-08 22:13 UTC, mulcahyk commented on app/controllers/patients_controller.rb
> +  def history_changes_singles(field, from, to)
I think that we can remove this function.  See comments on def history (line 28).

2016-09-08 22:13 UTC, mulcahyk commented on app/controllers/patients_controller.rb
> +  def history_changes_results(field, from, to, acts, exps, fordot)
I think that we can remove this function.  See comments on def history (line 28).

2016-09-20 14:17 UTC, edeyoung commented on app/assets/javascripts/models/patient.js.coffee
> +  getCalcValue: (population) ->
Consider adding a comment to this function and renaming so everything is spelled out.

2016-09-20 14:19 UTC, edeyoung commented on app/assets/javascripts/calculator.js.coffee
> +      result.set({patient_id: patient.id})
is `result.set({patient_id: patient.id})` the same as `result.patient_id = patient.id`? if so, change to the latter for consistency and readability. If not, what is this doing?

2016-09-20 14:19 UTC, edeyoung commented on app/assets/javascripts/calculator.js.coffee
> +      result.set({patient_id: patient.id})
Actually, is this `patient_id` ever used? If not, remove.

2016-09-20 14:23 UTC, edeyoung commented on app/assets/javascripts/models/measure.js.coffee
> +    attrs.archived_measures = new Thorax.Collections.ArchivedMeasures null, {measure_id: attrs._id, _fetched: false}
TODO: look in debugger

2016-09-20 14:23 UTC, edeyoung commented on app/assets/javascripts/models/patient.js.coffee
> +    _(this.get('calc_results')).find (result) -> result.measure_id == measure.get('hqmf_set_id') && result.population_index == population.index()
TODO: look in debugger

2016-09-20 14:25 UTC, edeyoung commented on app/assets/javascripts/models/result.js.coffee
> +# Treat/handle cached calculation results like "live" calculation results
what is the difference between `CachedResult` and `Result`?

2016-09-20 14:27 UTC, edeyoung commented on app/assets/javascripts/models/result.js.coffee
> +    @calculation.resolve()
In the parent class, `@calculation.resolvev()` is only called if certain conditions are met (`if @isPopulated() then @calculation.resolve() else @once 'change:rationale', -> @calculation.resolve()`). Does it make sense to not meet the conditions here? If so, provide a comment explaining this.

2016-09-20 14:29 UTC, edeyoung commented on app/assets/javascripts/models/upload_summary.js.coffee
> +  fetchDeferred: ->
add a comment explaining what this function does

2016-09-20 14:29 UTC, edeyoung commented on app/assets/javascripts/models/upload_summary.js.coffee
> +    fetchDef = $.Deferred()
spell out variable names

2016-09-20 14:32 UTC, edeyoung commented on app/assets/javascripts/models/upload_summary.js.coffee
> +    fetchDef = $.Deferred()
Same for the rest of the `fetchDef` variables in the rest of the file

2016-09-20 14:32 UTC, edeyoung commented on app/assets/javascripts/models/upload_summary.js.coffee
> +    @fetch(
TODO: check where this is defined in the debugger

2016-09-20 14:33 UTC, edeyoung commented on app/assets/javascripts/models/upload_summary.js.coffee
> +  fetchDeferred: ->
This method is repeated across several classes. Consider creating a class with this method and then subclassing for all of these classes. Or consider creating a helper function with the `fetchDeferred` content and reusing this.

2016-09-20 14:35 UTC, edeyoung commented on app/assets/javascripts/models/upload_summary.js.coffee
> +  initialize: (models, options) ->
Is `models` a required first element for a `Thorax.Collection`? I couldn't find that it is, but Thorax docs aren't great. If not, does this ever get called without a `null` argument for the first argument? If it doesn't, remove `models` as the first argument.

Also, instead of having an `options` parameter, you can just have the next argument be `measure_id` and not name it when you pass it in (e.g. if you kept `models`, the definition would look like `initialize:(models, model_id)` and the call would look like `new Thorax.Collections.UploadSummaries(null, <whatever measure_id is>)`. This removes a layer of obfuscation. I think you can also all the constructor like, `new Thorax.Collections.UploadSummaries(@measure_id=XXX)` or something along those lines. There should be examples in the code.

2016-09-20 14:51 UTC, edeyoung commented on app/assets/javascripts/models/measure.js.coffee
> +    attrs.archived_measures = new Thorax.Collections.ArchivedMeasures null, {measure_id: attrs._id, _fetched: false}
is `_fetched` a backbone, thorax, or other specially defined variable? If not, what's the reason for the `_` at the beginning?

2016-09-20 14:52 UTC, edeyoung commented on app/assets/javascripts/models/measure.js.coffee
> +    attrs.archived_measures = new Thorax.Collections.ArchivedMeasures null, {measure_id: attrs._id, _fetched: false}
Where is `_fetched` used? I only see it being set, I don't see it being gotten.

2016-09-20 15:02 UTC, thecristen commented on app/assets/javascripts/models/measure.js.coffee
> +    attrs.archived_measures = new Thorax.Collections.ArchivedMeasures null, {measure_id: attrs._id, _fetched: false}
I remember having the same comment on this! IIRC I remember @pete responding that it was a Thorax-specific thing

2016-09-20 16:48 UTC, pkmitre commented on app/assets/javascripts/models/measure.js.coffee
> +    attrs.archived_measures = new Thorax.Collections.ArchivedMeasures null, {measure_id: attrs._id, _fetched: false}
Probably worth a comment spelling out why it's being used here.

2016-09-20 22:25 UTC, mulcahyk commented on lib/tasks/setup_history_tracks.rake
> +       puts "Measure: #{measure.cms_id}\n\tPatient: #{patient.first} #{patient.last} (#{patient._id})\n\t\tPopulation Index: #{population_index}"
It gives us some way of knowing what is going on.  I have no issue removing it.

2016-09-21 16:40 UTC, hossenlopp commented on app/controllers/measures_controller.rb
> +    #render :json => results
This function was used by our initial prototype. I'll be removing it.

2016-09-26 12:05 UTC, edeyoung requested changes
I will have more comments but I want to make sure to release these comments so they can be worked on.

2016-09-26 12:05 UTC, edeyoung commented on app/assets/javascripts/models/upload_summary.js.coffee
> +  fetchAll: ->
can you walk me through how all the fetching stuff works?

2016-09-26 12:05 UTC, edeyoung commented on app/assets/javascripts/router.js.coffee
> +    'measures/:measure_hqmf_set_id/patients/:id/compare/at_upload/:upload_id':  'renderHistoricPatientCompare'
Consider moving this up to the other `measure` paths above

2016-09-26 12:05 UTC, edeyoung commented on app/assets/javascripts/router.js.coffee
> +    document.title += " - #{measure.get('cms_id')}" if measure?
I guess this is also a comment for `renderPatientBuilder`, but what's the expected action when you have a nil measure? In `renderPatientBuilder`, it looks like the the possibility of getting a nil reference is deferred until `new Thorax.Views.PatientBuilder(` is called (do we know if that handles a nil measure gracefully? out of scope for this, but good to know). Here, though, we do `if measure?` for `document.title` and grab attributes from measure without any checks for `upsums` and `archivedMeasures`.

If we don't want this page to load if there's a nil measure (same with `renderPatientBuilder`) consider putting a nil check at the beginning of the function and then making the function return the correct error page/error message if the measure is nil. If we do want the page to load anyways, put in safety checks for all the rest of the calls using `measure`. As written, it will just break.

(having not looked into this, I think this should show a nice error message if a measure isn't there and there should just be one nil check at the beginning)

2016-09-26 12:05 UTC, edeyoung commented on app/assets/javascripts/router.js.coffee
> +    $.when(upsums.fetchDeferred(), archivedMeasures.fetchDeferred())
it seems like the `fetchDeferred` logic should be hidden within the classes and I shouldn't have to see it here. Is there a way to rework this so if I want `upload_summaries`, I don't have to do all this, it's just done for me? Or at least I only have to do one `.then` call?

2016-09-26 12:05 UTC, edeyoung commented on app/assets/javascripts/router.js.coffee
> +    upsums = measure.get('upload_summaries')
rename to `upload_summaries`

2016-09-26 12:05 UTC, edeyoung commented on app/assets/javascripts/router.js.coffee
> +    upload_summary = null
make casing consistent - camel case or snake case within the file.

2016-09-26 12:05 UTC, edeyoung commented on app/assets/javascripts/router.js.coffee
> +    measure_summaries.fetchDeferred()
similar comment as above. Is there a way to hide this `fetchDeferred` logic?

2016-09-26 12:05 UTC, edeyoung commented on app/assets/javascripts/templates/breadcrumb.hbs
> +        {{#if fromHxTimeline}}
rename this to `fromHistoryTimeline`

2016-09-26 12:05 UTC, edeyoung commented on app/assets/javascripts/templates/logic/data_criteria.hbs
> +  {{#if suppressDataCriteriaHighlight}}
you can put this just around the thing you want to show/hide:

```
<span class="{{#if ../isSetOp}}{{#unless ../../dataCriteria.variable}}set-op-group{{/unless}}{{/if}} {{dataCriteria.key}} rationale-target {{#unless suppressDataCriteriaHighlight}}highlight-target{{/unless}}">
```

2016-09-26 12:05 UTC, edeyoung commented on app/assets/javascripts/templates/measure/percentage.hbs
> +  {{#ifCond percent '==' 0}}
what does this set of changes do?

2016-09-26 12:05 UTC, edeyoung commented on app/assets/javascripts/templates/measure_history.hbs
> +  <!-- TODO: Ensure that the stratification tabs toggle a render for the data -->
has this `TODO` been done or is it still active?

2016-09-26 12:05 UTC, edeyoung commented on app/assets/javascripts/templates/measure_history_diff.hbs
> +      <div class="col-md-6"><h3><strong>{{diff.left.cms_id}}</strong> @ {{diff.left.updateTime}}</h3><small>{{diff.left.hqmf_id}}</small></div>
instead of `diff.left` and `diff.right` consider renaming to something that represents the temporal aspect rather than the spatial. If we decide to show these in a different order, `left` and `right` won't make sense. You'd probably want something more concise, but maybe something along the lines of `diff.earlierUpload` and `diff.laterUpload`.

2016-09-26 12:05 UTC, edeyoung commented on app/assets/javascripts/templates/measure_history_diff.hbs
> +  {{#if diffView}}
should `diffView` be renamed to something like, `diffsLoaded`? This might make more sense with the `{{else}}` containing the `Loading comparison...` text.

2016-09-26 12:05 UTC, edeyoung commented on app/assets/javascripts/templates/measure_history_timeline.hbs
> +        {{/with}}
After each pair, can you make the line bold or something like that to more clearly differentiate each pair from the other pairs?

2016-09-26 12:05 UTC, edeyoung commented on app/assets/javascripts/templates/measure_upload_summary.hbs
> +{{! We are guaranteed to have at least one population, hence the [0] index}}
Awesome job commenting the assumptions 👍

2016-09-26 12:05 UTC, edeyoung commented on app/assets/javascripts/templates/measure_upload_summary.hbs
> +                <th width="1300px" class="centered"> <h2>Upload Summary</h2> </th>
Perhaps rename to "Patients Changed By Upload" (or something more graceful than that). "Upload Summary" makes me think I should be seeing everything.

2016-09-26 12:05 UTC, edeyoung commented on app/assets/javascripts/templates/measure_upload_summary.hbs
> +                <th width="1300px" class="centered"> <h2>{{populationTitle}}</h2> </th>
If there are multiple populations, then I think there should still be a title like, "Upload Summary" (or changed as described above) along with the population title.

2016-09-26 12:05 UTC, edeyoung commented on app/assets/javascripts/templates/measure_upload_summary.hbs
> +              <th width="150px" class="centered">&ensp;Current &emsp;&nbsp;Version</th>
@thecristen is there a cleaner way that the layout can be managed here?

2016-09-26 12:05 UTC, edeyoung commented on app/assets/javascripts/templates/measure_upload_summary.hbs
> +              <td rowspan="3">{{view "MeasurePercentageView" done=jQueryKnobBefore.done percent=jQueryKnobBefore.percent status=jQueryKnobBefore.status}}</td>
consider renaming the knobs to not include `jquery` in them

2016-09-26 12:05 UTC, edeyoung commented on app/assets/javascripts/templates/measure_upload_summary.hbs
> +                {{#ifCond after_status "==" "pass"}}
can a status just pass or fail? If so, should this be a boolean instead of a string?

2016-09-26 12:05 UTC, edeyoung commented on app/assets/javascripts/templates/patient_builder/patient_builder.hbs
> +
where is the body for this defined?

2016-09-26 12:05 UTC, edeyoung commented on app/assets/javascripts/templates/patient_builder/patient_version_compare.hbs
> +    {{#if populationInBefore}}
what does `populationInBefore` mean?

2016-09-26 12:05 UTC, edeyoung commented on app/assets/javascripts/templates/patient_builder/patient_version_compare.hbs
> +      <h3>The selected population of the measure is too large.</h3>
do we have "data doesn't exist" issues with after when we're doing the measure compare view and the patient was only created after the measure was uploaded, so there isn't data for right when the measure was uploaded? If so, add that case in here.

2016-09-26 12:05 UTC, edeyoung commented on app/assets/javascripts/templates/population_calculation.hbs
> +    <a href="#measures/{{measure_id}}/history"><i class="fa fa-history"></i> </i>MEASURE UPLOAD HISTORY</a>
mismatched `</i>`s

2016-09-26 12:12 UTC, edeyoung commented on app/assets/javascripts/views/breadcrumb.js.coffee
> +    patient_name = if patient.get('first') then "#{patient.get('last')} #{patient.get('first')}" else "Create new patient"
if you are editing a patient, should you gracefully error if there is no `first` for the patient? This seems like a different situation than adding a patient, which it looks like this code was taken from (`addPatient`).

2016-09-26 12:14 UTC, edeyoung commented on app/assets/javascripts/views/breadcrumb.js.coffee
> +      comparePatient: true
what does the `comparePatient` flag do? Does this go into the compare patient view? If so, should this function be called `editPatient` if it shows the compare view?
can you add a comment to the flag?

2016-09-26 12:14 UTC, edeyoung commented on app/assets/javascripts/views/breadcrumb.js.coffee
> +    patient_name = if patient.get('first') then "#{patient.get('last')} #{patient.get('first')}" else "Create new patient"
same comment as above. Should this error gracefully if the patient name does not exist?

2016-09-26 12:16 UTC, edeyoung commented on app/assets/javascripts/views/breadcrumb.js.coffee
> +    patient_id = patient.get('_id')
There's an assumption that the patient id exists, but not the name. If the name doesn't exist, this will likely error. See comment above that maybe we should assume the name does exist and error gracefully otherwise. Same for this. This is also applicable below.

2016-09-26 12:16 UTC, edeyoung commented on app/assets/javascripts/views/breadcrumb.js.coffee
> +      fromHxTimeline: true
spell out "history"

2016-09-26 12:17 UTC, edeyoung commented on app/assets/javascripts/views/logic/data_criteria_logic_view.js.coffee
> +    # TODO: Find a better way than logic in the template to disable highlighting when called from code other than patient builder.
has this `TODO` been resolved?

2016-09-26 12:18 UTC, edeyoung commented on app/assets/javascripts/views/logic/population_logic_view.js.coffee
> +    @setView new Thorax.Views.PopulationLogic(model: population, suppressDataCriteriaHighlight: @suppressDataCriteriaHighlight)
add a comment at the top of this class explaining that `suppressDataCriteriaHighlight` is a parameter that will get passed in to the initializer and what it does. As written, this is hidden and comes out of no where.

2016-09-26 12:21 UTC, edeyoung commented on app/assets/javascripts/views/measure_history_diff_view.js.coffee
> +    @diff = undefined
should these be set to `null` rather than `undefined`?

2016-09-26 12:22 UTC, edeyoung commented on app/assets/javascripts/views/measure_history_diff_view.js.coffee
> +    $.get('/measures/historic_diff?new_id='+newVersion+'&old_id='+oldVersion, (data) =>
add a comment explaining what is happening here. Are there potential performance issues with querying the server if several people are doing this at once?

2016-09-26 12:24 UTC, edeyoung commented on app/assets/javascripts/views/measure_history_diff_view.js.coffee
> +    if !oldVersion
is there any chance this wouldn't be passed in a `newVersion`? Should that be checked for as well?

2016-09-26 12:26 UTC, edeyoung commented on app/assets/javascripts/views/measure_history_timeline_view.js.coffee
> +      -> @$('#measure-diff-view-dialog').on 'hidden.bs.modal', @closeDiff
add a comment to this

2016-09-26 12:29 UTC, edeyoung commented on app/assets/javascripts/views/measure_history_timeline_view.js.coffee
> +    # if there is only one upload summary yet it has no 'measure_db_id_before', it is a new measure and has no history
`measure_db_id_before` doesn't seem descriptive enough for me as a variable name. What is this variable supposed to represent?

2016-09-26 12:31 UTC, edeyoung commented on app/assets/javascripts/views/measure_history_timeline_view.js.coffee
> +    else if @upload_summaries.size() == 1 && !@upload_summaries.at(0).has('measure_db_id_before')
what is the difference between having `@upload_summaries.size() < 1` and `@upload_summaries.size() == 1`? What does having an upload summary mean, particularly if it isn't indicative of having a history? Should there be two states that indicate that the measure is historyless? Is one of these a non-case after the script that needs to be run before this branch can be used is run?

2016-09-26 12:33 UTC, edeyoung commented on app/assets/javascripts/views/measure_history_timeline_view.js.coffee
> +          if _.findWhere(@patientIndex, {id: patientId}) == undefined
Since `undefined` is so funny, is there a different way we can do this comparison? Like maybe `if _.findWhere(@patientIndex, {id: patientId})?`?

2016-09-26 12:35 UTC, edeyoung commented on app/assets/javascripts/views/measure_history_timeline_view.js.coffee
> +      for population in upload_summary.get('population_summaries')
is there a different set of patients for each population?

2016-09-26 12:36 UTC, edeyoung commented on app/assets/javascripts/views/measure_history_timeline_view.js.coffee
> +    # pull out all patients that exist, even deleted ones, map id to names
Maybe reword to:
add all patients that exist (even deleted ones) to the patientIndex array. Store the patient id, patient name, and link to the patient.

2016-09-26 12:38 UTC, edeyoung commented on app/assets/javascripts/views/measure_history_timeline_view.js.coffee
> +  closeDiff: =>
why fat arrow instead of skinny arrow here?

2016-09-26 12:39 UTC, edeyoung commented on app/assets/javascripts/views/measure_history_timeline_view.js.coffee
> +    uploadID = $(e.target).data('uploadId')
what is `uploadID`? This name isn't descriptive enough for me. Is this the measure id for the latest uploaded measure? Or is this the id that tracks all the uploads for a particular measure?

2016-09-26 12:40 UTC, edeyoung commented on app/assets/javascripts/views/measure_history_timeline_view.js.coffee
> +    upload = @upload_summaries.findWhere({_id: uploadID})
what is an `upload` in this context? Is this the measure diff? What information is contained in this? This variable should also be more descriptive.

2016-09-26 12:41 UTC, edeyoung commented on app/assets/javascripts/views/measure_history_view.js.coffee
> +    @patientData = undefined
see comment above about initializing to `null` rather than `undefined`.

2016-09-26 12:45 UTC, edeyoung commented on app/assets/javascripts/views/measure_history_view.js.coffee
> +  initialize: ->
can you add a comment explaining the expected parameters?

2016-09-26 12:47 UTC, edeyoung commented on app/assets/javascripts/views/measure_history_view.js.coffee
> +  switchPopulation: (e) ->
above, there is `showDiffClicked` indicating an action. I don't really mind `Clicked` being included or not, but it is good to stay consistent. I don't think any of the rest of the code includes things like `Clicked`.

2016-09-26 12:48 UTC, edeyoung commented on app/assets/javascripts/views/measure_history_view.js.coffee
> +  populationContext: (population) ->
can you add a comment to this?

2016-09-26 17:25 UTC, hossenlopp commented on app/assets/javascripts/router.js.coffee
> +    $.when(upsums.fetchDeferred(), archivedMeasures.fetchDeferred())
Would it make sense to hide this logic in the Measure model, UploadSummaries collection and ArchivedMeasures collection? I could make it so that the entry functions for getting the data we need for these views are at the Measure model. These functions could just return a deferred that completes with all the data needed for creating the view.

2016-09-26 17:32 UTC, hossenlopp commented on app/assets/javascripts/templates/measure_history.hbs
> +  <!-- TODO: Ensure that the stratification tabs toggle a render for the data -->
This TODO has been completed. I didn't have to update this file to complete it, so I forgot to remove it.

2016-09-26 17:37 UTC, hossenlopp commented on app/assets/javascripts/templates/measure_history_timeline.hbs
> +        {{/with}}
That's a great idea! I'll give it a try and post an image.

2016-09-26 17:54 UTC, hossenlopp commented on app/assets/javascripts/templates/measure_upload_summary.hbs
> +                {{#ifCond after_status "==" "pass"}}
Good point. For some reason we have been storing status as 'pass' or 'fail' everywhere. I think it is incase we have another status that happens, perhaps 'error' or 'not-calculated'.

2016-09-26 17:58 UTC, hossenlopp commented on app/assets/javascripts/templates/population_calculation.hbs
> +    <a href="#measures/{{measure_id}}/history"><i class="fa fa-history"></i> </i>MEASURE UPLOAD HISTORY</a>
I thought I cleaned up this mismatched </i>. Maybe the commit got lost in the mess of staging deploys and rebases.

2016-09-26 19:16 UTC, edeyoung commented on app/assets/javascripts/views/measure_upload_summary_view.js.coffee
> +    'click .patient-link': 'patientSelected'
can you do something like (and I don't know if you can, but I vaguely remember seeing it somewhere):

```
`click .patient-link': =>@trigger "patient:selected"
```

This way you don't have to call the one-line method below (unless that's also called directly from somewhere else).

Also, would be good to comment the method below (or here if you move it) explaining what triggering the patientSelected will do because the action is not contained in this class, it's contained in the `measure_upload_summary_dialog`.

2016-09-26 19:17 UTC, edeyoung commented on app/assets/javascripts/views/measure_upload_summary_view.js.coffee
> +    populationInformation = [] # One element per population
What does this comment mean? one element of what per population?

2016-09-26 19:18 UTC, edeyoung commented on app/assets/javascripts/views/measure_upload_summary_view.js.coffee
> +      patientsWhoChanged = [] # One hash per patient who changed
hash of what?

2016-09-26 19:19 UTC, edeyoung commented on app/assets/javascripts/views/measure_upload_summary_view.js.coffee
> +    for eachPopulation, populationIndex in @model.get('population_summaries')
consider renaming `eachPopulation` to `population`.

Are these population sets? If so, should we make that clear in the name?

2016-09-26 19:20 UTC, edeyoung commented on app/assets/javascripts/views/measure_upload_summary_view.js.coffee
> +      percentPassedBefore = parseFloat(((populationSummary.pass_before/totalPatients) * 100).toFixed(1)) # toFixed converts to string
why are we converting to a string and then parsing the string?

2016-09-26 19:22 UTC, edeyoung commented on app/assets/javascripts/views/measure_upload_summary_view.js.coffee
> +    for eachPopulation, populationIndex in @model.get('population_summaries')
it looks like `population_summaries` is a new attribute on the model. It looks like this contains information about calculations across populations for different measure uploads. Consider renaming this variable to be more descriptive of what this actually is. This was not clear to me initially.

2016-09-26 19:25 UTC, edeyoung commented on app/assets/javascripts/views/measure_upload_summary_view.js.coffee
> +          @measure.get('patients').each((thisPatient, arrayIndex) ->
this should only catch for a single patient, yes? maybe do something like:
(I don't remember the exact syntax)

```
patient = @measure.get('patients').findWhere(_id: patientOID)
patientsWhoChanged.push(....)
```

2016-09-26 19:26 UTC, DPC15038 commented on app/assets/javascripts/views/measure_upload_summary_view.js.coffee
> +    populationInformation = [] # One element per population
I initially created these comments for myself when making the upload summary modal. For the summary modal, I create one element of this array for each of the populations. I then store a hash of information (the before status, the after status, name...etc within each element), and the hqmf_set_id, and info the jqueryKnob within each element. Should I remove the comments, or expand on them?

2016-09-26 19:27 UTC, edeyoung commented on app/assets/javascripts/views/measure_upload_summary_view.js.coffee
> +        if patientInformation.before_status != patientInformation.after_status
`before_status` and `after_status` seem too short-handy to me. If I looked at this object not in the context of the measure history, I wouldn't know what these meant. Consider making these names more descriptive. This is too verbose probably, but maybe something along the lines of `passFailStatusAfterMeasureUpload`.

2016-09-26 19:27 UTC, DPC15038 commented on app/assets/javascripts/views/measure_upload_summary_view.js.coffee
> +      patientsWhoChanged = [] # One hash per patient who changed
See above

2016-09-26 19:45 UTC, DPC15038 commented on app/assets/javascripts/views/measure_upload_summary_view.js.coffee
> +    for eachPopulation, populationIndex in @model.get('population_summaries')
I forget exactly how this works, but IIRC `@model.get('population_summaries')` returns an array where each element is a different population set. With that in mind, do you think `population` or `populationSet` would be more obvious?

2016-09-26 19:50 UTC, DPC15038 commented on app/assets/javascripts/views/measure_upload_summary_view.js.coffee
> +      percentPassedBefore = parseFloat(((populationSummary.pass_before/totalPatients) * 100).toFixed(1)) # toFixed converts to string
The initial division might have a repeating value, so I use `.toFixed(1)` to trim it to a single decimal. Then parse that string as a float, because jQuery Knob requires the value be float. Is there a better way to trim down to a single decimal?

2016-09-26 19:57 UTC, edeyoung commented on app/assets/javascripts/views/measure_upload_summary_view.js.coffee
> +      percentPassedBefore = parseFloat(((populationSummary.pass_before/totalPatients) * 100).toFixed(1)) # toFixed converts to string
Makes sense! Did a quick internet perusal and this seems to be a common approach. I'd say keep it and comment.

2016-09-26 20:00 UTC, edeyoung commented on app/assets/javascripts/views/measure_upload_summary_view.js.coffee
> +        jQueryKnobAfter: {done: true, percent: percentPassedAfter, status: if percentPassedAfter == 100 then 'pass' else 'fail'}
i think i commented this earlier, but consider renaming this to not include `jQuery`. Maybe also something more descriptive like `percentagePassedDial` or something like that.

2016-09-26 20:05 UTC, edeyoung commented on app/assets/javascripts/views/measure_upload_summary_view.js.coffee
> +    _(super).extend(populationInformation: populationInformation, numberOfPopulations: @measure.get('populations').size(), hqmfSetId: @measure.get('hqmf_set_id'))
What object are we extending here?

2016-09-26 20:07 UTC, DPC15038 commented on app/assets/javascripts/views/measure_upload_summary_view.js.coffee
> +    _(super).extend(populationInformation: populationInformation, numberOfPopulations: @measure.get('populations').size(), hqmfSetId: @measure.get('hqmf_set_id'))
`_(super)` refers to the view's context. @pkmitre could go into a lot more detail than I could on this.

2016-09-26 20:09 UTC, edeyoung commented on app/assets/javascripts/views/measures_view.js.coffee
> +        $(@i).val @cv + '%'
add a comment to this. what are `@i` and `@cv`?

2016-09-26 20:14 UTC, DPC15038 commented on app/assets/javascripts/views/measures_view.js.coffee
> +        $(@i).val @cv + '%'
They add a percent sign to whenever the Knob is drawn. `55.5` becomes `55.5%` 
Will add comment

2016-09-26 20:19 UTC, pkmitre commented on app/assets/javascripts/views/measure_upload_summary_view.js.coffee
> +    _(super).extend(populationInformation: populationInformation, numberOfPopulations: @measure.get('populations').size(), hqmfSetId: @measure.get('hqmf_set_id'))
`super` is a coffeescript keyword that basically means "whatever the results are when calling this method on the parent class". The method in this case is `context`, which is from Thorax and defines what variables should be available in the template when rendering; Thorax by default returns the contents of the views default model, etc, we add a bunch of stuff to that base via `extend`.

2016-09-26 20:24 UTC, edeyoung commented on app/assets/javascripts/views/patient_builder/patient_builder.js.coffee
> +    for mkey, mvalue of populations.models
`populations` is a thorax/backbone collection. These come with underscore functions associated with them, including a `forEach` method (http://backbonejs.org/#Collection-Underscore-Methods). This handles the backbone abstraction of putting the content of the collection into `models`. So you can make this:
(double check syntax)

```
populations.forEach (value, index) ->
  ...
```

see http://underscorejs.org/#each

2016-09-26 20:27 UTC, edeyoung commented on app/assets/javascripts/views/patient_builder/patient_builder.js.coffee
> +    for mkey, mvalue of populations.models
You are accessing an array here like it's a dictionary. The "key" here is actually an index. For future arrays (because I highly recommend using the built-in `forEach` method described above), you can get the object and the index using:

```
for value, index in array
  ...
```

2016-09-26 20:27 UTC, edeyoung commented on app/assets/javascripts/views/patient_builder/patient_builder.js.coffee
> +    for mkey, mvalue of populations.models
rename this variables to be more specific. `mkey` -> `populationIndex` and `mvalue` -> `population`.

2016-09-26 20:28 UTC, edeyoung commented on app/assets/javascripts/views/patient_builder/patient_builder.js.coffee
> +      this_pop = ['rationale', 'finalSpecifics'];
what does `this_pop` mean?

2016-09-26 20:28 UTC, edeyoung commented on app/assets/javascripts/views/patient_builder/patient_builder.js.coffee
> +      for dankey in population_names
what does `dankey` mean?

2016-09-26 20:29 UTC, edeyoung commented on app/assets/javascripts/views/patient_builder/patient_builder.js.coffee
> +    population_index = 0
the rest of this file seems to use camel case rather than snake case. I think the recommended style is to be snake case for coffeescript, but it's good to be existing within a file. Consider reworking these variables to be camel case to match the pre-existing code.

2016-09-26 20:32 UTC, edeyoung commented on app/assets/javascripts/views/patient_builder/patient_builder.js.coffee
> +        for mv of mvalue.attributes
`mvalue` (a `population`) is a thorax/backbone object. you can access attributes through the `get` method. This for loop should be rewritten as:

```
this_pop.push(mvalue.get(dankey))
```

2016-09-26 20:32 UTC, edeyoung commented on app/assets/javascripts/views/patient_builder/patient_builder.js.coffee
> +    final_pops = [];
rename `final_pops` to something more descriptive.

2016-09-26 20:34 UTC, edeyoung commented on app/assets/javascripts/views/patient_builder/patient_builder.js.coffee
> +      final_pops[mkey] = this_pop
if you change the loop above to iterate over an array as an array rather than an object (or using the `forEach` method), you will be iterating over it in order. You can then push the objects onto `final_pops` rather than using the index and they'll be in the same order as the original array:

```
final_pops.push(this_pop)
```

2016-09-26 20:39 UTC, edeyoung commented on app/assets/javascripts/views/patient_builder/patient_builder.js.coffee
> +  calculateAllResults: (callback) =>
I don't think I understand what this function is doing.

if I have a set of populations (`['IPP', 'DENOM', 'NUMER']`), does this just return an array that looks like:
`[['rationale', 'finalSpecifics', 'IPP'], ['rationale', 'finalSpecifics', 'DENOM'], ['rationale', 'finalSpecifics', 'NUMER]]`? If so, what is this used for? This also doesn't seem like it calculates anything.

Please add a comment to the function explaining what it does and consider renaming it.

2016-09-26 20:39 UTC, edeyoung commented on app/assets/javascripts/views/patient_builder/patient_builder.js.coffee
> +  calculateAllResults: (callback) =>
is the callback ever used? If not, remove.

2016-09-27 12:56 UTC, edeyoung commented on lib/ext/measure_upload_summary.rb
> +  SLICER.push('rationale', 'finalSpecifics')
This looks like these were added to handle the rake task. Look into a different way to manage the rake task. This appends `'rationale'` and `'finalSpecifics'` onto the list of population codes, but these are **not** population codes. This will likely lead to bugs in other areas of the code that iterate over this list. This must be changed.

2016-09-27 12:59 UTC, edeyoung commented on app/assets/javascripts/views/patient_builder/patient_builder.js.coffee
> +    calcNextResult()
This function as a whole has a lot of round-about ways of accessing the data. Consider something like below (tested). I'm not sure I like how the callback is called in the code below, so consider finding something more graceful.

```
  calculateAllResults: (callback) =>
    results = []
    @measure.get('populations').forEach (population) =>
      calculationResult = population.calculate(@model)
      calculationResult.calculation.done () =>
        filteredResult = {}
        for populationName in Thorax.Models.Measure.allPopulationCodes
          filteredResult[populationName]=calculationResult.get(populationName) if calculationResult.get(populationName)?
        filteredResult['rationale'] = calculationResult.get('rationale') if calculationResult.get('rationale')?
        filteredResult['finalSpecifics'] = calculationResult.get('finalSpecifics') if calculationResult.get('finalSpecifics')?
        
        filteredResult['measure_id'] = @measure.get('hqmf_set_id')
        filteredResult['population_index'] = population.get('index')
        
        results.push(filteredResult)
        
        if results.length == @measure.get('populations').length
          callback(results)
```

2016-09-27 14:13 UTC, hossenlopp commented on app/assets/javascripts/templates/patient_builder/patient_builder.hbs
> +<div class="modal fade diff-view-dialog" id="patient-compare-dialog" tabindex="-1" aria-hidden="true">
it looks like the 'diff-view-dialog' class survived the copy/paste.

2016-09-27 14:19 UTC, hossenlopp commented on app/assets/javascripts/templates/patient_builder/patient_builder.hbs
> +
The body is defined by the patient_builder/patient_version_compare.js.coffee view. It is filled on demand by a function 'showCompare' in the patient_builder/patient_builder.js.coffee view. It creates an instance of the PatientBuilderCompare view and appends it to the modal body before making the dialog popup.

2016-09-27 14:33 UTC, hossenlopp commented on app/assets/javascripts/views/measure_history_diff_view.js.coffee
> +    if !oldVersion
Good point. If either is if null then we should handle it.

2016-09-27 14:40 UTC, hossenlopp commented on app/assets/javascripts/views/measure_history_diff_view.js.coffee
> +    $.get('/measures/historic_diff?new_id='+newVersion+'&old_id='+oldVersion, (data) =>
I will add a comment about how the diff is generated on the server by the diffy gem.

2016-10-03 18:17 UTC, mulcahyk commented on app/assets/javascripts/templates/patient_builder/patient_version_compare.hbs
> +    {{#if populationInBefore}}
`populationInBefore` refers to if the population was there before the measure upload.  Will update the variable name.

2016-10-03 18:23 UTC, mulcahyk commented on app/assets/javascripts/templates/patient_builder/patient_version_compare.hbs
> +      <h3>The selected population of the measure is too large.</h3>
We handle this condition in the patient builder.  There we do a check to see if the patient has any history (i.e. is there a record in upload_summaries for that patient).  If there is no record then we don't show the compare button.

2016-10-03 19:04 UTC, edeyoung commented on app/assets/javascripts/templates/patient_builder/patient_version_compare.hbs
> +      <h3>The selected population of the measure is too large.</h3>
It seems like that should address the same issue with `populationInBefore`. Is the case checking for this above not necessary?

2016-10-05 20:30 UTC, mulcahyk commented on app/controllers/measures_controller.rb
> +    # TODO - take the patient after snapshot
This can be removed.

2016-10-05 20:30 UTC, mulcahyk commented on app/controllers/measures_controller.rb
> +      ########################################
Clarify the comment here.

2016-10-05 21:06 UTC, mulcahyk commented on app/assets/javascripts/views/measure_history_timeline_view.js.coffee
> +    # if there is only one upload summary yet it has no 'measure_db_id_before', it is a new measure and has no history
This is the _id of the measure in the database before it was updated.  The measure update process creates a new _id.

2016-10-07 12:15 UTC, hossenlopp commented on app/assets/javascripts/helpers.js.coffee
> +
I will merge this helper when rebasing with master now that patient dashboard is merged. @edeyoung's implementation has worked just fine in staging.

2016-10-07 12:17 UTC, hossenlopp commented on app/assets/javascripts/models/measure.js.coffee
> +    attrs.archived_measures = new Thorax.Collections.ArchivedMeasures null, {measure_id: attrs._id, _fetched: false}
Fetched is a backbone thing. Not well documented. But it is used for these lazy loaded collections and models. ArchivedMeasures are not bootstrapped, so I specifically set _fetched to false.

2016-10-07 13:26 UTC, hossenlopp commented on app/assets/javascripts/models/upload_summary.js.coffee
> +    @fetch(
This is defined in backbone. It runs a XHR call to populate the collection or model.

2016-10-10 13:14 UTC, hossenlopp reviewed
Added a bunch of comments on the Measures Controller.

2016-10-10 13:14 UTC, hossenlopp commented on app/controllers/measures_controller.rb
> +    upl_id = UploadSummary.collect_before_upload_state(measure, arch_measure)
`upl_id` should be more verbose in it's name. `upload_summary_id`

2016-10-10 13:14 UTC, hossenlopp commented on app/controllers/measures_controller.rb
> +        here = {"measure_id" => measure.hqmf_set_id, "population_index" => idx}
`here` is a bad name for what this is. It looks like a temp hash that stores the expected values for a specific population as you rebuild them.

2016-10-10 13:14 UTC, hossenlopp commented on app/controllers/measures_controller.rb
> +  def check_patient_expected_values(measure)
Needs a comment. Possibly RDoc explaining what it does.

Also should be in the `private` section of the class since it's an internal helper method.

2016-10-10 13:14 UTC, hossenlopp commented on app/controllers/measures_controller.rb
> +        next if measure.populations.count == patient['expected_values'].to_s.scan(/#{measure.hqmf_set_id}/).count
Converting an array of hashes to a string to do a count of how many items contain a key does not seem like a great idea. This is slower than looking at the data with the structure we know it has. Also, the to_s implementation may be different or change over time between ruby versions.

The select method of the ruby array should be used to find the populations for this measure. You give it a block that takes an array element and returns boolean if it should include it or not.
`patient.expected_values.select { |value| value[:measure_id] == measure.hqmf_set_id }.count`

2016-10-10 13:14 UTC, hossenlopp commented on app/controllers/measures_controller.rb
> +        exptd_vals.reject! { |ev| ev['population_index'] >= measure.populations.count } if measure.populations.count < patient['expected_values'].count
Why not use the regular `reject` method which returns a new array and remove the `dup` call on 298?

The block on this reject call ignores the measure_id. This would remove the expected values for other measures that have more populations than this one.

2016-10-10 13:14 UTC, hossenlopp commented on app/controllers/measures_controller.rb
> +        corrected_expected.each_index { |i| exptd_vals << corrected_expected[i] if i >= patient['expected_values'].count } if measure.populations.count > patient['expected_values'].count
This also ignores populations for other measures.

2016-10-10 15:51 UTC, thecristen commented on app/assets/javascripts/helpers.js.coffee
> +Handlebars.registerHelper 'dateFormat', (date, fmt) ->
We should figure out if we need both this `dateFormat` helper and the `moment` helper (they are identical except the moment one casts the time to UTC). If we do need both, I'd name them more similarly (maybe dateFormat and dateFormatUTC, or something like that).

2016-10-10 15:51 UTC, thecristen commented on app/assets/javascripts/models/patient.js.coffee
> +    @on 'change materialize', => @unset 'calc_results', silent: true
It seems a little unintuitive to me that we'll always want to unset `calc_results` on initialization, maybe add a comment on why that's needed?

2016-10-10 15:51 UTC, thecristen commented on app/assets/javascripts/models/upload_summary.js.coffee
> +  initialize: (models, options) ->
@edeyoung 

Most (all?) of the Thorax classes are based off the Backbone ones.
FWIW, the [Backbone documentation](http://backbonejs.org/#Collection-constructor) recommends passing in `null` to initialize a collection without models. 

Also, I'm not convinced 
```coffeescript
new Thorax.Collections.UploadSummaries(null, <whatever measure_id is>)
``` 
would be an improvement over
```coffeescript
new Thorax.Collections.UploadSummaries(null, {measure_id: <whatever measure_id is>})
```

2016-10-10 15:51 UTC, thecristen commented on app/assets/javascripts/router.js.coffee
> +    upload_summary = null
Should probably use consistent formatting for naming `upload_summary`, `beforeMeasure` and `afterMeasure`

2016-10-10 15:51 UTC, thecristen commented on app/assets/javascripts/router.js.coffee
> +        measure_summaries.findWhere({_id: summaryId}).fetchDeferred()
There are multiple instances of `thing.findWhere({_id: id})`

Instead of using `_id`, use `get()` to get a model from a collection  by id (e.g. `measure_summaries.get(summaryId)`)

2016-10-10 15:51 UTC, thecristen commented on app/assets/javascripts/templates/measure_history_diff.hbs
> +      <div class="col-md-6"><h3><strong>{{diff.left.cms_id}}</strong> @ {{diff.left.updateTime}}</h3><small>{{diff.left.hqmf_id}}</small></div>
Completely agree with this!!

2016-10-10 15:51 UTC, thecristen commented on app/assets/javascripts/templates/measure_upload_summary.hbs
> +              <th width="150px" class="centered">&ensp;Current &emsp;&nbsp;Version</th>
I'd avoid setting pixel widths on the columns like this. If it's a matter of ensuring the text inside does not wrap (I'm guessing that's why there's a width here), I'd use CSS

```css
.someselector {
  white-space: nowrap;
}
```

2016-10-10 15:51 UTC, thecristen commented on app/assets/javascripts/templates/patient_builder/patient_version_compare.hbs
> +        <h3>The selected data are too large.</h3>
Too large for what? Be specific.

2016-10-10 15:51 UTC, thecristen commented on app/assets/javascripts/templates/patient_builder/patient_version_compare.hbs
> +      <h3>The selected population of the measure is too large.</h3>
Too large for what? Again, be specific.

2016-10-10 15:51 UTC, thecristen commented on app/assets/javascripts/templates/population_calculation.hbs
> +    <div style="text-align:center;">
Use Bootstrap's `text-center` class instead of using the inline style attribute.

2016-10-10 15:51 UTC, thecristen commented on app/assets/javascripts/templates/population_calculation.hbs
> +      <a href="#measures/{{measure_id}}/history"><i class="fa fa-history"></i> </i>MEASURE UPLOAD HISTORY</a>
Add `aria-hidden="true"` attribute to this `fa-history` icon.

2016-10-10 15:51 UTC, thecristen commented on app/assets/javascripts/views/measure_history_diff_view.js.coffee
> +      @render()
why not just call `@clearDiff()` here, since it's the same code?

2016-10-10 15:51 UTC, thecristen commented on app/assets/javascripts/views/measure_history_timeline_view.js.coffee
> +          if _.findWhere(@patientIndex, {id: patientId}) == undefined
or maybe `if not _.findWhere(@patientIndex, {id: patientId})`?

2016-10-10 15:51 UTC, thecristen commented on app/assets/javascripts/views/measure_upload_summary_view.js.coffee
> +        }
I think the lines before this could be done in `initialize` rather than `context`

2016-10-10 15:51 UTC, thecristen commented on app/assets/javascripts/views/patient_builder/patient_builder.js.coffee
> +          if @.parent._view.patients.get(model)
Is there a better way to access these patients rather than `@.parent._view`?

2016-10-10 17:17 UTC, edeyoung commented on app/assets/javascripts/views/patient_builder/patient_builder.js.coffee
> +    calcNextResult = () =>
It appears that some of my comments for this code have disappeared. See screen shot below for those comments. This code needs to be rewritten.
![image](https://cloud.githubusercontent.com/assets/11574199/19244763/e2d9608a-8eeb-11e6-8a04-924c44f66626.png)

2016-10-10 17:31 UTC, edeyoung commented on app/assets/javascripts/views/patient_builder/patient_builder.js.coffee
> +    @calculateAllResults((calc_results) =>
@mayerm94 do you have specifics on why this failed? Does it still fail?

2016-10-10 17:32 UTC, edeyoung commented on app/assets/javascripts/views/patient_builder/patient_builder.js.coffee
> +          if @.parent._view.patients.get(model)
if you have access to the measure, the patients should be accessible from there

2016-10-10 18:45 UTC, mulcahyk commented on app/assets/javascripts/models/result.js.coffee
> +# Treat/handle cached calculation results like "live" calculation results
A **cached result** in this instance refers to the a previously calculated resulted that has been stored in the database.  This cached result will be read into Bonnie.  A **result** is what Bonnie has calculated during the session.  Whenever a patient is recalculated the result is pushed down to the database for caching.

2016-10-10 18:56 UTC, hossenlopp reviewed
Commenting on an issue found with the isPortfolio disabling history commit.

2016-10-10 18:56 UTC, hossenlopp commented on lib/ext/record.rb
> +  def calc_status
Could this function be centralized somewhere else? When the user is a portfolio user, this code breaks.

2016-10-10 18:56 UTC, hossenlopp commented on lib/ext/record.rb
> +      calc_results[pop_idx][:status] = (expected_values[pop_idx].to_a - calc_results[pop_idx].to_a).empty? ? 'pass' : 'fail'
If the user is a portfolio user and creates or saves a patient, this line breaks because calc_results does not exist.

2016-10-10 20:31 UTC, edeyoung requested changes
See comments.

2016-10-10 20:31 UTC, edeyoung commented on app/assets/javascripts/views/patient_builder/patient_builder.js.coffee
> +        success: (model) =>
suggest renaming `model` to something else. is this a patient? `model` is likely an artifact of how data is stored in the Thorax view.

2016-10-10 20:31 UTC, edeyoung commented on app/assets/javascripts/views/patient_builder/patient_builder.js.coffee
> +          @measure?.get('patients').add model # and the measure's patient collection
~~might this create duplicates within each of these collections? Wouldn't the patient (aka model) likely exist in these collections already?~~

It looks like this code is pre-existing, however, I am still confused about above and creating duplicates. Can this get looked into?

2016-10-10 20:31 UTC, edeyoung commented on app/assets/javascripts/views/patient_builder/patient_builder.js.coffee
> +          if bonnie.isPortfolio
~~should this be removed given that we're trying not to execute this all for portfolio view?~~

I'm not actually sure about the comment above. It looks like this was pre-existing. I think this should be reviewed and thought about carefully in the context of all the measure history stuff.

2016-10-10 20:31 UTC, edeyoung commented on app/assets/javascripts/views/patient_builder/patient_builder.js.coffee
> +      @patientCompareView.remove()
This looks like clean up code. It seems like this belongs somewhere else. Can you do the cleanup when the compare view is closed or navigated away from?

2016-10-10 20:31 UTC, edeyoung commented on app/assets/javascripts/views/patient_builder/patient_builder.js.coffee
> +      .then((latestUpsum) =>
rename `latestUpsum`

2016-10-10 20:31 UTC, edeyoung commented on app/assets/javascripts/views/patient_builder/patient_builder.js.coffee
> +    $.when(uploadSummaries.fetchDeferred())
Add a comment explaining the flow of what's happening here.

2016-10-10 20:31 UTC, edeyoung commented on app/assets/javascripts/views/patient_builder/patient_builder.js.coffee
> +        @patientCompareView = new Thorax.Views.PatientBuilderCompare(model: @model, measure: @measure, patients: @patients, measures: @measures, latestupsum: uploadSummaries.at(0), viaRoute: "fromEdi
rename `latestupsum` parameter

2016-10-10 20:31 UTC, edeyoung commented on app/assets/javascripts/views/patient_builder/patient_builder.js.coffee
> +        @patientCompareView = new Thorax.Views.PatientBuilderCompare(model: @model, measure: @measure, patients: @patients, measures: @measures, latestupsum: uploadSummaries.at(0), viaRoute: "fromEdi
rename `viaRoute`. What is `viaRoute`?

2016-10-10 20:31 UTC, edeyoung commented on app/assets/javascripts/views/patient_builder/patient_version_compare.js.coffee
> +    @thePatient = @latestupsum.get('population_summaries')[@measure.get('displayedPopulation').get('index')].patients[@model.id]
why `thePatient` instead of `patient`?

Rename `latestupsum` parameter

2016-10-10 20:31 UTC, edeyoung commented on app/assets/javascripts/views/patient_builder/patient_version_compare.js.coffee
> +      if !@thePatient.after_too_big
rename `after_too_big` and `before_too_big`

2016-10-10 20:31 UTC, edeyoung commented on app/assets/javascripts/views/patient_builder/patient_version_compare.js.coffee
> +        if @thePatient.after?
rename `after`

2016-10-10 20:31 UTC, edeyoung commented on app/assets/javascripts/views/patient_builder/patient_version_compare.js.coffee
> +            , {
comma placement is odd here

2016-10-10 20:31 UTC, edeyoung commented on app/assets/javascripts/views/patient_builder/patient_version_compare.js.coffee
> +    @selectedPopulation = @measure.get('displayedPopulation').get('index')
rename to `selectedPopulationIndex`. Also, does it make sense to actually have this be `@selectedPopulation = @measure.get('displayedPopulation')` because the actual population itself is referenced later? And then call `get('index')` on this?

2016-10-10 20:31 UTC, edeyoung commented on app/assets/javascripts/views/patient_builder/patient_version_compare.js.coffee
> +    @thePatient = @latestupsum.get('population_summaries')[@measure.get('displayedPopulation').get('index')].patients[@model.id]
use `@selectedPopulation` here instead of `@measure.get('displayedPopulation').get('index')`

2016-10-10 20:31 UTC, edeyoung commented on app/assets/javascripts/views/patient_builder/patient_version_compare.js.coffee
> +          @populationLogicViewBefore = new Thorax.Views.ComparePopulationLogic(isCompareView: true)
wouldn't it always make sense for the `ComparePopulationLogic` view to have `isCompareView` equal to `true`? When should this be false? If it makes sense for it ever to be false, should the variable be renamed to make its purpose more clear?

2016-10-10 20:31 UTC, edeyoung commented on app/assets/javascripts/views/patient_builder/patient_version_compare.js.coffee
> +          @populationPresentBeforeUpload = false
I'm having a hard time seeing the connection between `thePatient.after?` and `@populationPresentBeforeUpload`. It's possible that renaming `after` will help. It looks like the patient is really patient data from a particular population. Is it a new thing to map patient data to a particular population? If so, I think some additional explanatory text might be needed here. I initially was looking at this like a patient was associated with a measure, not that patient information was associated directly with a population. If this is new, I think I would have expected for population information to be included in the patient rather than the other way around. I think I just need more information on the flow here.

2016-10-10 20:31 UTC, edeyoung commented on app/assets/javascripts/views/patient_builder/patient_version_compare.js.coffee
> +        @beforeTooBig = true
should this be `beforeTooBig` or `afterTooBig`? This same logic is used below when doing a test on `thePatient.before_too_big`. It seems like what's in the `else` in these situations should be different. If not, maybe this should be renamed to `tooBig`.

2016-10-10 20:31 UTC, edeyoung commented on app/assets/javascripts/views/patient_builder/patient_version_compare.js.coffee
> +    if @viaRoute == "fromEdit"
I'm wondering if strings are the right way to check this. I'm guessing a boolean doesn't make sense because it could come from more than two places. Other options here?

2016-10-10 20:31 UTC, edeyoung commented on app/assets/javascripts/views/patient_builder/patient_version_compare.js.coffee
> +        if @beforemeasure.get('populations').at(@selectedPopulation)
watch your casing

2016-10-10 20:31 UTC, edeyoung commented on app/assets/javascripts/views/patient_builder/patient_version_compare.js.coffee
> +          @populationPresentBeforeUpload = true
why is the logic to determine if the population is present before upload so different here than above? Above, it's `@thePatient.after?`. Here, it's `if @beforemeasure.get('populations').at(@selectedPopulation)`. I'd expect parallelism between the two.

2016-10-10 20:31 UTC, edeyoung commented on app/assets/javascripts/views/patient_builder/patient_version_compare.js.coffee
> +            , {
weird comma again. maybe:
```
}, {
```

2016-10-10 20:31 UTC, edeyoung commented on app/assets/javascripts/views/patient_builder/patient_version_compare.js.coffee
> +          @populationLogicViewBefore.showRationale @cachedBeforeResult
the three lines above are repeated logic across the two `viaRoute` options. See if there's a way to extract this stuff out. I think this could also be done with some of the logic above.

2016-10-10 20:31 UTC, edeyoung commented on app/assets/javascripts/views/patient_builder/patient_version_compare.js.coffee
> +    if @viaRoute == "fromEdit"
This section needs lots of comments. It took commenting on the whole section to understand what was going on here and why `after` was being used for things that were setting `before` variables. I think this also indicates that some variable renaming is needed.

My understanding is that from the edit view, you are looking at the patient results right after upload and how they currently are, so the "after" in this case is in the "before" position. This is very confusing if you don't have this background (and confusing even if you do - this is something I knew about and was confusing to me). If you're looking at this from the timeline, you want the patient results right before the measure was upload and right after. There needs to be a comment explaining all of this.

I think this also addresses my thought about using a string for `viaRoute`. To me, it seems like it's not actually the route that matters, but what is shown. Whatever calls this can determine what is shown. What is shown actually is a binary (before/after or after/current). If you add a new view, it will want to show one of these two things. Possibly there might be other views that make sense. If you want to future proof for that, maybe you would have a way of specifying other than a boolean which view type to use, but I don't think that what called the function should be used to make this determination. It should be a view type parameter that gets passed in.

2016-10-10 20:31 UTC, edeyoung commented on app/assets/javascripts/views/patient_builder/patient_version_compare.js.coffee
> +    if @aftermeasure is undefined || @measure.id == @aftermeasure.id
this `if/else` statement is very confusing to me.

it is not clear how `@aftermeasure`'s existence and its values is related to `@thePatient.after`. The logical flow of why the `if` then goes into the `else` is not clear. At a minimum, these needs a comment to explain things. I think this should generally be reworked so a comment is not necessary.

2016-10-10 20:31 UTC, edeyoung commented on app/assets/javascripts/views/patient_builder/patient_version_compare.js.coffee
> +      @populationLogicViewAfter.showRationale @model
what is the type of `@model` here? is this a patient or is this a `CachedResult` object? If the latter, why isn't this always set to something so it can always be used as the argument for `@populationLogicView.After.showRationale`?

2016-10-10 20:31 UTC, edeyoung commented on app/assets/javascripts/views/patient_builder/patient_version_compare.js.coffee
> +      @populationLogicViewAfter = new Thorax.Views.ComparePopulationLogic
why isn't `isCompareView` passed in here?

2016-10-10 20:31 UTC, edeyoung commented on app/assets/javascripts/views/patient_builder/patient_version_compare.js.coffee
> +# Modified Thorax.Views.BuilderPopulationLogic that accepts new Thorax.Models.cachedResult
what does this comment mean and how is it related to the code below?

2016-10-10 20:31 UTC, edeyoung commented on app/assets/javascripts/views/patient_builder/patient_version_compare.js.coffee
> +  # This view will take a arguement of isCompareView (boolean) that when true will disable the scrolling arrows.
this should always be in compare view. This can just set that boolean in `initialize` and not require it to be passed in.

2016-10-10 20:31 UTC, edeyoung commented on app/assets/javascripts/views/patient_builder/patient_version_compare.js.coffee
> +class Thorax.Views.ComparePopulationLogic extends Thorax.LayoutView
based on the comment above, I'd expect this to subclass `Thorax.Views.BuilderPopulationLogic`. Is there a reason it isn't? It looks like most of the code below is duplicated.

2016-10-10 20:39 UTC, edeyoung commented on app/assets/javascripts/models/upload_summary.js.coffee
> +  initialize: (models, options) ->
yeah, I see that some models we have use `options` as an argument. Others do things like this, though: `initialize: (@patient, @patientDashboard, @measure, @patientResult, @populations, @populationSet)`. I personally like having the variables spelled out - it makes it clearer to me how to actually use the function. However, this seems like an acceptable use of the Thorax objects. It sounds like this is a personal preference thing and what's written here is perfectly fine. Thanks!

2016-10-10 20:56 UTC, thecristen commented on app/assets/javascripts/models/upload_summary.js.coffee
> +  initialize: (models, options) ->
Ah yes! It turns out that practice applies to Views rather than Models or Collections. From the [Thorax docs](http://thoraxjs.org/api.html#thorax.view) (emphasis mine):

> `Thorax.View` provides additive functionality over `Backbone.View` but **breaks compatibility in one important way in that it does not use an options object**. All properties passed to the constructor become available on the instance

Boo inconsistency 😂

2016-10-12 20:09 UTC, edeyoung requested changes
see comments. significant number of variable renaming necessary.

2016-10-12 20:09 UTC, edeyoung commented on app/controllers/archived_measures_controller.rb
> +class ArchivedMeasuresController < ApplicationController
can you add class comments and function comments to this?

2016-10-12 20:09 UTC, edeyoung commented on app/controllers/measures_controller.rb
> +    @old_measure = ArchivedMeasure.where({:measure_db_id => params[:old_id]}).first.to_measure unless @old_measure
add comments to explain the two cases (using `Measure` or `ArchivedMeasure`).

2016-10-12 20:09 UTC, edeyoung commented on app/controllers/measures_controller.rb
> +    results['right'] = { 'cms_id' => @new_measure.cms_id, 'updateTime' => (@new_measure.updated_at.tv_sec * 1000), 'hqmf_id' => @new_measure.hqmf_id }
should the keys be spacial or temporal? what about `'older'` `'newer'`?

2016-10-12 20:09 UTC, edeyoung commented on app/controllers/measures_controller.rb
> +        new_logic = @new_measure.measure_logic.select { |logic| logic['code'] == ((logic_code == 'VARIABLES') ? 'VARIABLES' : new_population[logic_code]) }.first
i think what's happening here is you're getting the `IPP_1` from the key `IPP`. I think that's a good thing to comment because unless you're deep in this stuff, it's hard to track that's what's happening here.

2016-10-12 20:09 UTC, edeyoung commented on app/controllers/measures_controller.rb
> +        old_logic_text = old_logic ? old_logic['lines'].slice(1, old_logic['lines'].length-1).join() : ""
style thing: I like to have a space between different concepts. I'd put a newline between `next if...` and `old_logic_text`.

Also, can you add a comment on why you need to do the slice? It's not self-apparent to me.

2016-10-12 20:09 UTC, edeyoung commented on app/controllers/measures_controller.rb
> +        population_diff << {}
am i right that this is a population set rather than a population? If so, can you rename things in this function to differentiate between the two?
Are you using `logic_code` for population (IPP, etc.)? If so, maybe rename this as well to be consistent with other parts of the code?

2016-10-12 20:09 UTC, edeyoung commented on app/controllers/measures_controller.rb
> +        population_diff << {}
why not create your object first and then push it on to `population_diff`? I'd find that easier to read than the last element access you have below.

2016-10-12 20:09 UTC, edeyoung commented on app/controllers/measures_controller.rb
> +      measure.populations.each_with_index do |pop, idx|
spell out population and index for variable names

2016-10-12 20:09 UTC, edeyoung commented on app/controllers/measures_controller.rb
> +        pop.slice(*HQMF::PopulationCriteria::ALL_POPULATION_CODES).each do |my_code, _v|
what is happening here? I thought `slice` took indices as arguments. is the idea to do an intersection between sets? If so, this can be done with the `&` operator.

2016-10-12 20:09 UTC, edeyoung commented on app/controllers/measures_controller.rb
> +        pop.slice(*HQMF::PopulationCriteria::ALL_POPULATION_CODES).each do |my_code, _v|
`_v` needs to be renamed.

2016-10-12 20:09 UTC, edeyoung commented on app/controllers/measures_controller.rb
> +        exptd_vals = patient.expected_values.dup
spell out `exptd_vals`

2016-10-12 20:09 UTC, edeyoung commented on app/controllers/measures_controller.rb
> +        exptd_vals.reject! { |ev| ev['population_index'] >= measure.populations.count } if measure.populations.count < patient['expected_values'].count
spell out `ev`

2016-10-12 20:09 UTC, edeyoung commented on app/controllers/measures_controller.rb
> +        corrected_expected.each_index { |i| exptd_vals << corrected_expected[i] if i >= patient['expected_values'].count } if measure.populations.count > patient['expected_values'].count
you have two statements with if conditionals - one with `if foo < bar` and one with `if foo > bar`. This is a good place to do a proper `if/else if` statement. An `if/else if` statement will tie these together more logically and increase readability.

2016-10-12 20:09 UTC, edeyoung commented on app/controllers/measures_controller.rb
> +        corrected_expected.each_index { |i| exptd_vals << corrected_expected[i] if i >= patient['expected_values'].count } if measure.populations.count > patient['expected_values'].count
is the only purpose of `corrected_expected` to add 0 values to populations that were not yet defined? If so, there should be a more direct way of doing this. I also recommend only creating the `corrected_expected` object (or whatever replaces it based on the first statement) if it's clear that it's needed (when measure pops > patient pops).

2016-10-12 20:09 UTC, edeyoung commented on app/controllers/measures_controller.rb
> +        exptd_vals.each_index do |evi|
spell out `evi`

2016-10-12 20:09 UTC, edeyoung commented on app/controllers/measures_controller.rb
> +    end # patients.count > 0
Work on simplifying this entire (above) section of logic. My gut (similar to the `calculateAllResults` logic) is that this can be significantly simplified.

2016-10-12 20:09 UTC, edeyoung commented on app/controllers/measures_controller.rb
> +    #TODO: Determine what to do with archived measures.
has this been figured out? I think we should keep. I, at least, delete and re-upload measures quite a bit. I think it would be good to keep the history. If measure devs disagree, they'll let us know.

2016-10-12 20:09 UTC, edeyoung commented on app/controllers/measures_controller.rb
> +      # For the initial relase of the Measure Upload History the feature will be disabled for portfolio users
make all the portfolio user statments `TODOs`. This will make them easier to spot in the future.

2016-10-12 20:09 UTC, edeyoung commented on app/controllers/measures_controller.rb
> +        upl_id = UploadSummary::MeasureSummary.where(measure_db_id_after: measure.id).first.id
change `upl_id`
change `measure_db_id_after`

2016-10-12 20:09 UTC, edeyoung commented on app/controllers/measures_controller.rb
> +      flash[:uploaded_summary_id] = upl_id
what is `flash`? consider renaming.

2016-10-12 20:09 UTC, edeyoung commented on app/controllers/patients_controller.rb
> +     patient.calc_results = params['calc_results'] unless current_user.is_portfolio?
spacing looks off here.

2016-10-12 20:09 UTC, edeyoung commented on app/controllers/upload_summaries_controller.rb
> +  skip_before_action :verify_authenticity_token, only: [:show, :value_sets]
add a comment for this

2016-10-12 20:09 UTC, edeyoung commented on app/controllers/upload_summaries_controller.rb
> +  def index
add function comment. does the name need to be more descriptive?

2016-10-12 20:09 UTC, edeyoung commented on app/controllers/upload_summaries_controller.rb
> +  def show
add function comment. does the name need to be more descriptive?

2016-10-12 20:09 UTC, edeyoung commented on lib/ext/archived_measure.rb
> +  field :hqmf_id, type: String # should be using this one as primary id!!
can you add a comment mentioning why? is this a TODO? should things change?

2016-10-12 20:09 UTC, edeyoung commented on lib/ext/archived_measure.rb
> +  field :measure_db_id, type: BSON::ObjectId
if a user deleted a measure and uploaded it again, would the db id change?

2016-10-12 20:09 UTC, edeyoung commented on lib/ext/archived_measure.rb
> +  field :measure_hash, type: Hash
should this be `measure_content` or `measure`? `measure_hash` isn't doing it for me.

2016-10-12 20:09 UTC, edeyoung commented on lib/ext/measure_upload_summary.rb
> +  SLICER = HQMF::PopulationCriteria::ALL_POPULATION_CODES + ['rationale', 'finalSpecifics']
is it necessary to build `SLICER` like this? `SLICER` should be renamed to something more descriptive.

2016-10-12 20:09 UTC, edeyoung commented on lib/ext/measure_upload_summary.rb
> +    field :upload_dtm, type: Time, default: -> { Time.current }
In archived measure, this is `uploaded_at`. Is there a reason for these to be different? If not, they should be consistent.

2016-10-12 20:09 UTC, edeyoung commented on lib/ext/measure_upload_summary.rb
> +    field :measure_db_id_after, type: BSON::ObjectId # The mongoid id of the measure after it is has been updated
rename these to something more descriptive so it can be understood outside of the context of this class. Maybe `measure_db_id_before_archive`, etc.

2016-10-12 20:09 UTC, edeyoung commented on lib/ext/measure_upload_summary.rb
> +    field :measure_hqmf_version_number_after, type: String
same comment about being more clear in the variable names.

2016-10-12 20:09 UTC, edeyoung commented on lib/ext/measure_upload_summary.rb
> +      pat_pop_idx = []
rename

2016-10-12 20:09 UTC, edeyoung commented on lib/ext/measure_upload_summary.rb
> +    embeds_many :population_summaries, cascade_callbacks: true
is this "population" or "population set"? If "population set", change the name.

2016-10-12 20:09 UTC, edeyoung commented on lib/ext/measure_upload_summary.rb
> +    def before_measure_load_compare(patient, pop_idx, m_id)
rename `pop_idx` and `m_id`.

2016-10-12 20:09 UTC, edeyoung commented on lib/ext/measure_upload_summary.rb
> +      patient.expected_values.each { |e| pat_pop_idx << e[:population_index] if e[:measure_id] == m_id }
rename `e`

2016-10-12 20:09 UTC, edeyoung commented on lib/ext/measure_upload_summary.rb
> +      trim_expected = (patient.expected_values.find {|p| p[:measure_id] == m_id && p[:population_index] == pop_idx }).slice(*SLICER)
I feel like this should be a set intersection rather than a slice. (`&`)

2016-10-12 20:09 UTC, edeyoung commented on lib/ext/measure_upload_summary.rb
> +      trim_expected = (patient.expected_values.find {|p| p[:measure_id] == m_id && p[:population_index] == pop_idx }).slice(*SLICER)
my preference is to have logic like `patient.expected_values.find {|p| p[:measure_id] == m_id && p[:population_index] == pop_idx }` in its own statement assigned to a variable, and then operate on the variable. I find that much easier to debug and read.

2016-10-12 20:09 UTC, edeyoung commented on lib/ext/measure_upload_summary.rb
> +      trim_before = (patient.calc_results.find {|p| p[:measure_id] == m_id && p[:population_index] == pop_idx }).slice(*SLICER) unless patient.too_big
add a comment explaining why you are trimming and what you are getting out the other end

2016-10-12 20:09 UTC, edeyoung commented on lib/ext/measure_upload_summary.rb
> +      # TODO: Make sure this can handle continuous value measures.
has this TODO been addressed?

2016-10-12 20:09 UTC, edeyoung commented on lib/ext/measure_upload_summary.rb
> +        if (patient.calc_results.find{ |p| p[:measure_id] == m_id && p[:population_index] == pop_idx })['status'] == 'pass'
this is another point where i'd find it easier to read to do `patient.calc_results.find{ |p| p[:measure_id] == m_id && p[:population_index] == pop_idx })` earlier and assign it to a variable. same with below.

2016-10-12 20:09 UTC, edeyoung commented on lib/ext/measure_upload_summary.rb
> +        if (patient.too_big_trimmed_results.find{ |p| p[:measure_id] == m_id && p[:population_index] == pop_idx })['status'] == 'pass'
i'm wondering if this should be renamed. I know what it means here because there's context all around it, but I could see this being confusing in other locations. (`too_big_trimmed_results`)

2016-10-12 20:09 UTC, edeyoung commented on lib/ext/measure_upload_summary.rb
> +      self[:patients][patient.id.to_s] = {
why change the id to a string?

2016-10-12 20:09 UTC, edeyoung commented on lib/ext/measure_upload_summary.rb
> +        expected: trim_expected,
should these be renamed to `trimmed_expected`? `trim_expected` implies an action, making this seem like a method name rather than an object name. same with `trim_before` below.

2016-10-12 20:09 UTC, edeyoung commented on lib/ext/measure_upload_summary.rb
> +        before: trim_before,
should this indicate `actual` somehow?

2016-10-12 20:09 UTC, edeyoung commented on lib/ext/measure_upload_summary.rb
> +  def self.collect_before_upload_state(measure, arch_measure)
rename all variables in this function

2016-10-12 20:09 UTC, edeyoung commented on lib/ext/measure_upload_summary.rb
> +  def self.collect_after_upload_state(measure, upl_id)
rename all variables in this function

2016-10-12 20:09 UTC, edeyoung commented on lib/ext/measure_upload_summary.rb
> +end
I will re-review this code once all the variables are renamed to make it easier for me to read.

2016-10-14 12:43 UTC, edeyoung requested changes
See comments

2016-10-14 12:43 UTC, edeyoung commented on lib/ext/record.rb
> +  field :results_size, type: Integer
can `has_measure_history` be determined by looking at other data? Does it need it's own flag?

rename `too_big`, `too_big_trimmed_results`, and `results_size` to give more context.

2016-10-14 12:43 UTC, edeyoung commented on lib/ext/record.rb
> +                :version_field => :version,   # adds "field :version, :type => Integer" to track current version, default is :version
should `:type` be integer or string for `:version`? does this need to handle "1.4.3" for example?

2016-10-14 12:43 UTC, edeyoung commented on lib/ext/record.rb
> +  def my_changes
remove this function and just use `sdc_changes` on line 88 (`:on =>..., chances_method: :sdc_changes`)

2016-10-14 12:43 UTC, edeyoung commented on lib/ext/record.rb
> +  def sdc_changes
rename - expand sdc

2016-10-14 12:43 UTC, edeyoung commented on lib/ext/record.rb
> +    modified_dc = changes['source_data_criteria'][1].index_by { |sdc| sdc['criteria_id'] }
rename. expand "dc"

2016-10-14 12:43 UTC, edeyoung commented on lib/ext/record.rb
> +    modified_dc = changes['source_data_criteria'][1].index_by { |sdc| sdc['criteria_id'] }
also expand "sdc"

2016-10-14 12:43 UTC, edeyoung commented on lib/ext/record.rb
> +    # changed, and another with criteria that have been added and criteria that have been changed
maybe change this comment to something like: "create two arrays. The first contains the old version of data criteria that have been modified or deleted. The second contains the new version of data criteria that have been modified or deleted." There might be better language for this. I just wasn't understanding that one had the "old" version of the data and the other had the "new" version of the data from the comments.

2016-10-14 12:43 UTC, edeyoung commented on lib/ext/record.rb
> +  def sdc_changes
Is the purpose of this method to only save relevant changes to the source data criteria? Add a comment explaining this at the top of the method.

2016-10-14 12:43 UTC, edeyoung commented on lib/ext/record.rb
> +      # indexes are zero based
this is an unnecessary comment

2016-10-14 12:43 UTC, edeyoung commented on lib/ext/record.rb
> +    expected_values.each_index do |pop_idx|
expand "pop_idx"

2016-10-14 12:43 UTC, edeyoung commented on lib/ext/record.rb
> +      # TODO: fix the expected values on the patient based on what the measure has
has this been addressed?

2016-10-14 12:43 UTC, edeyoung commented on lib/ext/record.rb
> +      calc_results[pop_idx][:status] = (expected_values[pop_idx].to_a - calc_results[pop_idx].to_a).empty? ? 'pass' : 'fail'
this line of logic confuses me. for `expected_values`, do I have something that looks like: `[["IPP":1, "DENOM":0,...],["IPP":0, "DENOM":0,...],...]`? So when I do the array subtraction, it only removes things that are exactly the same, so if I have `IPP:1` in `expected_values` but `IPP:0` in `calc_results`, it won't be removed so it won't be empty so it fails?
That's clever, but it needs a comment because it's not immediately intuitive.

2016-10-14 12:43 UTC, edeyoung commented on lib/ext/record.rb
> +    if self.results_size > 12000000
this number should be a configuration parameter somewhere rather than directly in the code.

2016-10-14 12:43 UTC, edeyoung commented on lib/ext/record.rb
> +      calc_results.each do |cr|
rename `cr`

2016-10-14 12:43 UTC, edeyoung commented on lib/ext/record.rb
> +    if self.results_size > 12000000
where else is `results_size` used? does it need to be forever stored on the object?

2016-10-14 12:43 UTC, edeyoung commented on lib/ext/record.rb
> +    if self.results_size > 12000000
I just did a find for results_size. It doesn't look like it needs to be stored.

2016-10-14 12:43 UTC, edeyoung commented on lib/ext/record.rb
> +      self.too_big_trimmed_results = calc_results
rename `too_big_trimmed_results`.

2016-10-14 12:43 UTC, edeyoung commented on lib/ext/record.rb
> +      self.too_big = true
rather than using the `too_big` flag, can something just check to see if `calc_results` is stored or if `too_big_trimmed_results` is stored and remove `too_big`? that way we don't have redundant data that can get out of sync.

2016-10-14 12:43 UTC, edeyoung commented on lib/tasks/setup_history_tracks.rake
> +          strat_pops = population.keys.reject { |k| k == 'id' || k == 'title' }
rename `strat_pops`. Is this supposed to mean "stratifications or population sets"? or is this supposed to be all the populations in the population set? If the latter, the "population set" could actually be either a stratification or population set (it seems like this might be just assuming stratification?). The Bonnie code generally just calls these populations (or in our new, clearer terminology, "population sets").

2016-10-14 12:43 UTC, edeyoung commented on lib/tasks/setup_history_tracks.rake
> +            setup_exception = "Measure setup exception: #{e.message}"
do we want to `next` (or `continue` or whatever is applicable here) if there's an exception rather than use the exception flag in an if statement below?

2016-10-14 12:43 UTC, edeyoung commented on lib/tasks/setup_history_tracks.rake
> +                calculation_exception = "Measure calculation exception: #{e.message}"
should there be a `next` or `continue` here?

2016-10-14 12:43 UTC, edeyoung commented on lib/tasks/setup_history_tracks.rake
> +            next unless result
will there always be a result if there's not an error? If so, we can get rid of this line if we have the `next` or `continue` statement in the error handler.

2016-10-14 12:43 UTC, edeyoung commented on lib/tasks/setup_history_tracks.rake
> +                raise
include an error message here

2016-10-14 12:43 UTC, edeyoung commented on lib/tasks/setup_history_tracks.rake
> +                retry
why will this have different results on retry? does something change in the data?

2016-10-14 12:43 UTC, edeyoung commented on lib/tasks/setup_history_tracks.rake
> +    def calculate_all(options = {})
include a `desc` thing here

2016-10-14 12:43 UTC, edeyoung commented on lib/tasks/setup_history_tracks.rake
> +      measures = Measure
why assign `Measure` to a variable?

2016-10-14 12:43 UTC, edeyoung commented on lib/tasks/setup_history_tracks.rake
> +      mdone = 1
rename

2016-10-14 12:43 UTC, edeyoung commented on lib/tasks/setup_history_tracks.rake
> +        pdone = 1
rename

2016-10-14 12:43 UTC, edeyoung commented on lib/tasks/setup_history_tracks.rake
> +          pop.slice(*HQMF::PopulationCriteria::ALL_POPULATION_CODES).each do |my_code, _v|
do you need `rational` and `finalSpecifics` as well?

2016-10-14 12:43 UTC, edeyoung commented on lib/tasks/setup_history_tracks.rake
> +      measures.each do |measure|
is the purpose of this function to get rid of stray `DENEX`s, etc? If so, there should be much simpler ways to do this. Check out the code I rewrote and we went over earlier. It's in a different language, but similar things should be able to be done here to simplify this a lot.

2016-10-14 12:43 UTC, edeyoung commented on lib/tasks/setup_history_tracks.rake
> +          puts "\n\n  Error with user #{measure.user.email} measure #{measure.cms_id} patient '#{patient.first} #{patient.last}':"
do we want to do anything else if there's an error? it seems like this will get lost in the noise.

2016-10-14 12:43 UTC, edeyoung commented on lib/tasks/setup_history_tracks.rake
> +       puts "Measure: #{measure.cms_id}\n\tPatient: #{patient.first} #{patient.last} (#{patient._id})\n\t\tPopulation Index: #{population_index}"
because of how errors are reported (also as put statements), they'll get lost in the noise if all patients are reported. If you want to do `.` or something to show progress for every 100 patients calculated or something like that, that would work. That way the errors will actually stand out.

2016-10-16 01:33 UTC, mulcahyk commented on lib/ext/record.rb
> +                :version_field => :version,   # adds "field :version, :type => Integer" to track current version, default is :version
This is something that is set by the history tracking gem.  It has nothing to do with the version of Bonnie.  It is also not something that can be renamed.

2016-10-16 01:55 UTC, mulcahyk commented on lib/ext/record.rb
> +    if self.results_size > 12000000
results_size is one of the fields tracked for changes.  I am keeping right now for a double check on when we trim the full result set down.  I also think that it is useful for seeing if the logic had an impact in the size of results.

2016-10-17 20:07 UTC, hossenlopp commented on app/controllers/measures_controller.rb
> +    @new_measure = Measure.where({:_id => params[:new_id]}).first
These calls need to be scoped by the the current user. I'll fix this.

2016-10-17 20:48 UTC, mulcahyk commented on lib/ext/record.rb
> +      # TODO: fix the expected values on the patient based on what the measure has
Yes.  There is a rake task to do this when we roll out Measure Upload History.  There is also a method in the measures_controller.rb that each time a new version of the measure is uploaded will check that we are only storing the appropriate values.

2016-10-19 21:18 UTC, mulcahyk commented on lib/tasks/setup_history_tracks.rake
> +          pop.slice(*HQMF::PopulationCriteria::ALL_POPULATION_CODES).each do |my_code, _v|
Not here.  At this point we are going through each patient for each measure and making sure that for each population set the populations match (between expected values and what is on the measure).  This is to see if a population was added or removed.

2016-10-24 22:17 UTC, mulcahyk commented on app/controllers/measures_controller.rb
> +    #TODO: Determine what to do with archived measures.
We should probably ask the users what they want in terms of behavior here.  When a measure is deleted are you deleting that version or the whole thing?  
We probably should look at allowing the users to select what history they want to keep around; after the annual update all of the intermediate steps might not be so valuable.

2016-10-27 20:59 UTC, mulcahyk commented on app/controllers/measures_controller.rb
> +    results['right'] = { 'cms_id' => @new_measure.cms_id, 'updateTime' => (@new_measure.updated_at.tv_sec * 1000), 'hqmf_id' => @new_measure.hqmf_id }
The spacial variable names work because of their meaning within the diff view.  I will add comments to make it clearer why we are using _'left'_ and _'right'_ (instead of something temporal).

2016-10-27 21:16 UTC, mulcahyk commented on app/controllers/measures_controller.rb
> +        population_diff << {}
Updated:
- new_population >> new_population_**set**
- old_population >> old_population_**set**
- logic_code >> **population**_code
- logic_title >> **population**_title
This is in keeping with the definitions of these concepts as defined in the wiki.

2016-10-27 21:24 UTC, thecristen commented on app/controllers/measures_controller.rb
> +    results['right'] = { 'cms_id' => @new_measure.cms_id, 'updateTime' => (@new_measure.updated_at.tv_sec * 1000), 'hqmf_id' => @new_measure.hqmf_id }
I echo @edeyoung's comment.... what if we want to show it top and bottom next year?  Decoupling the names from its presentation now means the variable names will still make sense later, and I really think you should reconsider.... 
Other diff examples I've seen tend to go with `original`/`new` or `original`/`changed` , though echoing `old_measure`/`new_measure` here would seem to make sense as well.

2016-10-27 21:58 UTC, mulcahyk commented
Fair point.  I’ll make the change.  I’m going to use “pre_upload” and “post_upload”

From: cristen jones <notifications@github.com>
Reply-To: projecttacoma/bonnie <reply@reply.github.com>
Date: Thursday, October 27, 2016 at 5:24 PM
To: projecttacoma/bonnie <bonnie@noreply.github.com>
Cc: "Mulcahy, Kristian P." <kmulcahy@mitre.org>, Mention <mention@noreply.github.com>
Subject: Re: [projecttacoma/bonnie] Measure History PR Dry Run (#567)


@thecristen commented on this pull request.

________________________________

In app/controllers/measures_controller.rb<https://github.com/projecttacoma/bonnie/pull/567>:

> @@ -14,6 +16,52 @@ def show

       end

     end

   end

+

+  def historic_diff

+    # get the two versions to diff

+    @new_measure = Measure.where({:_id => params[:new_id]}).first

+    @new_measure = ArchivedMeasure.where({:measure_db_id => params[:new_id]}).first.to_measure unless @new_measure

+

+    @old_measure = Measure.where({:_id => params[:old_id]}).first

+    @old_measure = ArchivedMeasure.where({:measure_db_id => params[:old_id]}).first.to_measure unless @old_measure

+

+    results = {}

+    results['diff'] = []

+    results['left'] = { 'cms_id' => @old_measure.cms_id, 'updateTime' => (@old_measure.updated_at.tv_sec * 1000), 'hqmf_id' => @old_measure.hqmf_id }

+    results['right'] = { 'cms_id' => @new_measure.cms_id, 'updateTime' => (@new_measure.updated_at.tv_sec * 1000), 'hqmf_id' => @new_measure.hqmf_id }

I echo @edeyoung<https://github.com/edeyoung>'s comment.... what if we want to show it top and bottom next year? Decoupling the names from its presentation now means the variable names will still make sense later, and I really think you should reconsider....
Other diff examples I've seen tend to go with original/new or original/changed , though echoing old_measure/new_measure here would seem to make sense as well.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://github.com/projecttacoma/bonnie/pull/567>, or mute the thread<https://github.com/notifications/unsubscribe-auth/AQ6OLBRBBuBSjCLWG2lZ16SLPrQKkUzaks5q4RZ6gaJpZM4JqWSj>.

2016-10-31 15:46 UTC, mulcahyk commented on lib/ext/archived_measure.rb
> +  field :hqmf_id, type: String # should be using this one as primary id!!
@edeyoung We probably should be using the hqmf_id as the primary key here but two things prevent us from doing that.
- Multiple users can upload the same measure
- The same measure can be uploaded multiple times by the same user; current each upload is considered to be unique
I will clarify the comment.

2016-10-31 17:25 UTC, mulcahyk commented on lib/ext/archived_measure.rb
> +  field :measure_db_id, type: BSON::ObjectId
Yes the db id is going to change.  The database id is unique to the combination of user and measure.
We could theoretically "recycle" database ids but we don't.  It would mean checking the archive_measures collection each time we load a measure.

2016-11-02 22:28 UTC, mulcahyk commented on app/assets/javascripts/views/measure_history_timeline_view.js.coffee
> +    uploadID = $(e.target).data('uploadId')
@edeyoung An uploadID is the basically the identifier for the measure upload event.  Within the context of measure history uploadID makes a lot of sense.  I have updated the module comment for UploadSummary that explains what the concept of an upload is.

2016-11-02 22:30 UTC, mulcahyk commented on app/assets/javascripts/views/measure_history_timeline_view.js.coffee
> +    upload = @upload_summaries.findWhere({_id: uploadID})
see [(https://github.com/projecttacoma/bonnie/pull/567#discussion_r86257036)]

2016-11-14 20:31 UTC, hossenlopp commented on app/assets/javascripts/models/upload_summary.js.coffee
> +  initialize: (models, options) ->
I'm adding a comment to explain the need for the measure_id in the options. Just following the JSDoc format.

2016-11-16 15:19 UTC, edeyoung commented on app/assets/javascripts/views/patient_builder/patient_builder.js.coffee
> +          callback(results)
@hossenlopp please look at lines 175 and 176 and rework so that it doesn't do the conditional call back

2016-11-17 16:13 UTC, edeyoung commented on lib/tasks/setup_history_tracks.rake
> +namespace :upgrade_add_hx_tracks do
reworked this file.

2016-11-17 20:50 UTC, edeyoung commented on lib/ext/record.rb
> +    modified.reject! { |dc| dc['id'] == 'MeasurePeriod' }
should this also be removed from `original`?

2016-11-18 13:12 UTC, edeyoung commented on lib/ext/measure_upload_summary.rb
> +    field :measure_hqmf_version_number_after, type: String
what is the difference between "pre-upload/post-upload" and "before/after"? If they represent the same concept , they should use the same name.

2016-11-18 13:14 UTC, edeyoung commented on lib/ext/measure_upload_summary.rb
> +    index "user_id" => 1
what is the purpose of this line?

2016-11-18 20:47 UTC, edeyoung commented on lib/ext/history_tracker.rb
> +class HistoryTracker
Is this used anywhere? Should this get deleted?

2016-11-18 20:53 UTC, edeyoung commented on db/convert_hqmf_version_number_to_string.js
> +db.draft_measures.find( { 'hqmf_version_number' : { $type: 16 } } ).forEach( function (x) {
should this be a rake task?

2016-11-18 20:57 UTC, edeyoung commented on app/views/layouts/application.html.erb
> +        <% end %>
@hossenlopp can you take a look at this and make sure this makes sense as an entry point for this view?

2016-11-18 21:23 UTC, edeyoung commented on app/controllers/measures_controller.rb
> +  # GET /measures/:id
Is this the typical way of commenting routes? I feel like I read this and got super confused about it's relation to the code below. Does it make sense to have it be:

```
##
# Route to method
# GET /measures/:id
#
# ...
```

2016-11-18 21:26 UTC, edeyoung commented on app/controllers/measures_controller.rb
> +  # GET /measures/:id
Also, this documentation isn't on all the methods accessible by routes. I feel like we should add the information to all the methods in this file (at least the `# GET ...` information because with only some commented this way, it makes it seem like the others aren't accessible through routes.

2016-11-18 21:30 UTC, edeyoung commented on app/controllers/measures_controller.rb
> +    @new_measure = ArchivedMeasure.where({:measure_db_id => params[:new_id]}).first.to_measure unless @new_measure
(change I'm making)

reworking so `unless @new_measure` is first. With it at the end of the line, this was initially confusing because my first thought was "but we just assigned that." with the `unless` first, I know that we're doing this only if we didn't access the measure through the DB.

2016-11-19 00:01 UTC, mulcahyk commented on lib/ext/record.rb
> +    modified.reject! { |dc| dc['id'] == 'MeasurePeriod' }
The way the history tracking gem works if you knock out the value in _modified_ it gets ignored.

2016-11-19 00:04 UTC, mulcahyk commented on lib/ext/history_tracker.rb
> +class HistoryTracker
This defines the name of the history tracking table.  Definitely shouldn't be deleted.  I'll add a comment as to why it is here.

2016-11-19 00:20 UTC, mulcahyk commented on db/convert_hqmf_version_number_to_string.js
> +db.draft_measures.find( { 'hqmf_version_number' : { $type: 16 } } ).forEach( function (x) {
I couldn't have a way to do this ruby.  This was the cleanest and simplest way I found.

2016-11-21 12:46 UTC, edeyoung commented on db/convert_hqmf_version_number_to_string.js
> +db.draft_measures.find( { 'hqmf_version_number' : { $type: 16 } } ).forEach( function (x) {
because a string conversion to a string conversion is fine, as is an int64, etc., couldn't you do something like:

```
Measure.each do |measure|
  measure.hqmf_version_number = measure.hqmf_version_number.to_s
  measure.save
end
```

2016-11-21 12:50 UTC, edeyoung commented on db/convert_hqmf_version_number_to_string.js
> +db.draft_measures.find( { 'hqmf_version_number' : { $type: 16 } } ).forEach( function (x) {
If you want to ensure you're only converting ints, you could do something like:

```
Measure.each do |measure|
  if measure.hqmf_version_number.is_a?(Fixnum)
    measure.hqmf_version_number = measure.hqmf_version_number.to_s
    measure.save
  end
end
```

but i think it's fine to just do a generic switch

2016-11-22 15:59 UTC, edeyoung commented on db/convert_hqmf_version_number_to_string.js
> +db.draft_measures.find( { 'hqmf_version_number' : { $type: 16 } } ).forEach( function (x) {
This actually isn't necessary. Just need to change the type in bonnie_bundler. *I've done this.*

2016-11-23 20:16 UTC, edeyoung commented on db/convert_hqmf_version_number_to_string.js
> +// converts hqmf_version_numbers from int types to string types.
REVIEWED

2016-11-23 20:16 UTC, edeyoung commented on lib/ext/archived_measure.rb
> +class ArchivedMeasure
REVIEWED

2016-11-23 20:17 UTC, edeyoung commented on lib/ext/history_tracker.rb
> +# Create a new class to track histories. All histories are stored in this tracker.
REVIEWED

2016-11-23 20:18 UTC, edeyoung commented on lib/tasks/setup_history_tracks.rake
> +namespace :bonnie do
REVIEWED

2016-11-23 20:22 UTC, edeyoung commented on lib/ext/record.rb
>  # Extensions to the Record model in health-data-standards to add needed functionality for test patient generation
REVIEWED

At some point, it may be worth looking at: can we get rid of `condensed_calc_results`?
It looks like when the results are processed for coloring, etc., this is done as part of the `CachedResults` object which individually gets the `rationale` and the `finalSpecifics` off of the stored results. This makes me think we could do something like:

``` ruby
field: results                # everything in the results object except rationale and finalSpecifics
field: rationale              # only exists if the results are small enough
field: finalSpecifics         # only exists if the results are small enough
field: results_exceed_storage # probably should be named something else in this instance
```

This would make it so we wouldn't need to do all sorts of `if/else` statements when we just want to access things in the results that aren't the rationale or finalSpecifics, which is most of the time.

2016-11-23 20:26 UTC, edeyoung commented on config/routes.rb
> +    resources :upload_summaries
@hossenlopp can you explain to me the resources here are used when they're embedded in another resource?

2016-11-23 20:27 UTC, edeyoung commented on config/bonnie.yml
>      api_url: https://vsac.nlm.nih.gov/vsac/svs/RetrieveMultipleValueSets
REVIEWED

2016-11-23 20:30 UTC, edeyoung commented on app/controllers/patients_controller.rb
>      # patient['measure_period_end'] = measure_period['end_date']
REVIEWED

2016-11-23 20:56 UTC, edeyoung commented on app/controllers/measures_controller.rb
> +    upload_summary_id = UploadSummary.collect_before_upload_state(measure, arch_measure) unless current_user.is_portfolio?
why is this put ahead of `measure.save!`?

2016-11-23 20:56 UTC, edeyoung commented on app/controllers/measures_controller.rb
> +    end
review this logic after reviewing `measure_upload`.

2016-11-23 21:01 UTC, edeyoung commented on app/controllers/archived_measures_controller.rb
> +  def index
this comment doesn't seem to match the function

2016-11-28 15:08 UTC, edeyoung commented on app/assets/stylesheets/diffy.less
> +/* Style from diffy gem */
REVIEWED

2016-11-28 15:09 UTC, edeyoung commented on app/assets/stylesheets/bootstrap3.less
> +.btn-wrap {
was this manually added into this style sheet or from an update? If manually added, it should probably go in a different location.

@thecristen where is the best place for a change like this to go?

2016-11-28 15:09 UTC, edeyoung commented on app/assets/stylesheets/application.css.less
>  @import "measures";
REVIEWED

2016-11-28 15:10 UTC, edeyoung commented on app/assets/javascripts/views/population_calculation_view.js.coffee
>    clonePatient: (e) ->
REVIEWED

2016-11-29 14:20 UTC, edeyoung commented on config/routes.rb
> +    resources :upload_summaries
this does nested resource routing. e.g.: asdfasdf/measures/<measure_id>/archived_measures. TODO: add to code comments.

2016-11-29 14:23 UTC, edeyoung commented on app/views/layouts/application.html.erb
>          <% if (flash[:error]) %>
REVIEWED

2016-11-29 14:25 UTC, edeyoung commented on app/controllers/upload_summaries_controller.rb
> +  skip_before_action :verify_authenticity_token, only: [:show, :value_sets]
remove `:value_sets`

2016-11-29 14:29 UTC, edeyoung commented on app/controllers/measures_controller.rb
> +    #TODO: Determine what to do with archived measures.
TODO: double check behavior when a measure gets deleted and re-uploaded. Does the user have access to the archived measures from the deleted measure?

Currently, let's delete the archived measure information. Let's talk to users about best course of action at some point.

Also delete patient audit trail.

2016-11-29 14:36 UTC, edeyoung commented on app/assets/stylesheets/bootstrap3.less
> +.btn-wrap {
Looks like this *is* actually a file that gets edited manually.
Recommendation: fix spacing.

2016-11-29 14:39 UTC, edeyoung commented on app/assets/javascripts/views/patient_builder/patient_version_compare.js.coffee
> +class Thorax.Views.ComparePopulationLogic extends Thorax.LayoutView
@hossenlopp - work with kristian to subclass

2016-11-29 14:43 UTC, edeyoung commented on app/assets/javascripts/views/measure_history_timeline_view.js.coffee
> +    uploadID = $(e.target).data('uploadId')
add a one-liner comment explaining the context of the `uploadId` here

2016-11-30 14:52 UTC, edeyoung commented on app/assets/javascripts/views/patient_builder/patient_version_compare.js.coffee
> +    if @postuploadmeasureversion is undefined && @preuploadmeasureversion is undefined
why `undefined` rather than `nil` here?

2016-11-30 14:54 UTC, edeyoung commented on app/assets/javascripts/views/patient_builder/patient_version_compare.js.coffee
> +      populationToShow = @preuploadmeasureversion.get('populations').at(@measure.get('displayedPopulation').get('index'))
the way the logic is written, `preuploadmeasureversion` could be undefined in this context. Should the `if` statement above change?

2016-11-30 14:55 UTC, edeyoung commented on app/assets/javascripts/views/patient_builder/patient_version_compare.js.coffee
> +    if rationaleToShow isnt undefined
`undefined` vs `nil`?

2016-12-01 00:10 UTC, edeyoung commented on app/controllers/measures_controller.rb
> +    #TODO: Determine what to do with archived measures.
decision to delete history, although this can wait until later iteration of this work.

2016-12-01 15:24 UTC, edeyoung commented on app/assets/javascripts/views/patient_builder/patient_version_compare.js.coffee
> +class Thorax.Views.ComparePopulationLogic extends Thorax.LayoutView
I am subclassing this.

2016-12-02 17:24 UTC, edeyoung commented on app/assets/javascripts/views/patient_builder/patient_version_compare.js.coffee
> +class Thorax.Views.PatientBuilderCompare extends Thorax.Views.BonnieView
REVIEWED

2016-12-02 17:31 UTC, hossenlopp commented on app/assets/javascripts/templates/patient_bank/patient_bank.hbs
> +    <a href="#measures/{{measure_id}}/history"><i class="fa fa-history"></i> </i>MEASURE UPLOAD HISTORY</a>
FIXED

2016-12-02 22:06 UTC, hossenlopp commented on lib/ext/measure_upload_summary.rb
> +        case !patient.too_big
This has been addressed.

2016-12-02 22:34 UTC, hossenlopp commented on app/assets/javascripts/helpers.js.coffee
> +Handlebars.registerHelper 'dateFormat', (date, fmt) ->
It turns out Measure History is the only one using the `moment` helper. We DON'T want it to cast to UTC. I am removing the `dateFormat` helper and removing the UTC cast from it. PR created #601 on new branch.

2016-12-02 23:04 UTC, hossenlopp commented on app/assets/javascripts/helpers.js.coffee
> +  (block.fn(i) for i in [0...n]).join("")
The times helper is only used in valueset code listing. The definition of it is later in the file. I removed this extra helper on the new branch and created PR #603.

2016-12-02 23:05 UTC, hossenlopp commented on app/assets/javascripts/helpers.js.coffee
> +
This has been merged with the rebase. All is good.

2016-12-02 23:08 UTC, hossenlopp commented on app/assets/javascripts/templates/measure_upload_summary_dialog.hbs
> +        <h5>Your measure has uploaded successfully!</h5>
This has been FIXED.

2016-12-02 23:12 UTC, hossenlopp commented on app/assets/javascripts/templates/measure_upload_summary.hbs
> +          <tr>
FIXED in 6fbff87ba72902036e6f27189f2d160163f7b7ef.

2016-12-02 23:17 UTC, hossenlopp commented on app/assets/stylesheets/measure_history.less
> +/* Style from diffy gem */
FIXED. Was moved to its own file.

2016-12-02 23:18 UTC, hossenlopp commented on app/assets/javascripts/templates/measure_upload_summary_dialog.hbs
> +        <h1 id="uploadSummaryTitle">Measure Upload Completed</h1>
I FIXED this a while ago.

2016-12-02 23:19 UTC, hossenlopp commented on app/controllers/patients_controller.rb
> +  #   {label: "Jack Sparrow", times: [{result:"pass", updateTime: 1451606400000},
I believe these were cleaned up quite some time ago. FIXED

2016-12-02 23:29 UTC, hossenlopp commented on app/assets/javascripts/views/patient_builder/patient_version_compare.js.coffee
> +      # @populationInBefore = true
It looks like it was removed with other code cleanups. FIXED

2016-12-02 23:29 UTC, hossenlopp commented on app/assets/javascripts/views/patient_builder/patient_version_compare.js.coffee
> +          # @fromEdit = true
It looks like it was removed with other code cleanups. FIXED

2016-12-02 23:32 UTC, hossenlopp commented on app/controllers/measures_controller.rb
> +    #render :json => results
I removed the history function. FIXED.

2016-12-02 23:38 UTC, hossenlopp commented on app/assets/javascripts/views/measure_history_timeline_view.js.coffee
> +    #$.get('/measures/history?id='+@model.attributes['hqmf_set_id'], @loadHistory)
This line was cleaned up. FIXED

2016-12-02 23:58 UTC, hossenlopp commented on app/assets/javascripts/models/upload_summary.js.coffee
> +  fetchDeferred: ->
This has been renamed and explained with comments.

2016-12-02 23:59 UTC, hossenlopp commented on app/assets/javascripts/models/upload_summary.js.coffee
> +    fetchDef = $.Deferred()
They have been renamed and explained with comments. FIXED IN #598

2016-12-02 23:59 UTC, hossenlopp commented on app/assets/javascripts/models/upload_summary.js.coffee
> +  fetchDeferred: ->
FIXED IN #598

2016-12-02 23:59 UTC, hossenlopp commented on app/assets/javascripts/models/upload_summary.js.coffee
> +    @fetch(
Addressed with comments and FIXED IN #598

2016-12-03 00:02 UTC, hossenlopp commented on app/assets/javascripts/models/upload_summary.js.coffee
> +  initialize: (models, options) ->
Addressed in #598

2016-12-03 00:02 UTC, hossenlopp commented on app/assets/javascripts/models/measure.js.coffee
> +    attrs.archived_measures = new Thorax.Collections.ArchivedMeasures null, {measure_id: attrs._id, _fetched: false}
Addressed in #598

2016-12-03 00:03 UTC, hossenlopp commented on app/assets/javascripts/models/measure.js.coffee
> +    attrs.archived_measures = new Thorax.Collections.ArchivedMeasures null, {measure_id: attrs._id, _fetched: false}
Addressed in #598

2016-12-03 00:04 UTC, hossenlopp commented on app/assets/javascripts/models/upload_summary.js.coffee
> +  fetchAll: ->
Walked lizzie through this stuff in a group programming monday.

2016-12-03 00:06 UTC, hossenlopp commented on app/assets/javascripts/router.js.coffee
> +    'measures/:measure_hqmf_set_id/patients/:id/compare/at_upload/:upload_id':  'renderHistoricPatientCompare'
This was moved to hang out with the other measure paths in 332434f9ce35e6f51fb28c82e2cc761fc3621abd.

2016-12-03 14:57 UTC, edeyoung commented on app/assets/javascripts/helpers.js.coffee
> +Handlebars.registerHelper 'dateFormat', (date, fmt) ->
ADDRESSED

2016-12-03 15:08 UTC, edeyoung commented on app/assets/stylesheets/bootstrap3.less
> +.btn-wrap {
** fixing spacing. will be in upcoming PR to measure_history_rebase **

2016-12-05 15:59 UTC, hossenlopp commented on app/assets/javascripts/router.js.coffee
> +    upsums = measure.get('upload_summaries')
This was addressed during the lazyloading refactor.

2016-12-05 15:59 UTC, hossenlopp commented on app/assets/javascripts/router.js.coffee
> +    upload_summary = null
This was addressed during the lazyloading refactor.

2016-12-05 16:00 UTC, hossenlopp commented on app/assets/javascripts/router.js.coffee
> +    $.when(upsums.fetchDeferred(), archivedMeasures.fetchDeferred())
This was addressed during the lazyloading refactor.

2016-12-05 16:03 UTC, hossenlopp commented on app/assets/javascripts/router.js.coffee
> +    measure_summaries.fetchDeferred()
This specific instance was not hidden. Should it be?

2016-12-05 16:05 UTC, hossenlopp commented on app/assets/javascripts/templates/breadcrumb.hbs
> +        {{#if fromHxTimeline}}
FIXED in 332434f9ce35e6f51fb28c82e2cc761fc3621abd.

2016-12-05 16:08 UTC, hossenlopp commented on app/assets/javascripts/templates/logic/data_criteria.hbs
> +  {{#if suppressDataCriteriaHighlight}}
Looks like the suggestion was added in 332434f9ce35e6f51fb28c82e2cc761fc3621abd.

2016-12-08 14:12 UTC, edeyoung commented on lib/ext/measure_upload_summary.rb
> +module UploadSummary
REVIEWED

Reviewed and refactored as part of pull request 612: https://github.com/projecttacoma/bonnie/pull/612

2016-12-08 14:21 UTC, edeyoung commented on app/controllers/measures_controller.rb
> +  include UploadSummary
REVIEWED

Several changes are included in the 612 pull request. https://github.com/projecttacoma/bonnie/pull/612

2016-12-08 14:21 UTC, edeyoung commented on app/assets/stylesheets/bootstrap3.less
> +
REVIEWED

Change in https://github.com/projecttacoma/bonnie/pull/612

2016-12-08 14:21 UTC, edeyoung commented on app/assets/stylesheets/bootstrap3.less
> +.btn-wrap {
In https://github.com/projecttacoma/bonnie/pull/612

2016-12-08 14:25 UTC, edeyoung commented on app/assets/javascripts/views/measures_view.js.coffee
> +    # Draws a % sign on the output of the dial.
REVIEWED

2016-12-08 14:33 UTC, edeyoung commented on app/assets/javascripts/views/measure_view.js.coffee
> +    @populationCalculation = new Thorax.Views.PopulationCalculation(model: population, dontShowMeasureUpload: bonnie.isPortfolio)
REVIEWED

Renaming in future pull request to `dontShowMeasureHistory` to be more descriptive.

2016-12-08 15:42 UTC, edeyoung commented on app/assets/javascripts/views/measure_upload_summary_view.js.coffee
> +class Thorax.Views.MeasureUploadSummary extends Thorax.Views.BonnieView
REVIEWED

made Cristen's recommended modifications and some variable name changes. Will be in upcoming pull request.

2016-12-08 15:44 UTC, edeyoung commented on app/assets/javascripts/views/measure_upload_summary_dialog_view.js.coffee
> +class Thorax.Views.MeasureUploadSummaryDialog extends Thorax.Views.BonnieView
REVIEWED

2016-12-08 23:13 UTC, hossenlopp commented on app/assets/javascripts/templates/measure_history_diff.hbs
> +      <div class="col-md-6"><h3><strong>{{diff.left.cms_id}}</strong> @ {{diff.left.updateTime}}</h3><small>{{diff.left.hqmf_id}}</small></div>
FIXED in a7abd38b1f141e8b5d09415d487b1df386264696.

2016-12-08 23:14 UTC, hossenlopp commented on app/assets/javascripts/templates/measure_history_timeline.hbs
> +        {{/with}}
@thecristen has redesigned this template and addressed this.

2016-12-08 23:18 UTC, hossenlopp commented on app/assets/javascripts/templates/measure_history_diff.hbs
> +  {{#if diffView}}
`diffView` isn't a boolean. It is the structure that contains all the diff view data, if it is undefined then that means it isn't loaded.

2016-12-09 13:48 UTC, edeyoung commented on app/assets/javascripts/views/measure_history_timeline_view.js.coffee
> +class Thorax.Views.MeasureHistoryTimelineView extends Thorax.Views.BonnieView
REVIEWED

Comments below addressed in future PR to the measure history rebase branch.

2016-12-09 13:55 UTC, edeyoung commented on app/assets/javascripts/views/measure_history_diff_view.js.coffee
> +class Thorax.Views.MeasureHistoryDiffView extends Thorax.Views.BonnieView
REVIEWED

comments below addressed in upcoming pull request to measure_history_rebase.

2016-12-09 13:56 UTC, edeyoung commented on app/assets/javascripts/views/logic/population_logic_view.js.coffee
>  class Thorax.Views.PopulationsLogic extends Thorax.LayoutView
REVIEWED

2016-12-09 13:56 UTC, edeyoung commented on app/assets/javascripts/views/logic/data_criteria_logic_view.js.coffee
> +    # TODO: Find a better way than logic in the template to disable highlighting when called from code other than patient builder.
No, and it won't be for this iteration of measure history.

2016-12-09 13:56 UTC, edeyoung commented on app/assets/javascripts/views/logic/data_criteria_logic_view.js.coffee
>    events:
REVIEWED

2016-12-09 14:23 UTC, edeyoung commented on app/assets/javascripts/templates/patient_builder/population_logic.hbs
>  <h1 class="heading-muted"><i class="fa fa-tasks" aria-hidden="true"></i> {{cms_id}}</h1>
REVIEWED

2016-12-09 14:23 UTC, edeyoung commented on app/assets/javascripts/templates/patient_builder/patient_version_compare.hbs
> +
REVIEWED

2016-12-09 14:26 UTC, edeyoung commented on app/assets/javascripts/templates/measure_upload_summary.hbs
> +{{! The total number of patients remains constant across different populations}}
REVIEWED-ish

Cristen has reworked this class somewhat already. This is in https://github.com/projecttacoma/bonnie/pull/611 pull request.

2016-12-09 14:27 UTC, edeyoung commented on app/assets/javascripts/templates/measure_history_timeline.hbs
> +<div>
REVIEWED-ish

Cristen reworked in https://github.com/projecttacoma/bonnie/pull/608

2016-12-09 14:30 UTC, edeyoung commented on app/assets/javascripts/templates/measure_history_diff.hbs
> +<div class="measure-diff">
REVIEWED

2016-12-09 15:31 UTC, edeyoung commented on app/assets/javascripts/router.js.coffee
> +    document.title += " - #{measure.get('cms_id')}" if measure?
ADDRESSED

2016-12-09 15:32 UTC, edeyoung commented on app/assets/javascripts/templates/measure_history.hbs
> +  <!-- TODO: Ensure that the stratification tabs toggle a render for the data -->
This is being addressed.

2016-12-09 15:33 UTC, edeyoung commented on app/assets/javascripts/templates/measure_upload_summary_dialog.hbs
> +<div class="modal fade measureUploadSummaryDialog" id="measureUploadSummaryDialog" tabindex="-1" aria-hidden="true">
REVIEWED

2016-12-09 15:35 UTC, edeyoung commented on app/assets/javascripts/templates/patient_builder/patient_builder.hbs
> +    {{#if has_measure_history}}
REVIEWED

2016-12-09 15:41 UTC, edeyoung commented on app/assets/javascripts/views/breadcrumb.js.coffee
>        period: bonnie.measurePeriod
REVIEWED

2016-12-09 15:47 UTC, edeyoung commented on app/assets/javascripts/views/measure_history_view.js.coffee
> +class Thorax.Views.MeasureHistoryView extends Thorax.Views.BonnieView
REVIEWED

2016-12-09 19:35 UTC, hossenlopp commented on app/controllers/upload_summaries_controller.rb
> +  skip_before_action :verify_authenticity_token, only: [:show, :value_sets]
This line can actually be removed. Will remove in PR to address and comment ArchivedMeasures and UploadSummaries Controllers.

2016-12-13 17:10 UTC, thecristen commented on app/assets/javascripts/templates/measure_upload_summary.hbs
> +              <th width="150px" class="centered">&ensp;Current &emsp;&nbsp;Version</th>
Addressed in #620

2016-12-13 17:12 UTC, thecristen commented on app/assets/javascripts/templates/patient_builder/patient_version_compare.hbs
> +        <h3>The selected data are too large.</h3>
Looks like this was already addressed.

2016-12-13 17:12 UTC, thecristen commented on app/assets/javascripts/templates/patient_builder/patient_version_compare.hbs
> +      <h3>The selected population of the measure is too large.</h3>
Looks like this was addressed.

2016-12-13 17:14 UTC, thecristen commented on app/assets/javascripts/templates/population_calculation.hbs
> +      <a href="#measures/{{measure_id}}/history"><i class="fa fa-history"></i> </i>MEASURE UPLOAD HISTORY</a>
This was addressed

2016-12-13 17:16 UTC, thecristen commented on app/assets/javascripts/templates/population_calculation.hbs
> +    <div style="text-align:center;">
Addressed in #620

2016-12-13 17:18 UTC, thecristen commented on app/assets/javascripts/views/measure_upload_summary_view.js.coffee
> +        }
This was fixed!

2016-12-13 17:47 UTC, thecristen commented on app/assets/stylesheets/measure_history.less
> +  color: #730800;
Addressed in #620

2017-04-19 11:57 UTC, edeyoung commented
Measure history has been merged into the master branch of bonnie. This PR was kept to maintain comments. It is no longer needed.

2017-04-19 11:57 UTC, closed without merging