Backend fixture grouping
MeasureAuthoringTool/bonnie pull request #585
Opened 2016-10-10 13:57 UTC by mayerm94

Record sets can now be used by putting records into a sub directory of the records fixture folder and passing that path to the collections_fixtures test helper method as normal

2016-10-12 12:13 UTC, edeyoung requested changes
Looks good - expand to users and draft_measures and rename "set_1".

2016-10-12 12:13 UTC, edeyoung commented on test/test_helper.rb
> +        # The collection (Record,User,Measures) is the root of the collection sets
can you add some additional comments here? why does this need to be split?

2016-10-12 12:13 UTC, edeyoung commented on test/functional/admin_users_controller_test.rb
> +    records_set = File.join("records","set_1")
I think it makes sense to rename this to "base_tests" instead of "set_1" or something more descriptive. Then as we add tests, they can be in directories like, "measure_history_tests" (or something like that).
I also think it makes sense to do this for the users and the records, as you had suggested in an earlier standup.
Is it possible to combine sets together? Can I use records that would be in both "set_1" and "set_2" or would I need to copy the records I want from "set_1" into "set_2"?

2016-10-14 14:04 UTC, mayerm94 commented on test/functional/admin_users_controller_test.rb
> +    records_set = File.join("records","set_1")
Yes, you can include multiple sets. To include multiple sets you would need to do create a file path for each set (set_1 and set_2 for example) and pass both of the file paths to the collection_fixtures function. In this instance, all records in set_1 and set_2 would be added to the records collection

2016-10-18 17:37 UTC, edeyoung approved these changes

2016-10-18 17:43 UTC, merged

2016-10-18 23:08 UTC, mulcahyk commented
@mayerm94 can you give an example of how you would add fixtures other than what is in the base set?  It would be helpful to have that in the comments in test_helper.rb.