Removed hard coded email address
MeasureAuthoringTool/bonnie pull request #593
Opened 2016-11-22 16:23 UTC by holmesie

Removed hard coded email address; Made email config (email.yml) server specific.

2016-11-22 16:56 UTC, c-monkey commented on config/environment.rb
> +APP_CONFIG.merge! YAML.load_file(Rails.root.join('config', 'email.yml')) if File.exists? Rails.root.join('config', 'email.yml')
server.yml is already optional, is there a reason you've split out email from this file?

2016-11-22 17:17 UTC, holmesie commented on config/environment.rb
> +APP_CONFIG.merge! YAML.load_file(Rails.root.join('config', 'email.yml')) if File.exists? Rails.root.join('config', 'email.yml')
`server.yml` handles SMTP/hostname settings, i.e. things reliant on the actual machine the deployment is running on. I felt the email address we are sending errors/signups/etc is more server agnostic, so it should have its own config.

2016-11-22 20:46 UTC, mulcahyk commented on test/functional/admin_users_controller_test.rb
> -    assert_equal "bonnie-feedback-list@lists.mitre.org", mail.from.first
Do we have some way of testing to make sure that the correct email will show up when we need it?

2016-11-22 20:49 UTC, mulcahyk commented on config/bonnie.yml
> +  bonnie_email: bonnie@example.com
Do we have it documented somewhere what this value is for and what it should be changed to?
What happens if this is not a valid email address or is blank?

2016-11-22 21:01 UTC, holmesie commented on config/bonnie.yml
> +  bonnie_email: bonnie@example.com
This is the default value in case Bonnie was not deployed with an email configuration (`email.yml`). The email value for certain parts of Bonnie can not be set to null, so this needs to exist (since `email.yml` is optional, and local to a deployment server). If this field is not valid, it would be like sending an email to an invalid email address - not an issue.

The intention is to add information for this and `email.yml` for deployments in our deployment instructions/documentation, but I feel that should wait until this is merged.

2016-11-22 21:06 UTC, holmesie commented on test/functional/admin_users_controller_test.rb
> -    assert_equal "bonnie-feedback-list@lists.mitre.org", mail.from.first
We could probably do that - I'll add that in.

2016-12-12 13:28 UTC, edeyoung requested changes
Add comment about email in config file and resolve Kristian's comment about adding a test to ensure the correct email will actually show up.

2016-12-12 13:28 UTC, edeyoung commented on config/bonnie.yml
> +  bonnie_email: bonnie@example.com
I agree with @mulcahyk that this should have a comment associated with it, especially as `bonnie@example.com` is not a valid email address.

Maybe something like:
"Place holder email for error alerts. This email is not valid. This email should be configured in X file."

2017-01-04 20:00 UTC, edeyoung approved these changes

2017-12-21 19:01 UTC, holmesie commented
Reviving this change for CQL in a new pr.

2017-12-21 19:01 UTC, closed without merging