Measure history population fixes
MeasureAuthoringTool/bonnie pull request #595
Opened 2016-11-23 23:06 UTC by mulcahyk

Work dealing with the handling of changes to the number of populations from pre-upload to post-upload.

2016-11-28 13:34 UTC, edeyoung commented on lib/ext/measure_upload_summary.rb
> +    # patients = Record.where(user_id: measure.user_id, measure_ids: measure.hqmf_set_id)
remember to go back through and delete commented out code.

2016-11-28 14:06 UTC, edeyoung requested changes

2016-11-28 14:06 UTC, edeyoung commented on lib/ext/measure_upload_summary.rb
> +  def self.collect_before_upload_state(measure, arch_measure, measure_patients)
watch naming again. It took me two looks to get that `arch_measure` was `archived_measure` and I was honestly confused for a second about why we care about arches.

2016-11-28 14:06 UTC, edeyoung commented on lib/ext/measure_upload_summary.rb
> +    # if measure_upload_summary.population_set_summaries.count < measure.populations.count
delete old lines of code.

2016-11-28 14:06 UTC, edeyoung commented on lib/ext/measure_upload_summary.rb
> +      # Add the missing population sets
we're adding missing population sets. do we need to remove population sets that are no longer there?

2016-11-28 14:06 UTC, edeyoung commented on lib/ext/measure_upload_summary.rb
> +      # It needs to be done this way as the order of the population sets is their population_index.
we now have three places in the code where we are getting populations and expected values to align.
Is there somewhere we can put this in a common place? Can this be a function on the patient model or the measure model?

2016-11-28 14:06 UTC, edeyoung commented on lib/ext/measure_upload_summary.rb
> +        (measure.populations[-i].keys.to_a - ['id', 'title']).each { |population| missing_expected_values[population] = 0 }
`to_a` is unnecessary here. `keys` returns an array.

what about doing the slice with `HQMF::PopulationCriteria::ALL_POPULATION_CODES` instead here? this will ensure we're only dealing with populations.

2016-11-28 14:06 UTC, edeyoung commented on lib/ext/measure_upload_summary.rb
> +        measure_patients.each { |patient| new_population_set['patients'][patient.id.to_s] = {:expected => missing_expected_values} }
does the `patient.id` need to be converted to a string for use as a key?

2016-11-28 14:06 UTC, edeyoung commented on lib/ext/measure_upload_summary.rb
> +      # It needs to be done this way as the order of the population sets is their population_index.
is this still necessary with the work to align populations and expected values done on measure load?

2016-11-28 14:06 UTC, edeyoung commented on test/functional/measures_controller_test.rb
> +    # measure = Measure.where({cms_id: "CMS123v3"}).first
should this line be deleted?

2016-11-28 14:06 UTC, edeyoung commented on test/functional/measures_controller_test.rb
> +    p = Record.where(first: 'John, III', measure_ids: 'C0D72444-7C26-4863-9B51-8080F8928A85').first
add comment about what you're doing here. Is the point to make this patient exceed the record size limit?

2016-11-28 14:06 UTC, edeyoung commented on test/functional/measures_controller_test.rb
> +    upl = UploadSummary::MeasureSummary.where(hqmf_id: '40280381-51F0-825B-0152-229B7B2F16F9').first
names :)

2016-11-28 14:06 UTC, edeyoung commented on test/functional/measures_controller_test.rb
> +    assert_equal 'CMS123v5', upl.measure_cms_id_after
do we need an assert for `measure_cms_id_before`?

2016-11-28 14:06 UTC, edeyoung commented on test/functional/measures_controller_test.rb
> +    collection_fixtures('records')
add comment explaining why you are doing this. Also, does this make sense to put in a `setup` operation so it's done for all tests?

2016-11-28 14:06 UTC, edeyoung commented on test/functional/measures_controller_test.rb
> +    upl = UploadSummary::MeasureSummary.where(hqmf_id: '40280382-5859-6598-0158-92BE72260A7E').first
name :)

2016-11-28 14:06 UTC, edeyoung commented on test/functional/measures_controller_test.rb
> +    # Go from two population sets to three
i don't think it's asserted anywhere above that there are 2 population sets. This should be added.

2016-11-28 14:06 UTC, edeyoung commented on test/functional/measures_controller_test.rb
> +    assert_equal 3, upl.population_set_summaries.count # Represents that there are 3 population sets
should this also check the before/after population set counts on the object?

2016-11-28 14:06 UTC, edeyoung commented on test/functional/measures_controller_test.rb
> +    assert_not_nil upl.population_set_summaries[2]['patients'][test_patient.id.to_s]['post_upload_results']
this assertion doesn't align with the comment. Clarify the comment.

2016-11-28 20:25 UTC, mulcahyk commented on lib/ext/measure_upload_summary.rb
> +        (measure.populations[-i].keys.to_a - ['id', 'title']).each { |population| missing_expected_values[population] = 0 }
I wasn't sure if the measure had the OBSERV_UNITS in it or not.

2016-11-28 20:27 UTC, mulcahyk commented on lib/ext/measure_upload_summary.rb
> +        measure_patients.each { |patient| new_population_set['patients'][patient.id.to_s] = {:expected => missing_expected_values} }
As it is `patient.id` is a BSON::ObjectId.  You have to make it a string to use it as a key.

2016-11-28 20:41 UTC, mulcahyk commented on test/functional/measures_controller_test.rb
> +    collection_fixtures('records')
This was left as a reminder of sorts that when we merge into `master` we need to switch to using the new call for loading fixtures.  
I'll remove it now and leave a `# TODO` to come back and change this.

2016-11-29 19:19 UTC, mulcahyk commented on test/functional/measures_controller_test.rb
> +    assert_equal 3, upl.population_set_summaries.count # Represents that there are 3 population sets
@edeyoung which *object* are you referring to here?

2016-11-29 19:24 UTC, edeyoung commented on test/functional/measures_controller_test.rb
> +    assert_equal 3, upl.population_set_summaries.count # Represents that there are 3 population sets
`upl`

it would be related to this type of thing:

```coffee
    measure_upload_summary.measure_population_set_count[:pre_upload] = before_upload_population_sets.count
    measure_upload_summary.measure_population_set_count[:post_upload] = measure.populations.count
```

2016-11-29 20:30 UTC, mulcahyk commented on test/functional/measures_controller_test.rb
> +    p = Record.where(first: 'John, III', measure_ids: 'C0D72444-7C26-4863-9B51-8080F8928A85').first
Yes, that is exactly it.  I have updated the comment.

2016-11-29 21:31 UTC, mulcahyk commented on lib/ext/measure_upload_summary.rb
> +        measure_patients.each { |patient| new_population_set['patients'][patient.id.to_s] = {:expected => missing_expected_values} }
per our conversation we are going to leave this as is for the time being.

2016-12-02 22:09 UTC, edeyoung approved these changes

2016-12-02 22:19 UTC, merged