Bonnie 158 create test tool
MeasureAuthoringTool/bonnie pull request #597
Opened 2016-11-29 14:49 UTC by alexanderelliott121

Creates a test framework for qrda export and a selection of fixtures.

2016-11-29 18:21 UTC, edeyoung commented
looks like there might be an issue with the config for running the tests in travis

2016-11-29 18:28 UTC, edeyoung requested changes

2016-11-29 18:28 UTC, edeyoung commented on test/functional/qrda_export_test.rb
> +  test "QRDA Export Test" do
add a high level comment here - iterating over the qrda test fixtures. compares output qrda with supplied qrda (or something along those lines)

2016-11-29 18:28 UTC, edeyoung commented on test/functional/qrda_export_test.rb
> +        HealthDataStandards::SVS::ValueSet.all.each do |vs|
add comment for why you need to do this step

2016-11-29 18:28 UTC, edeyoung commented on test/functional/qrda_export_test.rb
> +        tags_to_remove = ["ClinicalDocument id", "ClinicalDocument effectiveTime", "ClinicalDocument time"]
add comment explaining why these tags should be removed

2016-11-29 18:28 UTC, edeyoung commented on test/functional/qrda_export_test.rb
> +require 'test_helper'
consider adding a comment to the top of this about how the directories should be formed. For example, there should be one fixture (or XML) file in each leaf directory.

2016-11-29 18:29 UTC, edeyoung commented
@alexanderelliott121 is test/functional/qrda_export_test.rb the only file with logic in it?

2016-11-29 18:31 UTC, edeyoung commented
@mayerm94 @holmesie i'm interested in your thoughts. Alex and I had a long conversation about the directory structure for the tests. I think what he did makes a lot of sense but it shifts away from how this was done in other areas of the code.It allows you to simply iterate over the directory structures, which is really nice. I'm interested in what you guys think.

2016-11-29 18:34 UTC, alexanderelliott121 commented
@edeyoung 
Yes, qrda_export_test.rb is the only file with logic in it.

2016-11-29 18:34 UTC, alexanderelliott121 commented
Note, this is dependant on the hds changes before it will pass travis.

2016-11-30 18:17 UTC, alexanderelliott121 commented on test/functional/qrda_export_test.rb
> +        HealthDataStandards::SVS::ValueSet.all.each do |vs|
So, that's something that I put in when I was trying to fix the bson id problem and never removed.
It doesn't hurt, but it doesn't help either.

2016-12-30 01:37 UTC, edeyoung commented
This change has been incorporated in this pull request: https://github.com/projecttacoma/bonnie/pull/653

2016-12-30 01:39 UTC, edeyoung commented
Scratch my previous comment. the tool for generating fixtures is in pull request https://github.com/projecttacoma/bonnie/pull/653 but the new fixtures and tests for them is not.

2016-12-30 01:40 UTC, edeyoung requested changes
this likely needs some significant revisions to sit on top of the measure_history_rebase branch

2017-01-31 21:30 UTC, edeyoung commented
@alexanderelliott121 is there anything from this pull request that we should pull over? If not, should we close it (given the reset test generation code you completed)?

2017-10-11 15:39 UTC, edeyoung commented
closing. obsolete

2017-10-11 15:39 UTC, closed without merging