Measure History New Controllers Comments and Fixes
MeasureAuthoringTool/bonnie pull request #615
Opened 2016-12-09 20:13 UTC by hossenlopp

- Added comments to controllers and new routes
- Removed skip_before_action. This was bad copy pasting.
- Made it so limited attribute database calls include _id.
  - @mayerm94 showed me these being excluded are causing silent errors that appear in tests
- Removed extraneous routes to controller methods that don't exist.

2016-12-09 21:51 UTC, mulcahyk approved these changes

2016-12-12 11:33 UTC, mayerm94 commented on app/controllers/archived_measures_controller.rb
> +      # Fetch only hqmf_set_id of the measure so we can use it to grab the archived measures for that hqmf_set_id.
Fetch only hwmf_set_id **and** _id

2016-12-12 11:35 UTC, mayerm94 commented on app/controllers/upload_summaries_controller.rb
> +      # Fetch only hqmf_set_id of the measure so we can use it to grab the upload summaries for that hqmf_set_id.
Same as above, fetch hqmf_set_id **and** _id

2016-12-12 13:07 UTC, edeyoung commented on app/controllers/archived_measures_controller.rb
> +
this is very minor, but I actually find it confusing when there's a space between a function comment and the function itself. It makes me think the comment is not associated with the function. Is this a recommended style? If not, can you remove the extra space for all these function comments?

2016-12-12 13:32 UTC, edeyoung requested changes
address Matt's comments on the comments. Consider my comment about removing space between comments and functions.

2016-12-12 14:29 UTC, hossenlopp commented on app/controllers/archived_measures_controller.rb
> +
I was just following the RDoc style. https://github.com/rdoc/rdoc#writing-documentation

I don't like the space either, I was just trying to be correct.

2016-12-12 14:39 UTC, hossenlopp commented on app/controllers/archived_measures_controller.rb
> +      # Fetch only hqmf_set_id of the measure so we can use it to grab the archived measures for that hqmf_set_id.
FIXED in 5f1d6a57c84b46f0075fd445d4097ead7517bee6.

2016-12-12 14:39 UTC, hossenlopp commented on app/controllers/upload_summaries_controller.rb
> +      # Fetch only hqmf_set_id of the measure so we can use it to grab the upload summaries for that hqmf_set_id.
FIXED in 5f1d6a57c84b46f0075fd445d4097ead7517bee6.

2016-12-12 14:44 UTC, edeyoung commented on app/controllers/archived_measures_controller.rb
> +
Let's keep it then. Maybe at some point we'll make the rest of the files conform so it won't look as different (code debt task!).

2016-12-12 15:07 UTC, c-monkey commented on app/controllers/archived_measures_controller.rb
> +
The lazy programmer's solution here is probably the best. Have the team consent to a standard pretty printer format that can be automated. Once the configuration for the pretty printing is shared with the team, then we all conform at the press of a button.

2016-12-12 15:10 UTC, hossenlopp commented on app/controllers/archived_measures_controller.rb
> +
So... waiting on this PR until we decide a format? I thought we did the research months ago and chose RDoc.

2016-12-12 15:45 UTC, edeyoung commented on app/controllers/archived_measures_controller.rb
> +
@c-monkey can you clarify your comment?
@hossenlopp no, this is not on hold based on the comment format. Please keep the comments as they are.

2016-12-12 15:49 UTC, c-monkey commented on app/controllers/archived_measures_controller.rb
> +
Sorry! Wasn't trying to cause confusion, I was just musing that if the team agrees upon a format that can be automatically applied, then any member can be confident they are producing properly formatted code by running the pretty printer.

I am not advocating for any *particular* format, as long as it can be automated.

2016-12-12 15:51 UTC, hossenlopp commented on app/controllers/archived_measures_controller.rb
> +
Automated in what sense? Generating class documentation html pages or some other automation.

2016-12-12 16:02 UTC, c-monkey commented on app/controllers/archived_measures_controller.rb
> +
Lizzie's comment started off about the pretty printing of your comment itself (specifically a line of whitespace between the comment and the function declaration). That's just a formatting of the source code, not a formatting of the generated documentation! Oops, I can see why my feedback might be ambiguous. I don't want to configure RDoc, I assume the default format for that is preferable. I was only mentioning that user error formatting the source code can be fixed automatically with a code pretty printer.

2016-12-12 16:05 UTC, hossenlopp commented on app/controllers/archived_measures_controller.rb
> +
I don't know if it can. I don't even have a code pretty printer setup. 😕

2016-12-12 18:41 UTC, edeyoung approved these changes

2016-12-12 18:41 UTC, merged

2016-12-12 19:19 UTC, c-monkey commented on app/controllers/archived_measures_controller.rb
> +
Other more established languages do have easy pretty printing, but I don't see anything for Ruby with a cursory Google session. That sucks!

One could consider https://github.com/bbatsov/rubocop it seems okay. There is an Atom plugin (rubocop-auto-correct) for applying Rubocop changes automatically. It does some whitespace revisions, but doesn't care either way about spaces between RDoc blocks and the code. The Ruby style guide actually says to *not* have a space between them, but Rubocop doesn't seem to have support for enforcing that.

Certainly we need to table this issue for now, but if there were tension in the team over pretty printing, perhaps we should consider checking out Rubocop or something else.