Add test to ensure presence/absence of empty history warning
MeasureAuthoringTool/bonnie pull request #638
Opened 2016-12-22 19:34 UTC by mayerm94

Bonnie-268 Add test to ensure presence/absence of empty history warning depending on amount of uploadsummaries

2016-12-22 21:28 UTC, edeyoung requested changes

2016-12-22 21:28 UTC, edeyoung commented on spec/javascripts/views/measure_history_display_spec.js.coffee
> +    expect(@measure_history_view.$el.html()).not.toContain 'No history found.'
this test is being expanded past its original intent. I'd either create a new test to test that "no history found" shows up (preferred) or change the test description

2016-12-22 21:28 UTC, edeyoung commented on spec/javascripts/views/measure_history_display_spec.js.coffee
> +  beforeEach (done) ->
There's a lot of repetition here. Should this test file be structured more like:

```
describe 'MeasureHistoryView', ->
   
  beforeEach (done) ->
    jasmine.getJSONFixtures().clearCache()
    @mainView = new Thorax.LayoutView(el: '#bonnie')
    @measure = new Thorax.Models.Measure getJSONFixture('measure_data/measure_history_set/version_display/measures_frontend.json'), parse: true
    @patients = new Thorax.Collections.Patients()
    @patients.add(new Thorax.Models.Patient patientFixture) for patientFixture in getJSONFixture('records/measure_history_set/patients.json')

  describe 'with history', ->

    beforeEach (done) ->
      @uploadSummaries= new Thorax.Collections.UploadSummaries([], {measure_id: @measure.id, _fetched: true})
      @uploadSummaries.add(new Thorax.Models.UploadSummary uploadSummaryFixture) for uploadSummaryFixture in getJSONFixture('upload_summaries/measure_history_set/upload_summary.json')
      @measure.attributes.upload_summaries = @uploadSummaries
      @measure_history_view = new Thorax.Views.MeasureHistoryView model: @measure, patients: @patients, upload_summaries: @uploadSummaries
      @measure_history_view.on "rendered", ->
        done()
      @measure_history_view.render()

    it 'asdf' ->
      ...

  describe 'with no history', ->

    beforeEach (done) ->
      @uploadSummaries= new Thorax.Collections.UploadSummaries([], {measure_id: @measure.id, _fetched: true})
      @measure.attributes.upload_summaries = @uploadSummaries
      @measure_history_view = new Thorax.Views.MeasureHistoryView model: @measure, patients: @patients, upload_summaries: @uploadSummaries
      @measure_history_view.on "rendered", ->
        done()
      @measure_history_view.render()

    it 'asdf' ->
      ...
```

2016-12-22 21:28 UTC, edeyoung commented on spec/javascripts/views/measure_history_display_spec.js.coffee
> +    @measure = new Thorax.Models.Measure getJSONFixture('measure_data/measure_history_set/version_display/measures_frontend.json'), parse: true
this is the measure for things that don't require calculation. however, in a sense, it's an artifact of when we didn't know how to get things set up properly so the tests would be atomic. I'd like to move away from using this for new tests. I'd like to use the new infrastructure even if calculations aren't necessary.

because this will already be touched, can you update the pre-existing test as well to use the new infrastructure if it's trivial? If it's non-trivial, than we can do it later.

2016-12-22 22:21 UTC, c-monkey commented
So, I didn't see Lizzie's suggestion, but since Matt had gone home, I wrote it up and pushed it so we could discuss.

Then...I saw Lizzie was also concerned about the duplication...and I guess great minds think alike? 😅

2016-12-23 13:03 UTC, edeyoung commented
@c-monkey great! I like what you did! My suggestion wouldn't have actually worked now that I look at it again. I'm glad you were able to reduce the duplication and do something that did work!

2016-12-28 22:18 UTC, edeyoung requested changes

2016-12-28 22:18 UTC, edeyoung commented on spec/javascripts/views/measure_history_display_spec.js.coffee
> +    jasmine.getJSONFixtures().clearCache()
this line is embedded in the measureHistorySpecLoader (because it loads through the bonnieroutercache, which does this) and is not necessary here.

2016-12-28 22:18 UTC, edeyoung commented on spec/javascripts/views/measure_history_display_spec.js.coffee
> +      @uploadSummaries = new Thorax.Collections.UploadSummaries([], {measure_id: @measure.id, _fetched: true})
rather than clear out the upload summaries, should this do `window.measureHistorySpecLoader.loadWithoutHistory`?

This is probably a more accurate approach because really, there should be a single upload summary that only has "post upload" information and no "pre-upload" information.

2016-12-28 22:18 UTC, edeyoung commented on spec/javascripts/views/measure_history_display_spec.js.coffee
> +      expect(@uploadSummaries.length).toEqual 0
this should actually be 1 because there should be an upload summary from the initial upload (see previous comment)

2016-12-28 22:18 UTC, edeyoung commented on spec/javascripts/views/measure_history_display_spec.js.coffee
> +      expect(@measure_history_view.$el.html()).toContain 'No history found.'
this should still be accurate even with the initial upload summary present.

2016-12-28 22:18 UTC, edeyoung commented on spec/javascripts/views/measure_history_display_spec.js.coffee
> +    it 'has length two', ->
change description

2016-12-29 13:17 UTC, edeyoung approved these changes

2016-12-29 13:20 UTC, merged