Bonnie 402 backbone 404 page routing
MeasureAuthoringTool/bonnie pull request #665
Opened 2017-01-11 17:46 UTC by mayerm94

Add default route to page not found error page and also route to the page not found page when a page for a non existent resource is requested. Handlebars template and Thorax view are added for the error page.

2017-01-11 20:16 UTC, edeyoung requested changes
Overall looks really good. some minor changes requested.

2017-01-11 20:16 UTC, edeyoung commented on app/assets/javascripts/router.js.coffee
> +      # show loading view because this data is loaded async. Show breadcrumb now so people know where they are heading.
this comment got moved around. recommend moving it back above line 115

2017-01-11 20:16 UTC, edeyoung commented on app/assets/javascripts/router.js.coffee
> +          .fail( => @showError title: "Measure History Load Failed", summary: "Historic data failed to load due to a server error." )
indentation looks like it got messed up in the copy/paste

2017-01-11 20:16 UTC, edeyoung commented on app/assets/javascripts/router.js.coffee
> +    '*path':                                            'showPageNotFound'
consider adding a comment explaining that this catches any unspecified routes.

(nice addition, by the way)

2017-01-11 20:16 UTC, edeyoung commented on app/assets/javascripts/templates/error_view.hbs
> +<div class="error-page">
@thecristen does this page need any 508 tags added to it or is the included text sufficient?

2017-01-11 20:16 UTC, edeyoung commented on spec/javascripts/views/patient_builder_spec.js.coffee
> +    bonnie.renderPatientBuilder('non_existant_hqmf_set_id',@patient.id)
include a space after the comma. same in other parts of the code.

2017-01-13 13:53 UTC, thecristen approved these changes

2017-01-13 13:53 UTC, thecristen commented on app/assets/javascripts/templates/error_view.hbs
> +<div class="error-page">
@edeyoung The included text is sufficient! 👍🏼

2017-01-13 17:57 UTC, edeyoung approved these changes

2017-01-13 18:01 UTC, merged

2017-01-25 18:46 UTC, holmesie commented on app/assets/javascripts/templates/error_view.hbs
> +    <img src="/assets/Rabbit-96-blue.png" alt = "">
This won't work on production deployments of Rails, see: http://guides.rubyonrails.org/asset_pipeline.html#what-is-fingerprinting-and-why-should-i-care-questionmark