BONNIE-163 Overlap support for attribute value sets
MeasureAuthoringTool/bonnie pull request #666
Opened 2017-01-13 03:15 UTC by c-monkey

Added https://jira.mitre.org/browse/BONNIE-431 for missing test that requires a new fixture

2017-01-13 17:53 UTC, edeyoung requested changes

2017-01-13 17:53 UTC, edeyoung commented on app/assets/javascripts/views/measure_value_sets.js.coffee
> +  _createValueSet: (objectProp, name) ->
Consider using a more descriptive name for `objectProp` or, if that's hard to do because it could be a data criteria or attribute, describe what it is in the function comment.

2017-01-13 17:53 UTC, edeyoung commented on app/assets/javascripts/views/measure_value_sets.js.coffee
> +    objectProp.cid ?= "fake#{@fakeIndex++}"
consider re-describing the purpose of `fakeIndex` here.

2017-01-13 18:59 UTC, c-monkey commented
For demonstration purposes, check out these measures:

- CMS128 shows only data criteria (DC) and supplemental data elements (SDE)
- CMS154 shows DC, SDE, and overlapping value sets (OVS)
- CMS53V5 (original issue logged about this measure) shows DC, SDE, attribute value sets (AVS), and OVS that are from AVS
- CMS160V5 shows DC, SD, and AVS

2017-01-15 15:21 UTC, edeyoung approved these changes

2017-01-15 15:32 UTC, merged