Bonnie 410 update fixtures tool
MeasureAuthoringTool/bonnie pull request #667
Opened 2017-01-17 14:34 UTC by alexanderelliott121

Updates the fixture generation tool to create frontend fixtures, updates backend fixture generation signature to be more streamlined/generalized.

2017-01-17 15:54 UTC, mayerm94 requested changes

2017-01-17 15:54 UTC, mayerm94 commented on lib/tasks/generate_fixtures.rake
> +      user = User.find_by email: args[:user_email]
Should probably end if user is not found

2017-01-17 15:54 UTC, mayerm94 commented on lib/tasks/generate_fixtures.rake
> +      end
Indent

2017-01-17 15:54 UTC, mayerm94 commented on lib/tasks/generate_fixtures.rake
> +      us_filename = "#{args[:test_name]}.json"
Why is the upload_summaries filename named after an argument but the archived_measures, value_sets and measures are named after what they contain, ie: measures.json, archived_measures.json and value_sets.json

2017-01-17 15:54 UTC, mayerm94 commented on lib/tasks/generate_fixtures.rake
> +        measure = user.measures.find_by(cms_id: args[:measure_id])
Getting the user and determining if the cms_hqmf arg is a cms_id or hqmf_id seems to be repeated code between rake tasks. Perhaps it could be moved to it's own function

2017-01-17 16:41 UTC, alexanderelliott121 commented on lib/tasks/generate_fixtures.rake
> +      us_filename = "#{args[:test_name]}.json"
This is a weird one.
At the moment, the infrastructure we have looks upload_summaries in a specific way: it expects three files called initialLoad, update1 and update2.
I'm not adverse to changing this or updating the load tool, but I decided not to change the existing structures in this branch.

2017-01-18 12:25 UTC, alexanderelliott121 commented on lib/tasks/generate_fixtures.rake
> +      user = User.find_by email: args[:user_email]
It does, mongoid error.

2017-01-18 13:11 UTC, mayerm94 approved these changes

2017-01-18 14:14 UTC, edeyoung commented on lib/tasks/generate_fixtures.rake
> +      elsif (cms_hqmf == 'hqmf')
should this also be `downcase`?

2017-01-18 14:42 UTC, edeyoung requested changes
Please excuse my brevity. rushed the comments. i'm curious about the resulting file structure. let's discuss. i'm also curious because the fixtures for front and back end seem the same other than being in an array or separate. i thought there were differences. does it turn out there aren't?

2017-01-18 14:42 UTC, edeyoung commented on lib/tasks/generate_fixtures.rake
> +      elsif (cms_hqmf == 'hqmf')
or maybe these should be exact matches? you have a nice error message if they're not. then we don't downcase anything.

2017-01-18 14:42 UTC, edeyoung commented on lib/tasks/generate_fixtures.rake
> +    # cms_hqmf: Use cms or hqmf id.
Change comment to "indicates if a CMS id or an HQMF id is used"

2017-01-18 14:42 UTC, edeyoung commented on lib/tasks/generate_fixtures.rake
> +    # path: Fixture path.
Change to "path to output fixture files" or something similarly more explanatory

2017-01-18 14:42 UTC, edeyoung commented on lib/tasks/generate_fixtures.rake
> +    # test_name: Name of the test the fixture is for.
What about `test_type`? That makes this seem more generalizable. I'd like to use the same set of fixtures across multiple tests as long as I want similar sort of behavior (e.g. proportion measure with multiple populations).

2017-01-18 14:42 UTC, edeyoung commented on lib/tasks/generate_fixtures.rake
> +    # measure_id: id of measuer to export
should we mention that the measure needs to be contained in user_email's account?

2017-01-18 14:42 UTC, edeyoung commented on lib/tasks/generate_fixtures.rake
> +    # user_email: email of user to export
should we also add something about this being the account that will be used for patients/measure/etc.?

2017-01-18 14:42 UTC, edeyoung commented on lib/tasks/generate_fixtures.rake
> +    ###
Can you confirm that this comment follows ruby comment guidance? Talk with Hoss for where to find the guidance. Most of our comments don't follow this, but since this is so comprehensive and for an important rake task, I think it would be good to follow the guidance here.

2017-01-18 14:42 UTC, edeyoung commented on lib/tasks/generate_fixtures.rake
> +    # bundle exec rake HDS:test:generate_fixtures[cms,test/CMSFakevFake,initialLoad,fake@fake,CMSFakevFake]
Can you note that this is an example usage?
Can you use real-ish data? the "FakevFake" is hard to parse.
To ensure there are no typos, it would be good to use an example that you were actually able to execute on your machine.

2017-01-18 14:42 UTC, edeyoung commented on lib/tasks/generate_fixtures.rake
> +    # bundle exec rake HDS:test:generate_fixtures[cms,test/CMSFakevFake,initialLoad,fake@fake,CMSFakevFake]
Also, please add spaces after the commas for readability.

2017-01-18 14:42 UTC, edeyoung commented on lib/tasks/generate_fixtures.rake
> +      cms_dir = File.join(args[:test_name], args[:measure_id])
why is this called `cms_dir`? Should this be `output_dir` or something similar?

2017-01-18 14:42 UTC, edeyoung commented on lib/tasks/generate_fixtures.rake
> +      cms_dir = File.join(args[:test_name], args[:measure_id])
for `test_name` may be worth adding to the comment above that this will be used to build the path to the tests along with the `path` argument.

2017-01-18 14:42 UTC, edeyoung commented on lib/tasks/generate_fixtures.rake
> +      measure_file = File.join(fixtures_path, 'measure_data', args[:path], cms_dir, 'measures.json')
add a comment above this along the lines of "generating the fixtures for the measure. these go in a `measure_data` parent directory. the measure file is called `measures.json`. The accompanying value sets file is called `value_sets.json`"

2017-01-18 14:42 UTC, edeyoung commented on lib/tasks/generate_fixtures.rake
> +      value_sets = measure.value_sets.each do |vs|
move this value set stuff up to the measure stuff to create cohesion in where things are being generated.

2017-01-18 14:42 UTC, edeyoung commented on lib/tasks/generate_fixtures.rake
> +      records = Record.by_user_and_hqmf_set_id(user, measure.hqmf_set_id)
isn't the fixture for a record a bit different on the front end than the back end?

2017-01-18 14:42 UTC, edeyoung commented on lib/tasks/generate_fixtures.rake
> +      records = Record.by_user_and_hqmf_set_id(user, measure.hqmf_set_id)
add a similar high level comment as described above to this patient section.

2017-01-18 14:42 UTC, edeyoung commented on lib/tasks/generate_fixtures.rake
> +      us_filename = "#{args[:test_name]}.json"
rename to upload_summaries_filename or something similar. `us` is confusing.

2017-01-18 14:42 UTC, edeyoung commented on lib/tasks/generate_fixtures.rake
> +      measure_summaries = UploadSummary::MeasureSummary.by_user_and_hqmf_set_id(user, measure.hqmf_set_id).first
consider moving these declarations down to where the fixtures get generated for them.

2017-01-18 14:42 UTC, edeyoung commented on lib/tasks/generate_fixtures.rake
> +    ###
consider adding to the comments a comment outlining what the file structure will look like after this is run.

2017-01-18 14:42 UTC, edeyoung commented on lib/tasks/generate_fixtures.rake
> +    ###
also consider adding an explanation on where each of these files should go in the actual spec file structure.

what happened to making these be in one collective space so you wouldn't have to move individual files?

2017-01-18 14:42 UTC, edeyoung commented on lib/tasks/generate_fixtures.rake
> +    task :generate_fixtures, [:cms_hqmf, :path, :user_email, :measure_id] => [:environment] do |t, args|
should this be renamed to "generate_backend_fixtures"?

2017-01-18 14:42 UTC, edeyoung commented on lib/tasks/generate_fixtures.rake
> +    # measure_id: id of measuer to export
see all comments above re making comments more explanatory.

2017-01-18 14:42 UTC, edeyoung commented on lib/tasks/generate_fixtures.rake
> +        rec_name = rec.first + "_" + rec.last + ".json"
the first and last names often have spaces in them. does it make sense (as painful as it is) to use a space here instead of an underscore?

2017-01-18 14:42 UTC, edeyoung commented on lib/tasks/generate_fixtures.rake
> +    desc "Exports a set of fixtures that can be loaded for testing purposes"
it seems like there is some repeated code in here. Is it worth refactoring to reduce repeated code?

2017-01-24 00:27 UTC, edeyoung requested changes
Hey, it looks like several of my comments were missed. github is doing weird stuff which is making  me wonder if maybe they didn't show up. If they did show up and you disagreed with them so didn't implement them, can you make sure to respond to the comment noting that? Thanks!

2017-01-24 00:27 UTC, edeyoung commented on lib/tasks/generate_fixtures.rake
> +          elsif k == '_id' || k == 'bundle_id' || k == 'user_id'
does this cause an issue with `cms_id`?

2017-01-24 00:27 UTC, edeyoung commented on lib/tasks/generate_fixtures.rake
> +    def collection_fixtures(*collection_names)
are these duplicated from elsewhere in the code? if so, can these just call that code? if not, please add a comment explaining why the duplication was necessary.

2017-01-24 00:27 UTC, edeyoung commented on lib/tasks/generate_fixtures.rake
> +    # bundle exec rake HDS:test:generate_frontend_fixtures[cms,test/CMSFakevFake,initialLoad,fake@fake,CMSFakevFake]
`HDS:test:` got changed to `bonnie:fixtures` above

2017-01-24 00:27 UTC, edeyoung commented on lib/tasks/generate_fixtures.rake
> +    # bundle exec rake HDS:test:generate_frontend_fixtures[cms,test/CMSFakevFake,initialLoad,fake@fake,CMSFakevFake]
try using real data for the example. the fake data is hard to read.

2017-01-24 00:27 UTC, edeyoung commented on lib/tasks/generate_fixtures.rake
>      # user_email: email of user to export
from previous review: "should we also add something about this being the account that will be used for patients/measure/etc.?"

2017-01-24 00:27 UTC, edeyoung commented on lib/tasks/generate_fixtures.rake
>      # measure_id: id of measuer to export
from previous review: "should we mention that the measure needs to be contained in user_email's account?
 Show outdated"

2017-01-24 00:27 UTC, edeyoung commented on lib/tasks/generate_fixtures.rake
> +    # bundle exec rake HDS:test:generate_frontend_fixtures[cms,test/CMSFakevFake,initialLoad,fake@fake,CMSFakevFake]
from the previous review: 
Can you note that this is an example usage?
Can you use real-ish data? the "FakevFake" is hard to parse.
To ensure there are no typos, it would be good to use an example that you were actually able to execute on your machine.

2017-01-24 00:27 UTC, edeyoung commented on lib/tasks/generate_fixtures.rake
>        archived_measures = ArchivedMeasure.by_user_and_hqmf_set_id(user, measure.hqmf_set_id)
from previous review: consider moving these declarations down to where the fixtures get generated for them.
 Hide outdated

2017-01-24 00:27 UTC, edeyoung commented on lib/tasks/generate_fixtures.rake
> +      measure_file = File.join(fixtures_path, 'measure_data', args[:path], 'measures.json')
from previous review: add a comment above this along the lines of "generating the fixtures for the measure. these go in a measure_data parent directory. the measure file is called measures.json. The accompanying value sets file is called value_sets.json"

2017-01-24 00:27 UTC, edeyoung commented on lib/tasks/generate_fixtures.rake
> +      records = Record.by_user_and_hqmf_set_id(user, measure.hqmf_set_id)
from previous review: add a similar high level comment as described above to this patient section.
 Show outdated

2017-01-24 16:12 UTC, alexanderelliott121 commented on lib/tasks/generate_fixtures.rake
> +          elsif k == '_id' || k == 'bundle_id' || k == 'user_id'
Nope

2017-01-24 16:14 UTC, edeyoung commented on lib/tasks/generate_fixtures.rake
> +          elsif k == '_id' || k == 'bundle_id' || k == 'user_id'
why not?

2017-01-24 16:18 UTC, alexanderelliott121 commented on lib/tasks/generate_fixtures.rake
> +          elsif k == '_id' || k == 'bundle_id' || k == 'user_id'
k == '_id' isn't a regex, so it doesn't recognize/convert the cms_id.
cms_id isn't a bson object, so no conversion is required.

2017-01-31 13:47 UTC, edeyoung commented
@alexanderelliott121 

I do not seem to be able to login to the bonnie user after I wipe my db.

please check out my very minor changes.

2017-01-31 14:04 UTC, edeyoung approved these changes

2017-01-31 14:26 UTC, merged