Bonnie 273 patient history test
MeasureAuthoringTool/bonnie pull request #668
Opened 2017-01-17 16:36 UTC by alexanderelliott121

Adds a test to ensure that newly created patients have no history.

2017-01-18 18:25 UTC, edeyoung requested changes

2017-01-18 18:25 UTC, edeyoung commented on test/functional/patients_controller_test.rb
>      assert_equal "pass", r.calc_results[0]['status'], "Checking that calc_status worked."
this line only looks at the `calc_results` status. Can you also check the values for each population?

2017-01-18 18:25 UTC, edeyoung commented on test/functional/patients_controller_test.rb
> +    assert_equal nil, UploadSummary::PopulationSetSummary.first
I'm unclear on why this assertion belongs here. Can you explain?

2017-01-18 18:25 UTC, edeyoung commented on test/functional/patients_controller_test.rb
> +    assert_equal nil, UploadSummary::PopulationSetSummary.first
These are all the new fields added for measure history:

```
  field :calc_results, type: Array, default: []
  field :has_measure_history, type: Boolean, default: false # has the record gone through an update to the measure
  field :results_exceed_storage, type: Boolean, default: false # True when the size of calc_results > 12000000
  field :condensed_calc_results, type: Array
  field :results_size, type: Integer
```

Can you check that each exists and has the appropriate value?

2017-01-25 19:36 UTC, alexanderelliott121 commented on test/functional/patients_controller_test.rb
> +    assert_equal nil, UploadSummary::PopulationSetSummary.first
Fields have been added

2017-01-25 19:37 UTC, alexanderelliott121 commented on test/functional/patients_controller_test.rb
> +    assert_equal nil, UploadSummary::PopulationSetSummary.first
My original thought was that the PopulationSetSummary contained patient upload history.
Its inclusion is an error.

2017-01-27 14:32 UTC, edeyoung commented on test/functional/patients_controller_test.rb
> +    assert_equal nil, UploadSummary::PopulationSetSummary.first
should this be more like `UploadSummary::PopulationSetSummary.where(...)` and we give it the appropriate info to find the patient?

Or, if you're comfortable that we know that state (that it's basically an empty DB with no measure uploaded/updated that have patients associated with them), can you add a comment noting that?

Other than this, this PR looks good! once this gets updated I'll pull it in!

2017-01-31 01:34 UTC, edeyoung approved these changes

2017-01-31 13:34 UTC, merged