add tests for measure history timeline patient display
MeasureAuthoringTool/bonnie pull request #669
Opened 2017-01-18 18:22 UTC by thecristen

2017-01-18 20:10 UTC, edeyoung requested changes
i like the `does show current patients` test. I think the `does *not* show new patients` may need to be reworked.

2017-01-18 20:10 UTC, edeyoung commented on spec/javascripts/views/measure_history_display_spec.js.coffee
> +    it 'does *not* show new patients', ->
I don't think this method of adding new patients exercises the functionality being tested. I believe that this view checks if `has_measure_history` is true on the patient. If so, it displays it. Here, `new_clone` actually does have `has_measure_history` as true. I think you may need to create the new patient (I think as you did here is ok for `new_patient`), associate it with the measure, and then create a new instance of measure history to check that it's not showing the new patient. It may also be worth adding `new_clone` as you have here, but expecting that to show up (because `has_measure_history` is true).

@hossenlopp can you add your thoughts on how to appropriately test this?

2017-01-24 16:22 UTC, hossenlopp commented on spec/javascripts/views/measure_history_display_spec.js.coffee
> +    it 'does *not* show new patients', ->
`has_measure_history` is not used by the measure history timeline view or template. It looks through all of the upload summaries to collect the list of patients. If a patient (found by id) is not in an upload summary, then it will not be in the `@patientIndex` that is used to populate the template.

I think this test is very close. I have two suggestions:
- The two added patients should have specific `_id`s that are not in any of the upload summaries and unique so they will not be included in `@patientIndex`.
- Create the MeasureHistoryView from scratch to ensure it is redoing all of its initialization.
  - The correct result you have now is happening simply because the loadHistory function is not being called again. Its code is what needs to be tested.

2017-01-31 15:45 UTC, edeyoung commented on spec/javascripts/views/measure_history_display_spec.js.coffee
> +    it 'does *not* show new patients', ->
I think the patients may also need to be added to the measure and have the measure hqmf_set_id referenced in `measure_ids` on the patient

2017-02-09 22:10 UTC, thecristen commented on spec/javascripts/views/measure_history_display_spec.js.coffee
> +        @measure.get('patients').push [patient]
You shouldn't need to loop through the patients; you can add them the same way as in line 80 (adding models to a Thorax.Collection):

```coffeescript
@measure.get('patients').add [@new_patient, @new_clone]
```

2017-02-10 11:40 UTC, edeyoung commented on spec/javascripts/views/measure_history_display_spec.js.coffee
> +        @measure.get('patients').push [patient]
I second cristen's comment. additionally, looping through this way, you're re-adding patients that are already on the measure (if the measure history fixture loader does things correctly).

2017-02-10 11:43 UTC, edeyoung requested changes

2017-02-10 11:43 UTC, edeyoung commented on spec/javascripts/views/measure_history_display_spec.js.coffee
> +        expect(@measure_history_view.$('th[class="history-patient-header"]').length).not.toEqual 4
you can just check that it equals 2

2017-02-10 11:43 UTC, edeyoung commented on spec/javascripts/views/measure_history_display_spec.js.coffee
> +        @measure.get('patients').push [patient]
we talked about you editing the spec loader so that it properly adds patients to the measure. that code is located here: spec/javascripts/helpers/measure_history_spec_loader. after line 52, you can add something along the lines of:

```
measure.set('patients', patients)
```

2017-02-14 13:51 UTC, edeyoung commented on spec/javascripts/views/measure_history_display_spec.js.coffee
> +      @measure.get('patients').add [@new_patient, @new_clone]
the patient's measure ids also need to be reset (didn't think of this when we were talking).

For example (untested):

```
@new_patient.set('measure_ids', [@measure.get('hqmf_set_id'), null])
@new_clone.set('measure_ids', [@measure.get('hqmf_set_id'), null])
```

2017-02-14 15:11 UTC, mulcahyk commented on spec/javascripts/views/measure_history_display_spec.js.coffee
> +      @measure.get('patients').add [@new_patient, @new_clone]
The patients already have their `measures_ids` set.  In fact it looks like the patients in this test are portfolio patients in that they have multiple `measure_ids`.

2017-02-14 16:22 UTC, edeyoung commented on spec/javascripts/views/measure_history_display_spec.js.coffee
> +      @measure.get('patients').add [@new_patient, @new_clone]
i don't think they're necessarily set to the current measure. you can clear it out and reset it to the current measure (which is what the example code i gave you would do).

2017-02-16 12:43 UTC, edeyoung approved these changes

2017-02-16 14:56 UTC, mulcahyk approved these changes
I'm approving the work that Cristen and Chris H. did.

2017-02-16 18:56 UTC, hossenlopp requested changes
A few small changes, mainly casing of variables. This test is a bit odd since it does a lot of things that test the template instead of the view. Not sure if that is normal/expected or not.

2017-02-16 18:56 UTC, hossenlopp commented on spec/javascripts/views/measure_history_display_spec.js.coffee
> +      @new_patient.set('measure_ids', [@measure.get('hqmf_set_id'), null])
The `null` at the end of the array shouldn't be needed. I don't why bonnie adds that to all `measure_ids` arrays.

2017-02-16 18:56 UTC, hossenlopp commented on spec/javascripts/views/measure_history_display_spec.js.coffee
> +      @measure.get('patients').add [@new_patient, @new_clone]
That `null` at the end of the array in @edeyoung's example shouldn't be needed. I don't know why bonnie adds that.

2017-02-16 18:56 UTC, hossenlopp commented on spec/javascripts/views/measure_history_display_spec.js.coffee
> +        # Confirm that the number of uploadSummaries hasn't changed
This comment doesn't match the check that is being done below it. It is checking the first (and only?) upload summary has only two patients in it's record.

2017-02-16 18:56 UTC, hossenlopp commented on spec/javascripts/views/measure_history_display_spec.js.coffee
> +        expect(@measure_history_view.$('th[class="history-patient-header"]').length).toEqual 2
Same as above. This could look at the `patientIndex` of the MeasureHistoryTimelineView.

2017-02-16 18:56 UTC, hossenlopp commented on spec/javascripts/views/measure_history_display_spec.js.coffee
>      suite.measure_history_view = new Thorax.Views.MeasureHistoryView
`measure_history_view` should be camelcase.

2017-02-16 18:56 UTC, hossenlopp commented on spec/javascripts/views/measure_history_display_spec.js.coffee
> +      @new_patient = new Thorax.Models.Patient getJSONFixture('records/base_set/patients.json')[0], parse: true
`@new_patient` and `@new_clone` should both be camelcase.

2017-02-16 18:56 UTC, hossenlopp commented on spec/javascripts/views/measure_history_display_spec.js.coffee
> +      expect(@measure_history_view.$('th[class="history-patient-header"]').length).toEqual 2
To check the number of patients, it would be easier to look at the data that the template is using than to look at the resultant DOM. The MeasureHistoryTimelineView has a member `patientIndex` that could be checked. ex:

```coffeescript
expect(@measure_history_view.measureTimelineView.patientIndex.length).toEqual 2
```

Unless the point of this suite is to test the template too, then ignore me.

2017-02-16 18:56 UTC, hossenlopp commented on spec/javascripts/views/measure_history_display_spec.js.coffee
> +        for population_set_summary in us.get('population_set_summaries')
This test would fail if there is more than one population set because only one is rendered at a time. I think it should specifically look at the 0th population set instead of all of them.

2017-02-20 19:25 UTC, mulcahyk commented on spec/javascripts/views/measure_history_display_spec.js.coffee
> +      expect(@measure_history_view.$('th[class="history-patient-header"]').length).toEqual 2
I didn't write the initial version of this test.  I'm going to err on the of caution here and say we leave it as is given that this test is more extensive.  I can also be easily convinced that it should be changed.

2017-02-21 15:47 UTC, hossenlopp approved these changes

2017-02-21 18:34 UTC, merged