Bonnie 335
MeasureAuthoringTool/bonnie pull request #670
Opened 2017-01-19 22:52 UTC by mulcahyk

Test baseline functionality for simple measure (proportion with a single population set).

Created a test for measure history related measures where the tests themselves are defined as methods and then those methods are "applied" to the measure.

2017-01-23 20:37 UTC, mayerm94 commented
The CI tests for this pull request should pass once https://github.com/projecttacoma/bonnie/pull/671 is merged into master and this branch is rebased onto master. OR you could rebase onto  BONNIE-440-Remove-Console-Errors

2017-01-24 00:28 UTC, edeyoung commented
#671 has been merged into master.
@mulcahyk can you do the rebase so these pass?

2017-01-24 00:29 UTC, edeyoung commented on test/fixtures/records/measure_history_set/base_example/patient_1.json
> +  "_id": { "$oid": "58514916e76e941a3d000489"},
@alexanderelliott121 it looks like kristian added this here so the id would parse nicely. is this something that you can ensure in the fixture generation code?

2017-01-24 01:02 UTC, edeyoung requested changes
I have more to review.

This is looking very good! I have some minor comments but nothing major.

2017-01-24 01:02 UTC, edeyoung commented on test/functional/measures_controller_measure_history_granular_test.rb
> +    FileUtils.rm_r @error_dir if File.directory?(@error_dir)
is `@error_dir` used anywhere? can these lines be deleted?

2017-01-24 01:02 UTC, edeyoung commented on test/functional/measures_controller_measure_history_granular_test.rb
> +    dump_database
It looks like the upper code is temporary code as a place holder until the fixtures get re-generated (makes sense). Can you add a comment explaining that? it will help remind us to do the update.

2017-01-24 01:02 UTC, edeyoung commented on test/functional/measures_controller_measure_history_granular_test.rb
> +require 'test_helper'
thoughts on moving this into `meaures_controller_measure_history_test`?

2017-01-24 01:02 UTC, edeyoung commented on test/functional/measures_controller_measure_history_granular_test.rb
> +    assert_equal '40280381-4555-E1C1-0145-DC7DC26A44BF', measure.hqmf_id
what about adding an `hqmf_set_id` assert here? the above assertion that the measure is not yet loaded uses the `hqmf_set_id`. Using it here would directly demonstrate the counter to the previous test.

2017-01-24 01:02 UTC, edeyoung commented on test/functional/measures_controller_measure_history_granular_test.rb
> +    assert_equal '40280381-51F0-825B-0152-227DFBAC15AA', measure[:hqmf_id]
same comment here about checking `hqmf_set_id`.

also, i like things parallel. above, there's `measure.hqmf_id`. here, there's `measure[:hqmf_id]`. these should be the same.

2017-01-24 01:02 UTC, edeyoung commented on test/functional/measures_controller_measure_history_granular_test.rb
> +  test 'measure archiving' do
is there any point to doing this for each measure type? i'm leaning toward no. curious in what you think.

2017-01-24 01:02 UTC, edeyoung commented on test/functional/measures_controller_measure_history_granular_test.rb
> +    # Load version 1 of the measure. Starts with two population sets
i don't think this comment is necessary

2017-01-24 01:02 UTC, edeyoung commented on test/functional/measures_controller_measure_history_granular_test.rb
> +    # Load version 1 of the measure. Starts with two population sets
I don't think this comment is necesary

2017-01-24 01:02 UTC, edeyoung commented on test/functional/measures_controller_measure_history_granular_test.rb
> +    assert_equal '40280381-4555-E1C1-0145-DC7DC26A44BF', measure.hqmf_id
same thought as above with `hqmf_set_id`

2017-01-24 01:02 UTC, edeyoung commented on test/functional/measures_controller_measure_history_granular_test.rb
> +    # Assert that there is information for the "post" upload portion
can you add to the comment something like, "and there is no "pre" upload portion."

2017-01-24 01:02 UTC, edeyoung commented on test/functional/measures_controller_measure_history_granular_test.rb
> +    # Move on if there are no patients associated with this measure for this user
didn't we just load patients? if there are no patients, should we error out?

2017-01-24 01:02 UTC, edeyoung commented on test/functional/measures_controller_measure_history_granular_test.rb
> +      patient.save!
is this being unset and saved to ensure that the latest calc results are used? if so, can you add that in a comment. If not, can you comment on why calc results are being unset?

2017-01-24 01:02 UTC, edeyoung commented on test/functional/measures_controller_measure_history_granular_test.rb
> +      next
what is being `next`ed out of?

2017-01-24 01:02 UTC, edeyoung commented on test/functional/measures_controller_measure_history_granular_test.rb
> +      begin
we don't want a rescue here. we want to explicitly fail in our test if something unexpected happens.

2017-01-24 01:02 UTC, edeyoung commented on test/functional/measures_controller_measure_history_granular_test.rb
> +      patients.no_timeout.each_with_index do |patient, patient_index|
`no_timeout` shouldn't be necessary here. we have a controlled small set of patients.

2017-01-24 01:02 UTC, edeyoung commented on test/functional/measures_controller_measure_history_granular_test.rb
> +        # For some reason, patients show up multiple times during this iteration.
we don't need to do this check here.

2017-01-24 01:02 UTC, edeyoung commented on test/functional/measures_controller_measure_history_granular_test.rb
> +        begin
no rescues for the test.

2017-01-24 01:02 UTC, edeyoung commented on test/functional/measures_controller_measure_history_granular_test.rb
> +    measure = Measure.where(hqmf_id: '40280381-51F0-825B-0152-227DFBAC15AA', user_id: @user.id).first
should this be accessed with `cms_id` like it is earlier?

2017-01-24 01:02 UTC, edeyoung commented on test/functional/measures_controller_measure_history_granular_test.rb
> +    assert_equal '40280381-51F0-825B-0152-227DFBAC15AA', measure.hqmf_id
see above re checking `hqmf_set_id`

2017-01-24 01:02 UTC, edeyoung commented on test/functional/measures_controller_measure_history_granular_test.rb
> +    assert_equal 2, upload_summary.population_set_summaries[0][:summary][:pass_before]
in a perfect world, one fixture would pass before and fail after. although, this might be the measure that is so simple that there are no changes across versions.

2017-01-24 14:19 UTC, edeyoung requested changes
I still have a bit more to review.

as stated earlier, looks good! the comments are pretty minor. My biggest thoughts: watch your copy/pasting and determine what actually should be included; watch your whitespace; make your comments explain the why as well as the what.

2017-01-24 14:19 UTC, edeyoung commented on test/functional/measures_controller_measure_history_granular_test.rb
> +    # Test the patient fields
add whitespace here

2017-01-24 14:19 UTC, edeyoung commented on test/functional/measures_controller_measure_history_granular_test.rb
> +    measure_patients_post_upload = Record.where(measure_ids: '9A032D9C-3D9B-11E1-8634-00237D5BF174', user_id: @user.id)
is it worth making this an array too so it can be accessed in the same way as the`measure_patients_pre_upload`?

2017-01-24 14:19 UTC, edeyoung commented on test/functional/measures_controller_measure_history_granular_test.rb
> +      assert_equal 8, patient.count
can you add a comment here? It seems odd to check the count of a hash. is the idea to ensure that you don't have any more fields than the fields that you are testing for?

2017-01-24 14:19 UTC, edeyoung commented on test/functional/patient_expected_and_calc_values_test.rb
> +  # TODO: See if the can be set to tests Record
reword comment - doesn't make sense as is.

2017-01-24 14:19 UTC, edeyoung commented on test/functional/patient_expected_and_calc_values_test.rb
> +    # Load the measure
add whitespace above this line.

2017-01-24 14:19 UTC, edeyoung commented on test/functional/patient_expected_and_calc_values_test.rb
> +    measure_file = fixture_file_upload(File.join('test', 'fixtures', 'measure_exports', 'measure_history_set', 'base_example', 'CMS68v6.zip'), 'application/zip')
This also needs to be changed in measures_controller_measure_history:

`calculation_type` should be `patient` or `episode`. You are currently using `proportional`.

For CMS68: should be `episode` with `Occurrence A of Encounter, Performed: Medications Encounter Code Set` (or closest if this is encompassed by a variable)
For CMS160: should be `patient`
For CMS104: should be `episode` with `Encounter, Performed: Non-Elective Inpatient Encounter` (or closest if this is encompassed by a variable). *104 is also an EH measure not an EP measure*
For CMS32: should be `episode` with `Encounter, Performed: Emergency Department Visit` (or closest if this is encompassed by a variable) (it looks like you've already done this).

You can see if it's `patient` vs `episode` from the .html file. If there's a "Measure Item Count" field, then it's `episode`. That field describes what the`episode` is. Otherwise, it's `patient`.

2017-01-24 14:19 UTC, edeyoung commented on test/functional/patient_expected_and_calc_values_test.rb
> +    @golden_results = {}
add comment explaining what the `@golden_results` are

2017-01-24 14:19 UTC, edeyoung commented on test/functional/patient_expected_and_calc_values_test.rb
> +    records_set = File.join('records', "measure_history_set", "base_example")
oy. this is making me realize that the patient fixtures may not be the best test patient fixtures. There are a lot of zeros down there.
when the fixtures get regenerated, can you create the test patients similar to how they're done for the hand tests?

Also, let's chat before those fixtures get generated. I think we should have a game plan on when we create the patients, etc.

2017-01-24 14:19 UTC, edeyoung commented on test/functional/patient_expected_and_calc_values_test.rb
> +    # associate_measures_with_patients([@measure], Record.all)
should this be deleted?

2017-01-24 14:19 UTC, edeyoung commented on test/functional/patient_expected_and_calc_values_test.rb
> +    # TODO: When measure fixtures are available switchh to loading them
consider breaking some of the functionalities below into their own methods. that will make the code easier to read. For example, you could have:

```
  setup do
    @error_dir = File.join('log', 'load_errors')
    FileUtils.rm_r @error_dir if File.directory?(@error_dir)
    dump_database
    users_set = File.join('users', 'base_set')
    collection_fixtures(users_set)
    @user = User.by_email('bonnie@example.com').first
    sign_in @user

    @load_measures
    @load_patients
    @get_golden_results_for_patients
  end

  def load_measures
    measure_file = fixture_file_upload(File.join('test', 'fixtures', 'measure_exports', 'measure_history_set', 'base_example', 'CMS68v6.zip'), 'application/zip')
    ....
  end

  ....
```

2017-01-24 14:19 UTC, edeyoung commented on test/functional/patient_expected_and_calc_values_test.rb
> +    records_set = File.join('records', "measure_history_set", "multi_population")
consider adding a comment above each section saying, "loading patients for CMS104" etc.

2017-01-24 14:19 UTC, edeyoung commented on test/functional/patient_expected_and_calc_values_test.rb
> +      begin
see notes in previous review about rescue statements. they shouldn't be used in tests. same for any other rescue statements.

2017-01-24 14:19 UTC, edeyoung commented on test/functional/patient_expected_and_calc_values_test.rb
> +      flunk "No patients for measure #{measure.cms_id}"
is `flunk` what should be used here? do we want to fail if there are no patients? Is the idea that we assume there always are patients so if there aren't, that's a problem?

2017-01-24 14:19 UTC, edeyoung commented on test/functional/patient_expected_and_calc_values_test.rb
> +      processed_patients_array = []
don't need to track this for tests.

2017-01-24 14:19 UTC, edeyoung commented on test/functional/patient_expected_and_calc_values_test.rb
> +    calc_results_keys = ['IPP', 'rationale', 'finalSpecifics', 'measure_id', 'population_index', 'status', 'values', 'STRAT']
it's the same either way, but my slight preference is to move `IPP` out of this list and put it in both the lists below. That makes the lists make more sense to me. The initial list is all the metadata items. The lists being added are all the population sets for each group.

what happens if you put all the calc_results_keys together? like, the `MSRPOPL` with the `DENOM` and don't have two different lists? would it still work? if so, that might be the easiest thing to do. Then would this just be the same as unioning that master populations list (which is used in the code a bunch) with the extras list (`rationale`, `finalSpecifics`, etc.)?

2017-01-24 14:19 UTC, edeyoung commented on test/functional/patient_expected_and_calc_values_test.rb
> +      assert_equal measure.populations.length, patient[:calc_results].count, "Failed calc_results count on patient name #{patient.first} #{patient.last} for measure #{measure.cms_id}"
I'm not sure this failure message adequately explains the failure condition. This is similar for the other messages as well.

Consider changing to something like, "patient #{patient.first} #{patient.last} for measure #{measure.cms_id} did not have same number of calc results as there are populations. Number of calc_results: #{...}. Number of populations: #{...}."

Take a look at the other messages to see if they should be changed. If there is a fail message (which I think is awesome that you added), then have it be explanatory. For example, I don't known what "failed measure_id
 means, but I do know what "mismatched measure_id for patient calculation results and given measure" (or something along those lines.

2017-01-24 14:19 UTC, edeyoung commented on test/functional/patient_expected_and_calc_values_test.rb
> +      assert_operator 4, :<, patient[:results_size]
add comment explaining this. it's a pretty arbitrary number. people should understand where it comes from.

2017-01-24 14:19 UTC, edeyoung commented on test/functional/patient_expected_and_calc_values_test.rb
> +      assert_not_nil patient[:calc_results], "Failed not_nil calc_results exists on patient name #{patient.first} #{patient.last} for measure #{measure.cms_id}"
you check `not_nil` here but earlier you access `.count` for `calc_results`. The `not_nil` check should precede accessing attributes.

2017-01-24 14:19 UTC, edeyoung commented on test/functional/patient_expected_and_calc_values_test.rb
> +    Record.where(user_id: @user.id, measure_ids: measure.hqmf_set_id).each do |patient|
white space is your friend with this type of thing. Use it liberally to separate concepts to make this more readable.

Consider something along the lines of:

```
// golden results - assertion and getting the golden results

// all things related to results size

// all things related to calc_results

// loop over populations
  // calc_results assertions

  // golden results assertions
```

2017-01-24 14:19 UTC, edeyoung commented on test/functional/patient_expected_and_calc_values_test.rb
> +  def calculation_results (measure)
add comments to the top of each of these tests explaining at a high level what they'll be testing and how.

2017-01-24 14:19 UTC, edeyoung commented on test/functional/patient_expected_and_calc_values_test.rb
> +  def expected_values_empty_properly_populated (measure)
I don't understand the name for this function. can you explain and possibly reword?

2017-01-24 14:19 UTC, edeyoung commented on test/functional/patient_expected_and_calc_values_test.rb
> +    # Remove any calc results and related fields that might have been loaded
this explains the what but not the why. can you add a note on why you're removing the calc results?

2017-01-24 14:19 UTC, edeyoung commented on test/functional/patient_expected_and_calc_values_test.rb
> +    # Set the expected values to be empty
can you explain the why as well as the what here?

2017-01-24 14:19 UTC, edeyoung commented on test/functional/patient_expected_and_calc_values_test.rb
> +      # Test that the number of populations match
every time you have a comment, add a newline ahead of it. it helps visually separate the logic and makes the code way easier to read.

2017-01-24 14:19 UTC, edeyoung commented on test/functional/patient_expected_and_calc_values_test.rb
> +      measure.populations.each_with_index do |population_set, population_index|
when you go into loops, unless the line above is directly related to the loop (like initiates a variable used in the loop), add a newline ahead of it.

2017-01-24 14:19 UTC, edeyoung commented on test/functional/patient_expected_and_calc_values_test.rb
> +        assert_equal [:measure_id, :population_index], (patient[:expected_values][population_index].keys - population_set.keys), "Failed population set is filled with the correct populations on patie
may be worth noting that we expect `population_set` to have keys that `expected_values` doesn't have, but not the other way around.

2017-01-24 14:19 UTC, edeyoung commented on test/functional/patient_expected_and_calc_values_test.rb
> +        assert_equal [:measure_id, :population_index], (patient[:expected_values][population_index].keys - population_set.keys), "Failed population set is filled with the correct populations on patie
isn't `expected_values` the structure where the population sets aren't necessarily in order? if that's the case, we can't rely on `population_index` for this array.

2017-01-24 14:19 UTC, edeyoung commented on test/functional/patient_expected_and_calc_values_test.rb
> +      patient.update_expected_value_structure!(measure)
consider adding a comment that (a) this is the functionality that you are particularly testing with this code and (b) you are expecting this to add in all relevant populations and initialize them to 0 or [] as appropriate

2017-01-24 18:42 UTC, mulcahyk commented on test/functional/measures_controller_measure_history_granular_test.rb
> +require 'test_helper'
I don't mind doing that.  I think we are going to make `meaures_controller_measure_history_test` rather long doing that.  To help keep it clear I will make a "section" for these tests with some comments to identity their purpose.

For the sake of tracking the comments, this will be the last change that I make.

2017-01-24 18:47 UTC, mulcahyk commented on test/functional/measures_controller_measure_history_granular_test.rb
> +    dump_database
Just a bit confused about this comment.  Are you referring to:
`users_set = File.join('users', 'base_set')`
`collection_fixtures(users_set)`
If so, then yes, this is temporary until the final fixtures are ready.
I will add the TODO comment to replace this.

2017-01-24 18:50 UTC, mulcahyk commented on test/functional/measures_controller_measure_history_granular_test.rb
> +  test 'measure archiving' do
I don't really think that it matters.  The archive process just copies the data from one collection to another in the database.  Add other measure types would be just to further test the copy functionality of Ruby, Rails, and MongoDB.

2017-01-24 22:21 UTC, mulcahyk commented on test/functional/measures_controller_measure_history_granular_test.rb
> +    assert_equal 2, upload_summary.population_set_summaries[0][:summary][:pass_before]
I think that is the case here.
![image](https://cloud.githubusercontent.com/assets/17731116/22269450/67b37e4c-e259-11e6-8309-4d4339a82fa8.png)

2017-01-24 22:32 UTC, mulcahyk commented on test/functional/measures_controller_measure_history_granular_test.rb
> +    measure_patients_post_upload = Record.where(measure_ids: '9A032D9C-3D9B-11E1-8634-00237D5BF174', user_id: @user.id)
The `measure_patients_pre_upload` is kludge way of accessing the data.  I would rather not propagate that.  I know that you want things to be the same everywhere but I don't think it works here.  If you think it would help with readability then I'm happy to change it.  Otherwise I think a comment would be enough.

2017-01-24 22:39 UTC, mulcahyk commented on test/functional/patient_expected_and_calc_values_test.rb
> +  # TODO: See if the can be set to tests Record
This comment comes from a conversation we had about the testing of measure history.  I was using `tests MeasuresController` so that I could load the measures from zip files.  All of these tests though have more to do with what happens at the `record` level.  This comment was to change the controller we are using.  You wanted me to come back to it after I got this working.

2017-01-25 13:59 UTC, edeyoung commented on test/functional/measures_controller_measure_history_granular_test.rb
> +    dump_database
Yes, that's what I was referring to. Thanks!

2017-01-25 14:00 UTC, edeyoung commented on test/functional/measures_controller_measure_history_granular_test.rb
> +  test 'measure archiving' do
Agree - let's just do it for one type.

2017-01-25 14:01 UTC, edeyoung commented on test/functional/measures_controller_measure_history_granular_test.rb
> +    assert_equal 2, upload_summary.population_set_summaries[0][:summary][:pass_before]
yes, it is. bummer.

2017-01-25 14:01 UTC, edeyoung commented on test/functional/measures_controller_measure_history_granular_test.rb
> +  test 'measure upload summary' do
should the upload summary be done for multiple measure types?

2017-01-25 14:02 UTC, edeyoung commented on test/functional/measures_controller_measure_history_granular_test.rb
> +    measure_patients_post_upload = Record.where(measure_ids: '9A032D9C-3D9B-11E1-8634-00237D5BF174', user_id: @user.id)
leaving it makes sense. like you suggested, a comment might be nice.

2017-01-25 14:03 UTC, edeyoung commented on test/functional/patient_expected_and_calc_values_test.rb
> +  # TODO: See if the can be set to tests Record
The comment doesn't reflect that very well (I think there are some typos in it). Can you reword the comment to reflect what you wrote above? It doesn't have to be that verbose - can still be a one-liner, but as it is, it doesn't make sense.

2017-01-25 22:32 UTC, mulcahyk commented on test/functional/patient_expected_and_calc_values_test.rb
> +    calc_results_keys = ['IPP', 'rationale', 'finalSpecifics', 'measure_id', 'population_index', 'status', 'values', 'STRAT']
Good point.  I'll set it the same way as the code.

2017-01-26 18:22 UTC, mulcahyk commented on test/functional/measures_controller_measure_history_granular_test.rb
> +    assert_equal 2, upload_summary.population_set_summaries[0][:summary][:pass_before]
Is it worth it to make a measure with the MAT to test this as opposed to sorting through all of the existing measures and hoping we hit on one?

2017-01-26 18:36 UTC, mulcahyk commented on test/functional/patient_expected_and_calc_values_test.rb
> +    # TODO: When measure fixtures are available switchh to loading them
Do you think that it is over to have the `golden_results` method verify that there is an entry for every patient record that has been loaded?

2017-01-27 13:27 UTC, edeyoung commented on test/functional/patient_expected_and_calc_values_test.rb
> +    Record.where(user_id: @user.id, measure_ids: measure.hqmf_set_id).each do |patient|
Add a comment explaining what you're doing here and why

2017-01-27 13:27 UTC, edeyoung commented on test/functional/patient_expected_and_calc_values_test.rb
> +      patient.update_expected_value_structure!(measure)
is this the main functionality being tested? If so, note that.

2017-02-15 22:24 UTC, mulcahyk commented
Please see PR #683 for the final version.

2017-03-21 14:47 UTC, edeyoung commented
This pull request was maintained for comments in support of https://github.com/projecttacoma/bonnie/pull/683. https://github.com/projecttacoma/bonnie/pull/683 has been accepted and will be merged so this pull request is no longer necessary.

2017-03-21 14:47 UTC, closed without merging