Clone calc results
MeasureAuthoringTool/bonnie pull request #676
Opened 2017-01-31 21:27 UTC by edeyoung

2017-02-01 02:20 UTC, c-monkey commented
tests look good, everything seems in order, nice job

2017-02-01 02:21 UTC, c-monkey approved these changes

2017-02-01 16:40 UTC, hossenlopp requested changes

2017-02-01 16:40 UTC, hossenlopp commented on app/assets/javascripts/models/patient.js.coffee
> +      promise.resolve(@)
In a perfect world the deferred should be rejected and still returned instead of `false`. But then things that may expect calculateAndSave to return `false` would need to be written to handle the fail state of the deferred.

2017-02-01 16:40 UTC, hossenlopp commented on app/assets/javascripts/models/patient.js.coffee
> +    promise
`promise.promise()` should be returned if you want to return a promise. Otherwise still return deferred (we just pass deferreds elsewhere in bonnie.

2017-02-01 16:40 UTC, hossenlopp commented on app/assets/javascripts/models/patient.js.coffee
> +          $.when(savePromise).then =>
This should handle the fail situation of the savePromise and reject the `promise`.

2017-02-02 18:31 UTC, edeyoung commented
Addressed Hoss's comments. To test failed clones (create a validation error), you can remove the first name field of the patient before you attempt to clone it within the browser debugger. E.g. `patient.set('first', '')`.

2017-02-02 18:45 UTC, c-monkey commented
I consent to these changes and see nothing wrong.

2017-02-02 19:58 UTC, hossenlopp approved these changes

2017-02-03 15:49 UTC, merged