Updates backend test fixture loading to convert ids to bson objects, …
MeasureAuthoringTool/bonnie pull request #677
Opened 2017-02-06 14:10 UTC by alexanderelliott121

Updates test infrastructure to address issues raised by updating fixture loading.
Adding logic to convert id fields into bson objects conflicted with existing fixtures.  Those fixtures had to have their id's updated, and the tests that reference them as well.

This had the side effect of fixing a longstanding bug in the tests where value sets were being exported incorrectly due to inconsistencies with ids.

2017-02-06 14:25 UTC, edeyoung requested changes

2017-02-06 14:25 UTC, edeyoung commented on test/test_helper.rb
> +  # Code is derived from set_mongoid_ids function defined in test/test_helper.rb
update comment - this is when it was copy/pasted from this file into the new file you were working on.

2017-02-06 14:25 UTC, edeyoung commented on test/test_helper.rb
> +  # Code is derived from collection_fixtures function found in test/test_helper.rb
update comment.

2017-02-06 14:25 UTC, edeyoung commented on test/test_helper.rb
> +#      Mongoid.default_session[collection_name].drop
should this be commented? if so, why? if so, remove.

2017-02-06 14:25 UTC, edeyoung commented on test/test_helper.rb
> +  ###
by moving the modified functions into here, can you just remove them from wherever it is you modified them and use these instead?

2017-02-06 14:25 UTC, edeyoung commented on test/functional/admin_users_controller_test.rb
> +      assert_equal 29, zip_file.glob(File.join('value_sets', '**', '*.json')).count
why does the number of value sets increase?

2017-02-06 15:23 UTC, alexanderelliott121 commented on test/functional/admin_users_controller_test.rb
> +      assert_equal 29, zip_file.glob(File.join('value_sets', '**', '*.json')).count
This one is weird.  The tests create value_sets to populate the measures.  29 value_sets are created, and they all have unique oids.
The 27 was a bug in the test, resulting from the way the fixtures were loaded.

I actually saw the same issue back when I was working on the vs consolidation.

2017-02-06 15:26 UTC, alexanderelliott121 commented on test/test_helper.rb
> +#      Mongoid.default_session[collection_name].drop
Should be removed.

2017-02-06 15:58 UTC, edeyoung requested changes

2017-02-06 15:58 UTC, edeyoung commented on test/functional/populations_controller_test.rb
> +    measure = Measure.by_user(@user).find("53ce63744d4d32e2cd4b0502")
shouldn't these be BSON ids?

2017-02-06 15:58 UTC, edeyoung commented on test/functional/admin_users_controller_test.rb
> +      assert_equal 29, zip_file.glob(File.join('value_sets', '**', '*.json')).count
if this was a bug in the test, why didn't the test fail previously? has anything changed about how the value sets are being loaded?

2017-02-06 15:58 UTC, edeyoung commented on test/test_helper.rb
> +  ###
Can you address this comment? Should wherever these are being duplicated be deleted and these functions referenced instead?

2017-02-06 15:58 UTC, edeyoung commented on test/test_helper.rb
> +      collection_name = collection.split(File::SEPARATOR)[0]
why were we able to remove `Mongoid.default_session[collection].drop`?

2017-02-06 17:38 UTC, alexanderelliott121 commented on test/test_helper.rb
> +  ###
Done

2017-02-06 17:39 UTC, alexanderelliott121 commented on test/functional/populations_controller_test.rb
> +    measure = Measure.by_user(@user).find("53ce63744d4d32e2cd4b0502")
They get converted into BSON by the find method.

2017-02-06 17:46 UTC, alexanderelliott121 commented on test/test_helper.rb
> +      collection_name = collection.split(File::SEPARATOR)[0]
The drop_database method that is called before most tests clears out the db.
I'm in favor of relying on drop_database over having the database clean up enforced in the loading function since I feel it opens up flexibility in execution: this way, you can load fixtures of the same type from multiple directories.

Example: lets say you want CMS160 and CMS68 from the measure_history_set fixtures, which have different paths.  Relying on loading for clean up would result in one being loaded, then being wiped before the other one is.

This does have the knock on effect of requiring a clean db for the fixture upload tool, but I think that that is acceptable.

2017-02-06 17:51 UTC, alexanderelliott121 commented on test/functional/populations_controller_test.rb
> +    measure = Measure.by_user(@user).find("53ce63744d4d32e2cd4b0502")
For some reason, I can't reply to the testing bug question or the "address comment" comment.
For the test: I'm a bit confused myself.  There are 29 unique oids, so it wasn't a matter of writing the same vs twice.

"Can you address this comment? Should wherever these are being duplicated be deleted and these functions referenced instead?"
I'm not sure what you're requesting.

2017-02-06 18:01 UTC, edeyoung commented on test/test_helper.rb
> +      collection_name = collection.split(File::SEPARATOR)[0]
ah, got it. thanks!

2017-02-06 18:04 UTC, edeyoung commented on test/functional/populations_controller_test.rb
> +    measure = Measure.by_user(@user).find("53ce63744d4d32e2cd4b0502")
for the "can you address" comment - it was more or less a rephrasing of the first comment, which it looks like you addressed it (the functions were deleted in the other class). Maybe I missed this when I went through the second time or maybe it was happening right when I was commenting on it again? I think I thought you were done going through the comments when I wrote that.

2017-02-06 18:09 UTC, edeyoung commented on lib/tasks/generate_fixtures.rake
> +    require_relative "../../test/test_helper.rb"
oh... interesting. these are in two completely different scopes, which i hadn't realized.

thoughts on how best to handle this? Is this creating a weird dependency? should the loading code be put somewhere else?

2017-02-06 18:33 UTC, alexanderelliott121 commented on lib/tasks/generate_fixtures.rake
> +    require_relative "../../test/test_helper.rb"
It seems to be safe enough, given that it is in a rake task rather than in the main code.
The only people who will be interacting with it are devs.

2017-02-06 18:34 UTC, mulcahyk commented on lib/tasks/generate_fixtures.rake
>      # Generates a set of front end fixtures representing a specific database state.
I think that it might be helpful to have a comment describing the difference between front-end and back-end fixtures.  

Does it make sense to have one task with a parameter to specific front-end, back-end or both types of fixtures?

2017-02-06 18:58 UTC, mulcahyk commented on lib/tasks/generate_fixtures.rake
>      # Generates a set of front end fixtures representing a specific database state.
I can't seem to leave the following comments where I want to so I'm lumping them all here:

- When making front-end fixtures why are all the patients dumped into one file while for the back-end they are put in separate files?
- [Here](https://github.com/projecttacoma/bonnie/pull/677/files#diff-26c2c3094f9eb41aaa209e58589f491eR73) you have a "magic number/identifier" without explaining why or what it is used for.
- It seems like there is a fair bit of repeated code between the front and back end tasks.  Could they be converted to functions?
- I'm not clear on the purpose of the `generate_oid_to_valuesets` task.  Could you add a brief comment on when or why you would use this task?

2017-02-06 19:00 UTC, mulcahyk commented on test/functional/admin_users_controller_test.rb
> +    @user.measures.find('53ce63744d4d32e2cd4b0500').value_set_oids.uniq.each do |oid|
Magic identifier.  Why this id?

2017-02-06 19:17 UTC, mulcahyk commented on test/functional/populations_controller_test.rb
> +    measure = Measure.by_user(@user).find("53ce63744d4d32e2cd4b0502")
Magic identifier.
If you are looking the measure up by BSON Id when why don't you do that directly?

2017-02-06 19:20 UTC, mulcahyk commented on test/functional/populations_controller_test.rb
> +    measure = Measure.by_user(@user).find("53ce63744d4d32e2cd4b0502")
@edeyoung Do we have a standard way of looking objects up?  I like the exactness of doing it by BSON Id but that seems very brittle.  Could/should we be using something more immutable like cms_id or hqmf_id?

2017-02-06 19:22 UTC, mulcahyk commented on test/functional/users_controller_test.rb
> +    @user.measures.find('53ce63744d4d32e2cd4b0500').value_set_oids.uniq.each do |oid|
Magic identifier.  Why this value?

2017-02-06 19:44 UTC, mulcahyk commented on test/test_helper.rb
> +          # To ensure we have consistent collection names in Mongoid, we need to take the file directory as the collection name.
I'm not sure if it is a spacing issue or not but these comments are bit confusing.  I appreciate the background information but in this case I think for clarity it would be better to just say we are naming the collections after the file directory.

2017-02-07 14:54 UTC, alexanderelliott121 commented on test/functional/admin_users_controller_test.rb
> +    @user.measures.find('53ce63744d4d32e2cd4b0500').value_set_oids.uniq.each do |oid|
I think using specific identifiers for tests is acceptable.  It isn't going to change unless the fixture is changed, and is more robust than the previous approach of just grabbing the first element in the collection.

2017-02-07 14:57 UTC, alexanderelliott121 commented on test/functional/admin_users_controller_test.rb
> +    @user.measures.find('53ce63744d4d32e2cd4b0500').value_set_oids.uniq.each do |oid|
Point of clarification based on your other comment:
find converts the given argument into a bson and compares against _id

2017-02-08 14:14 UTC, alexanderelliott121 commented on test/functional/users_controller_test.rb
> +    @user.measures.find('53ce63744d4d32e2cd4b0500').value_set_oids.uniq.each do |oid|
It is the bson id of the measure, ensuring that the measure retrieved is determanistic

2017-02-08 14:14 UTC, alexanderelliott121 commented on test/functional/populations_controller_test.rb
> +    measure = Measure.by_user(@user).find("53ce63744d4d32e2cd4b0502")
The id is stored in the fixture, so I wouldn't exactly call it mutable.

2017-02-08 15:15 UTC, mulcahyk approved these changes
The changes look good to me.

2017-02-08 15:55 UTC, edeyoung approved these changes

2017-02-08 15:56 UTC, merged