Bonnie 460
MeasureAuthoringTool/bonnie pull request #683
Opened 2017-02-13 16:40 UTC by mulcahyk

Picking from where the work on Bonnie 335 ended.
Tests are now loading data from test fixtures instead of zip files (where appropriate).

2017-02-13 16:42 UTC, mulcahyk commented
`measures_controller_measure_history_granular_test.rb` is still a separate file for the ease of review.  It will be merged into the `measures_controller_measure_history_test.rb` when the reviews are done.

2017-02-15 21:50 UTC, mulcahyk commented
I should note that this pull request started life as PR #670.  Started a new branch to resolve some issues with test cases.

2017-02-16 19:23 UTC, hossenlopp requested changes
Here are the comments I have right now. There is still more for me to go through, but Lizzie asked me to release these.

2017-02-16 19:23 UTC, hossenlopp commented on config/mongoid.yml
> +      database: bonnie_460
Remove this change.

2017-02-16 19:23 UTC, hossenlopp commented on test/functional/measures_controller_measure_history_granular_test.rb
> +    post :finalize, {"t551"=>{"hqmf_id"=>"40280381-4555-E1C1-0145-DC7DC26A44BF", "episode_ids"=>["OccurrenceAMedicationsEncounterCodeSet1"]}}
Perhaps verify the it was successful and the finalize step is needed. i.e. Assert that the `measure.need_finalize` field is true.

2017-02-16 19:23 UTC, hossenlopp commented on test/functional/measures_controller_measure_history_granular_test.rb
> +    post :finalize, {"t551"=>{"hqmf_id"=>"40280381-51F0-825B-0152-227DFBAC15AA", "episode_ids"=>["OccurrenceA_MedicationsEncounterCodeSet_EncounterPerformed_40280381_3e93_d1af_013e_a36090dc2cf5_sourc
Perhaps verify the it was successful and the finalize step is needed. i.e. Assert that the `measure.need_finalize` field is true.

2017-02-16 19:23 UTC, hossenlopp commented on test/functional/measures_controller_measure_history_granular_test.rb
> +    archive = ArchivedMeasure.where(hqmf_set_id: '9A032D9C-3D9B-11E1-8634-00237D5BF174', user_id: @user.id)
`archived_measures` would be a more descriptive name for this variable. But this could be done in one line and the by_user_and_hqmf_set_id scope should be used.

```ruby
assert_equal 0, ArchivedMeasure.by_user_and_hqmf_set_id(@user, '9A032D9C-3D9B-11E1-8634-00237D5BF174').count
```

2017-02-16 19:23 UTC, hossenlopp commented on test/functional/measures_controller_measure_history_granular_test.rb
> +    archive = ArchivedMeasure.where(hqmf_set_id: '9A032D9C-3D9B-11E1-8634-00237D5BF174', user_id: @user.id)
Same as above, could be done in one line.

2017-02-16 19:23 UTC, hossenlopp commented on test/functional/measures_controller_measure_history_granular_test.rb
> +    archive = ArchivedMeasure.where(hqmf_set_id: '9A032D9C-3D9B-11E1-8634-00237D5BF174', user_id: @user.id)
Same as above, could be done in one line.

2017-02-16 19:23 UTC, hossenlopp commented on test/functional/measures_controller_measure_history_granular_test.rb
> +    post :finalize, {"t551"=>{"hqmf_id"=>"40280381-4555-E1C1-0145-DC7DC26A44BF", "episode_ids"=>["OccurrenceAMedicationsEncounterCodeSet1"]}}
Same as above, perhaps make sure the create worked and finalize needed.

2017-02-16 19:23 UTC, hossenlopp commented on test/functional/measures_controller_measure_history_granular_test.rb
> +    upload_summary = UploadSummary::MeasureSummary.where(hqmf_set_id: '9A032D9C-3D9B-11E1-8634-00237D5BF174', user_id: @user.id)
Could be done in one line and use the scope.

```ruby
assert_equal 0, UploadSummary::MeasureSummary.by_user_and_hqmf_set_id(@user, '9A032D9C-3D9B-11E1-8634-00237D5BF174').count
```

2017-02-16 19:23 UTC, hossenlopp commented on test/functional/measures_controller_measure_history_granular_test.rb
> +    assert_equal upload_summary.first.measure_db_id_post_upload, measure.id
The expected value should come first. In this case it is `measure.id` in my opinion. Likewise for the few checks below because the UploadSummary is supposed to follow what the measure is making the measure fields the expected values.

2017-02-20 18:34 UTC, mulcahyk commented on test/functional/measures_controller_measure_history_granular_test.rb
> +    archive = ArchivedMeasure.where(hqmf_set_id: '9A032D9C-3D9B-11E1-8634-00237D5BF174', user_id: @user.id)
Done.

2017-02-20 18:34 UTC, mulcahyk commented on test/functional/measures_controller_measure_history_granular_test.rb
> +    archive = ArchivedMeasure.where(hqmf_set_id: '9A032D9C-3D9B-11E1-8634-00237D5BF174', user_id: @user.id)
Done.

2017-02-20 18:38 UTC, mulcahyk commented on test/functional/measures_controller_measure_history_granular_test.rb
> +    archive = ArchivedMeasure.where(hqmf_set_id: '9A032D9C-3D9B-11E1-8634-00237D5BF174', user_id: @user.id)
Yes but I use `archive` for the next two tests as well.  Leaving it as is but renaming to `measure_from_archive`.

2017-02-20 18:39 UTC, mulcahyk commented on test/functional/measures_controller_measure_history_granular_test.rb
> +    upload_summary = UploadSummary::MeasureSummary.where(hqmf_set_id: '9A032D9C-3D9B-11E1-8634-00237D5BF174', user_id: @user.id)
Done.

2017-02-20 18:59 UTC, mulcahyk commented on test/functional/measures_controller_measure_history_granular_test.rb
> +    assert_equal upload_summary.first.measure_db_id_post_upload, measure.id
Done.

2017-02-20 19:09 UTC, mulcahyk commented on test/functional/measures_controller_measure_history_granular_test.rb
> +    post :finalize, {"t551"=>{"hqmf_id"=>"40280381-4555-E1C1-0145-DC7DC26A44BF", "episode_ids"=>["OccurrenceAMedicationsEncounterCodeSet1"]}}
Done

2017-02-20 19:10 UTC, mulcahyk commented on test/functional/measures_controller_measure_history_granular_test.rb
> +    post :finalize, {"t551"=>{"hqmf_id"=>"40280381-51F0-825B-0152-227DFBAC15AA", "episode_ids"=>["OccurrenceA_MedicationsEncounterCodeSet_EncounterPerformed_40280381_3e93_d1af_013e_a36090dc2cf5_sourc
Done

2017-02-20 19:10 UTC, mulcahyk commented on test/functional/measures_controller_measure_history_granular_test.rb
> +    post :finalize, {"t551"=>{"hqmf_id"=>"40280381-4555-E1C1-0145-DC7DC26A44BF", "episode_ids"=>["OccurrenceAMedicationsEncounterCodeSet1"]}}
Done

2017-02-24 17:31 UTC, hossenlopp requested changes
There are numerous TODOs and commented out code left over.

2017-02-24 17:31 UTC, hossenlopp commented on test/functional/patient_expected_and_calc_values_test.rb
> +  # test 'CMS32v4' do
Remove commented out code.

2017-02-24 17:31 UTC, hossenlopp commented on test/functional/patient_expected_and_calc_values_test.rb
> +  def expected_values_reduce_number_population_sets (measure)
This function appears to be a helper function and not a test. Perhaps the comment should reflect that.

2017-02-24 17:31 UTC, hossenlopp commented on test/functional/patient_expected_and_calc_values_test.rb
> +  def expected_values_values_retained (measure)
This function appears to be a helper function and not a test. Perhaps the comment should reflect that.

2017-02-24 17:31 UTC, hossenlopp commented on test/functional/patient_expected_and_calc_values_test.rb
> +  def expected_values_properly_populated_when_empty (measure)
This function appears to be a helper function and not a test. Perhaps the comment should reflect that.

2017-02-24 17:31 UTC, hossenlopp commented on test/functional/patient_expected_and_calc_values_test.rb
> +  def calculation_results (measure)
This function appears to be a helper function and not a test. Perhaps the comment should reflect that.

2017-02-24 17:31 UTC, hossenlopp commented on test/functional/patient_expected_and_calc_values_test.rb
> +    # load_patients
Remove commented out code.

2017-02-24 17:31 UTC, hossenlopp commented on test/functional/patient_expected_and_calc_values_test.rb
> +  # TODO: Consider converting this to a test of Record instead of the MeasuresController.
Remove TODO if it was not decided to be changed.

2017-02-24 17:31 UTC, hossenlopp commented on test/functional/patient_expected_and_calc_values_test.rb
> +    # TODO: When measure fixtures are available switchh to loading them
Was this TODO completed?

2017-02-24 17:31 UTC, hossenlopp commented on test/functional/patient_expected_and_calc_values_test.rb
> +    # TODO
Remove TODO if it is not being finished here. Perhaps make it a JIRA task.

2017-03-01 16:00 UTC, mulcahyk commented on test/functional/patient_expected_and_calc_values_test.rb
> +    # load_patients
Done.

2017-03-01 16:00 UTC, mulcahyk commented on test/functional/patient_expected_and_calc_values_test.rb
> +    # TODO: When measure fixtures are available switchh to loading them
Done.

2017-03-01 16:10 UTC, mulcahyk commented on test/functional/patient_expected_and_calc_values_test.rb
> +    # TODO
Done.
This will be addressed when BONNIE-337 and BONNIE-338 are done.

2017-03-01 16:14 UTC, mulcahyk commented on test/functional/patient_expected_and_calc_values_test.rb
> +  def calculation_results (measure)
The idea when this approach is to have modular tests where all you have to do is pass in a new measure.  You are correct that normally this would be a helper function but in this instance it is being used as a repeatable test.

2017-03-09 19:11 UTC, hossenlopp requested changes
There are a few outstanding code comment things that I think need to be addressed to make it less confusing for the next person that comes across this file.

2017-03-09 19:11 UTC, hossenlopp commented on test/functional/patient_expected_and_calc_values_test.rb
> +  def calculation_results (measure)
Could the comments on these reusable test fragments be updated to explicitly state they are reusable test fragments?

2017-03-13 20:13 UTC, edeyoung requested changes
only two of my comments below require changes or responses before i'll approve. consider making or responding to the other comments. the comments have a note if a response/change is required.

2017-03-13 20:13 UTC, edeyoung commented on test/functional/measures_controller_measure_history_test.rb
> +    measure_file = fixture_file_upload(File.join('test', 'fixtures', 'measure_exports', 'measure_history_set', 'base_example', 'CMS68v4.zip'), 'application/zip')
moving comment over: should the upload summary be done for multiple measure types?

[[response requested but not necessary for approval]]

2017-03-13 20:13 UTC, edeyoung commented on test/functional/patient_expected_and_calc_values_test.rb
> +    @error_dir = File.join('log', 'load_errors')
moving comment: 
is `@error_dir` used anywhere? can these lines be deleted?

[[response or change required for approval]]

2017-03-13 20:13 UTC, edeyoung commented on test/functional/patient_expected_and_calc_values_test.rb
> +    collection_fixtures(users_set)
![image](https://cloud.githubusercontent.com/assets/11574199/23871443/cd75fe68-0800-11e7-909f-5030dcd685da.png)


[[response or change required for approval]]

2017-03-13 20:13 UTC, edeyoung commented on test/functional/measures_controller_measure_history_test.rb
> +      assert_equal 8, patient.keys.count
add comment why you are checking for 8. are these the fields you are checking? If so, would it be better to have those fields in an array and make sure that there are no differences in the array and in the `patient.keys`?

[[change recommended but not necessary for approval]]

2017-03-13 20:13 UTC, edeyoung commented on test/functional/patient_expected_and_calc_values_test.rb
> +    @golden_results.store(BSON::ObjectId('58514916e76e941a3d000489'), [{'IPP'=> 1, 'DENOM'=> 1, 'NUMER'=> 1, 'DENEX'=> 0, 'DENEXCEP'=> 0, 'NUMEX'=> 0, 'status'=> 'pass'}])
![image](https://cloud.githubusercontent.com/assets/11574199/23872197/c2d47dce-0803-11e7-8503-54c5be5a3e37.png)

[[please add this to our back log. no changes necessary for approval]]

2017-03-14 17:16 UTC, mulcahyk commented on test/functional/measures_controller_measure_history_test.rb
> +    measure_file = fixture_file_upload(File.join('test', 'fixtures', 'measure_exports', 'measure_history_set', 'base_example', 'CMS68v4.zip'), 'application/zip')
I don't think that there is anything in particular for upload summary that is specific to a certain type of measure type.  That said more testing isn't a bad thing.  I'll create a JIRA ticket for it.

2017-03-14 22:17 UTC, mulcahyk commented on test/functional/measures_controller_measure_history_test.rb
> +      assert_equal 8, patient.keys.count
Took your suggestion and am comparing `patient.keys` to an array of values.

2017-03-14 22:31 UTC, mulcahyk commented on test/functional/patient_expected_and_calc_values_test.rb
> +    collection_fixtures(users_set)
I think that this is a result of some confusion on my part.  I am loading the `user` from the fixture.  I'm not sure why I said that it was temporary; maybe I was thinking of `patients` (`records`) instead of `users`.

2017-03-14 22:39 UTC, mulcahyk commented on test/functional/patient_expected_and_calc_values_test.rb
> +    @golden_results.store(BSON::ObjectId('58514916e76e941a3d000489'), [{'IPP'=> 1, 'DENOM'=> 1, 'NUMER'=> 1, 'DENEX'=> 0, 'DENEXCEP'=> 0, 'NUMEX'=> 0, 'status'=> 'pass'}])
Actually there are some 1's in there as well as measures with multiple stratifications.  Since the testing is "automated" it should be easy to add more patients, for example with all 0's or all 1's.  There is still an outstanding JIRA ticket to add continuous variables.
(JIRA BONNIE-525)

2017-03-15 15:21 UTC, mulcahyk commented on test/functional/patient_expected_and_calc_values_test.rb
> +  # TODO: Consider converting this to a test of Record instead of the MeasuresController.
Removing `tests MeasuresController` from the `patient_expected_and_calc_values_test.rb` give the same results  as with having the line in.
Changing from `ActionController::TestCase` to `ActiveSupport::TestCase` causes the test to fail with the message:
`NoMethodError: undefined method `env' for nil:NilClass`.
I'm going to leave the it as `ActionController::TestCase`.

2017-03-20 16:32 UTC, edeyoung approved these changes

2017-03-20 17:55 UTC, hossenlopp approved these changes

2017-03-21 14:50 UTC, merged