BONNIE-455 fixing CQL based measures to support episode of care
MeasureAuthoringTool/bonnie pull request #684
Opened 2017-02-15 16:25 UTC by c-monkey

- changed placeholder checkboxes in patient builder to text boxes, for simplicity, as JB says these are going away when we add highlighting
 - put in temporary "This is a CQL measure" description for episodes of care at top of measure view - JB, Kristian, and Chris theorize we might be able to show actual CQL statements here

 ----------------------------------------------
 Need associated changes in bonnie_bundler
 ----------------------------------------------

Tested loading CQL and HQMF measures. It is desired behavior to skip the finalize dialog for CQL-based measures with episodes of care

2017-02-15 20:13 UTC, c-monkey commented
JB discovered that the finalize dialog is shown with multiple populations and gave me a CQL based measure with which to test and resolve this issue

2017-02-16 14:15 UTC, edeyoung requested changes

2017-02-16 14:15 UTC, edeyoung commented on app/assets/javascripts/views/measure_view.js.coffee
> +    return null if @model.get('cql')
add a comment explaining that cql measures don't need a list of defined episodes of care

2017-02-16 14:15 UTC, edeyoung commented on app/controllers/measures_controller.rb
> +      is_cql = measure == nil
can you add comments or rearrange the logic for this? on first pass, it was confusing to access the measure, then say it's cql if the measure doesn't exist (which makes sense, but on first pass it was confusing), and then access the measure again (the if statement is hidden at the end).

maybe:

```
# try to access qdm-based measure
measure = Measure.by_user(current_user).where(hqmf_id: data['hqmf_id']).first
# if measure doesn't exist in qdm measures, it must be a cql measure
is_cql = measure == nil
if is_cql
  measure = CqlMeasure.by_user(current_user).where(hqmf_id: data['hqmf_id']).first if is_cql
end
```

2017-02-16 14:15 UTC, edeyoung commented on app/controllers/measures_controller.rb
> +      measure['episode_ids'] = data['episode_ids'] if !is_cql
add comment that cql-based measures don't need a list of episode of care ids

2017-02-16 14:15 UTC, edeyoung commented on app/controllers/measures_controller.rb
> +      measure.generate_js(clear_db_cache: true) if !is_cql
add comment why this shouldn't be cleared if it's a cql-based measure.

2017-02-16 14:15 UTC, edeyoung commented on app/controllers/measures_controller.rb
> +      measure.needs_finalize = (!is_cql && measure_details['episode_of_care']) || measure.populations.size > 1
for the line 182 section, the only reason I think this works is because it does not appear that cql-based measures can currently be updated. it may be worth adding a TODO in this section that this needs to be updated to not check the episode ids for cql based measures on update once that's implemented or that logic can be added now although it can't be tested.

2017-02-16 15:02 UTC, mulcahyk commented on app/controllers/measures_controller.rb
> +      measure.generate_js(clear_db_cache: true) if !is_cql
Ruby style point: consider `unless is_cql`.

2017-02-16 16:51 UTC, c-monkey commented on app/controllers/measures_controller.rb
> +      measure.needs_finalize = (!is_cql && measure_details['episode_of_care']) || measure.populations.size > 1
@jbradl11 do you have a preference?

2017-02-16 16:57 UTC, c-monkey commented on app/assets/javascripts/templates/measure.hbs
> +          {{#if cql}}
@jbradl11 JB, are we considering ever supporting identification of episodes of care CQL statements? If not, then I need to annotate the code in multiple places indicating that.

2017-02-16 16:57 UTC, jbradl11 commented on app/controllers/measures_controller.rb
> +      measure.needs_finalize = (!is_cql && measure_details['episode_of_care']) || measure.populations.size > 1
I think adding a TODO here and mentioning the TODO in the JIRA task that relates to implementing CQL measure update should be sufficient.

2017-02-16 17:04 UTC, c-monkey commented on app/assets/javascripts/templates/measure.hbs
> +          {{#if cql}}
@edeyoung Do you have a better suggestion for how we might have this section in the web page look? Should we omit the whole "Episode(s) of Care:" altogether? The "This is a CQL measure" is clearly placeholder.

2017-02-16 17:25 UTC, c-monkey commented on app/controllers/measures_controller.rb
> +      measure.needs_finalize = (!is_cql && measure_details['episode_of_care']) || measure.populations.size > 1
@jbradl11 I'd love to do that, great suggestion. I can't find this task. Can you please confirm that it doesn't exist? I don't mind authoring it, if needed. Thanks!

2017-02-16 17:31 UTC, jbradl11 commented on app/controllers/measures_controller.rb
> +      measure.needs_finalize = (!is_cql && measure_details['episode_of_care']) || measure.populations.size > 1
I don't believe one exists yet.

2017-02-16 17:53 UTC, edeyoung commented on app/assets/javascripts/templates/measure.hbs
> +          {{#if cql}}
Maybe for cql, have it just say:

**Episode of Care Based Measure**

And leave it at that.

The episodes of care will not be available in the logic. However, they can be parsed out from the human readable HTML, so if we wanted to show what the episode of care is, that's how we'd do it. I'd say let's add that as a low priority JIRA task (to parse out the episode of care label) and not list anything for now.

2017-02-16 17:54 UTC, c-monkey commented on app/controllers/measures_controller.rb
> +      measure.needs_finalize = (!is_cql && measure_details['episode_of_care']) || measure.populations.size > 1
Done

2017-02-16 17:54 UTC, c-monkey commented on app/controllers/measures_controller.rb
> +      is_cql = measure == nil
Done

2017-02-16 17:55 UTC, edeyoung commented on app/controllers/measures_controller.rb
> +      measure.needs_finalize = (!is_cql && measure_details['episode_of_care']) || measure.populations.size > 1
I also added a comment similar to this in this pull request: https://github.com/projecttacoma/bonnie/commit/20c49d59421943ca50000504d2d948b9672010ea#diff-9f6c25d2ea5170e4953a469c855a47d4R91

2017-02-16 18:19 UTC, c-monkey commented on app/assets/javascripts/templates/measure.hbs
> +          {{#if cql}}
Done.

2017-02-16 18:20 UTC, c-monkey commented on app/assets/javascripts/views/measure_view.js.coffee
> +    return null if @model.get('cql')
@mulcahyk recommend instead to check for the existence of episode_ids; incidentally due to the change in measure.hbs this code is not currently hit for CQL-based measures

2017-02-16 18:34 UTC, c-monkey commented on app/controllers/measures_controller.rb
> +      measure['episode_ids'] = data['episode_ids'] if !is_cql
Done

2017-02-16 18:35 UTC, c-monkey commented on app/controllers/measures_controller.rb
> +      measure.generate_js(clear_db_cache: true) if !is_cql
Done

2017-02-16 18:48 UTC, mulcahyk commented on app/assets/javascripts/templates/measure.hbs
> +          {{#if cql}}
Here on line 26 you have `{{#if cql}}` but up on line 7 there is `{{#if isNotCQL}}`.  Can just one of these be used to avoid confusion?

2017-02-16 18:59 UTC, mulcahyk commented on app/controllers/measures_controller.rb
> +      if !is_cql
Ruby style: use **unless** instead of `if !something`.

2017-02-16 19:17 UTC, c-monkey commented on app/assets/javascripts/templates/measure.hbs
> +          {{#if cql}}
Done

2017-02-16 19:35 UTC, c-monkey commented on app/controllers/measures_controller.rb
> +      if !is_cql
Done

2017-02-16 20:55 UTC, jbradl11 approved these changes
Looks Good

2017-02-16 21:02 UTC, edeyoung commented on app/controllers/measures_controller.rb
> +    if !is_cql
here's another place for `unless`

2017-02-16 21:15 UTC, c-monkey commented on app/controllers/measures_controller.rb
> +    if !is_cql
Done

2017-02-16 21:25 UTC, edeyoung approved these changes

2017-02-16 21:45 UTC, merged