Addressed code review comments; pulled out CQL and QDM calculators
MeasureAuthoringTool/bonnie pull request #688
Opened 2017-03-08 14:39 UTC by jbradl11

2017-03-08 21:00 UTC, holmesie approved these changes

2017-03-09 19:13 UTC, c-monkey approved these changes
All changes requested in https://github.com/projecttacoma/bonnie/commit/20c49d59421943ca50000504d2d948b9672010ea appear to have been resolved.

2017-03-09 19:13 UTC, c-monkey commented on app/assets/javascripts/cql_calculator.js.coffee
> +     # Loop over all population codes ("IPP", "DENOM", etc.)
extraneous space

2017-03-09 19:13 UTC, c-monkey commented on app/assets/javascripts/cql_calculator.js.coffee
> +        index = if defined_pops.length > 1 then index else 0
why not `index = 0 unless defined_pops.length > 1`?

2017-03-14 13:09 UTC, edeyoung commented
For this comment, please add a TODO

![image](https://cloud.githubusercontent.com/assets/11574199/23902016/ee15a070-0895-11e7-86dd-72d83c193639.png)

2017-03-14 13:15 UTC, edeyoung requested changes

2017-03-14 13:15 UTC, edeyoung commented on app/assets/javascripts/cql_calculator.js.coffee
> +      result.state = 'cancelled'
This is for the code a few lines up. Should this be addressed? Or is it ok to have it be 'undefined' for new patients?

![image](https://cloud.githubusercontent.com/assets/11574199/23901384/5e1c9872-0893-11e7-97cc-02fdbb12a898.png)

2017-03-14 13:15 UTC, edeyoung commented on app/assets/javascripts/cql_calculator.js.coffee
> +        # before the parser returned multiple populations in an array.
when can we move away from this? Can you add a TODO here? I'd like to have this not be present for when we move the code to production when we'll be starting from scratch. Can we make a list of the measures that this is necessary for and ask the users to delete/re-upload them?

2017-03-14 13:15 UTC, edeyoung commented on app/assets/javascripts/cql_calculator.js.coffee
> +        cql_population = defined_pops[index]
I'm not sure this was addressed - i think more logic changes would have been needed. let's discuss to make sure I'm understanding the code properly.

![image](https://cloud.githubusercontent.com/assets/11574199/23901552/1e60de22-0894-11e7-9565-1f348e498f1c.png)

2017-03-14 13:15 UTC, edeyoung commented on app/assets/javascripts/cql_calculator.js.coffee
> +          if Array.isArray(value) and value.length > 0
Does this work with the episode of care changes?

2017-03-14 13:15 UTC, edeyoung commented on app/controllers/measures_controller.rb
>      begin
I think we still need to discuss this:

![image](https://cloud.githubusercontent.com/assets/11574199/23901896/8b549298-0895-11e7-9c93-80bb899c5ca2.png)

2017-04-04 19:12 UTC, edeyoung commented on app/controllers/measures_controller.rb
>      begin
explained - the upload logic is lower down and split into xml and zip loading types. the cql logic will be further integrated over time as we move towards supporting updates.

2017-04-13 01:19 UTC, jbradl11 commented on app/assets/javascripts/cql_calculator.js.coffee
> +      result.state = 'cancelled'
This works as expected.

2017-04-13 01:20 UTC, jbradl11 commented on app/assets/javascripts/cql_calculator.js.coffee
> +     # Loop over all population codes ("IPP", "DENOM", etc.)
Good catch. Updated.

2017-04-13 01:22 UTC, jbradl11 commented on app/assets/javascripts/cql_calculator.js.coffee
> +        # before the parser returned multiple populations in an array.
Added a TODO

2017-04-13 01:30 UTC, jbradl11 commented on app/assets/javascripts/cql_calculator.js.coffee
> +        index = if defined_pops.length > 1 then index else 0
I like it. Makes sense to me.

2017-04-13 13:21 UTC, jbradl11 commented on app/assets/javascripts/cql_calculator.js.coffee
> +          if Array.isArray(value) and value.length > 0
Yes it does. I believe this was your suggestion, and its much clearer compared to the previous version.

2017-04-13 17:55 UTC, edeyoung commented on app/assets/javascripts/cql_calculator.js.coffee
> +        cql_population = defined_pops[index]
Tohline, Adam, and I discussed. This is something Tohline will take a look at.

2017-04-14 18:41 UTC, edeyoung approved these changes
This set of changes appears to require a hard-reload for the user. When we deploy to staging, we'll need to confirm if users will need to clear their cache for this to work. if so, is there something we can do to make this easier for users?

2017-04-18 12:36 UTC, merged