Cql4bonnie qdm 5.01
MeasureAuthoringTool/bonnie pull request #692
Opened 2017-03-22 17:50 UTC by mayerm94

2017-03-29 14:33 UTC, c-monkey requested changes
Looks good. My trivial suggestions should take you like 5 minutes.

2017-03-29 14:33 UTC, c-monkey commented on Gemfile
> -# gem 'health-data-standards', :path => '../health-data-standards'
More nitpicky feedback: these extra whitespace should be removed.

2017-03-29 14:33 UTC, c-monkey commented on Gemfile
> +gem 'health-data-standards', :git => 'https://github.com/projectcypress/health-data-standards.git', :branch => 'QDM-5.02-CQL'#'cql4bonnie'
You should clean up these changes, get rid of the commented-out branches. Ideally, we should integrate the QDM-5.0* branches into cql4bonnie and revert these altogether. Is there a reason to merge this pull request into cql4bonnie before we merge the other 2 into cql4bonnie?

2017-03-29 14:33 UTC, c-monkey commented on app/assets/javascripts/templates/patient_builder/edit_criteria.hbs
> +            {{log values}}
remove this and below debugging `log` statements

2017-03-29 14:33 UTC, c-monkey commented on app/assets/javascripts/templates/patient_builder/edit_value.hbs
> +
remove this extra line of whitespace

2017-03-29 16:33 UTC, mayerm94 commented on Gemfile
> +gem 'health-data-standards', :git => 'https://github.com/projectcypress/health-data-standards.git', :branch => 'QDM-5.02-CQL'#'cql4bonnie'
The dependencies will need to be merged into cql4bonnie before this pull request can be merged. I kept the changes in this file so that those who pull down this won't have broken builds due to incorrect dependency versions.

2017-03-29 17:18 UTC, c-monkey commented on Gemfile
> +gem 'health-data-standards', :git => 'https://github.com/projectcypress/health-data-standards.git', :branch => 'QDM-5.02-CQL'#'cql4bonnie'
My assumption was that it would be preferable to have that merge happen first - do we have a convention? The only advantage would be we wouldn't have to create a separate pull request to update the Gemfile - but that's really no biggie.

2017-03-29 17:18 UTC, c-monkey approved these changes
Thank you

2017-04-05 15:38 UTC, edeyoung requested changes

2017-04-05 15:38 UTC, edeyoung commented on Gemfile
> +#  gem 'hqmf2js', path: '../hqmf2js'
before this pull request gets integrated completely, the gemfile file should look unchanged (all branches should reference cql4bonnie once those branches have been updated, all extraneous spaces should be removed, etc.)

2017-04-05 15:38 UTC, edeyoung commented on app/assets/javascripts/templates/patient_builder/edit_criteria.hbs
> +          {{#ifCond type '==' "COL"}}
`COL` makes me think of column. Maybe `COLL`? Or `CLTN`?

this is a nitpick, so don't worry about changing if you don't like either of my suggestions. As long as there's an explanatory comment somewhere defining it, I think it makes sense. I'd say to put a comment here, but that's tricky to do.

2017-04-05 15:38 UTC, edeyoung commented on Gemfile
> +gem 'health-data-standards', :git => 'https://github.com/projectcypress/health-data-standards.git', :branch => 'QDM-5.02-CQL'#'cql4bonnie'
cql4bonnie should be updated to the QDM 5.0 work at this point. this can be modified now.

2017-04-05 15:38 UTC, edeyoung commented on app/assets/javascripts/views/patient_builder/data_criteria.js.coffee
> +        $(e.target).model().collection.add clone
i'm confused about the comments and what is happening in the code.

if there are no items left, wouldn't `.length == 0` rather than `.length > 0`?

Does adding the clone to the target model make it get destroyed in the later `destroy` call?

why are we cloning the model?

2017-04-05 15:38 UTC, edeyoung commented on app/assets/javascripts/views/patient_builder/data_criteria.js.coffee
> +       @values.add col
It looks like we do the following:

* clone col from values
* remove col from values
* add to cloned col
* add cloned col to values

Why do we need to do the cloning/removing/adding business? Can we just do this?

* retrieve col from values
* add to col

2017-04-05 15:38 UTC, edeyoung commented on app/assets/javascripts/views/patient_builder/data_criteria.js.coffee
> -
watch white space changes

2017-04-05 15:38 UTC, edeyoung commented on app/assets/javascripts/views/patient_builder/data_criteria.js.coffee
> +       @values.remove @values.findWhere(key: @model.get('key'))
The lines above were confusing for me to read and I think would be helped by some variables:

```
   if @model.get('type') == "CMP"
       compare_collection = @values.findWhere(key: compare_key)
       if compare_collection
         col = compare_collection.clone()
       @values.remove compare_collection
```

2017-04-05 15:38 UTC, edeyoung commented on app/assets/javascripts/views/patient_builder/data_criteria.js.coffee
> +         col = @values.findWhere(key: @model.get('key')).clone()
why are we cloning this?

2017-04-05 15:38 UTC, edeyoung commented on app/assets/javascripts/views/patient_builder/data_criteria.js.coffee
> +       @values.remove @values.findWhere(key: @model.get('key'))
should `@values.remove...` be indented to be under the `if` statement? It doesn't hurt to have it outside, but it seems like it makes the most sense to have it outside.

2017-04-05 15:38 UTC, edeyoung commented on app/assets/javascripts/views/patient_builder/data_criteria.js.coffee
> +         col.get('values').push @model.clone().toJSON()
I think you can rewrite this section as:

```
       if !col
         col = {'key': @model.get('key'), 'type': "COL",'values': []}
       # Push the JSON object representation instead of the backbone model
       # The values when sent and saved are JSON objects, not backbone models
       col.get('values').push @model.clone().toJSON()
```

because at this point you know that `col` exists so can add to it outside of the `if` statement.

2017-04-05 15:38 UTC, edeyoung commented on lib/measures/patient_builder.rb
> +        fields.select{|key,value| value["type"] == "COL"}.values.each {|collection| collection["values"].each{ |value| recursive_field_value_oid_concat({'VALUE'=>value}, oids)}}
take a look at splitting this across multiple lines. There's a lot of logic to follow in a single line and this will be hard to debug if there are any issues.

2017-04-05 15:38 UTC, edeyoung commented on lib/measures/patient_builder.rb
> +    def self.recursive_field_value_oid_concat(fields,oids)
add a comment explaining the purpose of this function and how it supports collection types.

2017-04-05 15:38 UTC, edeyoung commented on lib/measures/patient_builder.rb
> +      field_value = {}
why did this get moved out of the if statement? It looks like the assignment to `{}` is only relevant for the first if statement. everything else does a straight assignment. Moving it outside makes it seem like it should always be a dict.

2017-04-05 15:38 UTC, edeyoung commented on lib/measures/patient_builder.rb
> +      field_accessor = nil
removed a newline which was nice for readability. Please add back in

2017-04-05 15:38 UTC, edeyoung commented on lib/measures/patient_builder.rb
> +        # will have to add code here if range exists
Make this a TODO statement

2017-04-05 15:38 UTC, edeyoung commented on lib/measures/patient_builder.rb
> +        # will have to add code here if range exists
make this a TODO statement

2017-04-05 15:38 UTC, edeyoung commented on lib/measures/patient_builder.rb
> +        # recur through entry
"recur" -> "recurse" I think

2017-04-05 15:38 UTC, edeyoung commented on lib/measures/patient_builder.rb
> +    def self.recursive_field_value_derivation(value, value_sets, name, entry)
add a comment to this function explaining what it does and why it exists (the collection field value types)

2017-04-05 15:38 UTC, edeyoung commented on test/unit/patient_builder_test.rb
> +                                                                            HealthDataStandards::SVS::Concept.new({"code_system_name" => "LOINC", "code" =>"CHACHA1"})]})
Why add new value set components rather than use the existing ones?

2017-04-05 15:38 UTC, edeyoung commented on test/unit/patient_builder_test.rb
> +    assert_equal 2, entry.components.values.length
is it worth testing the values as well to ensure that things were serialized/deserialized as expected?

2017-04-05 16:37 UTC, holmesie commented on app/assets/javascripts/templates/patient_builder/edit_criteria.hbs
> +          {{#ifCond type '==' "COL"}}
Does `COL` come from HDS (the parser or related code)? If that is the case, I've always hated how we use abbreviations for things like this, I still don't even know what some of them mean. Honestly I think it might be worth spelling out the entire thing, it's not like verbosity costs us anything. Very much a non-issue with this pull request, and we might just want to go with consistency - but still might be worth considering.

2017-04-05 16:42 UTC, holmesie approved these changes
Besides Lizzie's requested changes - looks good to me.

2017-04-07 15:23 UTC, mayerm94 commented on app/assets/javascripts/views/patient_builder/data_criteria.js.coffee
> +       @values.remove @values.findWhere(key: @model.get('key'))
Good call!

2017-04-07 18:22 UTC, mayerm94 commented on app/assets/javascripts/views/patient_builder/data_criteria.js.coffee
> +         col.get('values').push @model.clone().toJSON()
It cannot be changed to this because after the col is created, the values are accessed as col['values'] and when the collection already exists, the values are accessed as attributes on the col object using col.get('values')

2017-04-07 18:31 UTC, mayerm94 commented on app/assets/javascripts/views/patient_builder/data_criteria.js.coffee
> +       @values.add col
The whole addition/deletion process was a workaround to force a change event to be thrown so that the UI would update. Attempts to manually throw the change event did not work.

2017-04-07 18:44 UTC, mayerm94 commented on app/assets/javascripts/views/patient_builder/data_criteria.js.coffee
> +         col = @values.findWhere(key: @model.get('key')).clone()
I believe the cloning was a forgotten relic. I have removed cloning and behavior is unchanged.

2017-04-07 19:40 UTC, edeyoung commented on app/assets/javascripts/views/patient_builder/data_criteria.js.coffee
> +         col.get('values').push @model.clone().toJSON()
hm. That's concerning. The access should be the same. If it's different, things accessing it down the road will have issues. Is one a thorax object and the other a dict? If so, both should be thorax objects or both should be dicts.

2017-04-07 19:41 UTC, edeyoung commented on app/assets/javascripts/views/patient_builder/data_criteria.js.coffee
> +       @values.add col
@hossenlopp do you know how to force the UI update without the add/delete process?

@mayerm94 if there's not another way to do this, comment. My motto: "if you need to do something weird, comment."

2017-04-10 17:46 UTC, mayerm94 commented on lib/measures/patient_builder.rb
> +        # recur through entry
Tomato tomato (Made the change anyhow because I think a lot of people prefer recurse)

2017-04-10 18:14 UTC, mayerm94 commented on lib/measures/patient_builder.rb
> +      field_value = {}
I moved it to its own if statement so that if value was a non-number there would not be an error thrown when we try do do math on value for time conversion.

2017-04-10 18:16 UTC, mayerm94 commented on test/unit/patient_builder_test.rb
> +                                                                            HealthDataStandards::SVS::Concept.new({"code_system_name" => "LOINC", "code" =>"CHACHA1"})]})
I just wanted it to match what existed (and has since been removed in HDS rendering this change meaningless) for the value sets used for component.

2017-04-11 15:30 UTC, edeyoung commented on app/assets/javascripts/views/patient_builder/data_criteria.js.coffee
> +    if $(e.target).data('col-item-index')?
add a comment explaining the clone/destroy sequence to ensure that change events are triggered.

add a comment that this `if` statement is related to the new collection types and managing those appropriately.

2017-04-11 15:30 UTC, edeyoung commented on app/assets/javascripts/views/patient_builder/data_criteria.js.coffee
> +      # This prevents us from having an empty collection in our model when the last item in the collection is deleted
phrase this "positively":

"We only add non-empty collections"

2017-04-11 15:30 UTC, edeyoung commented on app/assets/javascripts/views/patient_builder/data_criteria.js.coffee
> +         col = {'key': @model.get('key'), 'type': "COL",'values': []}
make this a thorax object to be consistent with what comes back from the compare collection. this makes it so access will be the same for each col object.

2017-04-11 15:30 UTC, edeyoung commented on app/assets/javascripts/views/patient_builder/data_criteria.js.coffee
> +    if @model.get('type') == "CMP"
add comment for clone/delete process and this needing to be done to trigger a change event.

2017-04-11 15:30 UTC, edeyoung commented on lib/measures/patient_builder.rb
> +    # This function recursively searches through a collection of field values and returns the oids associated with the
make comment work with "rubydocs" (or whatever it's called).

Ask hoss if you can't find examples.

2017-04-11 15:30 UTC, edeyoung commented on lib/measures/patient_builder.rb
> +    def self.recursive_field_value_derivation(value, value_sets, name, entry)
add comment

2017-04-11 15:30 UTC, edeyoung commented on lib/measures/patient_builder.rb
> +      field_value = {}
sometimes a dict is assigned directly. sometimes it's built off of the `{}` foundation. either way, it's a dict, so this makes sense where it is.

2017-04-11 15:30 UTC, edeyoung commented on test/unit/patient_builder_test.rb
> +                                                                            HealthDataStandards::SVS::Concept.new({"code_system_name" => "CPT", "code" =>"CHACHA1"})]}),
remove extra comma

2017-04-12 19:11 UTC, mayerm94 commented
Rake test causing the travis test will continue to fail until https://github.com/projectcypress/health-data-standards/pull/483 is merged in

2017-04-13 17:52 UTC, edeyoung requested changes

2017-04-13 17:52 UTC, edeyoung commented on app/assets/javascripts/views/patient_builder/data_criteria.js.coffee
> +      # Clone the model and remove from the clone and then add the cloned model to the collection so that the UI change even it triggered
typo: `change even it triggered`

2017-04-13 17:52 UTC, edeyoung commented on app/assets/javascripts/views/patient_builder/data_criteria.js.coffee
> +       debugger
remove debugger statement

2017-04-18 13:18 UTC, edeyoung commented
To test, use:

[DepRem12Mo_v5_1_Artifacts (5)[1].zip](https://github.com/projecttacoma/bonnie/files/929757/DepRem12Mo_v5_1_Artifacts.5.1.zip)

you will have to point HDS to QDM-5.02-CQL and point the cql_qdm_patientapi to CQL_QDM_5.01_Updates in the Gemfile.

2017-04-18 14:56 UTC, edeyoung approved these changes

2017-04-18 17:53 UTC, edeyoung commented
failing check is due to reference to old hds. hds reference needs to be updated once hds is updated.

2017-04-18 18:32 UTC, c-monkey approved these changes
works, when testing as described by lizzie

2017-04-18 19:48 UTC, merged