Initial implementation of client side error handling using Costanza
MeasureAuthoringTool/bonnie pull request #694
Opened 2017-03-27 19:53 UTC by holmesie

Particular client side errors are now passed to the backend for inspection. For known errors, the backend crafts a more helpful error message that is passed back to the front end, to be displayed to the user in a flash message. Errors are also now emailed to the development team if seen in a production deployment.

Instructions for adding new types of known front end errors:
https://github.com/projecttacoma/bonnie/wiki/Adding-custom-error-messages-for-front-end-errors

This prevents the usual "blank screen" issue when JavaScript errors prevent the rest of certain pages from being loaded.

For testing, see: https://oncprojectracking.healthit.gov/support/projects/BONNIE/issues/BONNIE-226

2017-03-28 13:21 UTC, jbradl11 commented on app/assets/javascripts/calculator.js.coffee
> +        Costanza.run 'measure-calculation', {cms_id: result.measure.get('cms_id')}, () =>
I would recommend a comment here (and in the data_criteria_logic_view) explaining what is happening on this line.

2017-03-28 13:21 UTC, jbradl11 commented on app/assets/javascripts/views/logic/data_criteria_logic_view.js.coffee
> +    Costanza.run 'data-criteria-logic-view-creation', {reference: @reference}, () =>
Recommend adding a comment. Same as above.

2017-03-29 22:01 UTC, c-monkey reviewed
I didn't run it, but seems logical. Your screen capture seems superior.

2017-03-29 22:01 UTC, c-monkey commented on app/assets/javascripts/application.js.coffee
> -#= require cql_qdm_patientapi
Why was this block moved? It makes the diff less clear. The only actual change to this file is the addition of costanza. Or, was there a need to move this block due to a compiler error?

2017-03-29 22:01 UTC, c-monkey commented on app/helpers/error_helper.rb
> +    when /data-criteria-logic-view-creation/
Managing a lot of errors would get messy here, but assuming we refactor the implementation if it becomes burdensome, this is fine for now.

2017-03-29 22:20 UTC, hossenlopp requested changes

2017-03-29 22:20 UTC, hossenlopp commented on app/assets/javascripts/error_handler.js.coffee
> +    success: (message) ->
Perhaps the error handler should be implemented here too. If the server fails for some reason responding to the client_error the user will not see an error message at all.

2017-03-29 22:20 UTC, hossenlopp commented on config/routes.rb
> +  match 'application/client_error' => 'application#client_error', :via => :get
Why not use the following line?
```
get '/application/client_error' => 'application#client_error'
```

Why is this implemented as a GET? Wouldn't a POST make more sense for this sort of thing?

2017-03-29 22:20 UTC, hossenlopp commented on app/helpers/error_helper.rb
> +  def self.send_email(error_info)
Have you gotten to test the email sending to see if the mail received has enough info to denote it is a front end error and where it happened?

2017-03-29 22:34 UTC, holmesie commented on app/assets/javascripts/error_handler.js.coffee
> +    success: (message) ->
Agreed, that makes sense

2017-03-29 22:38 UTC, holmesie commented on config/routes.rb
> +  match 'application/client_error' => 'application#client_error', :via => :get
So the communication workflow goes: frontend => backend => frontend; meaning the frontend is essentially 'requesting' more information about an error, which made me think a GET makes the most sense, although I'm open to debate about it.

2017-03-29 22:43 UTC, holmesie commented on app/helpers/error_helper.rb
> +  def self.send_email(error_info)
For this I'd have to defer to what exactly a Costanza error looks like (see my link to that repo for more info), which is already way better than the usual `window.onerror`. That in addition to the Rails `current_user` being included in this email gives us enough info to look into potential issues (in my opinion).

2017-03-29 22:47 UTC, holmesie commented on app/assets/javascripts/application.js.coffee
> -#= require cql_qdm_patientapi
Yeah, this was a tricky change. The ace editor seems to seriously mess with our `window` namespaces; specifically, loading Costanza (which uses things like `module`) after ace.js causes serious issues (ace.js is used in the learn CQL tool). Loading Costanza before ace.js fixes those errors completely. I think this might justify more investigation into what ace.js is actually doing - but since we are planning on removing ace.js eventually in favor of generating our own human readable, perhaps that isn't worth the effort.

2017-03-29 22:50 UTC, holmesie commented on app/helpers/error_helper.rb
> +    when /data-criteria-logic-view-creation/
Agreed - perhaps a more "human readable" YAML configuration file containing this information might be more maintainable. I am not opposed to doing that work in this pull request (not too difficult). Thoughts?

2017-03-29 22:52 UTC, holmesie commented on config/routes.rb
> +  match 'application/client_error' => 'application#client_error', :via => :get
As to my using `match` here - just a habit with the Rails work I've done. What is the best practice in this case?

2017-03-30 14:39 UTC, c-monkey commented on app/helpers/error_helper.rb
> +    when /data-criteria-logic-view-creation/
I'm not a fan of over-engineering a solution before we have a problem. It is desirable to validate correspondence between the string in the error handler and the one in the `Costanza.run` match. Perhaps defining the set of errors in code that is shared via an .erb coffeescript module? That sounds trivial and can't get out of sync.

2017-03-30 14:41 UTC, c-monkey commented on config/routes.rb
> +  match 'application/client_error' => 'application#client_error', :via => :get
My only comment, w/out knowing Ruby best practices, is that consistency is golden. All the rest of the string matches are done with the `get` statement, so this wouldn't look different. There is no reason not to be consistent in this case.

2017-03-30 14:42 UTC, c-monkey commented on app/assets/javascripts/application.js.coffee
> -#= require cql_qdm_patientapi
Thanks for the explanation. I figured it wasn't arbitrary on your part, but it is good to confirm.

2017-03-30 14:44 UTC, c-monkey commented on app/assets/javascripts/calculator.js.coffee
> +        Costanza.run 'measure-calculation', {cms_id: result.measure.get('cms_id')}, () =>
Or, instead of a comment, a call to a helper method, as I ruminated on in my comment in `app/helpers/error_helper.rb` - the method would be documented once, rather than having to comment everywhere in the code.

2017-03-30 14:44 UTC, c-monkey commented on app/assets/javascripts/error_handler.js.coffee
> +    success: (message) ->
That's a really good idea. And trivial to test, just shut down your server.

2017-03-30 14:47 UTC, c-monkey requested changes

2017-03-30 14:47 UTC, c-monkey commented on app/helpers/error_helper.rb
> +  def self.send_email(error_info)
LOL, okay, now I can't consent to this pull request until I've tested seeing an email. I thought I was just poking at this code review, but it seems like a reasonable request that all its functionality has be executed.

2017-04-03 13:35 UTC, hossenlopp commented on config/routes.rb
> +  match 'application/client_error' => 'application#client_error', :via => :get
I think `match` is used for more complex routing situations.

In regards to using a POST: I see it as the frontend is POSTing an error to the server for it's logging purpose. It happens to maybe get useful stuff in the response. Using a GET request means all that data goes in query parameters, which means character encoding fun. Some browsers also chop off long query parameters. Additionally, if the same error happens the GET request could get cached and we won't get a report of that error happening.

2017-04-03 13:39 UTC, holmesie commented on config/routes.rb
> +  match 'application/client_error' => 'application#client_error', :via => :get
@hossenlopp Agreed, I think that reasoning makes sense and is enough to merit a change

2017-04-03 14:34 UTC, holmesie commented on app/helpers/error_helper.rb
> +    when /data-criteria-logic-view-creation/
Not so sure that would be as trivial as you think; mixing ERB with a JavaScript framework like Thorax and also pulling from that in the back end seems like it would introduce more complication than is necessary, while not really giving much benefit. I think your first comment seems to make the most sense on second thought.

2017-04-04 00:25 UTC, edeyoung commented on app/helpers/error_helper.rb
> +  def self.send_email(error_info)
There's an outstanding PR that hasn't been incorporated that sends emails because we haven't been able to test that. I believe someone mentioned that we can send up bonnie-review to send emails. Since this also has email settings, can we do that? I think this is a really important PR to incorporate and it would be nice to get that other one incorporated too.

2017-04-04 00:27 UTC, edeyoung reviewed
I'll defer to Tohline and Hoss's acceptance with an emphasis on Tohline's requirement to test that email works.

Looks good and will be a really great modification for Bonnie. Thanks!

2017-04-07 22:18 UTC, c-monkey commented
I loaded the issue described in https://oncprojectracking.healthit.gov/support/browse/BONNIE-226
(https://oncprojectracking.healthit.gov/support/secure/attachment/24379/OCM7_PrCA_AdjuvantHormonalTx_v4_3_Artifacts%20%286%29.zip)

I saw this work in some context when I was looking at it with you Adam, but don't remember where...anyway, it isn't working now. Getting this error in my local console, and no user error in the browser, although I do get a console error [Failed to load resource: the server responded with a status of 400 (Bad Request)]

Invalid request: HTTP element QUERY_STRING is longer than the (1024 * 10) allowed length.
	/Users/ctohline/.rvm/gems/ruby-2.3.0/gems/thin-1.6.3/lib/thin/request.rb:84:in `execute'
	/Users/ctohline/.rvm/gems/ruby-2.3.0/gems/thin-1.6.3/lib/thin/request.rb:84:in `parse'
	/Users/ctohline/.rvm/gems/ruby-2.3.0/gems/thin-1.6.3/lib/thin/connection.rb:39:in `receive_data'
	/Users/ctohline/.rvm/gems/ruby-2.3.0/gems/eventmachine-1.0.7/lib/eventmachine.rb:187:in `run_machine'
	/Users/ctohline/.rvm/gems/ruby-2.3.0/gems/eventmachine-1.0.7/lib/eventmachine.rb:187:in `run'
	/Users/ctohline/.rvm/gems/ruby-2.3.0/gems/thin-1.6.3/lib/thin/backends/base.rb:73:in `start'
	/Users/ctohline/.rvm/gems/ruby-2.3.0/gems/thin-1.6.3/lib/thin/server.rb:162:in `start'
	/Users/ctohline/.rvm/gems/ruby-2.3.0/gems/rack-1.5.5/lib/rack/handler/thin.rb:16:in `run'
	/Users/ctohline/.rvm/gems/ruby-2.3.0/gems/rack-1.5.5/lib/rack/server.rb:264:in `start'
	/Users/ctohline/.rvm/gems/ruby-2.3.0/gems/railties-4.1.12/lib/rails/commands/server.rb:69:in `start'
	/Users/ctohline/.rvm/gems/ruby-2.3.0/gems/railties-4.1.12/lib/rails/commands/commands_tasks.rb:81:in `block in server'
	/Users/ctohline/.rvm/gems/ruby-2.3.0/gems/railties-4.1.12/lib/rails/commands/commands_tasks.rb:76:in `tap'
	/Users/ctohline/.rvm/gems/ruby-2.3.0/gems/railties-4.1.12/lib/rails/commands/commands_tasks.rb:76:in `server'
	/Users/ctohline/.rvm/gems/ruby-2.3.0/gems/railties-4.1.12/lib/rails/commands/commands_tasks.rb:40:in `run_command!'
	/Users/ctohline/.rvm/gems/ruby-2.3.0/gems/railties-4.1.12/lib/rails/commands.rb:17:in `<top (required)>'
	/Users/ctohline/Projects/Bonnie/bonnie/bin/rails:9:in `require'
	/Users/ctohline/Projects/Bonnie/bonnie/bin/rails:9:in `<top (required)>'
	/Users/ctohline/.rvm/gems/ruby-2.3.0/gems/ruby-debug-ide-0.6.1.beta4/lib/ruby-debug-ide.rb:91:in `debug_load'
	/Users/ctohline/.rvm/gems/ruby-2.3.0/gems/ruby-debug-ide-0.6.1.beta4/lib/ruby-debug-ide.rb:91:in `debug_program'
	/Users/ctohline/.rvm/gems/ruby-2.3.0/gems/ruby-debug-ide-0.6.1.beta4/bin/rdebug-ide:156:in `<top (required)>'
	-e:1:in `load'
	-e:1:in `<main>'

Invalid request: HTTP element QUERY_STRING is longer than the (1024 * 10) allowed length.
	/Users/ctohline/.rvm/gems/ruby-2.3.0/gems/thin-1.6.3/lib/thin/request.rb:84:in `execute'
	/Users/ctohline/.rvm/gems/ruby-2.3.0/gems/thin-1.6.3/lib/thin/request.rb:84:in `parse'
	/Users/ctohline/.rvm/gems/ruby-2.3.0/gems/thin-1.6.3/lib/thin/connection.rb:39:in `receive_data'
	/Users/ctohline/.rvm/gems/ruby-2.3.0/gems/eventmachine-1.0.7/lib/eventmachine.rb:187:in `run_machine'
	/Users/ctohline/.rvm/gems/ruby-2.3.0/gems/eventmachine-1.0.7/lib/eventmachine.rb:187:in `run'
	/Users/ctohline/.rvm/gems/ruby-2.3.0/gems/thin-1.6.3/lib/thin/backends/base.rb:73:in `start'
	/Users/ctohline/.rvm/gems/ruby-2.3.0/gems/thin-1.6.3/lib/thin/server.rb:162:in `start'
	/Users/ctohline/.rvm/gems/ruby-2.3.0/gems/rack-1.5.5/lib/rack/handler/thin.rb:16:in `run'
	/Users/ctohline/.rvm/gems/ruby-2.3.0/gems/rack-1.5.5/lib/rack/server.rb:264:in `start'
	/Users/ctohline/.rvm/gems/ruby-2.3.0/gems/railties-4.1.12/lib/rails/commands/server.rb:69:in `start'
	/Users/ctohline/.rvm/gems/ruby-2.3.0/gems/railties-4.1.12/lib/rails/commands/commands_tasks.rb:81:in `block in server'
	/Users/ctohline/.rvm/gems/ruby-2.3.0/gems/railties-4.1.12/lib/rails/commands/commands_tasks.rb:76:in `tap'
	/Users/ctohline/.rvm/gems/ruby-2.3.0/gems/railties-4.1.12/lib/rails/commands/commands_tasks.rb:76:in `server'
	/Users/ctohline/.rvm/gems/ruby-2.3.0/gems/railties-4.1.12/lib/rails/commands/commands_tasks.rb:40:in `run_command!'
	/Users/ctohline/.rvm/gems/ruby-2.3.0/gems/railties-4.1.12/lib/rails/commands.rb:17:in `<top (required)>'
	/Users/ctohline/Projects/Bonnie/bonnie/bin/rails:9:in `require'
	/Users/ctohline/Projects/Bonnie/bonnie/bin/rails:9:in `<top (required)>'
	/Users/ctohline/.rvm/gems/ruby-2.3.0/gems/ruby-debug-ide-0.6.1.beta4/lib/ruby-debug-ide.rb:91:in `debug_load'
	/Users/ctohline/.rvm/gems/ruby-2.3.0/gems/ruby-debug-ide-0.6.1.beta4/lib/ruby-debug-ide.rb:91:in `debug_program'
	/Users/ctohline/.rvm/gems/ruby-2.3.0/gems/ruby-debug-ide-0.6.1.beta4/bin/rdebug-ide:156:in `<top (required)>'
	-e:1:in `load'
	-e:1:in `<main>'

2017-04-07 23:08 UTC, holmesie commented
I think I understand what is happening, I will get back to you on Monday.

2017-04-10 18:24 UTC, c-monkey approved these changes

2017-04-10 18:26 UTC, jbradl11 approved these changes

2017-04-14 13:42 UTC, hossenlopp requested changes

2017-04-14 13:42 UTC, hossenlopp commented on app/assets/javascripts/error_handler.js.coffee
> +      console.error(info) if info
This completely eats the error as far as the user is concerned. Perhaps the bonnie.showError() should be called to let them know there was an error but an issue with Bonnie or their connection prevented from more details being available.

2017-04-17 17:02 UTC, hossenlopp requested changes
Perhaps needs a more friendly message for errors from POSTing to client_error.

2017-04-17 17:02 UTC, hossenlopp commented on app/assets/javascripts/error_handler.js.coffee
> +      bonnie.showError({'body': info.status + ': ' + info.statusText}) if info
This results in very non-descript and ugly error. That info object is just jQXHR object. I ran a test where I loaded a broken measure after shutting the server down. (This could be similar to Bonnie going down or the user's network connection dying). It got double popups and didn't have much info. 
![uglyerror](https://cloud.githubusercontent.com/assets/11613067/25096368/e97f640e-236d-11e7-9040-97d523966616.gif)

2017-04-17 17:06 UTC, c-monkey commented on app/assets/javascripts/error_handler.js.coffee
> +      bonnie.showError({'body': info.status + ': ' + info.statusText}) if info
Thanks for testing this, we discussed it but I don't recall doing so.

2017-04-17 17:21 UTC, holmesie commented on app/assets/javascripts/error_handler.js.coffee
> +      bonnie.showError({'body': info.status + ': ' + info.statusText}) if info
Opinions for what the error message should say and consist of? I definitely do not want to be parsing 404s on the client side to make them look prettier, as in this case we are dealing with network issues, etc - and not calculation/measure logic issues.

2017-04-17 17:43 UTC, c-monkey commented on app/assets/javascripts/error_handler.js.coffee
> +      bonnie.showError({'body': info.status + ': ' + info.statusText}) if info
Random thoughts:
- Hoss, is your animated GIF showing the "ugly error" you refer to?
- Adam, can we fix the double-popup? When I load in some measure developers' dashboards there are tons of popups -- might we want to resolve this in the same fashion? If the 2 popups are identical, can we tell that and cull them? If that's the solution perhaps we should open another ticket.
- When Bonnie is getting an error due to a network outage, we don't really care, right? The existing text seems sufficient to me. Do we want power users to know the exact error? Assuming this is happening because we can't report the error to the mailing list, what is best for our needs?

2017-04-17 17:59 UTC, holmesie commented on app/assets/javascripts/error_handler.js.coffee
> +      bonnie.showError({'body': info.status + ': ' + info.statusText}) if info
Hmm, not so sure we can (or at least easily can). Errors are sent to the backend and dealt with on a case by case basis. If we tried to bundle similar things together, we might start approaching something that gets complicated quickly (e.g. do we wait X seconds an see if the same error comes in, and then tell the front end to only show things once?) - I'd really prefer to keep it simple in this case (even though the the same error showing multiple times isn't ideal).

To your third point, I totally agree - the error was caused by extenuating circumstances in this edge case, and isn't even remotely as important as the primary types of errors this pull request is trying to identify and describe (bad measure logic?, etc.). If a user did see this, and contacted us via mailing list/JIRA, we would instantly know either the server is down, or they had (seriously) intermittent network connectivity issues.

2017-04-18 12:26 UTC, hossenlopp commented on app/assets/javascripts/error_handler.js.coffee
> +      bonnie.showError({'body': info.status + ': ' + info.statusText}) if info
So the popups I captured were brought up in the error handler of the AJAX POST to /application/client_error. I turned off the server before clicking on the measure that breaks so the AJAX call would error out. I was surprised that the error was 404, since that's not a server response, the browser decided on 404 because the connection was rejected. I do wonder if this is consistent between browsers.

I think that if it is unable to succeed in the client_error call we should assume that the user's network connection dropped or Bonnie is down. The resulting error should say that.

2017-04-18 12:34 UTC, hossenlopp commented on app/assets/javascripts/error_handler.js.coffee
> +      bonnie.showError({'body': info.status + ': ' + info.statusText}) if info
What do people think of this? 
![connectionerror](https://cloud.githubusercontent.com/assets/11613067/25130860/c1f68166-2411-11e7-81f9-b3bacd0d9cfb.gif)

2017-04-18 13:13 UTC, holmesie commented on app/assets/javascripts/error_handler.js.coffee
> +      bonnie.showError({'body': info.status + ': ' + info.statusText}) if info
I'm thinking it should be more generic, what if it happens to be something other than 404? So rather than saying "Additionally, it appears...", we could say, "You may be experiencing network connectivity issues. Please check your network connection and reload." (or something like that).

Thoughts?

2017-04-18 13:36 UTC, c-monkey commented on app/assets/javascripts/error_handler.js.coffee
> +      bonnie.showError({'body': info.status + ': ' + info.statusText}) if info
Adam's solution we can implement in 5 minutes.

Hoss's solution we can implement in 60 minutes (unless we can't see the HTTP error code).

I think there's value in having different messages based on error code, but I guess I don't have enough information to be completely sure. What is the result on IE? Safari? Chrome? Firefox?

2017-04-18 20:39 UTC, hossenlopp approved these changes

2017-04-18 21:08 UTC, c-monkey approved these changes
tested on my machine using BonedensitywithPCaandADT_v4_6_eMeasure (1).xml

2017-04-19 15:41 UTC, merged