Bug fix of CQL support for stratifications
MeasureAuthoringTool/bonnie pull request #696
Opened 2017-03-31 18:39 UTC by c-monkey

See https://jira.mitre.org/browse/BONNIE-423

Note: must update this pull request with Gemfile change to point to https://github.com/projectcypress/health-data-standards/pull/484 after that change is merged.

2017-04-03 17:37 UTC, jbradl11 commented on app/assets/javascripts/cql_calculator.js.coffee
> +          index--
I would suggest a more detailed description as to what the special case is doing. For example, why are you calling "index--"?

2017-04-03 20:45 UTC, jbradl11 commented on app/assets/javascripts/cql_calculator.js.coffee
> +          # Ignore the STRAT popCode for "Population Criteria Section"
Is "Population Criteria Section" a user defined name? If so maybe we should change the description to match that.

2017-04-03 20:46 UTC, jbradl11 commented on app/assets/javascripts/cql_calculator.js.coffee
> +            continue
I would recommend rewriting this to "continue if index == 0"

2017-04-04 00:05 UTC, edeyoung requested changes
I think this needs clearer, longer comments. It's not clear to me why the given code had to be added.

2017-04-04 00:05 UTC, edeyoung commented on app/assets/javascripts/cql_calculator.js.coffee
> +          # Ignore the STRAT popCode for "Population Criteria Section"
what is the "population criteria section" and why does `index == 0` indicate the population criteria section?

2017-04-04 00:05 UTC, edeyoung commented on app/assets/javascripts/cql_calculator.js.coffee
> +          # stratification results array starts with 1st stratification 0-indexed
I'm confused about this.

why are we reducing the index? Do we assume all indices are 1 digit too high? But there's a 0th indexed one it looks like, we just don't add it? When/why does the 0th indexed one exists?

I think it would be worth adding a longer comment at the top of the `STRAT` section that explains the entire situation. The reason behind the special casing is not clear to me.

2017-04-04 16:24 UTC, c-monkey commented on app/assets/javascripts/cql_calculator.js.coffee
> +          # Ignore the STRAT popCode for "Population Criteria Section"
I guess it's the default in the MAT. Bonnie pulls the name from the HQMF section.

2017-04-04 16:24 UTC, c-monkey commented on app/assets/javascripts/cql_calculator.js.coffee
> +            continue
Fine by me

2017-04-04 16:26 UTC, c-monkey commented on app/assets/javascripts/cql_calculator.js.coffee
> +          # Ignore the STRAT popCode for "Population Criteria Section"
It's the name of the overall section #2 referenced in https://ecqi.healthit.gov/hqmf describing the High-level Structure.

I've added documentation to the code.

2017-04-04 16:58 UTC, c-monkey commented
Let's see how these comments read. Thanks

2017-04-04 20:15 UTC, jbradl11 approved these changes
This is much better. The new comments give me a better idea of what is going on.

2017-04-04 20:26 UTC, edeyoung approved these changes

2017-04-05 13:10 UTC, edeyoung requested changes
This is good, but I never ran it - i got caught up in, "my comments were addressed". Waiting for measure from Tohline. Once that works, I'll approve and we can incorporate.

2017-04-05 13:32 UTC, edeyoung approved these changes

2017-04-05 22:24 UTC, c-monkey commented
Sadly, this code doesn't work for CMS137!

Problem is we have 2 populations.

Our extraction code in HDS really seems to need to have an array of stratifications per population @holmesie @jbradl11 advice?

2017-04-18 17:51 UTC, edeyoung requested changes
the underlying hds commit did not properly accommodate non-strat functions. It's possible that this bonnie UI would actually do that. These need to be retested together with both a strat and a non-strat measure. the non-strat measure needs to be confirmed to NOT HAVE "STRAT" in the evaluation portion above the CQL view.

2017-05-17 17:02 UTC, c-monkey commented
Matt is reinventing the wheel on this puppy, closing this deprecated PR now.

2017-05-17 17:02 UTC, closed without merging