Fix bug that allows a CQL measure to be loaded twice
MeasureAuthoringTool/bonnie pull request #702
Opened 2017-04-18 12:32 UTC by mayerm94

2017-04-18 20:38 UTC, c-monkey approved these changes
tested extensively; I wish I knew what happened, but it all appears to be good now

2017-04-18 20:54 UTC, edeyoung requested changes

2017-04-18 20:54 UTC, edeyoung commented on app/controllers/measures_controller.rb
> +        if existing.count > 0
Please add a comment here that notes that this `existing.count` is intentionally different than the qdm one (1 vs 0). Please add a `TODO` noting that this should be more smoothly managed when the cql code is better incorporated in a future PR.

2017-04-19 17:14 UTC, edeyoung approved these changes

2017-04-19 17:23 UTC, merged