Fix issue with Patient Bank not loading
MeasureAuthoringTool/bonnie pull request #710
Opened 2017-04-26 19:12 UTC by mulcahyk

When a user goes to use the patient bank it appears to them that Bonnie has stopped responding.  The cause is a mongoid error.  This fixes that error.

Replace find method with keep_if

2017-04-27 14:23 UTC, c-monkey approved these changes
tested locally; fixes the bug

2017-04-27 16:13 UTC, holmesie requested changes

2017-04-27 16:13 UTC, holmesie commented on app/controllers/patients_controller.rb
> +    users = User.only(:_id, :email).to_a.keep_if { |u| user_ids.include?(u.id) }
Same as my comment on your master pull request:

I'm worried the to_a is making this less efficient than it needs to be.

Could you use where(id: user_ids)? find raises an exception if it couldn't find the object by the given id, but where will not.

That being said, this is MongoDB, so my concern might not even be worth it.

2017-04-27 17:16 UTC, c-monkey requested changes

2017-04-27 17:16 UTC, c-monkey commented on app/controllers/patients_controller.rb
> +    users = User.only(:_id, :email).to_a.keep_if { |u| user_ids.include?(u.id) }
+1 I agree with Adam.
Look at line 17 for almost exactly what you want, of course that's on Measure rather than User. Similar feedback was just added by @hossenlopp for the master branch PR.

2017-04-27 20:52 UTC, mulcahyk commented on app/controllers/patients_controller.rb
> +    users = User.only(:_id, :email).to_a.keep_if { |u| user_ids.include?(u.id) }
Done.

2017-05-01 15:24 UTC, c-monkey approved these changes
tested locally; fixes the bug

2017-05-01 15:43 UTC, holmesie approved these changes

2017-05-02 16:31 UTC, merged