Fix issue with Patient Bank not loading (master branch)
MeasureAuthoringTool/bonnie pull request #711
Opened 2017-04-26 20:34 UTC by mulcahyk

When a user goes to use the patient bank it appears to them that Bonnie has stopped responding. The cause is a mongoid error. This fixes that error.

Replace find with keep_if

2017-04-26 20:36 UTC, hossenlopp requested changes

2017-04-26 20:36 UTC, hossenlopp commented on app/controllers/patients_controller.rb
> +    debugger
Remove debugger line and commented out code.

2017-04-27 16:12 UTC, holmesie commented on app/controllers/patients_controller.rb
> +    users = User.only(:_id, :email).to_a.keep_if { |u| user_ids.include?(u.id) }
I'm worried the `to_a` is making this less efficient than it needs to be.

Could you use `where(id: user_ids)`? `find` raises an exception if it couldn't find the object by the given id, but where will not.

That being said, this is MongoDB, so my concern might not even be worth it.

2017-04-27 17:13 UTC, hossenlopp commented on app/controllers/patients_controller.rb
> +    users = User.only(:_id, :email).to_a.keep_if { |u| user_ids.include?(u.id) }
Looking at line 17 in this file. It is fetching based on the user_ids.

```
:user_id.in => user_ids
```

2017-04-27 18:56 UTC, mulcahyk reviewed
Made the updates that reviewers asked for.

2017-04-27 19:18 UTC, closed without merging