CQL JSON ELM based logic views with highlighting
MeasureAuthoringTool/bonnie pull request #723
Opened 2017-05-11 14:45 UTC by hossenlopp

- Replaces use of ACE Editor in the logic view.
- View for each define statement that gets highlighted from execution engine results.
- Used in patient builder as well with patient data highlighting for defines that result in a list of entries.

2017-05-11 18:02 UTC, holmesie requested changes

2017-05-11 18:02 UTC, holmesie commented on app/assets/javascripts/templates/logic/cql_logic.hbs
> +{{#if isOutdatedUpload}}
This won't be required when we eventually deploy to staging. I'd recommend adding a TODO here mentioning that.

2017-05-11 18:02 UTC, holmesie commented on app/assets/javascripts/views/logic/cql_logic_view.js.coffee
> +  @SKIP_STATEMENTS = ["SDE Ethnicity", "SDE Payer", "SDE Race", "SDE Sex"]
Why the capitals? Coffeescript doesn't have a `const`, and I don't think we do this anywhere else. Doesn't the `@` make it important enough?

2017-05-11 18:02 UTC, holmesie commented on app/assets/javascripts/views/logic/cql_logic_view.js.coffee
>  class Thorax.Views.CqlPopulationLogic extends Thorax.Views.BonnieView
Thoughts on moving this class to its own file? It seems big enough.

2017-05-11 18:02 UTC, holmesie commented on app/assets/javascripts/views/logic/cql_logic_view.js.coffee
> +    _.each @model.get('elm').library.statements.def, (statement) =>
Maybe add a few `?` null checks here?

2017-05-11 18:02 UTC, holmesie commented on app/assets/javascripts/views/logic/cql_logic_view.js.coffee
> +        if (statement.annotation[0].s.value[0] == "define ")
Why the space at the end of `"define "`? Is that what is in the ELM? A comment might help with my confusion about this.

2017-05-11 18:02 UTC, holmesie commented on app/assets/javascripts/views/logic/cql_logic_view.js.coffee
> +    if result == true  # Specifically a boolean true
I think there is similar logic in at least the cql_calculator (checking for the result type). Since this is the second place this logic exists, maybe we should move this to a central location. Thoughts?

2017-05-11 18:02 UTC, holmesie commented on app/assets/javascripts/views/logic/cql_logic_view.js.coffee
> +    @text = @statement.annotation[0].s.value[0]
Maybe null check here? Who knows what this structure might look like in weird cases.

2017-05-16 13:04 UTC, hossenlopp commented on app/assets/javascripts/templates/logic/cql_logic.hbs
> +{{#if isOutdatedUpload}}
Won't we need it when we deploy to staging since some people may still have uploaded on previous versions of the translation service?

2017-05-16 13:09 UTC, holmesie commented on app/assets/javascripts/templates/logic/cql_logic.hbs
> +{{#if isOutdatedUpload}}
Typo, meant production.

2017-05-16 13:10 UTC, hossenlopp commented on app/assets/javascripts/views/logic/cql_logic_view.js.coffee
> +  @SKIP_STATEMENTS = ["SDE Ethnicity", "SDE Payer", "SDE Race", "SDE Sex"]
I was following general guidelines that have the constant things capitalized. I think you may be right that in some places in Bonnie we don't capitalize constants. Here is a relevant article on the topic. https://coffeescript-cookbook.github.io/chapters/classes_and_objects/class-variables-and-instance-variables.

Let me know if you think I should change it.

2017-05-16 13:11 UTC, hossenlopp commented on app/assets/javascripts/templates/logic/cql_logic.hbs
> +{{#if isOutdatedUpload}}
Ahh yes. I will add the comment on that so we remember to remove once CQL settles down for production.

2017-05-16 13:14 UTC, hossenlopp commented on app/assets/javascripts/views/logic/cql_logic_view.js.coffee
> +        if (statement.annotation[0].s.value[0] == "define ")
I'll add some comments explaining this check better. The space comes after the "define" in the clause level annotation probably because it needs the space to end the keyword.

2017-05-16 13:16 UTC, hossenlopp commented on app/assets/javascripts/views/logic/cql_logic_view.js.coffee
> +    if result == true  # Specifically a boolean true
This is looking at the specific result for a statement (define). I will look at that code and see if it makes sense.

2017-05-16 13:17 UTC, holmesie commented on app/assets/javascripts/views/logic/cql_logic_view.js.coffee
> +  @SKIP_STATEMENTS = ["SDE Ethnicity", "SDE Payer", "SDE Race", "SDE Sex"]
Nope, your link was very informative. I think you should keep it.

2017-05-16 15:14 UTC, hossenlopp commented on app/assets/javascripts/views/logic/cql_logic_view.js.coffee
>  class Thorax.Views.CqlPopulationLogic extends Thorax.Views.BonnieView
In QDM land these are in the same file. I think The CQL Statement view should be moved to it's own file.

2017-05-16 17:48 UTC, jbradl11 approved these changes
Looks good.

2017-05-16 18:37 UTC, holmesie approved these changes

2017-05-16 19:36 UTC, hossenlopp commented
Rebased against the cql4bonnie branch.

2017-05-16 20:47 UTC, c-monkey commented
I tested this against "TESTCMS9_GA" from https://oncprojectracking.healthit.gov/support/browse/BONNIE-237 and am confused by the highlighting. Let's discuss.

2017-05-17 13:39 UTC, c-monkey approved these changes
This runs locally and looks great.

2017-05-17 13:39 UTC, merged