BONNIE-671 Improves performance.
MeasureAuthoringTool/bonnie pull request #758
Opened 2017-06-20 19:08 UTC by alexanderelliott121

Changes the algorithm to use maps to reduce number of required iterations.

2017-06-20 19:20 UTC, c-monkey commented
This was previous last revised in: https://github.com/projecttacoma/bonnie/commit/07474bb69e2b2a7f2851c66272c8836414b38a4e

Alex's change gets rid of bi-directional overlapping codes. Should he add these back in? Do we know the customer's needs?

2017-06-20 19:42 UTC, c-monkey commented
This PR is in response to:
https://oncprojectracking.healthit.gov/support/browse/BONNIE-271

On my local machine, run time for the 6/19 production backup version of "laura.vandenbosch@relayhealth.com" account measure CMS166V6
http://localhost:3000/#measures/B6016B47-B65D-4BE0-866F-1D397886CA89
this goes takes about 70s w/out the fix and 12s with it.

The general issue is these value sets are giant and the algorithm to check for overlapping value sets is very slow.

2017-06-20 20:56 UTC, c-monkey commented
![screen shot 2017-06-20 at 4 51 59 pm](https://user-images.githubusercontent.com/22219041/27355498-3a9e055a-55d9-11e7-9aae-095cafc808dc.png)

Screen shot of new (left) versus old (right), the difference is in the overlapping value sets. If you want to play with this yourself, try CMS53V5

2017-06-20 21:27 UTC, mulcahyk commented on app/assets/javascripts/views/measure_value_sets.js.coffee
> +        name2: valueSet2.name
Looks like you might be missing an ending CRLF.

2017-06-20 21:40 UTC, hossenlopp requested changes
Add some comments explaining what is going on here. Especially explain the hashes used for accumulating data while looping through.

Also add that missing CLRF.

2017-06-20 21:48 UTC, mulcahyk reviewed
I second Chris H's comment.
It would also be good to add back the comment about the codes being pageable.

2017-06-21 13:25 UTC, edeyoung commented
Having the lists duplicated I think was a very conscious decision to make sure that the items were as findable as possible. I think that this can still be done with the more efficient approach. I think we could just take the list that's there and copy everything and flip the primary and secondary value sets.

2017-06-21 13:30 UTC, edeyoung commented on app/assets/javascripts/views/measure_value_sets.js.coffee
> +      @overlappingValueSets.add
in order to get both sets of entries like existed before these changes, you can just add another object but swap the `oid1`/`name1` and `oid2`/`name2` entries. This will make the output match what it was before.

2017-06-21 16:24 UTC, c-monkey reviewed
I have not had time to test. Have we tested against CMS53V5?

2017-06-21 16:24 UTC, c-monkey commented on app/assets/javascripts/views/measure_value_sets.js.coffee
> +    #Outer loop itterates over valueSets, inner loop itterates over contained codes.
There is only 1 't' in the word "iterates"

2017-06-21 16:24 UTC, c-monkey commented on app/assets/javascripts/views/measure_value_sets.js.coffee
> +    #If it hasn't populate it with an empty array.
Add a comma after "hasn't" and consider rewriting to start this sentence on the previous line.

2017-06-22 13:24 UTC, hossenlopp commented
Tested CMS53v5 with the latest revision.

![image](https://user-images.githubusercontent.com/11613067/27436181-766a7a06-572c-11e7-9617-61d276b50285.png)

2017-06-22 13:24 UTC, hossenlopp approved these changes

2017-06-22 14:44 UTC, c-monkey approved these changes

2017-06-22 19:20 UTC, merged