CQL Logic Improvements BONNIE-669
MeasureAuthoringTool/bonnie pull request #760
Opened 2017-06-22 21:10 UTC by hossenlopp

-Does not highlight statements that define populations that are not being considered.
-The logic for this is stopgap until we move it and have clause level highlighting.

2017-06-23 12:53 UTC, edeyoung requested changes
Mostly questions

2017-06-23 12:53 UTC, edeyoung commented on app/assets/javascripts/views/logic/cql_logic_view.js.coffee
> +  _makePopulationResultShownMap: (result) ->
how does this work with multiple populations or multiple stratifications? Is the `result` object already split up by population so you only have one IPP inside, or are there potentially `IPP_1`, `IPP_2`, etc.?

2017-06-23 12:53 UTC, edeyoung commented on app/assets/javascripts/views/logic/cql_statement_view.js.coffee
> +      if result.length == 1 && result[0] == null # But if the array has one element that is null. Then we should make it red.
I know this is an edge case that you're handling - do we have a ticket to investigate why this is something that's being returned? It doesn't seem like this is a good value to have be returned and mean false.

2017-06-23 12:53 UTC, edeyoung commented on app/assets/javascripts/views/logic/cql_statement_view.js.coffee
> +    else if result == null  # Specifically no result
should no result be colored white instead of false? What does no result mean? Since everything gets executed, I'm guessing it shouldn't be colored white.

However - if these is a valid result than all my grandiose ideas about doing the "should this exist" at the calculation stage before the result gets passed back may not work out. How would we appropriately signal "this shouldn't be processed" if null is taken up already? Maybe a separate hash like what hoss has here?

2017-06-23 12:53 UTC, edeyoung commented on app/assets/javascripts/views/logic/cql_statement_view.js.coffee
> +    @latestResult = undefined
maybe this answers my question above...

2017-06-23 13:01 UTC, holmesie commented on app/assets/javascripts/views/logic/cql_logic_view.js.coffee
> +
I really like how readable all of this is! Makes me want to adjust the cql_calculator population rules to look something like this (if it makes sense)...

2017-06-23 13:31 UTC, hossenlopp commented on app/assets/javascripts/views/logic/cql_logic_view.js.coffee
> +  _makePopulationResultShownMap: (result) ->
The calculations are done with the scope of a population set or stratification. So the results are already normalized to their population names. Anyways the `IPP_N` is a structure only in QDM measures in Bonnie. The `populations_cql_map` used to map populations to the CQL statements that define them.

2017-06-23 14:02 UTC, hossenlopp commented on app/assets/javascripts/views/logic/cql_statement_view.js.coffee
> +      if result.length == 1 && result[0] == null # But if the array has one element that is null. Then we should make it red.
To me, it looks like an issue with the CQL. The issue in cqltest137_v5_0 in our Sharepoint repo, which also is good for testing the populations and stratifications. This check for an array with one `null` allows the logic to be highlighted as it is in this screenshot below when there is are no elements that would resolve in that `First`.
![screen shot 2017-06-23 at 10 00 11 am](https://user-images.githubusercontent.com/11613067/27485491-e85f08d8-57fa-11e7-89d6-89d3d4e66da2.png)
My guess is that the `{ }` around the `First` is turning the single element result into an array even if the result is nothing.

2017-06-23 14:11 UTC, hossenlopp commented on app/assets/javascripts/views/logic/cql_statement_view.js.coffee
> +    else if result == null  # Specifically no result
I'm treating a `null` result as a failed (red) highlight. I am assuming a `null` means that the statement had a single element result from a `First` or `Single`, etc... I think I found a measure that exhibits this instead of wrapping it in an array like the specific check above. I'll look for that again and report back.

2017-06-23 14:13 UTC, hossenlopp commented on app/assets/javascripts/views/logic/cql_logic_view.js.coffee
> +
We do want to move this stuff into the calculator so the result of this logic can be used elsewhere. This is just temporarily here and very verbose because I felt it was quite complicated. It doesn't handle the OBSERV and MSRPOPL stuffs too...

2017-06-23 15:32 UTC, edeyoung commented
What is a good alpha account and measure to test this with?

2017-06-23 18:47 UTC, edeyoung approved these changes

2017-06-23 18:47 UTC, edeyoung commented
My questions were answered and I checked it out locally. looks good!

2017-06-26 15:09 UTC, hossenlopp commented
I rebased this on my local machine and noticed that the stratifications are broken. None of the population defining statements are being labeled. Looking into this now.

2017-06-26 19:01 UTC, hossenlopp commented
Upon further investigation, I found that uploading the measure again gets the population labels to come back for stratifications. I think something changed in the upload process for stratifications since the measure was loaded into the account I was testing with.

2017-06-26 20:07 UTC, holmesie commented
Looks good

2017-06-26 20:08 UTC, holmesie approved these changes

2017-06-27 14:36 UTC, c-monkey approved these changes
tested locally

2017-06-27 14:36 UTC, merged