Added logic to further support observations in HQMF+CQL
MeasureAuthoringTool/bonnie pull request #765
Opened 2017-06-28 13:42 UTC by holmesie

This is the third of three pull requests, the other two are:
1. https://github.com/projectcypress/health-data-standards/pull/506
2. https://github.com/projecttacoma/bonnie_bundler/pull/87

Measure to test with:
[CMS55_v5_1_Artifacts.10.zip](https://github.com/projecttacoma/bonnie/files/1108862/CMS55_v5_1_Artifacts.10.zip)

2017-06-28 20:09 UTC, edeyoung requested changes

2017-06-28 20:09 UTC, edeyoung commented on app/assets/javascripts/cql_calculator.js.coffee
> +            population_results['values'].push(obs_result[0].value)
note assumption of a single valued results. (is this assumption accurate? how do we know?)

2017-06-28 20:09 UTC, edeyoung commented on app/assets/javascripts/cql_calculator.js.coffee
> +           observation_defs.push('BonnieFunction_' + obs.function_name)
"BonnieFunction" should probably be a constant defined somewhere... but it's not. so add a comment explaining that this is what gets added to the function definition name to create the definition name.

2017-06-29 14:07 UTC, holmesie commented on app/assets/javascripts/cql_calculator.js.coffee
> +            population_results['values'].push(obs_result[0].value)
Yeah, check the HQMF DTSU spec for CQL (in Paul's share), look at section 4.29 	measureObservationDefinition

2017-06-29 14:12 UTC, holmesie commented on app/assets/javascripts/cql_calculator.js.coffee
> +           observation_defs.push('BonnieFunction_' + obs.function_name)
Done!

2017-07-05 20:24 UTC, mayerm94 approved these changes
I have tested since your last changes, everything still works as expected

2017-07-06 11:05 UTC, edeyoung commented
Please test with re-uploading the attached measure on hmdmlantana. Note that the stratifications are not in the population context not the patient context (i've asked her to revise and re-upload). However, the first population should still work. With this code and re-uploading that measure, I do not see the OBSERV results.

[Test32_v5_1_Artifacts.zip](https://github.com/projecttacoma/bonnie/files/1127630/Test32_v5_1_Artifacts.zip)

2017-07-10 16:41 UTC, edeyoung approved these changes

2017-07-10 16:45 UTC, edeyoung commented
HDS and Bonnie-Bundler have been merged. Gemfile.lock needs to be updated to point to these branches.

2017-07-10 16:46 UTC, edeyoung commented
Also, looks like it needs to be updated with the latest.

2017-07-10 19:49 UTC, jbradl11 approved these changes

2017-07-10 19:57 UTC, merged