Implemented a rake task that rebuilds the ELM for CqlMeasure models i…
MeasureAuthoringTool/bonnie pull request #769
Opened 2017-07-12 19:54 UTC by holmesie

…n the local db using a locally running translation service

2017-07-12 20:05 UTC, hossenlopp requested changes

2017-07-12 20:05 UTC, hossenlopp commented on lib/tasks/cql.rake
> +          elsif measure[:cql].instance_of?(String) # Older version of the CqlMeasure model
We should be updating the model here instead of keeping it out of date. I would suggest checking if `cql` is a string and make it an array and then go to town with the code in the if it's an Array part. Note that we'll also have to populate the main_cql_library field.

2017-07-12 22:42 UTC, holmesie commented on lib/tasks/cql.rake
> +          elsif measure[:cql].instance_of?(String) # Older version of the CqlMeasure model
Done!

2017-07-12 23:58 UTC, hossenlopp requested changes

2017-07-12 23:58 UTC, hossenlopp commented on lib/tasks/cql.rake
> +          user = User.find_by('_id': measure[:user_id])
`'_id':` isn't a valid symbol. `_id:` will do the trick.

2017-07-13 00:15 UTC, holmesie commented on lib/tasks/cql.rake
> +          user = User.find_by('_id': measure[:user_id])
Fixed

2017-07-13 00:50 UTC, hossenlopp approved these changes

2017-07-13 00:50 UTC, merged