CQL4Bonnie With Coverage, Clause Level Highlighting, and Multi-Library Support
MeasureAuthoringTool/bonnie pull request #775
Opened 2017-07-14 21:14 UTC by mayerm94

For CODE REVIEW... you can test it if you want, use the 1.2.8 translator and run the update measures rake task

2017-07-14 23:39 UTC, c-monkey commented on app/assets/javascripts/cql_calculator.js.coffee
> +
This whitespace change is sloppy. Also line 73.

2017-07-15 13:28 UTC, holmesie commented on Gemfile
> +gem 'cql_qdm_patientapi', :git => 'https://github.com/projecttacoma/cql_qdm_patientapi.git', :branch => 'cql4bonnie_706_707'
This is fine for testing, but why is this included in a pull request?

2017-07-15 13:49 UTC, holmesie requested changes

2017-07-15 13:49 UTC, holmesie commented on Gemfile
> +gem 'bonnie_bundler', :git => 'https://github.com/projecttacoma/bonnie_bundler.git', :branch => 'statement_dep_and_clause_elm_merged'
Same as above

2017-07-15 13:49 UTC, holmesie commented on app/assets/javascripts/cql_calculator.js.coffee
> -        if results['patientResults'][patient.id][cql_population]? && population.get(popCode)?
Why was this check removed?

2017-07-15 13:49 UTC, holmesie commented on app/assets/javascripts/cql_calculator.js.coffee
> +  ###*
This is not the style of function comments we've been using for this file. If you are going to start using this style, you should change all of the other function comments.

2017-07-15 13:49 UTC, holmesie commented on app/assets/javascripts/cql_calculator.js.coffee
> +  _buildPopulationRelevanceMap: (result) ->
This looks like view related code; why is it in this file?

2017-07-15 13:49 UTC, holmesie commented on app/assets/javascripts/cql_calculator.js.coffee
> +  _buildStatementRelevanceMap: (populationRelevance, measure, populationSet) ->
Same as previous comment; this looks like view related code, why is it in this file?

2017-07-15 13:49 UTC, holmesie commented on app/assets/javascripts/cql_calculator.js.coffee
> +  _markStatementRelevant: (cql_statement_dependencies, statementRelevance, libraryName, statementName, relevant) ->
And again, same as previous comment; this looks like view related code, why is it in this file?

2017-07-15 13:49 UTC, holmesie commented on app/assets/javascripts/cql_calculator.js.coffee
> +  _buildStatementAndClauseResults: (measure, rawClauseResults, statementRelevance) ->
Same as previous comment

2017-07-15 13:49 UTC, holmesie commented on app/assets/javascripts/cql_calculator.js.coffee
> +  _setFinalResults: (params) ->
Same as previous comment, this seems way too much unrelated stuff to add to the cql_calculator

2017-07-15 13:49 UTC, holmesie commented on app/assets/javascripts/cql_calculator.js.coffee
> +  _findResultForStatementClause: (measure, libraryName, statementName, rawClauseResults) ->
Same as previous comment

2017-07-15 13:49 UTC, holmesie commented on app/assets/javascripts/cql_calculator.js.coffee
> +  _doesResultPass: (result) ->
Same as previous comment

2017-07-15 13:49 UTC, holmesie commented on app/assets/javascripts/models/measure.js.coffee
> +  _findAllLocalIdsInStatementByName: (libraryName, statementName) ->
Is this view related? Why is it in the model?

2017-07-15 13:49 UTC, holmesie commented on app/assets/javascripts/models/measure.js.coffee
> +  _findAllLocalIdsInStatement: (statement, libraryName, localIds, aliasMap, emptyResultClauses) ->
See previous comment

2017-07-15 13:49 UTC, holmesie commented on app/assets/stylesheets/cql_logic.less
> +      border-bottom-color: @state-success-text !important;
Generally it's not the nicest thing seeing `!important` in CSS, why is that necessary here?

2017-07-15 13:49 UTC, holmesie commented on lib/tasks/cql.rake
> +    task :rebuild_elm => :environment do
This looks pretty good!

2017-07-15 13:51 UTC, losborne commented on app/assets/javascripts/cql_calculator.js.coffee
> +      else
Can the array ever have multiple null values?

2017-07-15 13:51 UTC, losborne commented on app/assets/javascripts/models/coverage.js.coffee
> +        # Set coverage to the ratio of evaluated clauses to total clauses
I think 'ratio' should be 'percentage' here

2017-07-15 13:51 UTC, losborne commented on app/assets/javascripts/models/coverage.js.coffee
> +        # Initialize all_clauses list to all false and count number of clauses
change all_clauses in comment to be camel case to match variable name

2017-07-15 13:51 UTC, losborne commented on app/assets/javascripts/models/coverage.js.coffee
> +        @set coverage: ( passedClauses * 100 / totalClauses ).toFixed()
Should there be a check to make sure this always stays between 0 and 100?

2017-07-15 13:51 UTC, losborne commented on app/assets/javascripts/models/coverage.js.coffee
> +    if clause["final"] == "TRUE"
might be able to just say `return clause["final"] == "TRUE"`

2017-07-15 15:57 UTC, hossenlopp commented on Gemfile
> +gem 'cql_qdm_patientapi', :git => 'https://github.com/projecttacoma/cql_qdm_patientapi.git', :branch => 'cql4bonnie_706_707'
This is a first pass PR for just reviewing code. Having the gemfile changes is here so people don't have to remember to checkout the correct branches and modify their gemfile to point to the other local checkouts. This also allows us to put it on ALPHA-STG, which we have done for a short period yesterday.

2017-07-15 15:57 UTC, hossenlopp commented on Gemfile
> +gem 'bonnie_bundler', :git => 'https://github.com/projecttacoma/bonnie_bundler.git', :branch => 'statement_dep_and_clause_elm_merged'
Same response as above.

2017-07-15 16:08 UTC, hossenlopp commented on app/assets/javascripts/cql_calculator.js.coffee
> -        if results['patientResults'][patient.id][cql_population]? && population.get(popCode)?
Looking at the commit that was made the log message provides more context. https://github.com/projecttacoma/bonnie/commit/072de32102ed34bd12284514a9b78e8987fac406

So... I believe I removed it because the coffeescript `?` was effectively causing to not look at the result if it was `null` or `false`. But those ARE valid results and they are handled below. Perhaps someone should look at that... Perhaps this code should just call `@_doesResultPass`.

2017-07-15 19:17 UTC, hossenlopp commented on app/assets/javascripts/cql_calculator.js.coffee
> +  _buildPopulationRelevanceMap: (result) ->
This is view and coverage related code. Some of the big work in this branch to allow coverage calculation to work and be consistent with patient result highlighting is to use the same exact set of `clause_result`s that get returned from the CQLCalculator.

This function in particular determines which populations were even considered for calculation for this patient.  The structure generated here is used later to determine which CQL define statements should be considered touched (aka. relevant) in for this population calculation.

I will add some more comments to this function.

2017-07-15 19:20 UTC, hossenlopp commented on app/assets/javascripts/cql_calculator.js.coffee
> +  _buildStatementRelevanceMap: (populationRelevance, measure, populationSet) ->
Same as above comment in general. It is used to determine the `clause_results` used in coverage calculation and logic views.

This function in particular makes use of the population_relevance structure generated in `_buildPopulationRelevanceMap` to determine the statements that are relevant in the calculation for this patient.

2017-07-15 19:21 UTC, hossenlopp commented on app/assets/javascripts/cql_calculator.js.coffee
> +  _markStatementRelevant: (cql_statement_dependencies, statementRelevance, libraryName, statementName, relevant) ->
Similar to above comment. This is a helper recursive function for `_buildStatementRelevanceMap`.

2017-07-15 19:24 UTC, hossenlopp commented on app/assets/javascripts/cql_calculator.js.coffee
> +  _buildStatementAndClauseResults: (measure, rawClauseResults, statementRelevance) ->
Similar to above. This generates `statement_results` and `clause_results` that are added to the Result's attributes. Coverage and logic highlight both use these results. Although, right now I think there may be no usage of `statement_results` but I see it pretty important for ease of debugging and for the inevitable implementation of patient dashboard for CQL.

2017-07-15 19:36 UTC, hossenlopp commented on app/assets/javascripts/cql_calculator.js.coffee
> +  _setFinalResults: (params) ->
Similar to above. Used in coverage calculation and logic highlighting. (I already mentioned this in the function comment). I'm going to fill more info into the code comment.

This function in particular figures out if a clause should be NA, UNHIT, TRUE or FALSE.

- NA - Means Not Applicable. This means the clause was not relevant to this population set at all. This won't be highlighted or considered a clause that needs to be covered.
- UNHIT - This specific patient doesn't hit this clause. This is most likely because the statement it resides was not relevant to a population calculation for this patient.
- TRUE - This clause is relevant and has a truthy result. `_doesResultPass` determines this.
- FALSE - This clause is relevant, is hit, and has a falsey result.

2017-07-15 19:38 UTC, hossenlopp commented on app/assets/javascripts/cql_calculator.js.coffee
> +  _findResultForStatementClause: (measure, libraryName, statementName, rawClauseResults) ->
Similar to previous response. Important for coverage and logic highlighting.

2017-07-15 19:39 UTC, hossenlopp commented on app/assets/javascripts/cql_calculator.js.coffee
> +  _doesResultPass: (result) ->
Similar to previous response. Important for coverage and logic highlighting.

This function in particular is the sole source of if a statement or clause result is truthy or falsey (aka. highlight green or highlight red).

2017-07-15 19:39 UTC, c-monkey requested changes
I'm generally happy with this PR.

2017-07-15 19:39 UTC, c-monkey commented on lib/tasks/cql.rake
> +          elsif measure[:cql].instance_of?(String) # Old type of measure
What if cql isn't an array or a string? Obviously we have exceptions handlers, but why not explicitly call 'raise'?

2017-07-15 19:39 UTC, c-monkey commented on app/assets/javascripts/cql_calculator.js.coffee
> +  @SKIP_STATEMENTS = ["SDE Ethnicity", "SDE Payer", "SDE Race", "SDE Sex"]
This is duplicated from Thorax.Views.CqlPopulationLogic could it be shared?

2017-07-15 19:39 UTC, c-monkey commented on app/assets/javascripts/cql_calculator.js.coffee
> +  # Mark a statement as relevant if it hasn't already been marked relevant. Mark all dependent statement
This comment confused me since relevance is 3 values, no longer a boolean.

How about replace comment with:
Mark statement and its dependent statements relevance. Can change relevance from 'NA' to 'TRUE' or 'FALSE', can change 'FALSE' to 'TRUE', but does not change 'TRUE' if previously identified.

2017-07-15 19:39 UTC, c-monkey commented on app/assets/javascripts/cql_calculator.js.coffee
> +  # @param {string} statementName - The statement name.
missing 'relevant' param

2017-07-15 19:39 UTC, c-monkey commented on app/assets/javascripts/cql_calculator.js.coffee
> +  ###*
This language reads too awkward for me. How about:
Build a population to boolean map indicating if each define statement result should be highlighted, thus statements that are "not calculated" are unhighlighted in the UI.

2017-07-15 19:39 UTC, c-monkey commented on app/assets/javascripts/cql_calculator.js.coffee
> +        index = populationSet.get('index')
index is calculated identically each time through this loop except for a single "if"

How about we pull this calculation out of the "for"?

2017-07-15 19:39 UTC, c-monkey commented on app/assets/javascripts/cql_calculator.js.coffee
>        if population_results?
@hossenlopp as we discussed, add a comment for why we are returning all these values in the hash.

I like your suggestion that we document each of these hash values.

2017-07-15 19:39 UTC, c-monkey commented on app/assets/javascripts/cql_calculator.js.coffee
> +        statementResults[lib][statementName] = { raw: rawStatementResult}
like below in line 338, I think it would add clarity to call out that this section determines the statement results

2017-07-15 19:39 UTC, c-monkey commented on app/assets/javascripts/views/logic/cql/cql_clause.js.coffee
> +class Thorax.Views.CqlClauseView extends Thorax.Views.BonnieView
this is the only module in the 'cql' folder, we should get rid of the folder, since related modules (and this one, too) are all prefixed with 'cql_'

2017-07-15 19:39 UTC, c-monkey commented on app/assets/javascripts/views/logic/cql_logic_view.js.coffee
>                for pop, popStatements of @model.get('populations_cql_map')
this block of code is the same as line 285 of _buildStatementRelevanceMap (replacing population with populationSet)

2017-07-15 19:39 UTC, c-monkey commented on app/assets/javascripts/models/coverage.js.coffee
> -        covered_dc = covered_dc.concat(new CQL_QDM.CQLPatient(patient).getUniqueCoveredDataCriteria())
with this change, we should remove the placeholder function getUniqueCoveredDataCriteria from CQL_QDM.CQLPatient

2017-07-15 19:48 UTC, hossenlopp commented on app/assets/javascripts/cql_calculator.js.coffee
> +      else
Yes, if a CQL measure does something like this:
```
define "Array of Nulls": { first("something with no result"), first("somethingelse with no result") }
```

2017-07-15 19:56 UTC, mayerm94 commented on app/assets/javascripts/models/coverage.js.coffee
> -        covered_dc = covered_dc.concat(new CQL_QDM.CQLPatient(patient).getUniqueCoveredDataCriteria())
https://github.com/projecttacoma/cql_qdm_patientapi/tree/cql4bonnie_706_707

2017-07-15 20:06 UTC, c-monkey commented on app/assets/javascripts/models/coverage.js.coffee
> -        covered_dc = covered_dc.concat(new CQL_QDM.CQLPatient(patient).getUniqueCoveredDataCriteria())
Don't forget to make the PR for this.

2017-07-15 20:08 UTC, mayerm94 commented on app/assets/javascripts/models/coverage.js.coffee
> +        @set coverage: ( passedClauses * 100 / totalClauses ).toFixed()
There was never a check on QDM coverage. Not a bad idea, but I'm not sure what we would do about it if it ever fell outside those bounds.

2017-07-15 20:20 UTC, jbradl11 commented on app/assets/javascripts/cql_calculator.js.coffee
> +  _buildPopulationRelevanceMap: (result) ->
I think even if the code is related to the view,  it's ok to be here for now. In the future, it might make sense to move alot of the logic here in a separate file.

2017-07-15 20:26 UTC, hossenlopp commented on app/assets/javascripts/cql_calculator.js.coffee
> +  @SKIP_STATEMENTS = ["SDE Ethnicity", "SDE Payer", "SDE Race", "SDE Sex"]
I believe it can. I will look into this.

2017-07-15 20:26 UTC, holmesie commented on app/assets/javascripts/cql_calculator.js.coffee
> +  _buildPopulationRelevanceMap: (result) ->
@jbradl11 I disagree, this change should be made now, and not relegated to the "never-going-to-happen" future.

The code itself looks good, but I strongly believe it does not belong here. This file is already way too big (compare to the QDM version).

2017-07-15 20:27 UTC, holmesie commented on app/assets/javascripts/cql_calculator.js.coffee
> -        if results['patientResults'][patient.id][cql_population]? && population.get(popCode)?
Make sense

2017-07-15 20:28 UTC, mayerm94 commented on lib/tasks/cql.rake
> +          elsif measure[:cql].instance_of?(String) # Old type of measure
This file was already reviewed in another PR

2017-07-15 21:26 UTC, c-monkey commented on lib/tasks/cql.rake
> +          elsif measure[:cql].instance_of?(String) # Old type of measure
https://github.com/projecttacoma/bonnie/pull/769

If we don't need a performance optimization - Alex says this takes only a minute or two - then as long as we're okay with the spam, doesn't matter to me.

2017-07-16 13:15 UTC, hossenlopp commented on app/assets/javascripts/cql_calculator.js.coffee
> -        if results['patientResults'][patient.id][cql_population]? && population.get(popCode)?
We will not use `@_doesResultPass` right now because this may deal with collecting the results for episode of care based numbers, this means they need to know the number of things in an Array result.

2017-07-16 13:16 UTC, hossenlopp commented on app/assets/javascripts/cql_calculator.js.coffee
> +  _buildPopulationRelevanceMap: (result) ->
This is getting moved to a new helper file in a helpers folder.

2017-07-16 13:55 UTC, hossenlopp commented on app/assets/stylesheets/cql_logic.less
> +      border-bottom-color: @state-success-text !important;
This was a copy and paste from a previous implementation where it was needed. Removed them in ff8c5170de4ef78e0236531539970b5cd003e725.

2017-07-16 13:56 UTC, hossenlopp commented on app/assets/javascripts/models/coverage.js.coffee
> +        # Initialize all_clauses list to all false and count number of clauses
@mayerm94 handled this.

2017-07-16 13:57 UTC, hossenlopp commented on app/assets/javascripts/models/coverage.js.coffee
> +        # Set coverage to the ratio of evaluated clauses to total clauses
@mayerm94 handled this.

2017-07-16 14:03 UTC, hossenlopp commented on lib/tasks/cql.rake
> +          elsif measure[:cql].instance_of?(String) # Old type of measure
Since the beginning of cql4bonnie having CqlMeasure model that model has had `cql` as a field. The change to multi_library support meant we changed the type from `String` to `Array`. We need to handle upgrading to `cql` to an `Array` if isn't already.

2017-07-16 15:05 UTC, hossenlopp commented on app/assets/javascripts/cql_calculator.js.coffee
> +
@mayerm94 addressed this

2017-07-16 15:08 UTC, hossenlopp commented on app/assets/javascripts/models/measure.js.coffee
> +  _findAllLocalIdsInStatementByName: (libraryName, statementName) ->
We had a discussion about this. I forgot the result. This creates a structure relevant any calculation. It's additional calculated data that we could generate on the back end at upload, but having at the front end makes it easier to fix if there's an issue because it won't need a re-upload or rake task.

Now that I remember, this was something is ok to have on the Measure model, but the functions for calculating it should be shifted to a helper function. I will do that.

2017-07-16 15:30 UTC, hossenlopp commented on app/assets/javascripts/cql_calculator.js.coffee
> +        index = populationSet.get('index')
Oh gosh, I hate this block of code. It was copy pasted from the sister view code in `cql_logic_view.js.coffee`.

Basically what it is doing here is looking at each population in the population set (or stratification), figuring out which CQL statement defines the population. This should be moved to the Measure or the Population thorax model so it can be shared by calculator code and the logic view, since they both need to know which CQL statement defines which population.

2017-07-16 15:46 UTC, hossenlopp commented on app/assets/javascripts/views/logic/cql_logic_view.js.coffee
>                for pop, popStatements of @model.get('populations_cql_map')
Sure is... I commented on the other copy of this. I decided it belongs somewhere both calculator and this code can handle it. I have it as a tasker to refactor to a shared location.

2017-07-16 16:31 UTC, hossenlopp commented on app/assets/javascripts/cql_calculator.js.coffee
> +  @SKIP_STATEMENTS = ["SDE Ethnicity", "SDE Payer", "SDE Race", "SDE Sex"]
Will move this to `constants.js.coffee.erb`.

2017-07-16 21:04 UTC, c-monkey approved these changes
My comments have been addressed.

2017-07-16 21:06 UTC, c-monkey requested changes
@hossenlopp says more changes are comin'

2017-07-16 21:43 UTC, hossenlopp commented on app/assets/javascripts/cql_calculator.js.coffee
> +  ###*
This has been partially addressed. The rest of the functions will not have updated right now due to priorities.

2017-07-16 21:45 UTC, hossenlopp commented on app/assets/javascripts/cql_calculator.js.coffee
> +        index = populationSet.get('index')
@mayerm94 addressed this.

2017-07-17 00:56 UTC, hossenlopp commented on app/assets/javascripts/views/logic/cql_logic_view.js.coffee
>                for pop, popStatements of @model.get('populations_cql_map')
@mayerm94 Addressed this.

2017-07-17 15:23 UTC, holmesie approved these changes

2017-07-17 15:24 UTC, jbradl11 approved these changes
Looks good.

2017-07-25 20:44 UTC, closed without merging