BONNIE-757: adding 'component' attribute to 2 datatypes
MeasureAuthoringTool/bonnie pull request #807
Opened 2017-07-28 14:20 UTC by c-monkey

'Physical Exam, Performed' and 'Procedure, Performed'

See https://github.com/projecttacoma/bonnie/pull/776 which needs this PR to work.

(wip, will update this comment when I create the other PR)

2017-08-04 17:24 UTC, jbradl11 approved these changes
Looks good.

2017-08-07 15:34 UTC, hossenlopp requested changes

2017-08-07 15:34 UTC, hossenlopp commented on app/assets/javascripts/models/measure.js.coffee
> +      procedures: ['incision_time', 'anatomical_structure', 'ordinality', 'qdm_status','components']
Add a space after the comma for consistency. Same with line 102.

2017-08-07 20:14 UTC, hossenlopp approved these changes

2017-08-07 20:17 UTC, merged