Cql4bonnie qdm5 3 937 facility
MeasureAuthoringTool/bonnie pull request #819
Opened 2017-08-16 14:13 UTC by losborne

JIRA Test: https://jira.mitre.org/browse/BONNIE-968

Related PRs:
- 
- 
-

2017-08-16 14:56 UTC, losborne commented
The Travis CI tests fail because this change requires the branch cql4bonnie-QDM5_3_966 in health_data_standards.  Tests should be run locally with the Gemfile pointing to the corresponding branches in hds and cql_qdm_patientapi.

2017-08-16 16:23 UTC, mayerm94 submitted a review, later dismissed
Changes look good, my only comment is that when you add a facility location that only has an end date, the date is not shown in the field_value.

2017-08-16 20:34 UTC, c-monkey requested changes

2017-08-16 20:34 UTC, c-monkey commented on app/assets/javascripts/views/patient_builder/data_criteria.js.coffee
> +      compare_collection = @values.findWhere(key: @model.get('key'))
replace this additional lookup with `model_key`

2017-08-16 20:34 UTC, c-monkey commented on app/assets/javascripts/views/patient_builder/data_criteria.js.coffee
> +        col.set('key', @model.get('key'))
replace this additional lookup with `model_key`

2017-08-16 20:34 UTC, c-monkey commented on app/assets/javascripts/templates/patient_builder/edit_criteria.hbs
>                    {{value}} {{unit}}
Perhaps this is undesired behavior: if there is no start_date, the end_date is not shown. @losborne and I discussed and think we don't need to enforce anything here but do need to update the display for the case where a user accidentally enters end_date instead of start_date but that isn't visible in the display.

2017-08-16 20:34 UTC, c-monkey commented on lib/measures/patient_builder.rb
> +        field_value["locationPeriodLow"] = value['locationPeriodLow']
inconsistent quotes, other places in this function use double-quotes for hash keys of `value`

2017-08-16 20:34 UTC, edeyoung commented on config/bonnie.yml
> -  version: 2.0.0-alpha.13
has the underlying cql4bonnie-QDM5_3 been updated yet? Is this just an artifact from an old ancestor? If cql4bonnie-QDM5_3 hasn't been updated yet (latest cql4bonnie merged in) it should be

2017-08-17 12:50 UTC, losborne commented on config/bonnie.yml
> -  version: 2.0.0-alpha.13
cql4bonnie-QDM5_3 is showing as `version: 2.0.0-alpha.16`, so this is probably an artifact from an old ancestor

2017-08-18 20:24 UTC, c-monkey submitted a review, later dismissed

2017-08-21 17:46 UTC, edeyoung approved these changes
approving based on the approval of previous reviews and that the changes since were very minor (gemfile update and version update)

2017-08-21 17:47 UTC, merged