BONNIE-967 Implement excel export.
MeasureAuthoringTool/bonnie pull request #824
Opened 2017-08-21 15:05 UTC by alexanderelliott121

Exports a cql measure

2017-08-22 15:30 UTC, jbradl11 commented on app/assets/javascripts/templates/measure.hbs
> +          {{#if cql}}
Just for clarification, are we not supporting excel export for QDM+HQMF measures anymore?

2017-08-22 17:31 UTC, edeyoung commented on app/assets/javascripts/templates/measure.hbs
> +          {{#if cql}}
that's correct.

2017-08-22 17:59 UTC, mayerm94 commented on lib/patient_export.rb
> +            header_row = DISPLAYED_ATTRIBUTES + population_criteria*2
Why is population_criteria multiplied by two? (Also, add spaces around operator)

2017-08-22 18:44 UTC, jbradl11 commented on app/assets/javascripts/helpers/cql_measure_helpers.js.coffee
> +    ret = {}
Do we not already have a structure that links the Define Statement name to the actual statement?  Or is that not what this is doing? Either way I would recommend comments for this function and the function below this.

2017-08-22 18:51 UTC, jbradl11 commented on app/assets/javascripts/views/measure_view.js.coffee
> +    calc_results = {}
It looks like the exportPatientsView.exporting() loading screen was removed. I think we should add this back in.

2017-08-22 18:58 UTC, jbradl11 commented on app/assets/javascripts/views/measure_view.js.coffee
> +    for pop in @model.get('populations').models
Could this for loop be moved to the backend? Instead of passing the patients from the frontend you should be able to grab the patients and the measure on the backend and do the processing there.

2017-08-22 18:59 UTC, jbradl11 commented on app/assets/javascripts/views/measure_view.js.coffee
> +  removeRaw: (results) ->
Please add comments to each function.

2017-08-22 19:01 UTC, jbradl11 commented on app/controllers/patients_controller.rb
> +    cookies[:fileDownload] = "true" # We need to set this cookie for jquery.fileDownload
Looks like you need to remove the left over comment. Also the export shouldn't fail if there are 0 patients.

2017-08-22 19:07 UTC, jbradl11 commented on lib/patient_export.rb
> -                              "Population #{population_index+1}"
Why was this check for character length removed? I can't remember but I am fairly certain this can cause an error.

2017-08-22 19:09 UTC, jbradl11 requested changes
I am seeing formatting discrepancies between the original excel export and the CQL excel export. I am also getting a few bugs when testing.

2017-08-23 00:14 UTC, mayerm94 commented on test/functional/patients_controller_test.rb
> +    calc_results = '{"c10":{"c20":{"statement_results":{"MedianTimefromEDArrivaltoEDDepartureforAdmittedEDPatients":{"Patient":"NA","SDE Ethnicity":"NA","SDE Payer":"NA","SDE Race":"NA","SDE Sex":"NA
These results are gigantic, you might want to store them as a fixture

2017-08-23 00:48 UTC, mayerm94 requested changes

2017-08-23 00:48 UTC, mayerm94 commented on app/controllers/patients_controller.rb
> -    # Grab all records for the given measure
I don't think you should have removed this logic that grabs the records for the given measure, right now when you do an Excel export on a measure, the export contains the records from ALL measures

2017-08-23 12:17 UTC, mulcahyk commented on test/functional/patients_controller_test.rb
> +    calc_results = '{"c10":{"c20":{"statement_results":{"MedianTimefromEDArrivaltoEDDepartureforAdmittedEDPatients":{"Patient":"NA","SDE Ethnicity":"NA","SDE Payer":"NA","SDE Race":"NA","SDE Sex":"NA
You don't need to include **calc_results** in the Excel export.  That field is there for caching reasons.

2017-08-23 13:59 UTC, alexanderelliott121 commented on lib/patient_export.rb
> +            header_row = DISPLAYED_ATTRIBUTES + population_criteria*2
Pop criteria is doubled to represent actual vs. expected, will add spaces.

2017-08-23 14:01 UTC, alexanderelliott121 commented on app/assets/javascripts/helpers/cql_measure_helpers.js.coffee
> +    ret = {}
The structure linking define name to full statement was removed when we went to granular highlighting.  I don't think we have the full define statements available at the point where we're building the call to the back end.

Adding comments.

2017-08-23 14:06 UTC, alexanderelliott121 commented on app/assets/javascripts/views/measure_view.js.coffee
> +    calc_results = {}
Restoring.

2017-08-23 14:13 UTC, alexanderelliott121 commented on test/functional/patients_controller_test.rb
> +    calc_results = '{"c10":{"c20":{"statement_results":{"MedianTimefromEDArrivaltoEDDepartureforAdmittedEDPatients":{"Patient":"NA","SDE Ethnicity":"NA","SDE Payer":"NA","SDE Race":"NA","SDE Sex":"NA
Moving them to fixtures is something I'll try.

@mulcahyk I'm not sure I understand what you mean.  The calc_results variable is the core of the excel export.

2017-08-23 14:19 UTC, alexanderelliott121 commented on app/assets/javascripts/views/measure_view.js.coffee
> +    for pop in @model.get('populations').models
The loop actually needs to run the calculations, so it has to happen on the front end.
Since all the data is there, I don't see the value of doing the lookups again on the back end.

2017-08-23 15:25 UTC, alexanderelliott121 commented on app/controllers/patients_controller.rb
> -    # Grab all records for the given measure
Fix implemented in front end.

2017-08-23 15:34 UTC, alexanderelliott121 commented on lib/patient_export.rb
> -                              "Population #{population_index+1}"
Check restored.

2017-08-23 15:40 UTC, mulcahyk commented on test/functional/patients_controller_test.rb
> +    calc_results = '{"c10":{"c20":{"statement_results":{"MedianTimefromEDArrivaltoEDDepartureforAdmittedEDPatients":{"Patient":"NA","SDE Ethnicity":"NA","SDE Payer":"NA","SDE Race":"NA","SDE Sex":"NA
I was thrown off by the name.  I was thinking about the calc_results we used with the QDM logic.  You can ignore my comment.

2017-08-24 18:33 UTC, mayerm94 requested changes
Excel exports work for as expected for most measures, but I am getting an error when I upload this file, create a patient and try to export as excel. The error is ArgumentError (There is already a worksheet in this "workbook named 'Population Criteria Section'. Please use a unique name):"
[IETCQL_v5_0_Artifacts.zip](https://github.com/projecttacoma/bonnie/files/1249895/IETCQL_v5_0_Artifacts.zip)

2017-08-24 20:01 UTC, jbradl11 commented
@mayerm94 Without looking at the zip you added, I suspect that error is caused by having multiple populations on a measure and naming each "tab" in the excel export the same name.  @alexanderelliott121  I recommend you name each "tab" the name of the given Population. ( I believe this is how I did it in the previous version).

2017-08-24 20:07 UTC, jbradl11 commented on app/assets/javascripts/views/measure_view.js.coffee
> +    for pop in @model.get('populations').models
Did you test the performance of this code on a large measure with lots of patients?

2017-08-25 11:39 UTC, alexanderelliott121 commented on app/assets/javascripts/views/measure_view.js.coffee
> +    for pop in @model.get('populations').models
Yes, worked well

2017-08-25 11:58 UTC, alexanderelliott121 commented
@mayerm94 @jbradl11 
The measure has two populations with the same name.  I'm going to start incrementing the names.

2017-08-25 20:52 UTC, jbradl11 approved these changes
Tested locally, format looks good. Multiple populations work. Multiple libraries are supported. Measures with no patients export with message in export (eventually I think we should allow them to export the document with the headers populated, even if there are no patients). Approved.

2017-08-28 15:07 UTC, mayerm94 requested changes
Everything looks right.

2017-08-28 15:14 UTC, mayerm94 approved these changes

2017-08-29 19:23 UTC, alexanderelliott121 commented
JIRA Test added https://jira.mitre.org/browse/BONNIE-1003

2017-08-29 19:47 UTC, c-monkey approved these changes
https://jira.mitre.org/browse/BONNIE-1003 passed

2017-08-30 13:01 UTC, edeyoung commented
Also this JIRA test: https://jira.mitre.org/browse/BONNIE-1005

2017-08-30 13:21 UTC, edeyoung commented
all tests pass

2017-08-31 17:49 UTC, merged