Cql4bonnie 549
MeasureAuthoringTool/bonnie pull request #825
Opened 2017-08-23 15:54 UTC by mayerm94

2017-08-23 16:00 UTC, mayerm94 commented
This is a preliminary pull request, many of the tests removed from the measure_controller_test are in the process of being converted to CQL tests. Review should focus on the measure_controller

2017-08-23 20:10 UTC, hossenlopp commented on app/controllers/measures_controller.rb
> +          flash[:error] = {title: "Error Loading Measure1", summary: "An episode of care measure requires at least one specific occurrence for the episode of care.", body: "You have loaded the measur
Why was a '1' added to Measure? Also, I thought specific occurrences are no longer a thing for CQL measures.

2017-08-23 20:10 UTC, hossenlopp commented on app/controllers/measures_controller.rb
> +        flash[:error] = {title: "Error Loading Measure", summary: "The measure value sets could not be found.", body: "Please re-package the measure in the MAT and make sure &quot;VSAC Value Sets&quo
Value sets are no longer being included in the package. This check is probably not relevant.

2017-08-24 11:49 UTC, mayerm94 commented on app/controllers/measures_controller.rb
> +          flash[:error] = {title: "Error Loading Measure1", summary: "An episode of care measure requires at least one specific occurrence for the episode of care.", body: "You have loaded the measur
The 1 that was added was a fat finger addition, good catch. But I think you're right about the specific occurrences, Ill just remove the error logic for this.

2017-08-24 11:52 UTC, hossenlopp commented on app/controllers/measures_controller.rb
> +          flash[:error] = {title: "Error Loading Measure1", summary: "An episode of care measure requires at least one specific occurrence for the episode of care.", body: "You have loaded the measur
Maybe they still are relevant, just serve a different purpose. @holmesie and/ @jbradl11, have any thoughts on the this?

2017-08-24 12:07 UTC, mayerm94 commented on app/controllers/measures_controller.rb
> +        flash[:error] = {title: "Error Loading Measure", summary: "The measure value sets could not be found.", body: "Please re-package the measure in the MAT and make sure &quot;VSAC Value Sets&quo
Good point, I just checked all instances where this exception is thrown and it looks like it makes sense to remove this error.

2017-08-24 15:27 UTC, holmesie commented on app/controllers/measures_controller.rb
> +          flash[:error] = {title: "Error Loading Measure1", summary: "An episode of care measure requires at least one specific occurrence for the episode of care.", body: "You have loaded the measur
No, @hossenlopp you are correct, we don't care about those anymore.

2017-08-24 19:46 UTC, c-monkey commented
- You should re-enable the `updateMeasure` button on app/assets/javascripts/templates/measure.hbs

- When you upgrade, the type field on the upload view is empty. This can be fixed in bonnie_bundler in `lib/measures/loading/cql_loader.rb` in the function `load_mat_cql_exports` after the call to `Measures::Loader.load_hqmf_cql_model_json`. I did so with this one line:
`measure['type'] = measure_details['type']`
This is because `measure_details` is not passed into `load_hqmf_cql_model_json`

2017-08-24 19:46 UTC, c-monkey requested changes

2017-08-24 19:46 UTC, c-monkey commented on app/controllers/measures_controller.rb
> +        flash[:error] = {title: "Error Uploading Measure", summary: "The uploaded zip file is not a Measure Authoring Tool export.", body: "You have uploaded a zip file that does not appear to be a M
Should add back in a period and capitalize "Please", or put in a comma.

As for redirection, we have a task on the backlog for redirecting to the new server, probably put in a comment with TODO here but skip on changing the wording because it should be consistent between all the places in the code that we change for redirection.

2017-08-24 19:46 UTC, c-monkey commented on app/controllers/measures_controller.rb
> +        flash[:error] = {title: "Error Loading Measure", summary: "Incorrect Upload Format.", body: "The file you have uploaded does not appear to be a Measure Authoring Tool zip export of a measure
Should add back in a period, or else make "Please" lowercase and put in a comma.

2017-08-24 19:46 UTC, c-monkey commented on app/controllers/measures_controller.rb
> +    if extension && !['.zip'].include?(extension)
I think we should slightly change the logic of this if/else block. The first line should be:
`if !extension || extension != '.zip'`
and the `elsif` changed to a simple `else`

2017-08-24 19:46 UTC, c-monkey commented on app/controllers/measures_controller.rb
>        if !Measures::MATLoader.mat_export?(params[:measure_file])
Let's change this to be:
`if Measures::HQMFLoader.mat_hqmf_export?(params[:measure_file])`
and error indicating this is a MAT package that is no longer supported.

2017-08-24 19:46 UTC, c-monkey commented on app/controllers/measures_controller.rb
> +      if extension == '.zip' && Measures::CqlLoader.mat_cql_export?(params[:measure_file])
With my above suggested changes, you now can't get here unless uploaded file is a CQL-based measure. Therefore this if can be removed. You don't handle the `else` situation, but that's okay, it isn't necessary with my changes.

That being said, for clarity, I think above in the line before this `begin` block (_original numbering line_ `61`), we should add a comment, something like:
`# if we get here, uploaded file is a CQL-based measure in .zip format`

2017-08-24 19:46 UTC, c-monkey commented on app/controllers/measures_controller.rb
> +        existing = CqlMeasure.by_user(current_user).where(hqmf_set_id: measure.hqmf_set_id).first
This value of `existing` is unused. If is_update is true, then `existing` is set by the code on line 91. If false, then the variable `cql_existing` is used.

2017-08-28 16:50 UTC, c-monkey requested changes
Minor change requested. Everything else is good.

2017-08-28 16:50 UTC, c-monkey commented on app/assets/javascripts/templates/measure.hbs
> +          {{#button "showCQL" class="btn btn-default"}}Learn CQL{{/button}}
I think this button should be removed altogether. I tried messing around with it and I don't think it is helpful to be able to edit CQL this way anymore.

2017-08-28 17:08 UTC, c-monkey approved these changes

2017-08-29 14:52 UTC, holmesie approved these changes
Approved

2017-08-29 18:53 UTC, mayerm94 commented
Test: https://jira.mitre.org/browse/BONNIE-1001

2017-08-29 19:41 UTC, c-monkey approved these changes
https://jira.mitre.org/browse/BONNIE-1001 passed

2017-08-31 17:36 UTC, merged