Cql4bonnie qdm5 3 453
MeasureAuthoringTool/bonnie pull request #826
Opened 2017-08-24 16:20 UTC by losborne

JIRA Ticket: https://jira.mitre.org/browse/BONNIE-453

Unit tests included so no JIRA tests.  

UI Demo:
![component_ui](https://user-images.githubusercontent.com/14879344/29676621-8c3e5e62-88c6-11e7-8b43-bd61b236cbfd.gif)

NOTE:
`patient_builder_spec.js.coffee` looks like it has a lot of changes, but it is just an indentation change to separate QDM and CQL tests.

2017-08-24 16:50 UTC, c-monkey commented
if you click on the "files changed" tab above, and append "?w=1" to the end of the url, whitespace is ignored. You can't make comments, but it is a useful tool to show you only the non-whitespace changes.

2017-08-24 21:42 UTC, c-monkey requested changes

2017-08-24 21:42 UTC, c-monkey commented on app/assets/javascripts/templates/patient_builder/edit_criteria.hbs
> +                    {{title}}{{#if value}}, {{value}}{{/if}}{{#if unit}}, {{unit}}{{/if}}{{#if referenceRangeLow_value}}, Reference Range - Low: {{referenceRangeLow_value}}{{referenceRangeHigh_unit}}
3 issues with this line:
- there is an extra comma prior to the unit
- there is a missing space before the referenceRangeHigh_unit
- the referenceRangeHigh_unit is accidentally used for the referenceRangeLow

2017-08-25 12:54 UTC, losborne commented on app/assets/javascripts/templates/patient_builder/edit_criteria.hbs
> +                    {{title}}{{#if value}}, {{value}}{{/if}}{{#if unit}}, {{unit}}{{/if}}{{#if referenceRangeLow_value}}, Reference Range - Low: {{referenceRangeLow_value}}{{referenceRangeHigh_unit}}
Good catches--they should be fixed now, though I had to go into the "Files changed" page on Github to see the new version.

2017-08-25 17:36 UTC, c-monkey commented on app/assets/javascripts/templates/patient_builder/edit_criteria.hbs
> +                    {{title}}{{#if value}}, {{value}}{{/if}}{{#if unit}} {{unit}}{{/if}}{{#if referenceRangeLow_value}}, Reference Range - Low: {{referenceRangeLow_value}} {{referenceRangeLow_unit}}{
this is much better, but I think you need to put in the if statements around the reference units, if they're missing the whitespace looks bad

2017-08-25 17:37 UTC, c-monkey commented
Unit tests pass, only cosmetic changes remain.

2017-08-25 17:45 UTC, losborne commented on app/assets/javascripts/templates/patient_builder/edit_criteria.hbs
> +                    {{title}}{{#if value}}, {{value}}{{/if}}{{#if unit}} {{unit}}{{/if}}{{#if referenceRangeLow_value}}, Reference Range - Low: {{referenceRangeLow_value}} {{referenceRangeLow_unit}}{
Good call--should be fixed now:
![image](https://user-images.githubusercontent.com/14879344/29725845-96ed8524-899b-11e7-9ace-51cd16e6494a.png)

2017-08-25 17:47 UTC, c-monkey submitted a review, later dismissed

2017-08-29 11:44 UTC, c-monkey commented on spec/javascripts/views/patient_builder_spec.js.coffee
> -      # droppable 5 used because droppable 1 didn't have a start and end date
You didn't pay careful attention and threw away a previous change in your merge. This is twice now I've found you've done that. Please figure out a way to merge that you can ensure you aren't introducing bugs, please.

I caught this because the test that had been fixed in the previous change was broken again.

2017-08-29 11:44 UTC, c-monkey requested changes
Feature works as intended. Need to fix merge error.

2017-08-29 15:06 UTC, losborne commented on spec/javascripts/views/patient_builder_spec.js.coffee
> -      # droppable 5 used because droppable 1 didn't have a start and end date
Good catch, thanks.  The merge provided had the whole document duplicated with my changes sandwiched in the middle for some reason, and I guess I chose the newer of the two to remove. I'll make sure to be more careful in the future. 

@edeyoung this solves the broken test we discussed yesterday.

2017-08-29 15:11 UTC, c-monkey submitted a review, later dismissed

2017-08-29 15:42 UTC, alexanderelliott121 submitted a review, later dismissed
Seeing the desired frontend, all tests passing.
Not seeing any glaring code problems.

2017-09-05 12:41 UTC, alexanderelliott121 approved these changes
Looks good to me

2017-09-05 13:41 UTC, c-monkey approved these changes
manual and unit tests pass, still

2017-09-05 14:01 UTC, merged