If there is a Result just allow one Result
MeasureAuthoringTool/bonnie pull request #827
Opened 2017-08-24 20:44 UTC by mulcahyk

https://jira.mitre.org/browse/BONNIE-853

Align the behavior of Bonnie with the QDM spec (5.02, 5.3) that for certain data criteria there can be up to 1 Result per instance of that criteria.

2017-08-25 17:50 UTC, c-monkey submitted a review, later dismissed
tests pass, looks good

One question: for existing patients with multiple results, do we need to do some sort of mongo query and report to the MDs so they can fix them?

2017-08-25 18:03 UTC, edeyoung commented
good idea! kristian, can you pull that together?

2017-08-25 19:46 UTC, edeyoung requested changes

2017-08-25 19:46 UTC, edeyoung commented on app/assets/javascripts/views/patient_builder/data_criteria.js.coffee
> +      hideEditValueView: onlySingleResultAllowed
Consider making this just be:

```
hideEditValueView: @values.models.length > 0
```

2017-08-28 14:36 UTC, edeyoung approved these changes

2017-08-28 14:36 UTC, edeyoung commented
i've approved *code* changes. @c-monkey can you re-run the tests for this to confirm it all still works? Thanks!

2017-08-28 15:02 UTC, c-monkey approved these changes
Tests pass,  TestCMS167 (CMS21v0) in the epecqmama@gmail.com works as expected.

2017-08-31 17:47 UTC, merged