Cql4bonnie 1028
MeasureAuthoringTool/bonnie pull request #832
Opened 2017-08-31 11:39 UTC by mayerm94

Test with health-data-standards cql4bonnie_1028

2017-08-31 13:41 UTC, losborne commented on app/assets/javascripts/templates/patient_builder/edit_criteria.hbs
> +                  {{numerator}}/{{denominator}}
Should there be an #if to make sure there is a denominator?

2017-08-31 13:43 UTC, losborne commented on app/assets/javascripts/templates/patient_builder/edit_criteria.hbs
> +                  {{value}} {{unit}}
I think this will add an extra space if there are no units--add an #if block around the space and unit to just have 1 space in that case.

2017-08-31 16:13 UTC, holmesie requested changes

2017-08-31 16:13 UTC, holmesie commented on app/assets/javascripts/templates/patient_builder/edit_value.hbs
> +            <option value="RT" data-icon="fa fa-pencil-square-o">Ratio</option>
This is using the same icon as `Scalar`. Instead of `fa-pencil-square-o`, why not something like `fa-balance-scale`? Take a look at [this](http://fontawesome.io/cheatsheet/).

2017-08-31 16:20 UTC, hossenlopp commented on app/assets/javascripts/templates/patient_builder/edit_value.hbs
> +            <option value="RT" data-icon="fa fa-pencil-square-o">Ratio</option>
Why not `fa-percent`?

2017-08-31 21:02 UTC, losborne commented on app/assets/javascripts/templates/patient_builder/edit_value.hbs
> +          <input type="number" name="denominator" id="denominator{{@cid}}" class="form-control" placeholder="Denominator">
id should be `denominator_{{@cid}}` to be consistent with numerator and other ids

2017-08-31 21:17 UTC, lukoktonos requested changes
Just have one more suggestion--I think there needs to be a validation added to `bonnie/app/assets/javascripts/views/patient_builder/data_criteria.js.coffee` (validateForAddition, line 497) to validate that both a numerator and a denominator have been filled in before allowing the user to add.

(Note the boolean logic for components is wrong for that currently, so don't copy it. That will be fixed with my BONNIE-453 PR).

I think the correct logic should look like:
```
(attributes.type == 'RT' && (!attributes.denominator || !attributes.numerator)) || ...
```

2017-09-05 14:02 UTC, edeyoung commented
RATIO WORK NO LONGER BEING USED AS OF 9/1 DISCUSSION IN HQMF CQL TOOLING CALL

2017-09-05 14:02 UTC, closed without merging