Add support for ReferenceRange for LaboratoryTestPerformed, for QDM5.3
MeasureAuthoringTool/bonnie pull request #836
Opened 2017-09-04 18:47 UTC by losborne

Also pulled in UI changes from bonnie branch cql4bonnie-QDM5_3_453 needed for visual inspection.
(PR for those changes here: https://github.com/projecttacoma/bonnie/pull/826)

For CI tests to pass, need to point health-data-standards and cql_qdm_patientapi to branches cql4bonnie-QDM5_3_1000.

JIRA Ticket: https://jira.mitre.org/browse/BONNIE-1000

2017-09-05 13:26 UTC, mayerm94 commented on app/assets/javascripts/templates/patient_builder/edit_value.hbs
> +  <div class="row">
Tab in for ifCond block

2017-09-05 14:31 UTC, mayerm94 commented on app/assets/javascripts/templates/patient_builder/edit_value.hbs
> +      <div class="col-md-3">
col-md should sum to 12

2017-09-05 14:56 UTC, losborne commented on app/assets/javascripts/templates/patient_builder/edit_value.hbs
> +      <div class="col-md-3">
I think it looks better as is, because the input fields are vertically aligned.  If I change it to sum to 12, they are no longer aligned:
![image](https://user-images.githubusercontent.com/14879344/30067370-99027456-9228-11e7-86f7-02d9d46c55c4.png)
![image](https://user-images.githubusercontent.com/14879344/30067406-b2e331e4-9228-11e7-8806-de6334eb99d8.png)

2017-09-05 15:10 UTC, mayerm94 submitted a review, later dismissed
Changes look good

2017-09-05 17:07 UTC, holmesie requested changes

2017-09-05 17:07 UTC, holmesie commented on app/assets/javascripts/templates/patient_builder/edit_value.hbs
> +      <div class="col-md-3">
I don't think that would always be the case (between browsers now and into the future/tablets), these should _really_ add up to 12. Even if you used offsets, or had a blank div, that would be preferable imo.

2017-09-05 17:07 UTC, holmesie commented on lib/measures/patient_builder.rb
> +        if value["referenceRangeLow_value"]
Likely dumb question, but are we always assuming there will be a `referenceRangeHigh_value` if there is a `referenceRangeLow_value`? Do we care if if the value was ever just a blank string or something? I guess what I'm getting at is maybe a `present?` here couldn't hurt.

2017-09-05 17:29 UTC, losborne commented on app/assets/javascripts/templates/patient_builder/edit_value.hbs
> +      <div class="col-md-3">
I added a blank div at the end and it looks like it is still aligned vertically, so that should work.

2017-09-05 17:34 UTC, edeyoung commented on lib/measures/patient_builder.rb
> +        if value["referenceRangeLow_value"]
good point - i think you could have a referencehigh without a referenclow
i think these are meant to give you an idea if a lab result is too high or is too low.

2017-09-05 17:40 UTC, losborne commented on lib/measures/patient_builder.rb
> +        if value["referenceRangeLow_value"]
This `if value["referenceRangeLow_value"]` is meant to determine if this "CMP" is coming from a Component or a ResultComponent. It is OK if `value["referenceRangeLow_value"]` or `value["referenceRangeHigh_value"]` are `""`, because in rubyland that evaluates to true.  When the ResultComponent constructor gets called in cql_qdm_patientapi, the `""` evaluates to `false` in the if statement and so the range Interval has an undefined edge for that case.

There is a similar check to see if it is a Component vs ResultComponent in HDS:
```if json['referenceRangeLow_value']```

Do you think a comment clarifying this behavior would be sufficient? Or do you still think there needs to be some other change with the logic?

2017-09-05 17:52 UTC, holmesie commented on lib/measures/patient_builder.rb
> +        if value["referenceRangeLow_value"]
No, things are clearer to me now.

2017-09-05 17:53 UTC, holmesie submitted a review, later dismissed

2017-09-06 12:18 UTC, edeyoung approved these changes

2017-09-06 12:22 UTC, merged