Bonnie 1061
MeasureAuthoringTool/bonnie pull request #841
Opened 2017-09-08 13:14 UTC by losborne

JIRA Test:
https://jira.mitre.org/browse/BONNIE-1069

JIRA Task:
https://jira.mitre.org/browse/BONNIE-1061

2017-09-08 16:24 UTC, mulcahyk requested changes
The rake task is not updating the source_data_criteria.  This needs to be addressed.

2017-09-08 16:24 UTC, mulcahyk commented on lib/tasks/cql.rake
> +        new_datatype_facility['type'] = 'COL'
I understand the need for a `type`.  Is there something other than `COL` that could be used?  It just looks a lot like C**Q**L.

2017-09-08 16:24 UTC, mulcahyk commented on lib/tasks/cql.rake
> +      # Update old facilities and diagnoses to be collections with single elements
Comments needs to be updated. The comment says you are only doing this for facilities and diagnoses but the code is also checking for adverse events and procedures.

2017-09-08 16:24 UTC, mulcahyk commented on lib/tasks/cql.rake
> +              new_encounter_diagnosis
extra line??

2017-09-08 16:24 UTC, mulcahyk commented on lib/tasks/cql.rake
> +          patient.encounters.each do |encounter, index|
If you want to get the index use `.each_with_index`.  I don't see where you are using the index though.

2017-09-08 16:24 UTC, mulcahyk commented on lib/tasks/cql.rake
> +        print "\e[#{32}m#{"[Facility]"}\e[0m"
I like the coloring!

2017-09-08 16:28 UTC, losborne commented on lib/tasks/cql.rake
> +        new_datatype_facility['type'] = 'COL'
That's true--this change would need to be reflected in cql_qdm_patientapi, health-data-standards, and bonnie, however, so I don't think it's in the scope of this PR to modify.

2017-09-08 16:29 UTC, losborne commented on lib/tasks/cql.rake
> +      # Update old facilities and diagnoses to be collections with single elements
Facility is a possible sub-field of {encounter, adverse event, procedure}, and diagnosis is a sub-field of encounter.

2017-09-08 16:29 UTC, losborne commented on lib/tasks/cql.rake
> +          patient.encounters.each do |encounter, index|
Good catch--I had refactored the loop but forgot to remove the 'index'.

2017-09-08 16:30 UTC, losborne commented on lib/tasks/cql.rake
> +              new_encounter_diagnosis
Good catch--don't know what that's doing there.

2017-09-08 16:31 UTC, mulcahyk commented
This shows an example of a patient converted by the rake task with their source_data_criteria and the new encounter['facility'].  
![image](https://user-images.githubusercontent.com/17731116/30221392-066a9784-9491-11e7-942f-ab3d551bf9ed.png)
This still has the old field_values but not the new structure for facility location.

Here is a patient added using the latest cql4bonnie.
![image](https://user-images.githubusercontent.com/17731116/30221488-76bb9ff6-9491-11e7-965e-2e2086f1dfd5.png)

2017-09-08 17:41 UTC, alexanderelliott121 commented
JIRA test has a typo.
bundle exec **rails** bonnie:cql:update_facilities_and_diagnoses

should be

bundle exec **rake** bonnie:cql:update_facilities_and_diagnoses

2017-09-08 19:03 UTC, alexanderelliott121 commented
I've run the test and had it pass.

2017-09-08 19:19 UTC, alexanderelliott121 submitted a review, later dismissed
Test passed

2017-09-08 19:38 UTC, mulcahyk requested changes

2017-09-08 19:38 UTC, mulcahyk commented on lib/tasks/cql.rake
> +                  new_source_data_criterium_field_values['FACILITY_LOCATION'] = new_facility_location
source_data_criteria['field_values]['FACILITY_LOCATION'] in the old version does not have any time information.  Time information is in the fields FACILITY_LOCATION_ARRIVAL_DATETIME and FACILTIY_LOCATION_DEPARTURE_DATETIME.

2017-09-08 19:38 UTC, mulcahyk commented on lib/tasks/cql.rake
> +          patient.source_data_criteria.each_with_index do |source_data_criterium, index|
I don't see where you are using `index` - consider removing.

2017-09-10 13:02 UTC, edeyoung commented
Looks like "key" may be  missing from source data criteria conversion. Top is a converted value. Bottom is a value built afterwards.

![image](https://user-images.githubusercontent.com/11574199/30249267-cd0ce092-9606-11e7-98e4-d08424eb8107.png)

2017-09-10 13:18 UTC, edeyoung commented
Looks like 'key' is missing and the 'cd' type needs to be modified to 'fac'. Top is old converted one. Bottom is new one.

![image](https://user-images.githubusercontent.com/11574199/30249354-deba42ba-9608-11e7-8564-72e36f527c66.png)

Not in the scope of this PR, but the time likely should not be set if the date is set for a facility location. Will create ticket.

2017-09-11 13:35 UTC, mulcahyk requested changes

2017-09-11 13:35 UTC, mulcahyk commented on lib/tasks/cql.rake
> +                elsif field_value_key == 'FACILITY_LOCATION' && !(source_data_criterium['field_values']['FACILITY_LOCATION']['type'] == 'COL')
This is assuming that all encounters will have a FACILITY_LOCATION.  Most of the current patients don't have a FACILITY_LOCATION; only 14 of 90 do.  The rest have only the times.  When this runs it is deleting the time only soruce_data_criteria.

2017-09-11 15:18 UTC, mulcahyk requested changes
The issue I'm seeing still isn't fixed.
Look at this test patient:
First: "InEDPsychDiagPrincipal"
Last: "IPStrat1Pass"
Measure_ids: "28AC347D-2F91-4A0C-9395-2602134BAA89"
This test patient in the original has facility arrival and departure times only; no location.  After running the rake task the source_criteria with those field_values only has the PRINCIPAL_DIAGNOSIS left.  When you look at the encounter there is no facility information.

2017-09-11 16:56 UTC, losborne commented
@mulcahyk I think this is the correct behavior.  For the new version, in order to add a facility arrival/departure, the UI validates that a code has been entered.  It is impossible to add a time without a code.  

We purposefully remove any facility objects (and the corresponding source_data_critieria arrival/departure times) for any patients that have time information without a location code.

2017-09-11 16:57 UTC, losborne commented on lib/tasks/cql.rake
> +                elsif field_value_key == 'FACILITY_LOCATION' && !(source_data_criterium['field_values']['FACILITY_LOCATION']['type'] == 'COL')
I believe this is the intended behavior of the script.  @edeyoung is this the case?  If not, I can remove the part of the script that deletes these items.

2017-09-11 17:06 UTC, edeyoung commented
@mulcahyk yes, this is the correct behavior. The Location Period needs to be linked to a Location code.

2017-09-11 17:06 UTC, edeyoung commented
@losborne can you make the log show what patients in what measures in what accounts have this removed?

2017-09-11 18:09 UTC, losborne commented
@edeyoung log updated

2017-09-11 18:12 UTC, mulcahyk commented on lib/tasks/cql.rake
> +    end
More cool logging.  Love it!

2017-09-11 18:12 UTC, mulcahyk commented on lib/tasks/cql.rake
> +          datatype.remove_attribute(:facility)
This is a small issue.
It looks like every patient that has a `[Facilty]` also has a `[Removing]`.

2017-09-11 18:12 UTC, mulcahyk commented on lib/tasks/cql.rake
> +                  new_source_data_criterium_field_values.delete(field_value_key)
Can the `Removing` logging be done here as well?

2017-09-11 18:40 UTC, mulcahyk submitted a review, later dismissed

2017-09-12 13:41 UTC, mulcahyk approved these changes

2017-09-12 14:19 UTC, merged