Added warning message for outdated (pre-QDM 5.3) measures
MeasureAuthoringTool/bonnie pull request #847
Opened 2017-09-19 16:57 UTC by c-monkey

JIRA: https://jira.mitre.org/browse/BONNIE-1074
TESTS: added unit tests in cql_logic_view_spec.js.coffee

I recommend comparing the test file with the `?w=1` url suffix because I had to indent most of the file to split into 2 test fixtures

If you wish to see this in a manual test, download a package (or use any you already have) prior to MAT 5.4 from: https://gitlab.mitre.org/bonnie/internal-documentation/wikis/cql-measures-for-testing, upload to Bonnie, and open the measure details screen.

2017-09-19 17:40 UTC, holmesie requested changes

2017-09-19 17:40 UTC, holmesie commented on app/assets/javascripts/views/logic/cql_logic_view.js.coffee
> +          if (id.localIdentifier == "QDM")
It's not really Coffeescript style to use parens in If, Else, Unless, and Conditional Assignments, e.g. `if (stuff)`, but since I'm seeing it in other places in this file, I don't think it's an approval stopper.

2017-09-19 17:40 UTC, holmesie commented on app/assets/javascripts/views/logic/cql_logic_view.js.coffee
> +            versionParts = id.version.split('.')
Is it possible at any point for either `id` itself being null, or in this case, `version` being null (which causes the `.split` to raise an error)?

2017-09-19 17:40 UTC, holmesie commented on app/assets/javascripts/views/logic/cql_logic_view.js.coffee
> +                @hasOutdatedQDM = true
I think this all (previous 9 lines) can be simplified to:
```
version = parseFloat(id?.version)
unless isNaN(version)
   @hasOutdatedQDM = version < 5.3
```
parseFloat will ignore the second potential `.<number>`, so if we had `"5.0.2"`, it would return `5.0`.

NOTE: this would only make sense if we didn't ever care about patch numbers in QDM versions, which I am unsure of.

2017-09-19 19:09 UTC, c-monkey commented on app/assets/javascripts/views/logic/cql_logic_view.js.coffee
> +                @hasOutdatedQDM = true
Although extremely appealing, I think removing the flexibility isn't appropriate in the general case.

2017-09-19 19:11 UTC, c-monkey commented on app/assets/javascripts/views/logic/cql_logic_view.js.coffee
> +          if (id.localIdentifier == "QDM")
Nice catch. I was following the existing style as opposed to doing the right thing. Thanks!

2017-09-19 20:11 UTC, c-monkey commented on app/assets/javascripts/views/logic/cql_logic_view.js.coffee
> +            versionParts = id.version.split('.')
I added a null check just in case.

2017-09-19 20:11 UTC, c-monkey commented on app/assets/javascripts/views/logic/cql_logic_view.js.coffee
> +          if (id.localIdentifier == "QDM")
fixed this and some of the accompanying code

2017-09-20 13:33 UTC, holmesie submitted a review, later dismissed
Tests pass, my comments have been addressed, approved.

2017-09-20 17:53 UTC, alexanderelliott121 submitted a review, later dismissed

2017-09-22 16:43 UTC, edeyoung commented on app/assets/javascripts/views/logic/cql_logic_view.js.coffee
> +              @hasOutdatedQDM = true
I doubt this will happen, but what if we go to QDM 5.3.1?

This would falsely fire.

2017-09-22 16:46 UTC, edeyoung submitted a review, later dismissed
See comments

2017-09-22 16:46 UTC, edeyoung commented on app/assets/javascripts/views/logic/cql_logic_view.js.coffee
> +                @hasOutdatedQDM = true
What about something like this: 

```
Gem::Version.new('0.4.1') > Gem::Version.new('0.10.1')
```

from here: https://stackoverflow.com/questions/2051229/how-to-compare-versions-in-ruby

This would make it more generalized and we can then add the version we care about as a config variable (which we should do)

2017-09-22 16:48 UTC, c-monkey commented on app/assets/javascripts/views/logic/cql_logic_view.js.coffee
> +                @hasOutdatedQDM = true
I consent to this proposal.

2017-09-22 16:55 UTC, c-monkey commented on app/assets/javascripts/views/logic/cql_logic_view.js.coffee
> +                @hasOutdatedQDM = true
This would be perfect if this code were in Ruby. I'll figure out an equivalent for front-end.

2017-09-22 17:55 UTC, edeyoung commented on app/assets/javascripts/views/logic/cql_logic_view.js.coffee
> +                @hasOutdatedQDM = true
ha :) yes, thanks!

2017-09-25 14:26 UTC, alexanderelliott121 commented
I'm going to hold off on approval until the branch has been merged/rebased

2017-09-25 14:37 UTC, holmesie requested changes
What's going on with the Travis failures?

2017-09-25 14:37 UTC, holmesie commented on app/assets/javascripts/helpers/compare_version.js.coffee
> +class CompareVersion
I like this!

2017-09-25 14:37 UTC, holmesie commented on config/bonnie.yml
> +  support_qdm_version: 5.3
This will be nice to have

2017-09-25 19:27 UTC, c-monkey commented on app/assets/javascripts/views/logic/cql_logic_view.js.coffee
> +              @hasOutdatedQDM = true
I have added a unit test to show QDM 5.3.1 is equal to or newer than QDM 5.3 and will now pass.

2017-09-25 19:28 UTC, c-monkey commented on app/assets/javascripts/views/logic/cql_logic_view.js.coffee
> +                @hasOutdatedQDM = true
The new CompareVersion class should handle this.

2017-09-25 19:29 UTC, c-monkey commented
Still investigating 1 travis failure. I fixed some BonnieRouter global variable assignment to work both in the App and in Jasmine tests, but am still investigating the other failure.

2017-09-26 13:12 UTC, c-monkey commented
This test failure is similar to one we fixed in the master branch. The test fixture is being changed by other tests execution. One can reproduce this test failure in the `cql4bonnie` branch in the web-teaspoon runner by running just the MeasureView suite. Regardless, this PR is going to be held up until I can fix that test. I also noticed, while debugging this, that the new suite I added `CompareVersion` always runs, for example when you select a suite to debug.

2017-09-26 14:11 UTC, holmesie submitted a review, later dismissed

2017-10-17 13:10 UTC, c-monkey commented
rebased

2017-10-17 14:58 UTC, alexanderelliott121 approved these changes

2017-10-18 14:12 UTC, merged