Cql4bonnie 508 fixes
MeasureAuthoringTool/bonnie pull request #849
Opened 2017-09-21 17:47 UTC by losborne

This pull request is for several minor changes to update Bonnie to be 508 compliant.

*JIRA Test:* https://jira.mitre.org/browse/BONNIE-1099
*JIRA Ticket Links:*
- https://jira.mitre.org/browse/BONNIE-1015
- https://jira.mitre.org/browse/BONNIE-1016
- https://jira.mitre.org/browse/BONNIE-1018
- https://jira.mitre.org/browse/BONNIE-1019
- https://jira.mitre.org/browse/BONNIE-1020
- https://jira.mitre.org/browse/BONNIE-1023
- https://jira.mitre.org/browse/BONNIE-1024

Automated regression test passes: 
Before: cql4bonnie, After: cql4bonnie with these changes merged locally.

Pull requests into Bonnie require the following. (Reviewer should :heavy_check_mark:*when done*):
- [ ] This pull request describes *why* these changes were made.
- [ ] JIRA ticket for this PR: 
- [ ] JIRA ticket links to this PR.
- [ ] JIRA test for this PR: 
- [ ] JIRA test has been added to sprint.
- [ ] Automated regression test(s) pass (if possible): 
- [ ] Regression test screenshots before/after:

2017-09-21 20:48 UTC, c-monkey submitted a review, later dismissed
https://jira.mitre.org/browse/BONNIE-1099 passes, not all things are fixed but everything called out here is.

2017-09-21 20:48 UTC, c-monkey commented on app/assets/javascripts/models/difference.js.coffee
> +    generatePercentageId = ->
This was duplicated verbatim from `Thorax.Models.MeasureDataCriteria.generateCriteriaId` why not just use that? Or move to a shared location if needed? There is no need for duplication of code.

2017-09-22 20:42 UTC, ssayer approved these changes
This does fix everything described in the JIRA test, however the JIRA bugs described are more far reaching than what is fixed here (mostly contrast issues). I just want to be clear about the ticket status so they aren't closed prematurely.

2017-09-22 21:13 UTC, ssayer requested changes
After discussing with @edeyoung, this needs to address the contrast issues on the landing page. The blue links in the footer either need to be bold or a different color

2017-09-25 20:21 UTC, ssayer submitted a review, later dismissed
Addresses contrast issues

2017-09-25 23:48 UTC, edeyoung requested changes
Please respond to questions below. Otherwise, changes look good to me.

2017-09-25 23:48 UTC, edeyoung commented on app/assets/stylesheets/builder.less
> +          background-color: #003456;
should this have a css variable?

2017-09-25 23:48 UTC, edeyoung commented on app/assets/stylesheets/measures.less
> +      color: #005791;
should this have a css variable?

2017-09-26 00:12 UTC, edeyoung commented on app/assets/stylesheets/builder.less
> +          background-color: #003456;
I'm also liking `@blue-darkest` over this color: 

(blue-darkest)
![image](https://user-images.githubusercontent.com/11574199/30836681-af41ec1e-a22d-11e7-9a80-35f9a0fdbd67.png)

(this color)
![image](https://user-images.githubusercontent.com/11574199/30836699-c8ab1266-a22d-11e7-8ca9-704c6cdd1b80.png)

I think what is currently being used is too dark.

2017-09-26 00:15 UTC, edeyoung commented
Looks good other than optional comments to address. jira test passes and covers issues associated with this PR.

2017-09-26 11:49 UTC, losborne commented on app/assets/stylesheets/builder.less
> +          background-color: #003456;
Agreed--will change to blue-darkest.

2017-09-26 11:49 UTC, losborne commented on app/assets/stylesheets/measures.less
> +      color: #005791;
It looks like @blue-darkest will pass the 508 spec here, so I will switch it to that.

2017-09-26 12:20 UTC, edeyoung approved these changes

2017-09-26 15:23 UTC, merged