Cql4bonnie 1084 coverage issues
MeasureAuthoringTool/bonnie pull request #850
Opened 2017-09-22 16:55 UTC by mayerm94

Pull requests into Bonnie require the following. (Reviewer should :heavy_check_mark:*when done*):
- [ ] This pull request describes *why* these changes were made.
- [ ] JIRA ticket for this PR: 
- [ ] JIRA ticket links to this PR.
- [ ] JIRA test for this PR: 
- [ ] JIRA test has been added to sprint.
- [ ] Automated regression test(s) pass (if possible): 
- [ ] Regression test screenshots before/after:

2017-09-22 17:01 UTC, mayerm94 commented
This PR makes sure that 'from's without a 'return' expression local id dont  get added to the list of localId's used in coverage calculation
https://jira.mitre.org/browse/BONNIE-1084

2017-09-25 17:23 UTC, mayerm94 commented
JIRA Test https://jira.mitre.org/browse/BONNIE-1105

2017-09-25 20:08 UTC, holmesie requested changes

2017-09-25 20:08 UTC, holmesie commented on spec/javascripts/views/cql_logic_view_spec.js.coffee
> +    expectedResults = '[{"statementName":"SDE Ethnicity","final":"NA"},{"statementName":"SDE Ethnicity","final":"NA"},{"statementName":"SDE Payer","final":"NA"},{"statementName":"SDE Payer","final":"
So, why exactly was `{"statementName":"RelatedEDVisit","final":"NA"}` removed from the expected results? I'm not really understanding from the commit message.

2017-09-25 20:08 UTC, holmesie commented on app/assets/javascripts/helpers/cql_measure_helpers.js.coffee
> +        if alId?
What does it mean if `alId?` is false? Something went terribly wrong?

2017-09-25 20:08 UTC, holmesie commented on app/assets/javascripts/helpers/cql_measure_helpers.js.coffee
> +      if localIds[alias.expressionLocalId]? && alias.aliasLocalId?
Does the original comment above still apply with this added check? Or is the new check adding something important enough that warrants an explanation?

2017-09-26 11:19 UTC, mayerm94 commented on app/assets/javascripts/helpers/cql_measure_helpers.js.coffee
> +        if alId?
If there is not a alId that means that the scope entry does not have a 'as type specifier' to pull the local ID from. Because there is no localID to associate the 'astypespecifier' clause with, it can't be referenced in other parts of the logic and will not be added to the emptyResultClauses list to be considered in coverage.

2017-09-26 11:58 UTC, mayerm94 commented on spec/javascripts/views/cql_logic_view_spec.js.coffee
> +    expectedResults = '[{"statementName":"SDE Ethnicity","final":"NA"},{"statementName":"SDE Ethnicity","final":"NA"},{"statementName":"SDE Payer","final":"NA"},{"statementName":"SDE Payer","final":"
See the last step of the JIRA test associated with this PR https://jira.mitre.org/browse/BONNIE-1105 Before the changes there was an entry in the localIds list that was mapping undefined->"201". The clause results are built in buildStatementAndClauseResult in cql_results_helpers.js.coffee which iterates over all of the localIds list and maps the localId (or sourceLocalId) to a result. Because of the logic on line 70, the undefined->"201" key/value pair was never added to the localIds and when it came time to run buildStatementAndClauseResults(), the entry {"statementName":"RelatedEDVisit","final":"NA"}  which was representing the sourceLocalId that was mapped to Undefined was not added to the clause_results

2017-09-26 15:26 UTC, holmesie approved these changes
Comments addressed; had an in person review about remaining concerns; Looks good.

2017-09-26 16:32 UTC, jbradl11 requested changes
Jira Test cannot be completed. Looks like the measure on the account no longer has patients to test with.

2017-09-26 21:03 UTC, jbradl11 approved these changes
Changes make sense, Jira test passes. Looks good. It would be nice to have a regression test for measure logic coverage.

2017-09-26 21:19 UTC, merged