Cql4bonnie 1103 excel export
MeasureAuthoringTool/bonnie pull request #853
Opened 2017-09-25 20:44 UTC by jbradl11

Rewrote logic for checking character length of worksheet titles. Previously we were checking if the population['title'] was greater than 31 characters, if it wasn't we would use `Population index - population['title']`, which could then be greater than 31 characters. My fix checks if `Pop Index - population['title']` is greater than 31 characters. Also, updated fixture data to use the measure that caused this issue for greater edge case testing.  

Pull requests into Bonnie require the following. (Reviewer should :heavy_check_mark:*when done*):

Submitter:

- [ ] This pull request describes *why* these changes were made.
- [ ] Tests are included and test edge cases
- [ ] Link to JIRA test(s), if used:
- [ ] JIRA test(s) have been added to sprint, if used
- [ ] JIRA ticket for this PR: 
- [ ] JIRA ticket links to this PR.
- [ ] Automated regression test(s) pass (if applicable): 

Reviewer 1:
- [ ] The code is maintainable
- [ ] The code reuses code or resources within the project ecosystem where applicable
- [ ] The code achieves its purpose
- [ ] The tests appropriately test edge cases
- [ ] The tests pass

Reviewer 2:
- [ ] The code is maintainable
- [ ] The code reuses code or resources within the project ecosystem where applicable
- [ ] The code achieves its purpose
- [ ] The tests appropriately test edge cases
- [ ] The tests pass

2017-09-26 14:46 UTC, lukoktonos requested changes
Needs one change and an additional test.

2017-09-26 14:46 UTC, losborne commented on lib/patient_export.rb
> +                              "#{pop_index + 1} - #{worksheet_title}"
`worksheet_title` is undefined here because line 70 was removed.

2017-09-26 14:46 UTC, losborne commented on test/fixtures/functional/patient_controller/population_details.json
> +{"c10":{"title":"Population Criteria Section 1","statement_relevance":{"AntidepressantMedicationManagement":{"Patient":"NA","SDE Ethnicity":"NA","SDE Payer":"NA","SDE Race":"NA","SDE Sex":"NA","Medic
"Population Criteria Section 1" has length of 29.  There should be another test that has a length of > 31 as well to test both cases.  It might be good to add 1 to the length of one of these titles as well to have a test for length 30 (which worked when I tested manually).

2017-09-26 15:52 UTC, lukoktonos requested changes
Changes look good, only comment is to remove duplicated code in new tests

2017-09-26 15:52 UTC, losborne commented on test/functional/patients_controller_test.rb
> +    get :excel_export, calc_results: calc_results, patient_details: patient_details, population_details: population_details, statement_details: statement_details, file_name: "test"
There is a lot of repeated code in these tests--could you refactor them to either be one test that loops over an array of `population_details` filenames or make a helper function to take away the repeated code?

2017-09-26 16:32 UTC, lukoktonos approved these changes
Changes look good.

2017-09-26 21:36 UTC, c-monkey approved these changes
The unit tests verify no error arises due to export, but it might be good to have a manual test for validation since we are relying on a user's account that might change. JB suggested perhaps we need 1 overall Excel export test that includes this along with other manual tests of export.

Verified https://oncprojectracking.healthit.gov/support/browse/BONNIE-387 by locally changing population names and re-exporting.

This code is mirrored over from production. The code is easy to understand and maintainable.

Unit tests pass.

2017-09-27 13:11 UTC, losborne commented
Automated regression script shows no differences.

2017-09-27 15:33 UTC, merged