Cql4bonnie h1h2
MeasureAuthoringTool/bonnie pull request #859
Opened 2017-10-03 15:41 UTC by losborne

Previously, Bonnie used heading tags like <h1>, <h2>, etc. to add styling to a
page rather than just denote page division.  In order to be comlpiant with 508
specs, the styling was moved into CSS classes "h1-style", "h2-style", etc. and
the headings were removed except in cases where they actually denote a proper
page division.

Most changes should result in no UI changes, but there was one very minor space change that we couldn't get to be exactly the same on the patient builder page, but should be acceptable:
Before
![image](https://user-images.githubusercontent.com/14879344/31134170-5a1e64a8-a82f-11e7-85b1-10daee13e295.png)
After
![image](https://user-images.githubusercontent.com/14879344/31134181-6515ff4c-a82f-11e7-9ce4-e69fd0ef9197.png)

Pull requests into Bonnie require the following. Submitter and reviewer should :white_check_mark: when done. For items that are not-applicable, note it's not-applicable ("N/A") and :white_check_mark:.

**Submitter:**
- [X] This pull request describes why these changes were made.
- [X] JIRA ticket for this PR: https://jira.mitre.org/browse/BONNIE-1012
- [ ] JIRA ticket links to this PR
- [X] Code diff has been done and been reviewed
- [X] If UI changes have been made, google WAVE plug-in has been executed to ensure no 508 issues were introduced.
- [X] Tests are included and test edge cases (N/A)
- [X] Tests have been run locally and pass (remember to update Gemfile when applicable)
- [X] Automated regression test(s) pass

If JIRA tests were used to supplement or replace automated tests:
- [X] JIRA test links: https://jira.mitre.org/browse/BONNIE-1118
- [X] Justification for using JIRA tests: WAVE tool cannot be run in a unit test.
- [X] JIRA tests have been added to sprint

**Reviewer 1:** (@hossenlopp)

Name:
- [ ] Code is maintainable and reusable, reuses existing code and infrastructure where appropriate, and accomplishes the task’s purpose
- [ ] The tests appropriately test the new code, including edge cases
- [ ] You have tried to break the code

If JIRA tests were used to supplement or replace automated tests:
- [ ] JIRA tests have been run and pass
- [ ] You agree with the justification for use of JIRA tests or have provided input on why you disagree

**Reviewer 2:** (@holmesie)

Name:
- [ ] Code is maintainable and reusable, reuses existing code and infrastructure where appropriate, and accomplishes the task’s purpose
- [ ] The tests appropriately test the new code, including edge cases
- [ ] You have tried to break the code

If JIRA tests were used to supplement or replace automated tests:
- [ ] JIRA tests have been run and pass
- [ ] You agree with the justification for use of JIRA tests or have provided input on why you disagree

2017-10-04 14:42 UTC, holmesie requested changes

2017-10-04 14:42 UTC, holmesie commented on app/assets/javascripts/templates/patient_builder/edit_criteria.hbs
> +          {{!-- <p><strong>{{definition_title}}:</strong> {{description}}</p> --}}
Should this comment be removed?

2017-10-04 14:42 UTC, holmesie commented on app/assets/stylesheets/builder.less
> +
Remove this whitespace

2017-10-04 14:42 UTC, holmesie commented on app/assets/stylesheets/measures.less
> +.h2-style {
I'm not that well versed in how less works, but I'm pretty sure CSS classes are global. Wouldn't this interfere with the `h2-style` that you defined in `app/assets/stylesheets/builder.less`?

2017-10-04 15:03 UTC, losborne commented on app/assets/stylesheets/measures.less
> +.h2-style {
You are right--it is a redundant class, and the extra elements from `builder.less` were making their way through to the measures page as well. I removed it and checked that the measure page looked the same.

2017-10-04 17:40 UTC, holmesie submitted a review, later dismissed

2017-10-05 13:03 UTC, hossenlopp requested changes
I found a few visual discrepancies in the dashboard and the patient builder. Will comment with comparison screenshots.

2017-10-05 13:04 UTC, hossenlopp commented
Patient builder element headers went pretty wonky. Latest from alpha on the left, this branch on the right. 
![screen shot 2017-10-05 at 9 01 24 am](https://user-images.githubusercontent.com/11613067/31228637-2a1c69e8-a9ac-11e7-9523-685ded2001a9.png)

2017-10-05 13:05 UTC, hossenlopp commented
Column headers for the measure dashboard have something odd with their vertical alignment. Latests from alpha is on the left, this branch on the right.
![screen shot 2017-10-05 at 8 53 12 am](https://user-images.githubusercontent.com/11613067/31228687-53b27a54-a9ac-11e7-9381-399a3d0b4bab.png)

2017-10-05 13:33 UTC, losborne commented
These styles should match now.  Oddly on my chrome, I don't see the light gray box behind the column headers on either this branch or bonnie alpha.

2017-10-05 15:10 UTC, hossenlopp approved these changes

2017-10-05 18:10 UTC, holmesie approved these changes

2017-10-05 19:07 UTC, merged