Cql4bonnie remove qdm
MeasureAuthoringTool/bonnie pull request #860
Opened 2017-10-04 12:31 UTC by mayerm94

Pull requests into Bonnie require the following. Submitter and reviewer should :white_check_mark: when done. For items that are not-applicable, note it's not-applicable ("N/A") and :white_check_mark:.

**Submitter:**
- [ ] This pull request describes why these changes were made.
- [ ] JIRA ticket for this PR:
- [ ] JIRA ticket links to this PR
- [ ] Code diff has been done and been reviewed
- [ ] If UI changes have been made, google WAVE plug-in has been executed to ensure no 508 issues were introduced.
- [ ] Tests are included and test edge cases
- [ ] Tests have been run locally and pass (remember to update Gemfile when applicable)
- [ ] Automated regression test(s) pass

If JIRA tests were used to supplement or replace automated tests:
- [ ] JIRA test links:
- [ ] Justification for using JIRA tests:
- [ ] JIRA tests have been added to sprint

**Reviewer 1:**

Name:
- [ ] Code is maintainable and reusable, reuses existing code and infrastructure where appropriate, and accomplishes the task’s purpose
- [ ] The tests appropriately test the new code, including edge cases
- [ ] You have tried to break the code

If JIRA tests were used to supplement or replace automated tests:
- [ ] JIRA tests have been run and pass
- [ ] You agree with the justification for use of JIRA tests or have provided input on why you disagree

**Reviewer 2:**

Name:
- [ ] Code is maintainable and reusable, reuses existing code and infrastructure where appropriate, and accomplishes the task’s purpose
- [ ] The tests appropriately test the new code, including edge cases
- [ ] You have tried to break the code

If JIRA tests were used to supplement or replace automated tests:
- [ ] JIRA tests have been run and pass
- [ ] You agree with the justification for use of JIRA tests or have provided input on why you disagree

2017-10-04 12:36 UTC, mayerm94 commented
Changes were made in bonnie_bundler to remove QDM Loading and Bundle features. This caused errors/invalidated in certain bonnie tests. This PR addresses those errors/invalidations. Test with
https://github.com/projecttacoma/bonnie_bundler/pull/113

 https://jira.mitre.org/browse/BONNIE-1117

2017-10-05 09:48 UTC, c-monkey commented on test/functional/admin_users_controller_test.rb
> -  test "bundle download" do
If we decide to completely remove bundles code from the Bonnie project, then removing this test isn't nearly enough, but in that case let's do that removal in https://github.com/projecttacoma/bonnie/pull/857.

2017-10-05 16:28 UTC, jbradl11 requested changes
I believe all bundle code should be removed from Bonnie in this PR. If we leave it as is and accept the corresponding Bonnie_bundler PR, then we will have functions (the 'bundle' function in users_controller) that call non existing functions in Bonnie_Bundler, essentially leaving in broken code. It should be all or nothing, and if we are planning on bringing back bundle export, this code should be commented out with a detailed comment above it

2017-10-05 19:17 UTC, alexanderelliott121 submitted a review, later dismissed

2017-10-06 13:02 UTC, alexanderelliott121 requested changes
There are several rake tasks that reference things removed from bonnie bundler.

There is also export_bundle_view.coffee to consider.

2017-10-16 16:59 UTC, alexanderelliott121 approved these changes

2017-10-16 17:21 UTC, alexanderelliott121 submitted a review, later dismissed

2017-10-16 19:25 UTC, jbradl11 submitted a review, later dismissed
Looks good.

2017-10-16 19:47 UTC, edeyoung commented
tests aren't passing

2017-10-16 19:49 UTC, edeyoung submitted a review, later dismissed
address test failures

2017-10-17 16:55 UTC, edeyoung approved these changes
approving based on previous approvals

2017-10-17 18:32 UTC, merged