Display library value sets along with data criteria
MeasureAuthoringTool/bonnie pull request #865
Opened 2017-10-09 19:39 UTC by losborne

Previously, value sets from multiple libraries weren't entirely being added to the 'Data Criteria' list of value sets on the measure page.  This change adds them to the page on a new section that shows which library they are from.  This section does not appear if no library value sets are loaded.

Added a new section to the measure page to display value sets from libraries.

Added fixture with multiple value set libraries for testing.

Updated measure_view_spec to have QDM/CQL sections, added unit tests.

Pull requests into Bonnie require the following. Submitter and reviewer should :white_check_mark: when done. For items that are not-applicable, note it's not-applicable ("N/A") and :white_check_mark:.

**Submitter:**
- [X] This pull request describes why these changes were made.
- [X] JIRA ticket for this PR: https://jira.mitre.org/browse/BONNIE-1089
- [ ] JIRA ticket links to this PR
- [X] Code diff has been done and been reviewed
- [X] If UI changes have been made, google WAVE plug-in has been executed to ensure no 508 issues were introduced.
- [X] Tests are included and test edge cases
- [X] Tests have been run locally and pass (remember to update Gemfile when applicable)
- [X] Automated regression test(s) pass

If JIRA tests were used to supplement or replace automated tests:
- [X] JIRA test links: (N/A)
- [X] Justification for using JIRA tests: (N/A)
- [X] JIRA tests have been added to sprint (N/A)

**Reviewer 1:**

Name: @alexanderelliott121 
- [ ] Code is maintainable and reusable, reuses existing code and infrastructure where appropriate, and accomplishes the task’s purpose
- [ ] The tests appropriately test the new code, including edge cases
- [ ] You have tried to break the code

If JIRA tests were used to supplement or replace automated tests:
- [ ] JIRA tests have been run and pass
- [ ] You agree with the justification for use of JIRA tests or have provided input on why you disagree

**Reviewer 2:**

Name: @c-monkey 
- [ ] Code is maintainable and reusable, reuses existing code and infrastructure where appropriate, and accomplishes the task’s purpose
- [ ] The tests appropriately test the new code, including edge cases
- [ ] You have tried to break the code

If JIRA tests were used to supplement or replace automated tests:
- [ ] JIRA tests have been run and pass
- [ ] You agree with the justification for use of JIRA tests or have provided input on why you disagree

2017-10-16 20:13 UTC, c-monkey requested changes
I recognize this PR will change potentially for BONNIE-388, but the current state looks great. I have a couple minor change requests.

2017-10-16 20:13 UTC, c-monkey commented on app/assets/javascripts/views/measure_value_sets.js.coffee
>      @dataCriteria = new Thorax.Collections.ValueSetsCollection([], sorting: 'complex')  # all criteria that aren't supplemental criteria
the comment on this line has become out of date

2017-10-16 20:13 UTC, c-monkey commented on spec/javascripts/views/measure_view_spec.js.coffee
> +    it 'renders library value sets', ->
CMS107 v6 actually has overlapping value sets between data criteria in the main library and in an additional library. Therefore, I think your test should add assertions about these values being visible.

2017-10-16 20:14 UTC, c-monkey commented
As of today, this PR addresses the issue in https://oncprojectracking.healthit.gov/support/browse/BONNIE-360 and all unit tests pass.

2017-10-17 19:14 UTC, losborne commented on spec/javascripts/views/measure_view_spec.js.coffee
> +    it 'renders library value sets', ->
Adding this test directly based on the others didn't work, so I will have to investigate why.

2017-10-25 17:54 UTC, c-monkey submitted a review, later dismissed
- implemented as https://oncprojectracking.healthit.gov/support/browse/BONNIE-388?focusedCommentId=76118&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-76118
- https://oncprojectracking.healthit.gov/support/browse/BONNIE-360 resolved

2017-10-26 12:29 UTC, alexanderelliott121 requested changes
Change name of method setSummaryValueSets to better reflect its function (suggest addSummaryValueSet)

2017-10-26 12:29 UTC, alexanderelliott121 commented on app/assets/javascripts/views/measure_value_sets.js.coffee
> +  setSummaryValueSets: (valueSet, oid, cid, name, codes) ->
This name is misleading, given that the function adds a single valueset if it doesn't already exist.

Suggest:
addSummaryValueSet

2017-10-26 13:02 UTC, alexanderelliott121 approved these changes

2017-10-26 15:27 UTC, c-monkey approved these changes
all tests still pass; BONNIE-360 still resolved

2017-10-26 15:29 UTC, alexanderelliott121 approved these changes

2017-10-26 16:49 UTC, merged