Bonnie 1087 excel export details
MeasureAuthoringTool/bonnie pull request #866
Opened 2017-10-10 12:30 UTC by alexanderelliott121

Pull requests into Bonnie require the following. Submitter and reviewer should :white_check_mark: when done. For items that are not-applicable, note it's not-applicable ("N/A") and :white_check_mark:.

**Submitter:**
- [ ] This pull request describes why these changes were made.
- [ ] JIRA ticket for this PR:
- [ ] JIRA ticket links to this PR
- [ ] Code diff has been done and been reviewed
- [ ] If UI changes have been made, google WAVE plug-in has been executed to ensure no 508 issues were introduced.
- [ ] Tests are included and test edge cases
- [ ] Tests have been run locally and pass (remember to update Gemfile when applicable)
- [ ] Automated regression test(s) pass

If JIRA tests were used to supplement or replace automated tests:
- [ ] JIRA test links:
- [ ] Justification for using JIRA tests:
- [ ] JIRA tests have been added to sprint

**Reviewer 1:**

Name:
- [ ] Code is maintainable and reusable, reuses existing code and infrastructure where appropriate, and accomplishes the task’s purpose
- [ ] The tests appropriately test the new code, including edge cases
- [ ] You have tried to break the code

If JIRA tests were used to supplement or replace automated tests:
- [ ] JIRA tests have been run and pass
- [ ] You agree with the justification for use of JIRA tests or have provided input on why you disagree

**Reviewer 2:**

Name:
- [ ] Code is maintainable and reusable, reuses existing code and infrastructure where appropriate, and accomplishes the task’s purpose
- [ ] The tests appropriately test the new code, including edge cases
- [ ] You have tried to break the code

If JIRA tests were used to supplement or replace automated tests:
- [ ] JIRA tests have been run and pass
- [ ] You agree with the justification for use of JIRA tests or have provided input on why you disagree

2017-10-10 14:08 UTC, jbradl11 commented on Gemfile
> +gem 'google_drive'
Is this needed? I ran the tests without this gem and all tests pass.

2017-10-10 14:18 UTC, jbradl11 requested changes
Looks like Race and Ethnicity are not populating in the spreadsheet.

2017-10-10 14:47 UTC, lukoktonos requested changes
The unit test needs to be extended to check for death date (with a filled in value if one exists--this works when I test manually), ethnicity and race (which don't work, as JB mentioned), and to ensure that red denotes failed test cases, if that is possible with the gem.

2017-10-10 17:14 UTC, alexanderelliott121 commented on Gemfile
> +gem 'google_drive'
When I was running with the debugger, I had to include that in order to open files.

I'll try without it outside the debugger.

2017-10-17 11:20 UTC, lukoktonos approved these changes
Changes look good--race and ethnicity are populating correctly, and are tested.

2017-10-17 15:08 UTC, jbradl11 approved these changes
Code looks good. Tests pass. Notes / race / ethnicity all work now.

2017-10-17 15:41 UTC, merged