Determine the localId for library alias function references to fix coverage of them
MeasureAuthoringTool/bonnie pull request #867
Opened 2017-10-10 20:02 UTC by hossenlopp

- Adds a private helper function that looks at the annotation part of the elm to find the clause
  - The result is used to set the source result for the found localId to the clause of the function reference. This makes it match the coverage of library statement references.
- This fixes the issue of the library part not getting covered or considered for coverage.
- Adds a new helper file and test for testing this change

Pull requests into Bonnie require the following. Submitter and reviewer should :white_check_mark: when done. For items that are not-applicable, note it's not-applicable ("N/A") and :white_check_mark:.

**Submitter:**
- [x] This pull request describes why these changes were made.
- [x] JIRA ticket for this PR: https://jira.mitre.org/browse/BONNIE-984
- [ ] JIRA ticket links to this PR
- [x] Code diff has been done and been reviewed
- [x] If UI changes have been made, google WAVE plug-in has been executed to ensure no 508 issues were introduced. N/A
- [ ] Tests are included and test edge cases
- [x] Tests have been run locally and pass (remember to update Gemfile when applicable)
- [x] Automated regression test(s) pass [Tested with 2017-10-09 backup]

If JIRA tests were used to supplement or replace automated tests:
- [x] JIRA test links: N/A
- [x] Justification for using JIRA tests: N/A
- [x] JIRA tests have been added to sprint N/A

**Reviewer 1:**

Name:
- [ ] Code is maintainable and reusable, reuses existing code and infrastructure where appropriate, and accomplishes the task’s purpose
- [ ] The tests appropriately test the new code, including edge cases
- [ ] You have tried to break the code

If JIRA tests were used to supplement or replace automated tests:
- [ ] JIRA tests have been run and pass
- [ ] You agree with the justification for use of JIRA tests or have provided input on why you disagree

**Reviewer 2:**

Name:
- [ ] Code is maintainable and reusable, reuses existing code and infrastructure where appropriate, and accomplishes the task’s purpose
- [ ] The tests appropriately test the new code, including edge cases
- [ ] You have tried to break the code

If JIRA tests were used to supplement or replace automated tests:
- [ ] JIRA tests have been run and pass
- [ ] You agree with the justification for use of JIRA tests or have provided input on why you disagree

2017-10-11 13:02 UTC, mayerm94 requested changes

2017-10-11 13:02 UTC, mayerm94 commented on app/assets/javascripts/helpers/cql_measure_helpers.js.coffee
> +        if annotation.s[0].s?[0].value[0] == libraryName
This is alright if we can assume that the functionRef will always be the in the first index(s). I think the comment could be more detailed (an example of the annotation maybe?) because I could see this section being a source of contention in the future if the ELM format changes

2017-10-11 13:02 UTC, mayerm94 commented on spec/javascripts/helper_specs/cql_measure_helpers_spec.js.coffee
> +
Is there any way that we can make it more clear that 49 is the localId for the functionRef?

2017-10-11 13:09 UTC, mayerm94 commented on app/assets/javascripts/helpers/cql_measure_helpers.js.coffee
> +  @_findLocalIdForLibraryFunctionRef: (annotation, functionRefLocalId, libraryName) ->
In the spirit of writing unit tests for edge cases, we should have a test for when this function returns null

2017-10-25 19:16 UTC, holmesie submitted a review, later dismissed
Looks good, tests pass. Approving on condition of Matt's comments being addressed.

2017-10-25 19:16 UTC, holmesie commented on app/assets/javascripts/helpers/cql_measure_helpers.js.coffee
> +  # function reference. If that is not the case, it will keep recursing and may eventually return null.
+1 on the detailed commenting

2017-11-06 12:43 UTC, mayerm94 approved these changes

2017-11-06 13:00 UTC, hossenlopp commented
I approve of @mayerm94's test additions and fixes, if that means anything.

2017-11-06 15:00 UTC, holmesie approved these changes
Re-review passes.

2017-11-06 19:20 UTC, merged