Cql4bonnie 357
MeasureAuthoringTool/bonnie pull request #870
Opened 2017-10-16 16:17 UTC by mayerm94

Pull requests into Bonnie require the following. Submitter and reviewer should :white_check_mark: when done. For items that are not-applicable, note it's not-applicable ("N/A") and :white_check_mark:.

**Submitter:**
- [ ] This pull request describes why these changes were made.
- [ ] JIRA ticket for this PR:
- [ ] JIRA ticket links to this PR
- [ ] Code diff has been done and been reviewed
- [ ] If UI changes have been made, google WAVE plug-in has been executed to ensure no 508 issues were introduced.
- [ ] Tests are included and test edge cases
- [ ] Tests have been run locally and pass (remember to update Gemfile when applicable)
- [ ] Automated regression test(s) pass

If JIRA tests were used to supplement or replace automated tests:
- [ ] JIRA test links:
- [ ] Justification for using JIRA tests:
- [ ] JIRA tests have been added to sprint

**Reviewer 1:**

Name:
- [ ] Code is maintainable and reusable, reuses existing code and infrastructure where appropriate, and accomplishes the task’s purpose
- [ ] The tests appropriately test the new code, including edge cases
- [ ] You have tried to break the code

If JIRA tests were used to supplement or replace automated tests:
- [ ] JIRA tests have been run and pass
- [ ] You agree with the justification for use of JIRA tests or have provided input on why you disagree

**Reviewer 2:**

Name:
- [ ] Code is maintainable and reusable, reuses existing code and infrastructure where appropriate, and accomplishes the task’s purpose
- [ ] The tests appropriately test the new code, including edge cases
- [ ] You have tried to break the code

If JIRA tests were used to supplement or replace automated tests:
- [ ] JIRA tests have been run and pass
- [ ] You agree with the justification for use of JIRA tests or have provided input on why you disagree

2017-10-18 13:12 UTC, holmesie requested changes

2017-10-18 13:12 UTC, holmesie commented on test/functional/measures_controller_test.rb
> +    assert_equal "You have uploaded a zip file that does not appear to be a Measure Authoring Tool CQL zip file please re-export your measure from the MAT and select the 'eMeasure Package' option. Pl
The "Please use https://bonnie.healthit.gov/ for HQMF based measures." is a bit misleading, as the CQL measures still use HQMF. What about something like, "Please use https://bonnie.healthit.gov/ for QDM logic based HQMF based measures."?

2017-10-18 13:12 UTC, holmesie commented on lib/tasks/cql.rake
> +          puts errorString
Why not just `puts ex.to_s + " in measure " + measure.title + " " + measure._id.to_s`?

2017-10-18 13:12 UTC, holmesie commented on lib/tasks/cql.rake
> +      puts successString
Why not just `puts "Successfully updated " + successful.to_s + "/" + total.to_s`?

2017-10-18 13:15 UTC, mayerm94 commented on test/functional/measures_controller_test.rb
> +    assert_equal "You have uploaded a zip file that does not appear to be a Measure Authoring Tool CQL zip file please re-export your measure from the MAT and select the 'eMeasure Package' option. Pl
There is a branch out now https://github.com/projecttacoma/bonnie/commits/BONNIE-987-qdm-redirect that is redoing all of this text

2017-10-18 13:18 UTC, mayerm94 commented on lib/tasks/cql.rake
> +          puts errorString
Personal preference/style/Artifact from when I was testing the rake task.

2017-10-18 13:19 UTC, holmesie commented on test/functional/measures_controller_test.rb
> +    assert_equal "You have uploaded a zip file that does not appear to be a Measure Authoring Tool CQL zip file please re-export your measure from the MAT and select the 'eMeasure Package' option. Pl
Good to know, I'll make this comment there instead.

2017-10-18 15:27 UTC, holmesie approved these changes

2017-10-18 15:37 UTC, holmesie requested changes
Reverting approval for the time being

2017-10-19 12:25 UTC, alexanderelliott121 commented
Quick note: pull request does not actually have description of why the changes were made.

2017-10-25 14:59 UTC, holmesie commented
Looks like some issues with the tests failing, is that expected? Also has some conflicts that need to be addressed.

2017-10-25 15:18 UTC, alexanderelliott121 requested changes
The check to determine if a version is draft or not still needs to be addressed.

Was the draft check removed for a reason?

2017-10-25 15:18 UTC, alexanderelliott121 commented on app/assets/javascripts/views/measure_value_sets.js.coffee
> +        valueSet = { name: name, oid: oid, version: version, codes: codes, cid: cid, direct_reference: direct_reference }
Is there a reason you're nixing the check to see if the version is a draft?

2017-10-25 17:02 UTC, mayerm94 commented on app/assets/javascripts/views/measure_value_sets.js.coffee
> +        valueSet = { name: name, oid: oid, version: version, codes: codes, cid: cid, direct_reference: direct_reference }
Accidental deletion, good catch

2017-10-25 18:24 UTC, edeyoung commented on lib/tasks/cql.rake
> +          value_sets.each do |vs|
suggest printing out all modified value sets so we can visually confirm that they are all direct reference codes

2017-10-25 18:25 UTC, edeyoung commented on lib/tasks/cql.rake
> +      Example test@test.com
several white space related changes. please revert

2017-10-25 18:25 UTC, edeyoung commented on app/assets/javascripts/templates/measure/value_sets/value_sets.hbs
> +          {{#ifCond direct_reference "==" false}}
can this just be `{{#if direct_reference}}` because direct_reference is a boolean?

2017-10-25 18:27 UTC, edeyoung commented
I would like to see some sort of test of the script itself (JIRA?) to help confirm that we are not doing anything we don't want to do. @holmesie @alexanderelliott121 did you both test the script and confirm it works as expected?

2017-10-25 18:34 UTC, holmesie commented on lib/tasks/cql.rake
> +    task :update_value_set_direct_reference_field => :environment do
I've just had a thought about this task being in this file. We have a `bonnie_run_once.rake`, which is, in it's own words, "This rakefile is for tasks that are designed to be run once to address a specific problem". Perhaps we should start that tradition for CQL for now on, perhaps putting them in a `cql_run_once.rake`? I kind of like the sound of that seperation... Thoughts?

2017-10-25 18:53 UTC, mayerm94 commented on lib/tasks/cql.rake
> +      Example test@test.com
These whitespace changes were made before I enabled the feature in atom to not automatically fix trailing whitespace. I agree that the white space changes make the PR a little gross but I don't feel right deliberately making the codebase worse by going back and re-inserting meaningless whitespace (I can't just revert the commit because the commit includes actual non-whitespace changes)

2017-10-25 19:01 UTC, okeefm commented on lib/tasks/cql.rake
> +      Example test@test.com
You can amend the commit if need be (though it would get tricky if this isn't the last commit on this PR).

2017-10-25 19:24 UTC, mayerm94 commented on lib/tasks/cql.rake
> +    task :update_value_set_direct_reference_field => :environment do
Perhaps.....

2017-10-25 19:25 UTC, mayerm94 commented on lib/tasks/cql.rake
> +    task :update_value_set_direct_reference_field => :environment do
I like this idea, or we should start considering what belongs in bonnie vs what belongs in the server_scripts repo

2017-10-26 12:33 UTC, alexanderelliott121 submitted a review, later dismissed

2017-10-26 14:48 UTC, lukoktonos requested changes
The fixtures in `/spec/javascripts/fixtures/json/measure_data/CQL/*` also need to be updated.

2017-10-26 14:48 UTC, losborne commented on lib/tasks/cql.rake
> +          measure.save
Either `measure.save!` or 
```
if measure.save
  successful += 1
end
```
would be better here, in case it fails on saving the measure.

2017-10-26 14:48 UTC, losborne commented on lib/tasks/cql.rake
> +          value_sets.each do |vs|
I agree that this printout would be helpful.

2017-10-26 16:56 UTC, mayerm94 commented
JIRA Test for the rake task https://jira.mitre.org/browse/BONNIE-1158

2017-10-26 17:02 UTC, mayerm94 commented on app/assets/javascripts/templates/measure/value_sets/value_sets.hbs
> +          {{#ifCond direct_reference "==" false}}
Handlebars doesn't seem to support writing this like that

2017-10-30 12:23 UTC, alexanderelliott121 commented
I'm trying to run through the test for the rake task.
Unfortunately, the screenshots for expected results are too small for me to actually be able to compare them against my results.

2017-10-30 12:57 UTC, alexanderelliott121 commented
I've run the JIRA test, result appears mixed.

Upside, the db fields have 3 values (oid, version, direct_reference).

On the downside, steps 6 and 8 failed.
Step 6: Pre-script, the oid and version fields were populated, which the test indicates should not be the case.
Step 8: After the script, the direct reference codes were not visible.

I thought the issue might have been a result of the pre-existing state of my db, but they persisted after I cleared my db and re-ran the tests.

2017-10-30 13:27 UTC, losborne commented on app/assets/javascripts/templates/measure/value_sets/value_sets.hbs
> +          {{#ifCond direct_reference "==" false}}
I remember struggling with this for the special Components view.  It will work if (and probably only if) you flip the logic like this:

```
            {{#if direct_reference}}
              <div class="col-sm-5">Direct Reference Code</div>
              <div class="col-sm-2">N/A</div>
            {{else}}
              <div class="col-sm-5">{{oid}}</div>
              <div class="col-sm-2">{{version}}</div>
            {{/if}}
```

You can't do something like `{{#if !direct_reference}}` though, annoyingly.

2017-10-30 13:30 UTC, hossenlopp commented on app/assets/javascripts/templates/measure/value_sets/value_sets.hbs
> +          {{#ifCond direct_reference "==" false}}
Handlebars has an `{{#unless}}` block.

2017-10-31 18:06 UTC, closed without merging