Bonnie 987 qdm redirect
MeasureAuthoringTool/bonnie pull request #875
Opened 2017-10-19 00:26 UTC by losborne

This PR is to add a few redirect messages prompting users to go to the Bonnie-Prior website if they need support for HQMF-QDM based measures instead of CQL measures.  There is a banner that is displayed on the home/landing page and login page, as well as a link in the error message if an upload fails.

The JIRA ticket also suggests banners if a login fails, but that would be redundant as the login page where that error would pop up already has a banner.

Pull requests into Bonnie require the following. Submitter and reviewer should :white_check_mark: when done. For items that are not-applicable, note it's not-applicable ("N/A") and :white_check_mark:.

**Submitter:**
- [X] This pull request describes why these changes were made.
- [x] JIRA ticket for this PR: https://jira.mitre.org/browse/BONNIE-987
- [ ] JIRA ticket links to this PR
- [X] Code diff has been done and been reviewed
- [X] If UI changes have been made, google WAVE plug-in has been executed to ensure no 508 issues were introduced.
- [X] Tests are included and test edge cases
- [X] Tests have been run locally and pass (remember to update Gemfile when applicable)
- [X] Automated regression test(s) pass

If JIRA tests were used to supplement or replace automated tests:
- [x] JIRA test links: (N/A)
- [x] Justification for using JIRA tests: (N/A)
- [x] JIRA tests have been added to sprint (N/A)

**Reviewer 1:**

Name:
- [ ] Code is maintainable and reusable, reuses existing code and infrastructure where appropriate, and accomplishes the task’s purpose
- [ ] The tests appropriately test the new code, including edge cases
- [ ] You have tried to break the code

If JIRA tests were used to supplement or replace automated tests:
- [ ] JIRA tests have been run and pass
- [ ] You agree with the justification for use of JIRA tests or have provided input on why you disagree

**Reviewer 2:**

Name:
- [ ] Code is maintainable and reusable, reuses existing code and infrastructure where appropriate, and accomplishes the task’s purpose
- [ ] The tests appropriately test the new code, including edge cases
- [ ] You have tried to break the code

If JIRA tests were used to supplement or replace automated tests:
- [ ] JIRA tests have been run and pass
- [ ] You agree with the justification for use of JIRA tests or have provided input on why you disagree

2017-10-20 21:11 UTC, c-monkey commented on app/controllers/measures_controller.rb
> +      flash[:error] = {title: "Error Uploading Measure", summary: "The uploaded zip file is not a valid Measure Authoring Tool export of a CQL Measure.", body: 'Please use <a href=\"https://bonnie.he
This redirects me to an incorrect URL:
http://localhost:3000/%22https://bonnie.healthit.gov//%22

2017-10-20 21:17 UTC, c-monkey requested changes
tests pass and the code looks good except the garbled URL

2017-10-23 13:00 UTC, c-monkey commented
Merged in BONNIE-987-qdm-redirect_LDY, it looks good to me

2017-10-23 13:09 UTC, edeyoung commented on app/controllers/measures_controller.rb
> +        body: 'The file you have uploaded does not appear to be a Measure Authoring Tool (MAT) zip export of a measure. Please re-package and re-export your measure from the MAT.<br/>If this is an HQ
just realized a bunch of these are "bonnie.healthit.gov" instead of "bonnie-prior.healthit.gov". These all need to be modified.

2017-10-23 13:14 UTC, c-monkey commented on app/controllers/measures_controller.rb
> +        body: 'The file you have uploaded does not appear to be a Measure Authoring Tool (MAT) zip export of a measure. Please re-package and re-export your measure from the MAT.<br/>If this is an HQ
okay, I'll do this

2017-10-23 13:24 UTC, edeyoung commented
looks like the recent updates require changes to the jasmine tests

2017-10-24 11:36 UTC, alexanderelliott121 submitted a review, later dismissed

2017-10-25 14:06 UTC, alexanderelliott121 approved these changes

2017-10-25 14:43 UTC, c-monkey approved these changes

2017-10-25 14:46 UTC, edeyoung commented
Incorporation on hold until production deployment

It's ready to incorporate for production deployment

2017-11-09 21:04 UTC, merged