BONNIE-1087 Add support for continuous variable measures.
MeasureAuthoringTool/bonnie pull request #881
Opened 2017-10-26 14:40 UTC by alexanderelliott121

Pull request is intended to add support for excel export of CV measures.
Tested with CMS720 (found in cql_55 export).
Observe follows a different pattern in the results than other criteria.

Pull requests into Bonnie require the following. Submitter and reviewer should :white_check_mark: when done. For items that are not-applicable, note it's not-applicable ("N/A") and :white_check_mark:.

**Submitter:**
- [ ] This pull request describes why these changes were made.
- [ ] JIRA ticket for this PR:
- [ ] JIRA ticket links to this PR
- [ ] Code diff has been done and been reviewed (it **does not** contain: additional white space, not applicable code changes, debug statements, etc.)
- [ ] If UI changes have been made, google WAVE plug-in has been executed to ensure no 508 issues were introduced.
- [ ] Tests are included and test edge cases
- [ ] Tests have been run locally and pass (remember to update Gemfile when applicable)
- [ ] Code coverage has not gone down and all code touched or added is covered. 
     * See [front-end testing instructions](https://github.com/projecttacoma/bonnie/wiki/Testing#frontend-testing) for getting coverage for front-end tests
     * In rare situations, this may not be possible or applicable to a PR. In those situations:
         1. Note why this could not be done or is not applicable here: 
         2. Add TODOs in the code noting that it requires a test
         3. Add a JIRA task to add the test and link it here: 
- [ ] Automated regression test(s) pass

If JIRA tests were used to supplement or replace automated tests:
- [ ] JIRA test links:
- [ ] Justification for using JIRA tests:
- [ ] JIRA tests have been added to sprint

**Reviewer 1:**

Name:
- [ ] Code is maintainable and reusable, reuses existing code and infrastructure where appropriate, and accomplishes the task’s purpose
- [ ] The tests appropriately test the new code, including edge cases
- [ ] You have tried to break the code

If JIRA tests were used to supplement or replace automated tests:
- [ ] JIRA tests have been run and pass
- [ ] You agree with the justification for use of JIRA tests or have provided input on why you disagree

**Reviewer 2:**

Name:
- [ ] Code is maintainable and reusable, reuses existing code and infrastructure where appropriate, and accomplishes the task’s purpose
- [ ] The tests appropriately test the new code, including edge cases
- [ ] You have tried to break the code

If JIRA tests were used to supplement or replace automated tests:
- [ ] JIRA tests have been run and pass
- [ ] You agree with the justification for use of JIRA tests or have provided input on why you disagree

2017-10-26 16:10 UTC, lukoktonos requested changes

2017-10-26 16:10 UTC, losborne commented on lib/patient_export.rb
> +                  actual.push(calc_results[pop_key][patient_key]['criteria']['values'])
It appears this can be `[nil]` and `[]`.  Is this the expected behavior?
![image](https://user-images.githubusercontent.com/14879344/32063774-0fc66fd0-ba46-11e7-842c-64cf7fae785a.png)

Using the measure ED1_v5_3_Export.zip uploaded at https://oncprojectracking.healthit.gov/support/browse/BONNIE-357

2017-10-26 16:13 UTC, losborne commented on lib/patient_export.rb
> +                  actual.push(calc_results[pop_key][patient_key]['criteria']['values'])
Actually, after doing a hard refresh, only the `[nil]`s appear, but they are left justified instead of right justified:
![image](https://user-images.githubusercontent.com/14879344/32064130-0a3d0e4c-ba47-11e7-8f85-93a7eefe351f.png)

2017-10-26 16:53 UTC, c-monkey commented on lib/patient_export.rb
> +                if (criteria == "OBSERV")
ruby style guide suggests there should not be parenthesis around conditionals
also on lines 87/142/143 you made changes to in August

2017-10-26 17:03 UTC, losborne commented on lib/patient_export.rb
> +                  actual.push(calc_results[pop_key][patient_key]['criteria']['values'])
After discussing this with @alexanderelliott121 , we determined that `[]` and `[nil]` are OK and that the difference between screenshots was not caused by this code, but rather needing to clear the browser cache after switching branches. 

I do think that there should be unit tests where `[]` and `[nil]` appear, however.  

If it's possible to right-justify them in the excel, that would be best as well.

2017-10-26 17:24 UTC, c-monkey submitted a review, later dismissed
tests work, BONNIE-377 fixed, code is good except for a suggested style fix

2017-10-27 16:18 UTC, lukoktonos submitted a review, later dismissed
Changes and new tests look good.  Approved.

2017-10-27 16:48 UTC, c-monkey commented on lib/patient_export.rb
> +                if (criteria == "OBSERV")
why not make these suggested changes? you didn't even acknowledge them.

2017-10-27 16:49 UTC, c-monkey commented on lib/patient_export.rb
> +                  if (observ_expected.nil? && observ_actual == [])
parenthesis violates ruby style guide

2017-10-27 16:50 UTC, c-monkey commented on lib/patient_export.rb
> +                if (criteria == "OBSERV")
with your changes, now lines are: 87, 132, 135, 148, 149

2017-10-27 16:54 UTC, c-monkey commented on test/functional/patients_controller_test.rb
> +    #Ensure that observe does not equal itself as it should
missing test

2017-10-27 17:06 UTC, lukoktonos approved these changes
Newest changes look good.

2017-10-27 18:07 UTC, c-monkey approved these changes

2017-10-30 14:58 UTC, merged