Cql4bonnie use mat artifacts
MeasureAuthoringTool/bonnie pull request #883
Opened 2017-10-26 18:14 UTC by jbradl11

Pull requests into Bonnie require the following. Submitter and reviewer should :white_check_mark: when done. For items that are not-applicable, note it's not-applicable ("N/A") and :white_check_mark:.

Purpose: Is to support the new MAT packages that contain the JSON artifacts. In this PR rebuild_elm has been updated to support regenerating the elm using the new stored MAT packages if there is one, otherwise it will call the translation service for older measures.

JIRA TICKET: https://jira.mitre.org/browse/BONNIE-1153

**Submitter:**
- [ ] This pull request describes why these changes were made.
- [ ] JIRA ticket for this PR:
- [ ] JIRA ticket links to this PR
- [ ] Code diff has been done and been reviewed (it **does not** contain: additional white space, not applicable code changes, debug statements, etc.)
- [ ] If UI changes have been made, google WAVE plug-in has been executed to ensure no 508 issues were introduced.
- [ ] Tests are included and test edge cases
- [ ] Tests have been run locally and pass (remember to update Gemfile when applicable)
- [ ] Code coverage has not gone down and all code touched or added is covered. 
     * See [front-end testing instructions](https://github.com/projecttacoma/bonnie/wiki/Testing#frontend-testing) for getting coverage for front-end tests
     * In rare situations, this may not be possible or applicable to a PR. In those situations:
         1. Note why this could not be done or is not applicable here: 
         2. Add TODOs in the code noting that it requires a test
         3. Add a JIRA task to add the test and link it here: 
- [ ] Automated regression test(s) pass

If JIRA tests were used to supplement or replace automated tests:
- [ ] JIRA test links:
- [ ] Justification for using JIRA tests:
- [ ] JIRA tests have been added to sprint

**Reviewer 1:**

Name:
- [ ] Code is maintainable and reusable, reuses existing code and infrastructure where appropriate, and accomplishes the task’s purpose
- [ ] The tests appropriately test the new code, including edge cases
- [ ] You have tried to break the code

If JIRA tests were used to supplement or replace automated tests:
- [ ] JIRA tests have been run and pass
- [ ] You agree with the justification for use of JIRA tests or have provided input on why you disagree

**Reviewer 2:**

Name:
- [ ] Code is maintainable and reusable, reuses existing code and infrastructure where appropriate, and accomplishes the task’s purpose
- [ ] The tests appropriately test the new code, including edge cases
- [ ] You have tried to break the code

If JIRA tests were used to supplement or replace automated tests:
- [ ] JIRA tests have been run and pass
- [ ] You agree with the justification for use of JIRA tests or have provided input on why you disagree

2017-10-26 19:05 UTC, okeefm commented
Are there JIRA tests on this PR? I'm not sure how to find them if there are.

2017-10-26 19:11 UTC, lukoktonos requested changes

2017-10-26 19:11 UTC, losborne commented on test/unit/rebuild_elm_test.rb
> +    # Confirm measure model saved corectly.
Trailing whitespace

2017-10-26 19:11 UTC, losborne commented on test/unit/rebuild_elm_test.rb
> +    # Confirm there is still now associated MAT package.
"now associated" -> "no associated"

2017-10-26 19:11 UTC, losborne commented on lib/tasks/cql.rake
>            else
This else statement isn't covered by tests according to the coverage tool:
![image](https://user-images.githubusercontent.com/14879344/32072212-dca50dea-ba5f-11e7-8e2b-b3a606159240.png)

2017-10-26 19:11 UTC, losborne commented on test/unit/rebuild_elm_test.rb
> +      assert_not_equal nil, measure.elm_annotations
Should there be an assert here related to `measure.package`?

2017-10-26 19:18 UTC, jbradl11 commented on test/unit/rebuild_elm_test.rb
> +      assert_not_equal nil, measure.elm_annotations
We have a unit test to check this in Bonnie_bundler. I don't see a need to re-test, but I can if you think its worth it.

2017-10-26 19:51 UTC, lukoktonos submitted a review, later dismissed
Regression test passes with a rebuild_elm in-between.  

Confirmed file stored in db matches original zip package.

Everything looks good--approved.

2017-10-27 15:25 UTC, okeefm submitted a review, later dismissed
Looks good to me. rake task runs successfully, Bonnie seems to work afterwards, automated tests pass.

2017-10-27 15:53 UTC, lukoktonos approved these changes
Still looks good with updated hash.

2017-10-30 14:53 UTC, edeyoung commented on lib/tasks/cql.rake
> -          if measure[:main_cql_library].present?
should we be making the assumption that this is present? are we not worried about older measures? should we delete all old measures? (i assume they're on mitre accounts, but we should confirm of course).

2017-10-30 14:53 UTC, edeyoung commented on lib/tasks/cql.rake
> +            elm_json, elm_xml = CqlElm::CqlToElmHelper.translate_cql_to_elm(cql)
just want to confirm: if we have no packages using the CQL-to-ELM translator, and we don't have it running, this *will not* break, right? It would only break if a package needed the CQL-to-ELM translator?

2017-10-30 15:12 UTC, jbradl11 commented on lib/tasks/cql.rake
> -          if measure[:main_cql_library].present?
Yes I believe we can make this assumption, because if you look in the 'else' clause of this, there is a variable that is never set ("elms"). So I am pretty confident that this task would have crashed previously if measure[:main_cql_library] was not present.

2017-10-30 15:14 UTC, jbradl11 commented on lib/tasks/cql.rake
> +            elm_json, elm_xml = CqlElm::CqlToElmHelper.translate_cql_to_elm(cql)
Correct, this will task will work properly with the translator off if all measures being updated do not require it. I just ran my unit test without the service running, and it worked properly.

2017-10-30 15:15 UTC, okeefm approved these changes
Still looks good; rake task still works

2017-10-30 16:01 UTC, merged