Bonnie 1090
MeasureAuthoringTool/bonnie pull request #885
Opened 2017-10-31 17:58 UTC by losborne

Originally, only direct reference codes from the main library were added to the data criteria section.

With the most recent change, no direct reference codes were added to the "terminology section", which replaced the "data criteria" section.

With this change, all direct reference codes will be added to the "terminology" section.
Pull requests into Bonnie require the following. Submitter and reviewer should :white_check_mark: when done. For items that are not-applicable, note it's not-applicable ("N/A") and :white_check_mark:.

**Submitter:**
- [X] This pull request describes why these changes were made.
- [X] JIRA ticket for this PR: https://jira.mitre.org/browse/BONNIE-1090
- [ ] JIRA ticket links to this PR 
- [X] Code diff has been done and been reviewed (it **does not** contain: additional white space, not applicable code changes, debug statements, etc.)
- [X] If UI changes have been made, google WAVE plug-in has been executed to ensure no 508 issues were introduced.
- [X] Tests are included and test edge cases
- [X] Tests have been run locally and pass (remember to update Gemfile when applicable)
- [X] Code coverage has not gone down and all code touched or added is covered. 
     * See [front-end testing instructions](https://github.com/projecttacoma/bonnie/wiki/Testing#frontend-testing) for getting coverage for front-end tests
     * In rare situations, this may not be possible or applicable to a PR. In those situations:
         1. Note why this could not be done or is not applicable here: 
         2. Add TODOs in the code noting that it requires a test
         3. Add a JIRA task to add the test and link it here: 
- [ ] Automated regression test(s) pass

If JIRA tests were used to supplement or replace automated tests:
- [X] JIRA test links: NA
- [X] Justification for using JIRA tests: NA
- [X] JIRA tests have been added to sprint NA

**Reviewer 1:**

Name: @c-monkey 
- [ ] Code is maintainable and reusable, reuses existing code and infrastructure where appropriate, and accomplishes the task’s purpose
- [ ] The tests appropriately test the new code, including edge cases
- [ ] You have tried to break the code

If JIRA tests were used to supplement or replace automated tests:
- [ ] JIRA tests have been run and pass
- [ ] You agree with the justification for use of JIRA tests or have provided input on why you disagree

**Reviewer 2:**

Name: @jbradl11 
- [ ] Code is maintainable and reusable, reuses existing code and infrastructure where appropriate, and accomplishes the task’s purpose
- [ ] The tests appropriately test the new code, including edge cases
- [ ] You have tried to break the code

If JIRA tests were used to supplement or replace automated tests:
- [ ] JIRA tests have been run and pass
- [ ] You agree with the justification for use of JIRA tests or have provided input on why you disagree

2017-11-02 19:38 UTC, alexanderelliott121 requested changes
I think there are a few code improvements that I think would be worthwhile to look into.

2017-11-02 19:38 UTC, alexanderelliott121 commented on app/assets/javascripts/views/measure_value_sets.js.coffee
> +        version = oid_version.version
Is there a reason that this has to be done here, and not in the first isDirectReference else block?

2017-11-02 19:38 UTC, alexanderelliott121 commented on app/assets/javascripts/views/measure_value_sets.js.coffee
> +              if /-/.test(oid)
If I'm reading this right, for each code in each library it iterates over every entry of bonnie.valueSetsByOid, but in each iteration it only cares about the entries that are direct reference codes (DRCs).

You could do a first pass over bonnie.valueSetsByOid, pushing DRCs to an array then iterate over that in the inner loop.

It might be possible to do better than that, given than terminology will eventually be filtered for duplicates.

2017-11-06 11:41 UTC, alexanderelliott121 approved these changes

2017-11-06 18:12 UTC, holmesie approved these changes

2017-11-06 18:30 UTC, merged