Cql4bonnie test updates
MeasureAuthoringTool/bonnie pull request #910
Opened 2017-12-06 14:28 UTC by mayerm94

Pull requests into Bonnie require the following. Submitter and reviewer should :white_check_mark: when done. For items that are not-applicable, note it's not-applicable ("N/A") and :white_check_mark:.

**Submitter:**
- [ ] This pull request describes why these changes were made.
- [ ] JIRA ticket for this PR:
- [ ] JIRA ticket links to this PR
- [ ] Code diff has been done and been reviewed (it **does not** contain: additional white space, not applicable code changes, debug statements, etc.)
- [ ] If UI changes have been made, google WAVE plug-in has been executed to ensure no 508 issues were introduced.
- [ ] Tests are included and test edge cases
- [ ] Tests have been run locally and pass (remember to update Gemfile when applicable)
- [ ] Code coverage has not gone down and all code touched or added is covered. 
     * See [front-end testing instructions](https://github.com/projecttacoma/bonnie/wiki/Testing#frontend-testing) for getting coverage for front-end tests
     * In rare situations, this may not be possible or applicable to a PR. In those situations:
         1. Note why this could not be done or is not applicable here: 
         2. Add TODOs in the code noting that it requires a test
         3. Add a JIRA task to add the test and link it here: 
- [ ] Automated regression test(s) pass

If JIRA tests were used to supplement or replace automated tests:
- [ ] JIRA test links:
- [ ] Justification for using JIRA tests:
- [ ] JIRA tests have been added to sprint

**Reviewer 1:**

Name:
- [ ] Code is maintainable and reusable, reuses existing code and infrastructure where appropriate, and accomplishes the task’s purpose
- [ ] The tests appropriately test the new code, including edge cases
- [ ] You have tried to break the code

If JIRA tests were used to supplement or replace automated tests:
- [ ] JIRA tests have been run and pass
- [ ] You agree with the justification for use of JIRA tests or have provided input on why you disagree

**Reviewer 2:**

Name:
- [ ] Code is maintainable and reusable, reuses existing code and infrastructure where appropriate, and accomplishes the task’s purpose
- [ ] The tests appropriately test the new code, including edge cases
- [ ] You have tried to break the code

If JIRA tests were used to supplement or replace automated tests:
- [ ] JIRA tests have been run and pass
- [ ] You agree with the justification for use of JIRA tests or have provided input on why you disagree

2017-12-07 14:02 UTC, mayerm94 commented
This PR brings in changes that were made to the testing infrastructure in the master branch. The changes introduce the bonnieRouterCache, which are caches of the bonnie router that have sets of measures and patients loaded for use in specific sets of tests. The fixtures are organized by the sets to be loaded into the router in measures.js.erb.

2017-12-07 15:30 UTC, lukoktonos requested changes

2017-12-07 15:30 UTC, lukoktonos commented on spec/javascripts/router/router_cache.js.coffee
> +    @state[key] = window.bonnie
Newline at end of file requested here

2017-12-07 15:30 UTC, losborne commented on spec/javascripts/setup/measures.js.erb
> +<%# TODO: this value_sets_json is duplicated per state into bonnie.valueSetsByOid, but should be loaded separately?  %>
This looks like it loads the base set `value_sets.json` for all measures, rather than the `value_sets.json` that is in the fixture directory along with the measure json.  Should this load the latter instead down below in the glob starting on line 17?

2017-12-07 15:30 UTC, losborne commented on spec/javascripts/setup/measures.js.erb
> +<% Dir.glob (File.join(File.dirname(__FILE__), '../fixtures/json/measure_data/QDM/**/measures.json')) do |measure_file| %>
Should this also look at all measures in `/../fixtures/json/measure_data/CQL/**`?  Right now the tests that use CQL measures don't use this router and instead do the manual caching that this could get rid of, as in `cql_measure_helpers_spec.js.coffee`:

```
  beforeEach ->
    jasmine.getJSONFixtures().clearCache()
    #Failing to store and reset the global valueSetsByOid breaks the tests.
    #When integrated with the master branch context switching, this will need to be changed out.
    @universalValueSetsByOid = bonnie.valueSetsByOid

  afterEach ->
    bonnie.valueSetsByOid = @universalValueSetsByOid
```

2017-12-07 15:30 UTC, losborne commented on spec/javascripts/views/measure_view_spec.js.coffee
> +      # this is currently failing because several patients were added to the base_set
This fails when running in the browser or focusing the teaspoon test to this file with:
```
rake teaspoon files=/Users/lwosborne/git/bonnie/spec/javascripts/views/measure_view_spec.js.coffee
```
But it doesn't show any failures with `bundle exec rake teaspoon`.  Do we know why there is this difference in behavior?

2017-12-08 16:09 UTC, mayerm94 commented on spec/javascripts/setup/measures.js.erb
> +<% Dir.glob (File.join(File.dirname(__FILE__), '../fixtures/json/measure_data/QDM/**/measures.json')) do |measure_file| %>
The router cache is only necessary for QDM measures

2017-12-08 16:16 UTC, mayerm94 commented on spec/javascripts/views/measure_view_spec.js.coffee
> +      # this is currently failing because several patients were added to the base_set
We are not sure why this happens with this test, this has been a known problem unfortunately

2017-12-08 20:07 UTC, lukoktonos submitted a review, later dismissed

2017-12-11 15:40 UTC, mayerm94 commented on spec/javascripts/views/measure_view_spec.js.coffee
> +      # this is currently failing because several patients were added to the base_set
This has been fixed in the last commit

2017-12-11 15:50 UTC, lukoktonos submitted a review, later dismissed
Dial test now passes locally and in browser.

2017-12-12 21:11 UTC, lukoktonos approved these changes
Recent changes look good.

2017-12-12 21:37 UTC, jbradl11 approved these changes
Code looks good. All test pass.

2017-12-13 14:33 UTC, merged