Cql4bonnie multiple episode denex fixes
MeasureAuthoringTool/bonnie pull request #912
Opened 2017-12-12 21:12 UTC by hossenlopp

Fixes DENEX for multiple episode of care proportion measures to make it so any count in DENEX doesn't wipe out NUMER unless it is same or more than the count in DENOM.

Pull requests into Bonnie require the following. Submitter and reviewer should :white_check_mark: when done. For items that are not-applicable, note it's not-applicable ("N/A") and :white_check_mark:.

**Submitter:**
- [x] This pull request describes why these changes were made.
- [x] This PR is into the correct branch.
- [x] JIRA ticket for this PR: https://jira.mitre.org/browse/BONNIE-1229
- [ ] JIRA ticket links to this PR
- [x] Code diff has been done and been reviewed (it **does not** contain: additional white space, not applicable code changes, debug statements, etc.)
- [x] If UI changes have been made, google WAVE plug-in has been executed to ensure no 508 issues were introduced.
- [x] Tests are included and test edge cases
- [x] Tests have been run locally and pass (remember to update Gemfile when applicable)
- [x] Code coverage has not gone down and all code touched or added is covered. 
     * See [front-end testing instructions](https://github.com/projecttacoma/bonnie/wiki/Testing#frontend-testing) for getting coverage for front-end tests
     * In rare situations, this may not be possible or applicable to a PR. In those situations:
         1. Note why this could not be done or is not applicable here: 
         2. Add TODOs in the code noting that it requires a test
         3. Add a JIRA task to add the test and link it here: 
- [ ] Automated regression test(s) pass

If JIRA tests were used to supplement or replace automated tests:
- [ ] JIRA test links:
- [ ] Justification for using JIRA tests:
- [ ] JIRA tests have been added to sprint

**Reviewer 1:**

Name:
- [ ] Code is maintainable and reusable, reuses existing code and infrastructure where appropriate, and accomplishes the task’s purpose
- [ ] The tests appropriately test the new code, including edge cases
- [ ] You have tried to break the code

If JIRA tests were used to supplement or replace automated tests:
- [ ] JIRA tests have been run and pass
- [ ] You agree with the justification for use of JIRA tests or have provided input on why you disagree

**Reviewer 2:**

Name:
- [ ] Code is maintainable and reusable, reuses existing code and infrastructure where appropriate, and accomplishes the task’s purpose
- [ ] The tests appropriately test the new code, including edge cases
- [ ] You have tried to break the code

If JIRA tests were used to supplement or replace automated tests:
- [ ] JIRA tests have been run and pass
- [ ] You agree with the justification for use of JIRA tests or have provided input on why you disagree

2017-12-12 21:14 UTC, hossenlopp commented
Before:
----
Statements   : 56.92% ( 6736/11835 )
Branches     : 39.59% ( 1738/4390 )
Functions    : 47.46% ( 1122/2364 )
Lines        : 54.62% ( 6019/11019 )

After:
----
Statements   : 57% ( 6746/11835 )
Branches     : 39.81% ( 1748/4391 )
Functions    : 47.46% ( 1122/2364 )
Lines        : 54.71% ( 6029/11019 )

2017-12-13 15:32 UTC, lukoktonos requested changes

2017-12-13 15:32 UTC, losborne commented on app/assets/javascripts/cql_calculator.js.coffee
>      # If MSRPOPLEX is equal to MSRPOPL then OBSERVs are not calculated
Comment should be updated to say:
```
# If MSRPOPLEX is greater than or equal to MSRPOPL then OBSERVs are not calculated
```

2017-12-13 15:32 UTC, losborne commented on app/assets/javascripts/cql_calculator.js.coffee
> +    else if (population_results["DENEX"]? && !@isValueZero('DENEX', population_results) && (population_results["DENEX"] >= population_results["DENOM"]))
If `population_results["DENOM"] == 0` and `population_results["DENEX"] = 1`, then the else if statement on line 190 will get hit, which does not alter `'NUMEX'`.  Is that OK, or should `NUMEX` get 0ed out in that case?

2017-12-14 14:59 UTC, lukoktonos approved these changes

2017-12-14 16:00 UTC, jbradl11 approved these changes
Logic looks code. All tests pass.

2017-12-14 20:21 UTC, merged