added comments and wrapped dots in user-defined code set names
MeasureAuthoringTool/bonnie pull request #913
Opened 2017-12-13 18:32 UTC by c-monkey

Fix for issue https://jira.mitre.org/browse/BONNIE-1216. Wrapped dots in user-defined code set names so can be saved as json key in mongo document.

See also https://github.com/projecttacoma/bonnie_bundler/pull/128 which updates the comment to add the matching "<<WRAP 1>>" text. This is because I find this actual change likely to be difficult to maintain over time and want to make it as easy as possible to find matching calls which wrap/unwrap the json.

Pull requests into Bonnie require the following. Submitter and reviewer should :white_check_mark: when done. For items that are not-applicable, note it's not-applicable ("N/A") and :white_check_mark:.

**Submitter:**
- [ ] This pull request describes why these changes were made.
- [X] This PR is into the correct branch.
- [ ] JIRA ticket for this PR:
- [ ] JIRA ticket links to this PR
- [ ] Code diff has been done and been reviewed (it **does not** contain: additional white space, not applicable code changes, debug statements, etc.)
- [ ] If UI changes have been made, google WAVE plug-in has been executed to ensure no 508 issues were introduced.
- [X] Tests are included and test edge cases
- [X] Tests have been run locally and pass (remember to update Gemfile when applicable)
- [ ] Code coverage has not gone down and all code touched or added is covered. 
     * See [front-end testing instructions](https://github.com/projecttacoma/bonnie/wiki/Testing#frontend-testing) for getting coverage for front-end tests
     * In rare situations, this may not be possible or applicable to a PR. In those situations:
         1. Note why this could not be done or is not applicable here: 
         2. Add TODOs in the code noting that it requires a test
         3. Add a JIRA task to add the test and link it here: 
- [ ] Automated regression test(s) pass

If JIRA tests were used to supplement or replace automated tests:
- [X] JIRA test links: https://jira.mitre.org/browse/BONNIE-1232
- [X] Justification for using JIRA tests: Integration tests between ruby/backbone difficult as this is code in the main view.
- [X] JIRA tests have been added to sprint

**Reviewer 1:**

Name:
- [ ] Code is maintainable and reusable, reuses existing code and infrastructure where appropriate, and accomplishes the task’s purpose
- [ ] The tests appropriately test the new code, including edge cases
- [ ] You have tried to break the code

If JIRA tests were used to supplement or replace automated tests:
- [ ] JIRA tests have been run and pass
- [ ] You agree with the justification for use of JIRA tests or have provided input on why you disagree

**Reviewer 2:**

Name:
- [ ] Code is maintainable and reusable, reuses existing code and infrastructure where appropriate, and accomplishes the task’s purpose
- [ ] The tests appropriately test the new code, including edge cases
- [ ] You have tried to break the code

If JIRA tests were used to supplement or replace automated tests:
- [ ] JIRA tests have been run and pass
- [ ] You agree with the justification for use of JIRA tests or have provided input on why you disagree

2017-12-13 20:41 UTC, lukoktonos requested changes
After a code with a dot is added, the dispaly shows the altered format rather than the one with dots:

![image](https://user-images.githubusercontent.com/14879344/33961426-08fc7ba8-e01c-11e7-9006-f7c897d33686.png)

It seems that there needs to be another unwrap called as the codes are passed from `data_criteria.js.coffee` to `edit_criteria.hbs`.

2017-12-13 21:20 UTC, c-monkey commented
Luke please give repro steps. Perhaps you didn't do a hard refresh of your browser?

2017-12-14 12:57 UTC, lukoktonos submitted a review, later dismissed
Looks like it did just need a hard refresh.  Showing appropriately now.  

Everything looks good--JIRA test passes.

2017-12-14 14:43 UTC, mayerm94 requested changes
Luke's screenshot above was correct, if you hard reload it fixes the patient temporarily but when you close a patient and reopen it the 1^p2 2^p2 incorrect format comes back

2018-01-09 16:45 UTC, c-monkey commented
this work is being discarded; will be replaced by preventing the user from entering dots in the name

2018-01-09 16:45 UTC, closed without merging