Bonnie 1203
MeasureAuthoringTool/bonnie pull request #916
Opened 2017-12-15 17:52 UTC by jbradl11

Pull requests into Bonnie require the following. Submitter and reviewer should :white_check_mark: when done. For items that are not-applicable, note it's not-applicable ("N/A") and :white_check_mark:.

This PR is to address the lack of tests for Bonnie Rake tasks and to remove Rake tasks that no longer provide value.

JIRA Ticket: https://jira.mitre.org/browse/BONNIE-1203

**Submitter:**
- [x] This pull request describes why these changes were made.
- [x] This PR is into the correct branch.
- [x] JIRA ticket for this PR:
- [x] JIRA ticket links to this PR
- [x] Code diff has been done and been reviewed (it **does not** contain: additional white space, not applicable code changes, debug statements, etc.)
- [x] If UI changes have been made, google WAVE plug-in has been executed to ensure no 508 issues were introduced.
- [x] Tests are included and test edge cases
- [x] Tests have been run locally and pass (remember to update Gemfile when applicable)
- [x] Code coverage has not gone down and all code touched or added is covered. 
     * See [front-end testing instructions](https://github.com/projecttacoma/bonnie/wiki/Testing#frontend-testing) for getting coverage for front-end tests
     * In rare situations, this may not be possible or applicable to a PR. In those situations:
         1. Note why this could not be done or is not applicable here: 
         2. Add TODOs in the code noting that it requires a test
         3. Add a JIRA task to add the test and link it here: 
- [x] Automated regression test(s) pass

If JIRA tests were used to supplement or replace automated tests:
- [x] N/A JIRA test links:
- [x] N/A Justification for using JIRA tests:
- [x] N/A JIRA tests have been added to sprint

**Reviewer 1:**

Name:
- [ ] Code is maintainable and reusable, reuses existing code and infrastructure where appropriate, and accomplishes the task’s purpose
- [ ] The tests appropriately test the new code, including edge cases
- [ ] You have tried to break the code

If JIRA tests were used to supplement or replace automated tests:
- [ ] JIRA tests have been run and pass
- [ ] You agree with the justification for use of JIRA tests or have provided input on why you disagree

**Reviewer 2:**

Name:
- [ ] Code is maintainable and reusable, reuses existing code and infrastructure where appropriate, and accomplishes the task’s purpose
- [ ] The tests appropriately test the new code, including edge cases
- [ ] You have tried to break the code

If JIRA tests were used to supplement or replace automated tests:
- [ ] JIRA tests have been run and pass
- [ ] You agree with the justification for use of JIRA tests or have provided input on why you disagree

2017-12-18 15:24 UTC, lukoktonos requested changes

2017-12-18 15:24 UTC, lukoktonos commented on test/rake/bonnie_users_test.rb
> +
Will need to migrate the new test in https://github.com/projecttacoma/bonnie/pull/914 to this file.

2017-12-18 15:24 UTC, lukoktonos commented on lib/tasks/cql_testing.rake
> +end
Should put the newline at the end back in here

2017-12-18 15:24 UTC, lukoktonos commented on test/rake/bonnie_patients_test.rb
> +    # Aseert the before date + a year, equals the new birthdate of the patient and the new start and end dates of the data criteria.
Aseert -> Assert

2017-12-18 15:24 UTC, lukoktonos commented on test/rake/bonnie_helpers_test.rb
> +    copy_value_sets(@dest_user, value_sets_src)
It would be good to have some of the valuesets in `value_sets_hash_dest` not overlap with `value_sets_hash_src` in order to make sure that the rake task isn't clobbering any values.

2017-12-19 16:56 UTC, mayerm94 commented on test/rake/bonnie_patients_test.rb
> +    assert_equal 7, Record.where(measure_ids: hqmf_set_id).count
should also assert that the user_id of the records matches the user's id

2018-01-05 19:12 UTC, edeyoung commented on test/rake/bonnie_helpers_test.rb
> +    copy_value_sets(@dest_user, value_sets_src)
addressed

2018-01-05 19:13 UTC, edeyoung commented on test/rake/bonnie_users_test.rb
> +
addressed (it's in bonnie_patients_test. i didn't do this move - someone else did.)

2018-01-05 19:16 UTC, lukoktonos submitted a review, later dismissed

2018-01-08 17:39 UTC, lukoktonos approved these changes

2018-01-09 19:21 UTC, mayerm94 approved these changes
Approve of commits made by Lizzie since my last review. Branch update required

2018-01-09 21:48 UTC, merged