Cql4bonnie ebr remove msrpoplex observ
MeasureAuthoringTool/bonnie pull request #921
Opened 2018-01-03 17:43 UTC by mayerm94

For episode of care measures, track the population membership per episode, building a new structure, episode_results, that looks just like the population_results but keyed by the episode id.
This makes use of the episode based results for the patient level counts.

Commented out with a TODO in cql_calculator is the filtering out episodes that should not be "observed" because they are in the MSRPOPLEX. The PR that fixes the input box counts for MSRPOPLEX has been cherrypicked in. This will be re introduced in 2.1 with https://github.com/projecttacoma/bonnie/pull/917

The injected ELM to do the observation has been improved to return a list of tuples of the episode and the observed value. This allows us to match the observation with the episode.
Pull requests into Bonnie require the following. 

Submitter and reviewer should :white_check_mark: when done. For items that are not-applicable, note it's not-applicable ("N/A") and :white_check_mark:.

**Submitter:**
- [x] This pull request describes why these changes were made.
- [x] This PR is into the correct branch.
- [x] JIRA ticket for this PR: https://jira.mitre.org/browse/BONNIE-1234 https://oncprojectracking.healthit.gov/support/browse/BONNIE-402
- [] JIRA ticket links to this PR
- [x] Code diff has been done and been reviewed (it **does not** contain: additional white space, not applicable code changes, debug statements, etc.)
- [x] If UI changes have been made, google WAVE plug-in has been executed to ensure no 508 issues were introduced. NA
- [x] Tests are included and test edge cases
- [x] Tests have been run locally and pass (remember to update Gemfile when applicable)
- [ ] Code coverage has not gone down and all code touched or added is covered. 
     * See [front-end testing instructions](https://github.com/projecttacoma/bonnie/wiki/Testing#frontend-testing) for getting coverage for front-end tests
     * In rare situations, this may not be possible or applicable to a PR. In those situations:
         1. Note why this could not be done or is not applicable here: 
         2. Add TODOs in the code noting that it requires a test
         3. Add a JIRA task to add the test and link it here: 
- [x] Automated regression test(s) pass Only regression reported by the script is the buggy patient that is described in the external JIRA ticket

If JIRA tests were used to supplement or replace automated tests:
- [x] JIRA test links: NA
- [x] Justification for using JIRA tests: NA
- [x] JIRA tests have been added to sprint NA

**Reviewer 1:**

Name:
- [ ] Code is maintainable and reusable, reuses existing code and infrastructure where appropriate, and accomplishes the task’s purpose
- [ ] The tests appropriately test the new code, including edge cases
- [ ] You have tried to break the code

If JIRA tests were used to supplement or replace automated tests:
- [ ] JIRA tests have been run and pass
- [ ] You agree with the justification for use of JIRA tests or have provided input on why you disagree

**Reviewer 2:**

Name:
- [ ] Code is maintainable and reusable, reuses existing code and infrastructure where appropriate, and accomplishes the task’s purpose
- [ ] The tests appropriately test the new code, including edge cases
- [ ] You have tried to break the code

If JIRA tests were used to supplement or replace automated tests:
- [ ] JIRA tests have been run and pass
- [ ] You agree with the justification for use of JIRA tests or have provided input on why you disagree

2018-01-03 19:21 UTC, hossenlopp commented
Rebased and removed the OBSERV box count commit.

2018-01-04 21:12 UTC, lukoktonos commented on app/assets/javascripts/cql_calculator.js.coffee
> +      population_results = @handlePopulationValues(@createPatientPopulationValues(population, results, patient, observation_defs))
One of these functions does `@handlePopulationValues` inside of it, and for the other, it is done outside of the function.  It may be clearer to have them both do the same thing.

2018-01-04 21:12 UTC, lukoktonos commented on app/assets/javascripts/cql_calculator.js.coffee
> +    popIndex = population.get('index')
This assignment seems to be clobbered down below on line 286.  I think this line can be removed.

2018-01-04 21:12 UTC, lukoktonos commented on app/assets/javascripts/cql_calculator.js.coffee
> +        popIndex = population.getPopIndexFromPopName(popCode)
This re-uses the `popIndex` variable name from line 212--it might be better to have them be different, even though it technically doesn't cause any problems.

2018-01-04 21:12 UTC, losborne commented on app/assets/javascripts/cql_calculator.js.coffee
> +          if Array.isArray(values)
Should there be an `else` block here that throws an Exception in case `values` isn't an Array?

2018-01-04 21:12 UTC, losborne commented on app/assets/javascripts/cql_calculator.js.coffee
> +      else if popCode == 'OBSERV' && observation_defs?.length > 0
Should there be an `else` block to correspond to this that throws an exception if `popCode == 'OBSERV' && observation_defs?.length <= 0`?

2018-01-04 21:14 UTC, c-monkey requested changes
https://oncprojectracking.healthit.gov/support/browse/BONNIE-402 is resolved. Tests pass. I didn't find any runtime errors but do have the 1 piece of unexecuted code.

2018-01-04 21:14 UTC, c-monkey commented on app/assets/javascripts/cql_calculator.js.coffee
> +            # else create a new episode_result structure
This else statement doesn't do anything. Is this line missing from the end?

`episode_results[episodeId] = newEpisode`

I don't have a measure to test this because `popCodesInPopulation` always has something before OBSERV as that is the 8th population code in `Thorax.Models.Measure.allPopulationCodes`

Technically a bug, but I'm not sure if it's reachable code.

2018-01-09 20:14 UTC, c-monkey approved these changes
Tests pass, no regressions, ONC JIRA issue resolved.

2018-01-09 20:35 UTC, lukoktonos approved these changes
Changes look good.

2018-01-09 21:23 UTC, merged