BONNIE-1248
MeasureAuthoringTool/bonnie pull request #935
Opened 2018-02-06 20:26 UTC by c-monkey

Back end `patient_builder_test` - replace QDM with CQL-based fixtures

Pull requests into Bonnie require the following. Submitter and reviewer should :white_check_mark: when done. For items that are not-applicable, note it's not-applicable ("N/A") and :white_check_mark:.

**Submitter:**
- [X] This pull request describes why these changes were made.
- [X] This PR is into the correct branch.
- [X] JIRA ticket for this PR: https://jira.mitre.org/browse/BONNIE-1248
- [ ] JIRA ticket links to this PR
- [X] Code diff has been done and been reviewed (it **does not** contain: additional white space, not applicable code changes, debug statements, etc.)
- [X] If UI changes have been made, google WAVE plug-in has been executed to ensure no 508 issues were introduced.
- [X] Tests are included and test edge cases
- [X] Tests have been run locally and pass (remember to update Gemfile when applicable)
- [X] Code coverage has not gone down and all code touched or added is covered. 
     * In rare situations, this may not be possible or applicable to a PR. In those situations:
         1. Note why this could not be done or is not applicable here: 
         2. Add TODOs in the code noting that it requires a test
         3. Add a JIRA task to add the test and link it here: 
- [X] Automated regression test(s) pass

If JIRA tests were used to supplement or replace automated tests:
- [X] JIRA test links: N/A
- [X] Justification for using JIRA tests: N/A
- [X] JIRA tests have been added to sprint  N/A

**Reviewer into feature branch**

Name: @losborne 
- [ ] Code is maintainable and reusable, reuses existing code and infrastructure where appropriate, and accomplishes the task’s purpose
- [ ] The tests appropriately test the new code, including edge cases
- [ ] You have tried to break the code

If JIRA tests were used to supplement or replace automated tests:
- [X] JIRA tests have been run and pass  N/A
- [X] You agree with the justification for use of JIRA tests or have provided input on why you disagree  N/A

2018-02-06 21:58 UTC, losborne commented on test/test_helper.rb
> +require 'rake'
Why was this line added?  The tests seem to pass for me without it.

2018-02-06 22:01 UTC, c-monkey commented on test/test_helper.rb
> +require 'rake'
For some reason it is required for me to run tests in the RubyMine debugger, as a known requirement. I don't mind removing it from this PR if you think it's problematic.

2018-02-06 22:02 UTC, losborne commented on test/test_helper.rb
> +require 'rake'
Ah OK--tests work either way for me, so I don't mind.  Was just curious.

2018-02-06 22:14 UTC, lukoktonos requested changes
It looks like a couple of lines lost coverage with the updates:

![image](https://user-images.githubusercontent.com/14879344/35886863-723313b0-0b60-11e8-95f1-aba9e35ca924.png)
![image](https://user-images.githubusercontent.com/14879344/35886869-7f8ed440-0b60-11e8-8c41-27f34b9557d1.png)

EDIT: It was actually the other way around--coverage was _added_ for those two lines instead of removed.

2018-02-07 18:08 UTC, lukoktonos approved these changes
Looks good.

2018-02-07 18:24 UTC, c-monkey commented
(I couldn't reproduce Luke's issue, and neither could he, so he approved the PR)

2018-02-14 21:40 UTC, merged