Updated backend tests from QDM to CQL. Adjusted the test_helper to re…
MeasureAuthoringTool/bonnie pull request #936
Opened 2018-02-08 17:16 UTC by jbradl11

…ad in all json files in a directory. Updated User model for cql measures.

Pull requests into Bonnie require the following. Submitter and reviewer should :white_check_mark: when done. For items that are not-applicable, note it's not-applicable ("N/A") and :white_check_mark:.

**Submitter:**
- [x] This pull request describes why these changes were made.
- [x] This PR is into the correct branch.
- [x] JIRA ticket for this PR: https://jira.mitre.org/browse/BONNIE-1254
- [ ] JIRA ticket links to this PR
- [x] Code diff has been done and been reviewed (it **does not** contain: additional white space, not applicable code changes, debug statements, etc.)
- [x] If UI changes have been made, google WAVE plug-in has been executed to ensure no 508 issues were introduced.
- [x] Tests are included and test edge cases
- [x] Tests have been run locally and pass (remember to update Gemfile when applicable)
- [x] Automated regression test(s) pass

If JIRA tests were used to supplement or replace automated tests:
- [x] JIRA test links: N/A
- [x] Justification for using JIRA tests: N/A
- [x] JIRA tests have been added to sprint: N/A

**Reviewer 1:**

Name:
- [ ] Code is maintainable and reusable, reuses existing code and infrastructure where appropriate, and accomplishes the task’s purpose
- [ ] The tests appropriately test the new code, including edge cases
- [ ] You have tried to break the code

If JIRA tests were used to supplement or replace automated tests:
- [ ] JIRA tests have been run and pass
- [ ] You agree with the justification for use of JIRA tests or have provided input on why you disagree

**Reviewer 2:**

Name:
- [ ] Code is maintainable and reusable, reuses existing code and infrastructure where appropriate, and accomplishes the task’s purpose
- [ ] The tests appropriately test the new code, including edge cases
- [ ] You have tried to break the code

If JIRA tests were used to supplement or replace automated tests:
- [ ] JIRA tests have been run and pass
- [ ] You agree with the justification for use of JIRA tests or have provided input on why you disagree

2018-02-08 20:27 UTC, lukoktonos requested changes
Other than the rubocop errors, only 1 change requested.

2018-02-08 20:27 UTC, losborne commented on test/functional/patients_controller_test.rb
> +    cql_measures_set = File.join("cql_measures")
`cql_measures_set = File.join("cql_measures", "**")`

See comment below for `add_collection()`

2018-02-08 20:27 UTC, losborne commented on test/test_helper.rb
> +    Dir.glob(File.join(Rails.root, 'test', 'fixtures', collection, '**', '*.json')).each do |json_fixture_file|
I think it makes more sense to just include `'**'` in the call above rather than automatically loading all sub-directories, since most of the time we are just loading 1 file.

2018-02-08 20:31 UTC, c-monkey commented on test/functional/admin_users_controller_test.rb
>      # The following tests greater than 6 months, but 3 measures
"3" in this comment is out of date.

2018-02-09 18:59 UTC, lukoktonos approved these changes

2018-02-15 17:18 UTC, mayerm94 requested changes

2018-02-15 17:18 UTC, mayerm94 commented on test/functional/patients_controller_test.rb
> -  test "export patients" do
Is the spirit of this test mirrored somewhere else?

2018-02-15 17:18 UTC, mayerm94 commented on test/functional/registrations_controller_test.rb
> -    assert_equal false, @user.crosswalk_enabled
I don't see anywhere where the toggling of crosswalk_enabled is tested. Crosswalk_enabled is still a field on the user model so we should probably still be testing it

2018-02-19 22:42 UTC, jbradl11 commented on test/functional/registrations_controller_test.rb
> -    assert_equal false, @user.crosswalk_enabled
I believe this test is testing QDM Measure specific features. I don't believe CQL Measures have '.map_fns' which is used a little further down. Also, I don't believe we use ".crosswalk_enabled" anymore (no user on production has that flag enabled) and should be removed eventually from the model.

2018-02-20 15:27 UTC, mayerm94 requested changes

2018-02-20 15:27 UTC, mayerm94 commented on test/functional/patients_controller_test.rb
> +    records_set = File.join("records", "base_set")
Records base set is not going to exist, load from records, CMS134v6

2018-02-20 19:19 UTC, mayerm94 approved these changes

2018-02-21 14:28 UTC, merged