Episode based population relevance calculations
MeasureAuthoringTool/bonnie pull request #937
Opened 2018-02-08 20:16 UTC by mayerm94

When there are episode_results, calculate population_relevance based on all episode_results. Any EOC measure can be used to test this, look at hmdmlantana CMS333 for a good example.

Pull requests into Bonnie require the following. Submitter and reviewer should :white_check_mark: when done. For items that are not-applicable, note it's not-applicable ("N/A") and :white_check_mark:.

**Submitter:**
- [x] This pull request describes why these changes were made.
- [x] This PR is into the correct branch.
- [x] JIRA ticket for this PR: https://jira.mitre.org/browse/BONNIE-1272
- [ ] JIRA ticket links to this PR
- [x] Code diff has been done and been reviewed (it **does not** contain: additional white space, not applicable code changes, debug statements, etc.)
- [x] If UI changes have been made, google WAVE plug-in has been executed to ensure no 508 issues were introduced. NA
- [x] Tests are included and test edge cases
- [ ] Tests have been run locally and pass (remember to update Gemfile when applicable)
- [ ] Code coverage has not gone down and all code touched or added is covered. 
     * In rare situations, this may not be possible or applicable to a PR. In those situations:
         1. Note why this could not be done or is not applicable here: 
         2. Add TODOs in the code noting that it requires a test
         3. Add a JIRA task to add the test and link it here: 
- [x] Automated regression test(s) pass

If JIRA tests were used to supplement or replace automated tests:
- [x] JIRA test links: NA
- [x] Justification for using JIRA tests: NA
- [x] JIRA tests have been added to sprint NA

**Reviewer 1:**

Name:
- [ ] Code is maintainable and reusable, reuses existing code and infrastructure where appropriate, and accomplishes the task’s purpose
- [ ] The tests appropriately test the new code, including edge cases
- [ ] You have tried to break the code

If JIRA tests were used to supplement or replace automated tests:
- [ ] JIRA tests have been run and pass
- [ ] You agree with the justification for use of JIRA tests or have provided input on why you disagree

**Reviewer 2:**

Name:
- [ ] Code is maintainable and reusable, reuses existing code and infrastructure where appropriate, and accomplishes the task’s purpose
- [ ] The tests appropriately test the new code, including edge cases
- [ ] You have tried to break the code

If JIRA tests were used to supplement or replace automated tests:
- [ ] JIRA tests have been run and pass
- [ ] You agree with the justification for use of JIRA tests or have provided input on why you disagree

2018-02-08 23:58 UTC, hossenlopp requested changes
Looks good. Just a few small suggestions.

2018-02-08 23:58 UTC, hossenlopp commented on app/assets/javascripts/cql_calculator.js.coffee
> +          population_relevance = @_populationRelevanceForAllEpisodes(episode_results)
A comment explaining that the two sides of this if are for episode based and patient based measures could improve readability.

2018-02-08 23:58 UTC, hossenlopp commented on spec/javascripts/cql_calculator_spec.js.coffee
> +    it 'correctly builds population_relevance for multiple episodes in all populations', ->
I'd suggest having a test with the tricky DENEXCP issue that was reported.

2018-02-09 14:44 UTC, hossenlopp requested changes
Just got a test suggestion.

2018-02-09 14:44 UTC, hossenlopp commented on spec/javascripts/cql_calculator_spec.js.coffee
> +        episode1: {IPP: 3, DENOM: 0, DENEX: 0, DENEXCEP: 1, NUMER: 0, NUMEX: 0},
I just noticed another thing. The episode results should just be 1 or 0. This test seems odd because this is testing DENEXCEP to not be relevant. It would be impossible for `episode1` to have a 1 in DENEXCEP because it is 0 in the DENEX. So therefore it's showing not relevant.

I think the DENEXCEP issue test case would be:
```coffee
episode1: {IPP: 1, DENOM: 1, DENEX: 0, DENEXCEP: 0, NUMER: 1, NUMEX: 0}, #DENEXCEP is NOT relevant 
episode2: {IPP: 1, DENOM: 1, DENEX: 0, DENEXCEP: 0, NUMER: 0, NUMEX: 0}, #DENEXCEP is relevant 
episode3: {IPP: 1, DENOM: 1, DENEX: 1, DENEXCEP: 0, NUMER: 0, NUMEX: 0}  #DENEXCEP is NOT relevant 
```

2018-02-09 17:14 UTC, mayerm94 commented on spec/javascripts/cql_calculator_spec.js.coffee
> +        episode1: {IPP: 3, DENOM: 0, DENEX: 0, DENEXCEP: 1, NUMER: 0, NUMEX: 0},
Good point, doesn't make sense to have results >1 given that each represents a SINGLE episode

2018-02-09 18:14 UTC, hossenlopp approved these changes

2018-02-12 02:10 UTC, jbradl11 reviewed
Code looks good and tests pass. I want to sit down with you to do a final review of the functionality before I approve it (on Wednesday)

2018-02-14 15:33 UTC, jbradl11 approved these changes
Code looks good. Tests pass. Manually checked the fix on a patient with multiple episodes.

2018-02-14 16:43 UTC, merged