Cql testing overhaul old cql to new cql backend
MeasureAuthoringTool/bonnie pull request #955
Opened 2018-03-09 14:19 UTC by losborne

This PR is to update any back-end tests that were using non-core CQL fixtures to use the core ones when possible.  
Some tests were special cases and thus the related fixtures were moved into the special directory. Unused fixtures were then deleted.
In order to use new cql_measure_export fixtures, some vcr cassettes were re-recorded.

As part of updating the tests, there were a couple of non-test code changes that made sense to make:

*Non-Test changes:*
- The patient_export rake task was updated to use `CqlMeasure` rather than `Measure` along with the test.
- Refactor test_helper.rb and cql_testing.rake to remove duplicated functions (that were different, predictably).

Pull requests into Bonnie require the following. Submitter and reviewer should :white_check_mark: when done. For items that are not-applicable, note it's not-applicable ("N/A") and :white_check_mark:.

**Submitter:**
- [x] This pull request describes why these changes were made.
- [x] This PR is into the correct branch.
- [x] JIRA ticket for this PR: https://jira.mitre.org/browse/BONNIE-1255
- [ ] JIRA ticket links to this PR
- [x] Code diff has been done and been reviewed (it **does not** contain: additional white space, not applicable code changes, debug statements, etc.)
- [x] If UI changes have been made, google WAVE plug-in has been executed to ensure no 508 issues were introduced. N/A
- [x] Tests are included and test edge cases
- [x] Tests have been run locally and pass (remember to update Gemfile when applicable)
- [x] Code coverage has not gone down and all code touched or added is covered. 

| Branch | Coverage |
| -- | -- |
| cql_testing_overhaul_old_cql_to_new_cql_backend  | 1472 / 1796 LOC (81.96%) covered. |
| cql_testing_overhaul  | 1434 / 1784 LOC (80.38%) covered. |

- [x] Automated regression test(s) pass

If JIRA tests were used to supplement or replace automated tests:
- [x] JIRA test links: N/A
- [x] Justification for using JIRA tests: N/A
- [x] JIRA tests have been added to sprint N/A

**Reviewer 1:**

Name: @c-monkey 
- [ ] Code is maintainable and reusable, reuses existing code and infrastructure where appropriate, and accomplishes the task’s purpose
- [ ] The tests appropriately test the new code, including edge cases
- [ ] You have tried to break the code

If JIRA tests were used to supplement or replace automated tests:
- [x] JIRA tests have been run and pass N/A
- [x] You agree with the justification for use of JIRA tests or have provided input on why you disagree

**Reviewer 2:**

Name: @mayerm94
- [ ] Code is maintainable and reusable, reuses existing code and infrastructure where appropriate, and accomplishes the task’s purpose
- [ ] The tests appropriately test the new code, including edge cases
- [ ] You have tried to break the code

If JIRA tests were used to supplement or replace automated tests:
- [x] JIRA tests have been run and pass N/A
- [x] You agree with the justification for use of JIRA tests or have provided input on why you disagree N/A

2018-03-12 13:23 UTC, mayerm94 commented on lib/tasks/bonnie.rake
> -      raise "#{ENV['HQMF_SET_ID']} hqmf_set_id not found" unless measure = Measure.find_by(user_id: user._id, hqmf_set_id: ENV['HQMF_SET_ID'])
We need to support QDM measures for patient export. You can add a command-line option for measure type and do something like this `      # Check if MEASURE_TYPE is a CQL Based Measure
      if ENV['MEASURE_TYPE'] == 'CQL'
        raise "#{user_measure} not found" unless measure = CqlMeasure.find_by(user_id: user._id, hqmf_set_id: user_measure)
      else
        raise "#{user_measure} not found" unless measure = Measure.find_by(user_id: user._id, hqmf_set_id: user_measure)
      end`

Note, this will require the modification of the export patient task documentation on the wiki

2018-03-12 13:29 UTC, hossenlopp commented on lib/tasks/bonnie.rake
> -      raise "#{ENV['HQMF_SET_ID']} hqmf_set_id not found" unless measure = Measure.find_by(user_id: user._id, hqmf_set_id: ENV['HQMF_SET_ID'])
I don't believe we need to support QDM-logic measures. The bonnie prior branch needs to support it.

2018-03-12 14:11 UTC, mayerm94 commented on lib/tasks/bonnie.rake
> -      raise "#{ENV['HQMF_SET_ID']} hqmf_set_id not found" unless measure = Measure.find_by(user_id: user._id, hqmf_set_id: ENV['HQMF_SET_ID'])
If we can't have traces of the Measure type in the master branch then the patient import rake task will also need to be modified (see line 292). The patient import and export rake tasks do not yet exist on bonnie-prior, so these should be copied over to a PR into bonnie-prior before QDM Measure patient export is removed since all patient transfers from prior to production require QDM Measure patient export functionality.

2018-03-13 11:51 UTC, edeyoung commented on lib/tasks/bonnie.rake
> -      raise "#{ENV['HQMF_SET_ID']} hqmf_set_id not found" unless measure = Measure.find_by(user_id: user._id, hqmf_set_id: ENV['HQMF_SET_ID'])
how did you do QDM measure patient exports if these tasks don't exist on bonnie-prior? How did you get the QDM based patients previously? Or did you snag the snapshot of the prior db, but use this branch to get the info you needed?

If the latter, yes, let's definitely move these capabilities into bonnie-prior, and then let's remove the Measure type from here (so in the spot you noted).

@losborne can you put together the PR into bonnie master? I don't believe that should take much time.

2018-03-13 12:24 UTC, mayerm94 commented on lib/tasks/bonnie.rake
> -      raise "#{ENV['HQMF_SET_ID']} hqmf_set_id not found" unless measure = Measure.find_by(user_id: user._id, hqmf_set_id: ENV['HQMF_SET_ID'])
Q: how did you do QDM measure patient exports if these tasks don't exist on bonnie-prior? 
A: I used a bonnie-prior DB snapshot and used the rake task on the master branch
Q: How did you get the QDM based patients previously?
A: I used a bonnie-prior DB snapshot and used the rake task on the master branch
Q: did you snag the snapshot of the prior db, but use this branch to get the info you needed?
A: Yes

2018-03-13 17:21 UTC, losborne commented on lib/tasks/bonnie.rake
> -      raise "#{ENV['HQMF_SET_ID']} hqmf_set_id not found" unless measure = Measure.find_by(user_id: user._id, hqmf_set_id: ENV['HQMF_SET_ID'])
@lizzie @mayerm94 @hossenlopp made PR into bonnie-prior (https://github.com/projecttacoma/bonnie/pull/959) and updated this PR. Not that bonnie-prior travis is currently failing due to nokogiri, but tests are passing.

2018-03-13 21:07 UTC, hossenlopp requested changes
There are a bunch of measures in the `special_measures` folder that should be `deprecated_measures`. There are a few tests that still need updating to use the new fixture sets.

`test/unit/models/record_test.rb` is one that I could not comment on directly.

It should be noted that all of the special_measures are missing from backend fixtures in the base branch and this branch. I am working on a PR to fix that.

2018-03-13 21:07 UTC, hossenlopp commented on test/functional/measures_controller_test.rb
> +      measure_file = fixture_file_upload(File.join('test','fixtures', 'cql_measure_exports', 'special_measures', 'CMS169_v5_4_Artifacts_with_special_chars.zip'), 'application/xml')
I think the fixture for this test belongs in the `deprecated_measures` folder.

2018-03-13 21:07 UTC, hossenlopp commented on test/functional/measures_controller_test.rb
> +      measure_file = fixture_file_upload(File.join('test', 'fixtures', 'cql_measure_exports', 'special_measures', 'IETCQL_v5_0_Artifacts.zip'), 'application/xml')
I think the fixture for this test belongs in the `deprecated_measures` folder.

2018-03-13 21:07 UTC, hossenlopp commented on test/functional/measures_controller_test.rb
> +    update_measure_file = fixture_file_upload(File.join('test', 'fixtures', 'cql_measure_exports', 'special_measures', 'IETCQL_v5_0_Artifacts_HQMF_SetId_Mismatch.zip'), 'application/xml')
I think the fixture for this test belongs in the `deprecated_measures` folder.

2018-03-13 21:07 UTC, hossenlopp commented on test/functional/measures_controller_test.rb
> +    measure_file = fixture_file_upload(File.join('test','fixtures', 'cql_measure_exports', 'special_measures', 'IETCQL_v5_0_missing_vs_oid_Artifacts.zip'), 'application/xml')
I think the fixture for this test belongs in the `deprecated_measures` folder.

2018-03-13 21:07 UTC, hossenlopp commented on test/functional/measures_controller_test.rb
> +    measure_file = fixture_file_upload(File.join('test','fixtures', 'cql_measure_exports', 'special_measures', 'IETCQL_v5_0_initial_Artifacts.zip'), 'application/xml')
I think the fixture for this test belongs in the `deprecated_measures` folder.

2018-03-13 21:07 UTC, hossenlopp commented on test/functional/measures_controller_test.rb
> +    update_measure_file = fixture_file_upload(File.join('test','fixtures', 'cql_measure_exports', 'special_measures', 'IETCQL_v5_0_updates_Artifacts.zip'), 'application/xml')
I think the fixture for this test belongs in the `deprecated_measures` folder.

2018-03-13 21:07 UTC, hossenlopp commented on test/functional/measures_controller_test.rb
> +    measure_file = fixture_file_upload(File.join('test','fixtures', 'cql_measure_exports', 'special_measures', 'IETCQL_v5_0_bad_hqmf_Artifacts.zip'), 'application/xml')
I think the fixture for this test belongs in the `deprecated_measures` folder.

2018-03-13 21:07 UTC, hossenlopp commented on test/functional/measures_controller_test.rb
> +    assert_equal true, FileUtils.identical?(File.join(@error_dir, (Dir.entries(@error_dir).select { |f| f.end_with?('.xmlorzip') })[0]), File.join('test', 'fixtures', 'cql_measure_exports', 'special_
I think the fixture for this test belongs in the `deprecated_measures` folder.

2018-03-13 21:07 UTC, hossenlopp commented on test/rake/cql_test.rb
> +    @cql_mat_export_drc = File.new File.join('test', 'fixtures', 'cql_measure_exports', 'special_measures', 'CMS26v5_Artifacts_direct_reference_code.zip')
This should be updated to use a new fixture. The special_measures are missing on the branch at the moment.

2018-03-13 23:00 UTC, losborne commented
@hossenlopp for `test/unit/models/record_test.rb`, do you mean to move those patients into one of the core/special/deprecated directories? Those patients seem to be ones that can't be created directly from the UI, so it doesn't necessarily make sense to have them sitting on a bonnie-fixtures account.

2018-03-14 11:09 UTC, hossenlopp commented
I would consider them deprecated since we cannot have them in the bonnie-fixtures account.

2018-03-14 17:39 UTC, losborne commented
Regression test repeated at this stage and shows no regressions.

2018-03-19 15:21 UTC, hossenlopp requested changes
record_test.rb is using a special set fixture that does not exist.

2018-03-19 15:21 UTC, hossenlopp commented on test/unit/models/record_test.rb
> +    records_set = File.join("records", "deprecated_measures")
CMS72v5 is not a special set fixture. If one of the core or special set fixtues cannot be used for the test, then CMS72v5 should moved to the deprecated_measures folder. Also, the record fixtures should be in a `CMS72v5` folder in `records/deprecated_measures`.

Note that this branch does not have the special set properly exported. I started work on a PR #960 to clean up the fixtures and make sure all were exported properly.

2018-03-19 17:59 UTC, hossenlopp approved these changes

2018-03-19 20:55 UTC, merged