Bonnie 1199 update patient import
MeasureAuthoringTool/bonnie pull request #962
Opened 2018-03-16 15:07 UTC by losborne

This PR integrates the update_facilities_and_diagnoses rake task with the patient import rake task, so that it doesn't need to be run for every patient import.

NOTE: After this PR is integrated, the patient export instructions need to be edited to remove the step to update facilities and diagnoses.

Pull requests into Bonnie require the following. Submitter and reviewer should :white_check_mark: when done. For items that are not-applicable, note it's not-applicable ("N/A") and :white_check_mark:.

**Submitter:**
- [x] This pull request describes why these changes were made.
- [x] This PR is into the correct branch.
- [x] JIRA ticket for this PR: https://jira.mitre.org/browse/BONNIE-1199
- [ ] JIRA ticket links to this PR
- [x] Code diff has been done and been reviewed (it **does not** contain: additional white space, not applicable code changes, debug statements, etc.)
- [x] If UI changes have been made, google WAVE plug-in has been executed to ensure no 508 issues were introduced. N/A
- [x] Tests are included and test edge cases
- [x] Tests have been run locally and pass (remember to update Gemfile when applicable)
- [x] Code coverage has not gone down and all code touched or added is covered. 

Branch | Coverage
-- | --
master | 1566 / 1783 LOC (87.83%) covered.
bonnie-1199-update-patient-import | 1690 / 1919 LOC (88.07%) covered.

- [x] Automated regression test(s) pass

If JIRA tests were used to supplement or replace automated tests:
- [x] JIRA test links: N/A
- [x] Justification for using JIRA tests: N/A
- [x] JIRA tests have been added to sprint N/A

**Reviewer 1:**

Name:
- [ ] Code is maintainable and reusable, reuses existing code and infrastructure where appropriate, and accomplishes the task’s purpose
- [ ] The tests appropriately test the new code, including edge cases
- [ ] You have tried to break the code

If JIRA tests were used to supplement or replace automated tests:
- [x] JIRA tests have been run and pass N/A
- [x] You agree with the justification for use of JIRA tests or have provided input on why you disagree N/A

**Reviewer 2:**

Name:
- [ ] Code is maintainable and reusable, reuses existing code and infrastructure where appropriate, and accomplishes the task’s purpose
- [ ] The tests appropriately test the new code, including edge cases
- [ ] You have tried to break the code

If JIRA tests were used to supplement or replace automated tests:
- [x] JIRA tests have been run and pass N/A
- [x] You agree with the justification for use of JIRA tests or have provided input on why you disagree N/A

2018-03-19 14:42 UTC, mayerm94 requested changes
Should remove the QDM Measure support in the patient import and export tasks inside bonnie.rake IGNORE THIS COMMENT: CHANGES MADE IN OTHER PR INTO CQL_TESTING_OVERHAUL

2018-03-19 16:00 UTC, mayerm94 submitted a review, later dismissed

2018-03-20 00:56 UTC, jbradl11 commented on .rubocop_todo.yml
I think it would be better to not modify these values and instead add the new code to the rubocop ignore file.  Thoughts?

2018-03-20 15:04 UTC, mayerm94 approved these changes
Latest rubocop changes make sense

2018-03-20 15:35 UTC, jbradl11 approved these changes
Code changes makes sense. New unit test looks good and passes.

2018-03-20 16:39 UTC, edeyoung commented
failing due to vulnerability on master (loofah). We will be udpating.

2018-03-20 16:40 UTC, merged