Cql testing overhaul cleanup
MeasureAuthoringTool/bonnie pull request #968
Opened 2018-03-23 17:17 UTC by losborne

This PR is to get the cql_testing_overhaul branch ready to incorporate into version 2.1 by cleaning up unused fixtures and removing some checks for cql that are no longer applicable.

Pull requests into Bonnie require the following. Submitter and reviewer should :white_check_mark: when done. For items that are not-applicable, note it's not-applicable ("N/A") and :white_check_mark:.

**Submitter:**
- [x] This pull request describes why these changes were made.
- [x] This PR is into the correct branch.
- [x] JIRA ticket for this PR: https://jira.mitre.org/browse/BONNIE-1287
- [ ] JIRA ticket links to this PR
- [x] Code diff has been done and been reviewed (it **does not** contain: additional white space, not applicable code changes, debug statements, etc.)
- [x] If UI changes have been made, google WAVE plug-in has been executed to ensure no 508 issues were introduced. N/A
- [x] Tests are included and test edge cases
- [x] Tests have been run locally and pass (remember to update Gemfile when applicable)
- [x] Code coverage has not gone down and all code touched or added is covered. 

Branch | Back End Tests | Front End Tests
-- | -- | --
cql_testing_overhaul | 1462 / 1673 LOC (87.39%) covered. | Statements   : 47.25% ( 4456/9431 ) <br> Branches     : 28.02% ( 1078/3847 ) <br> Functions    : 37.22% ( 692/1859 ) <br> Lines        : 44.57% ( 3938/8835 )
cql_testing_overhaul_cleanup | 1462 / 1673 LOC (87.39%) covered. | Statements   : 47.3% ( 4451/9410 ) <br> Branches     : 27.99% ( 1073/3833 ) <br> Functions    : 37.26% ( 692/1857 ) <br> Lines        : 44.62% ( 3933/8814 )

- [x] Automated regression test(s) pass

If JIRA tests were used to supplement or replace automated tests:
- [x] JIRA test links: N/A
- [x] Justification for using JIRA tests: N/A
- [x] JIRA tests have been added to sprint N/A

**Reviewer 1:**

Name: @mayerm94 
- [ ] Code is maintainable and reusable, reuses existing code and infrastructure where appropriate, and accomplishes the task’s purpose
- [ ] The tests appropriately test the new code, including edge cases
- [ ] You have tried to break the code

If JIRA tests were used to supplement or replace automated tests:
- [x] JIRA tests have been run and pass
- [x] You agree with the justification for use of JIRA tests or have provided input on why you disagree

**Reviewer 2:**

Name: @hossenlopp 
- [ ] Code is maintainable and reusable, reuses existing code and infrastructure where appropriate, and accomplishes the task’s purpose
- [ ] The tests appropriately test the new code, including edge cases
- [ ] You have tried to break the code

If JIRA tests were used to supplement or replace automated tests:
- [x] JIRA tests have been run and pass
- [x] You agree with the justification for use of JIRA tests or have provided input on why you disagree

2018-03-28 17:47 UTC, c-monkey commented
CI failing for bundle-audit; issues resolved in master branch, but not merged into v2.1 yet.

2018-03-28 19:00 UTC, c-monkey approved these changes

2018-03-29 14:55 UTC, hossenlopp requested changes
I found a handful of fixtures that should be cleaned up. I'm still reviewing the rest of the changes.

- test/fixtures/cql_measure_exports/special_measures
-- does not have any of the special measure packages.
-- The Test134 that is there is not a special measure.

- test/fixtures/measure_exports
-- these should probably be moved to deprecated measures

- spec/javascripts/fixtures/json/measure_data/CQL
-- directory should be removed

- spec/javascripts/fixtures/json/records/CQL
-- directory should be removed

2018-03-29 17:56 UTC, hossenlopp approved these changes

2018-03-29 18:11 UTC, c-monkey approved these changes

2018-03-29 21:36 UTC, edeyoung commented
fails due to vulnerabilities which will be addressed before any sort of deploy

2018-03-29 21:36 UTC, merged