adding participation data type
MeasureAuthoringTool/bonnie pull request #978
Opened 2018-04-06 17:28 UTC by c-monkey

- [ ] ❗️**Don't forget to update Gemfile and Gemfile.lock after HDS and cql_qdm_patientapi PRs merged**
- See https://github.com/projectcypress/health-data-standards/pull/567
- See https://github.com/projecttacoma/cql_qdm_patientapi/pull/112
------
- note: shield icon is arbitrary, I'm not sure if we want to keep it or replace with some other icon

Pull requests into Bonnie require the following. Submitter and reviewer should :white_check_mark: when done. For items that are not-applicable, note it's not-applicable ("N/A") and :white_check_mark:.

**Submitter:**
- [X] This pull request describes why these changes were made.
- [X] This PR is into the correct branch.
- [X] JIRA ticket for this PR: https://jira.mitre.org/browse/BONNIE-1379
- [ ] JIRA ticket links to this PR
- [X] Code diff has been done and been reviewed (it **does not** contain: additional white space, not applicable code changes, debug statements, etc.)
- [X] If UI changes have been made, google WAVE plug-in has been executed to ensure no 508 issues were introduced.
- [X] Tests are included and test edge cases
- [X] Tests have been run locally and pass (remember to update Gemfile when applicable)
- [X] Test fixtures updated and documented as necessary ( see [internal wiki](https://gitlab.mitre.org/bonnie/internal-documentation/wikis/testing#test-fixtures) )
- [X] Code coverage has not gone down and all code touched or added is covered. 

Branch | Back End Coverage | Front End Coverage
-- | -- | --
bonnie-v2.1 | 1709 / 1928 LOC (88.64%) covered. | Statements   : 56.95% ( 6823/11981 ) <br> Branches     : 39.97% ( 1791/4481 ) <br> Functions    : 47.24% ( 1120/2371 ) <br> Lines        : 54.69% ( 6106/11165 )
bonnie_1025_participation_data_type | 1709 / 1928 LOC (88.64%) covered. | Statements   : 56.95% ( 6824/11983 ) <br> Branches     : 39.99% ( 1793/4484 ) <br> Functions    : 47.24% ( 1120/2371 ) <br> Lines        : 54.69% ( 6107/11167 )

- [X] Automated regression test(s) pass

If JIRA tests were used to supplement or replace automated tests:
- [X] JIRA test links: N/A
- [X] Justification for using JIRA tests: N/A
- [X] JIRA tests have been added to sprint N/A

**Reviewer 1:**

Name: @holmesie 
- [ ] Code is maintainable and reusable, reuses existing code and infrastructure where appropriate, and accomplishes the task’s purpose
- [ ] The tests appropriately test the new code, including edge cases
- [ ] You have tried to break the code

If JIRA tests were used to supplement or replace automated tests:
- [X] JIRA tests have been run and pass N/A
- [X] You agree with the justification for use of JIRA tests or have provided input on why you disagree N/A

**Reviewer 2:**

Name: @losborne 
- [ ] Code is maintainable and reusable, reuses existing code and infrastructure where appropriate, and accomplishes the task’s purpose
- [ ] The tests appropriately test the new code, including edge cases
- [ ] You have tried to break the code

If JIRA tests were used to supplement or replace automated tests:
- [X] JIRA tests have been run and pass N/A
- [X] You agree with the justification for use of JIRA tests or have provided input on why you disagree N/A

2018-04-06 18:38 UTC, c-monkey commented
The measure in https://oncprojectracking.healthit.gov/support/browse/BONNIE-442 is broken, we'll ask Paul for a new measure to test with and make it into a fixture.

2018-04-18 13:14 UTC, lukoktonos requested changes

2018-04-18 13:14 UTC, losborne commented on spec/javascripts/production_tests/production_patient_builder_spec.js.coffee
> +      bonnie.valueSetsByOid = getJSONFixture('measure_data/special_measures/CMS761/value_sets.json')
It must not affect this test as it is now, but this line should come before `@measure = new ... parse: true` because the parse function of `measure` uses `bonnie.valueSetsByOid`.

2018-04-18 13:19 UTC, losborne commented
Now that we have a working measure, https://gitlab.mitre.org/bonnie/internal-documentation/wikis/testing needs to be updated with the new special measure, and the measure package needs to be added to `test/fixtures/cql_measure_exports/`.

2018-04-18 13:33 UTC, c-monkey commented
great catches, luke! thank you

2018-04-18 16:20 UTC, c-monkey commented
I can't put the test fixture onto bonnie.heathit.gov until we deploy. Will break that out into a separate subtask: https://jira.mitre.org/browse/BONNIE-1400

2018-04-18 16:28 UTC, lukoktonos requested changes
Can we rename `test/fixtures/cql_measure_exports/CMS761_BTParticipation_v5_4_Artifacts-2.zip` to just be `test/fixtures/cql_measure_exports/CMS761_BTParticipation_v5_4_Artifacts.zip`, without the `-2`?

2018-04-18 16:38 UTC, holmesie approved these changes
I'm okay either way about renaming that fixture as suggested by @losborne. As far as everything else is concerned, I think this is good to go now.

2018-04-18 17:10 UTC, c-monkey commented
That was the filename give to me by Paul. I'll export it with the script and see what name comes out.

2018-04-18 17:23 UTC, c-monkey commented
@losborne what do you think about "CMS761v0_bonnie-fixtures@mitre.org_2018-04-17.zip" ? I can just rename it to CMS761v0_v5_4_Artifacts.zip I guess. That would conform with other files in this folder.

2018-04-18 17:25 UTC, edeyoung commented
my vote: rename to CMS761v0_v5_4_Artifacts.zip to conform

2018-04-18 17:25 UTC, losborne commented
@c-monkey I would rename it to match the others

2018-04-18 17:28 UTC, c-monkey commented
Sounds great. Pushed.

2018-04-18 17:39 UTC, lukoktonos approved these changes

2018-04-18 17:41 UTC, merged