Excel export now uses toString for datatype results
MeasureAuthoringTool/bonnie pull request #994
Opened 2018-05-14 15:21 UTC by holmesie

Excel export now uses toString for datatype results. This means that results in the excel export show the data criteria (description, start/stop time/ code) that resulted when a define statement was calculated against a patient.

Example:

![screen shot 2018-05-22 at 11 03 36 am](https://user-images.githubusercontent.com/14923551/40373195-62b0d2c8-5db4-11e8-9ece-90d1861e6f9b.png)

---

Pull requests into Bonnie require the following. Submitter and reviewer should :white_check_mark: when done. For items that are not-applicable, note it's not-applicable ("N/A") and :white_check_mark:.

**Submitter:**
- [x] This pull request describes why these changes were made.
- [x] This PR is into the correct branch.
- [x] JIRA ticket for this PR: https://jira.mitre.org/browse/BONNIE-1442
- [x] JIRA ticket links to this PR
- [x] Code diff has been done and been reviewed (it **does not** contain: additional white space, not applicable code changes, debug statements, etc.)
- [x] If UI changes have been made, google WAVE plug-in has been executed to ensure no 508 issues were introduced.
- [x] Tests are included and test edge cases
- [x] Tests have been run locally and pass (remember to update Gemfile when applicable)
- [x] Test fixtures updated and documented as necessary ( see [internal wiki](https://gitlab.mitre.org/bonnie/internal-documentation/wikis/testing#test-fixtures) )
- [x] Code coverage has not gone down and all code touched or added is covered. 
     * In rare situations, this may not be possible or applicable to a PR. In those situations:
         1. Note why this could not be done or is not applicable here: 
         2. Add TODOs in the code noting that it requires a test
         3. Add a JIRA task to add the test and link it here: 

Branch | Back End Coverage | Front End Coverage
-- | -- | --
master | 1746 / 1964 LOC (88.9%) covered | ![screen shot 2018-05-14 at 11 52 44 am](https://user-images.githubusercontent.com/14923551/40008447-585e0662-576d-11e8-86f1-8ef14e92e8c7.png)
excel_datatype_toString | 1746 / 1964 LOC (88.9%) covered | ![screen shot 2018-05-24 at 2 58 32 pm](https://user-images.githubusercontent.com/14923551/40505670-fee962fe-5f62-11e8-8d2d-360dfd04d4ac.png)

- [x] Automated regression test(s) pass

If JIRA tests were used to supplement or replace automated tests:
- [x] JIRA test links: N/A
- [x] Justification for using JIRA tests: N/A
- [x] JIRA tests have been added to sprint N/A

**Reviewer 1:**

Name: @losborne 
- [x] Code is maintainable and reusable, reuses existing code and infrastructure where appropriate, and accomplishes the task’s purpose
- [x] The tests appropriately test the new code, including edge cases
- [x] You have tried to break the code

If JIRA tests were used to supplement or replace automated tests:
- [x] JIRA tests have been run and pass
- [x] You agree with the justification for use of JIRA tests or have provided input on why you disagree

**Reviewer 2:**

Name: @mayerm94 
- [x] Code is maintainable and reusable, reuses existing code and infrastructure where appropriate, and accomplishes the task’s purpose
- [x] The tests appropriately test the new code, including edge cases
- [x] You have tried to break the code

If JIRA tests were used to supplement or replace automated tests:
- [x] JIRA tests have been run and pass
- [x] You agree with the justification for use of JIRA tests or have provided input on why you disagree

2018-05-15 16:05 UTC, losborne commented on app/assets/javascripts/views/measure_view.js.coffee
> +        ret[libKey][statementKey] = if result.raw && result.raw.length > 0 then result.raw.join('\n').replace(/\n$/, '') else result.final
For arrays, joining on `\n` looks pretty clean.  

Another option is to join on `,\n`, or add `[` and `]` (or perhaps `Array{}` to match CQL syntax) surrounding this string in order to be more explicit that an array is being returned.  

I think I prefer it as-is, but putting some examples of each here for discussion:

As-is:
```
Encounter, Performed: Encounter Inpatient
START: 01/01/2012 8:00 AM
STOP: 01/02/2012 8:00 AM
CODE: SNOMED-CT 8715000
Encounter, Performed: Encounter Inpatient
START: 01/01/2012 8:00 AM
STOP: 01/02/2012 8:00 AM
CODE: SNOMED-CT 183452005
```

Comma/newline join:
```
Encounter, Performed: Encounter Inpatient
START: 01/01/2012 8:00 AM
STOP: 01/02/2012 8:00 AM
CODE: SNOMED-CT 8715000,
Encounter, Performed: Encounter Inpatient
START: 01/01/2012 8:00 AM
STOP: 01/02/2012 8:00 AM
CODE: SNOMED-CT 183452005
```

Comma/newline + brackets:
```
[Encounter, Performed: Encounter Inpatient
START: 01/01/2012 8:00 AM
STOP: 01/02/2012 8:00 AM
CODE: SNOMED-CT 8715000,
Encounter, Performed: Encounter Inpatient
START: 01/01/2012 8:00 AM
STOP: 01/02/2012 8:00 AM
CODE: SNOMED-CT 183452005]
```

2018-05-15 16:43 UTC, holmesie commented on app/assets/javascripts/views/measure_view.js.coffee
> +        ret[libKey][statementKey] = if result.raw && result.raw.length > 0 then result.raw.join('\n').replace(/\n$/, '') else result.final
I also prefer as-is. The only alternative I think might be nicer is an empty line between them, but I don't think that's too much of an improvement.

2018-05-15 17:51 UTC, lukoktonos requested changes
The current code works for QDM datatypes but not other cql types like Code, Quantity, DateTime, etc.  See below for example output for those:

DateTime (this one somewhat works but doesn't match the JIRA task, which would expect something more similar to the CQL syntax)
![image](https://user-images.githubusercontent.com/14879344/40074106-c02d81ee-5846-11e8-9862-1d2e0737b47c.png)
![image](https://user-images.githubusercontent.com/14879344/40074111-c213967e-5846-11e8-8163-0d5ae05b4db1.png)

Code
![image](https://user-images.githubusercontent.com/14879344/40074140-d243fbba-5846-11e8-984e-d9a51e5d4e7d.png)
![image](https://user-images.githubusercontent.com/14879344/40074143-d3c3ab7a-5846-11e8-9293-cdfc3c6869e1.png)

Diagnoses
![image](https://user-images.githubusercontent.com/14879344/40074154-dbd5dbbc-5846-11e8-8892-889c43b4599d.png)

Quantity
![image](https://user-images.githubusercontent.com/14879344/40074163-e1eb0928-5846-11e8-8fc4-4a96cda7c082.png)

Interval
![image](https://user-images.githubusercontent.com/14879344/40074170-e68c0b30-5846-11e8-9c32-990094862eb2.png)

I think we should enumerate the supported types and syntax for each that needs to be supported and have tests for each of them.

2018-05-15 18:11 UTC, holmesie commented
@losborne 
Agreed about Interval, DateTime, and Code. I'll have to investigate a way to deal with those in a different way, because overriding toString is not an option for DateTime.

I think Quantity is fine as is.

I'm confused what you are doing with Diagnoses, it looks you constructed an artificial raw? Those look like the internal Bonnie diagnosis, not the actual Diagnosis<*> type from the cql_qdm_patientapi.

2018-05-15 18:32 UTC, losborne commented
@holmesie Ah right, here is the right Diagnosis result:

<img width="752" alt="image" src="https://user-images.githubusercontent.com/14879344/40076368-b71a2eda-584c-11e8-8bac-cf6d1a85e611.png">

2018-05-15 18:46 UTC, holmesie commented
@losborne Okay, I see.

Is that a special type? Looks like just an array of codes.

2018-05-15 19:03 UTC, lukoktonos commented
@holmesie It is an array of Codes--I'm not sure where `CQL_QDM.Diagnosis` would be used, but that extends from Datatype so should be OK.

2018-05-16 13:01 UTC, edeyoung commented
Some things that came out of yesterday's sprint burndown:

Have some way to represent groupings. We'll get into differentiating tuples/arrays/etc. at a later time.
Differentiate the different "falsey" types - false, null, empty

2018-05-22 19:40 UTC, lukoktonos requested changes
The excel export no longer prints out the datatypes.

Commit 0bde914c:
![image](https://user-images.githubusercontent.com/14879344/40385860-f91c203e-5dd5-11e8-9037-83e19a71cf0a.png)

Commit 951fbd14 (latest as of this comment):
![image](https://user-images.githubusercontent.com/14879344/40385942-4be0a7ea-5dd6-11e8-80d3-6be0f6dc52c4.png)

2018-05-22 19:40 UTC, lukoktonos commented on app/assets/javascripts/helpers/cql_results_helpers.js.coffee
> +  @_prettyResult: (result) ->
This function could use some more coverage for most of the cases.  The current tests only hit `Array` and `CQL_QDM.QDMDatatype`.

2018-05-23 19:09 UTC, lukoktonos requested changes

2018-05-23 19:09 UTC, losborne commented on app/assets/javascripts/helpers/cql_results_helpers.js.coffee
> +    else if result instanceof String
String literals fall through to `JSON.stringify(result, null, 2)`, which produces this:
![image](https://user-images.githubusercontent.com/14879344/40445723-ee673280-5e9a-11e8-8148-00bbe11e943a.png)
![image](https://user-images.githubusercontent.com/14879344/40445729-f37fa7f2-5e9a-11e8-9e68-112992834954.png)

I think there needs to be an `or typeof(result) == 'string'` here.   

It would also be good to add a test to cover this case (it's the only case still uncovered).

2018-05-23 19:17 UTC, holmesie commented on app/assets/javascripts/helpers/cql_results_helpers.js.coffee
> +    else if result instanceof String
Good call! I think with that additional test, the existing tests should hit that branch. Just need to add another `expect`.

2018-05-23 19:27 UTC, holmesie commented on app/assets/javascripts/helpers/cql_results_helpers.js.coffee
> +  @_prettyResult: (result) ->
All lines now covered.

2018-05-23 19:32 UTC, lukoktonos approved these changes
Looks good!

2018-05-24 15:26 UTC, hossenlopp commented on app/assets/javascripts/helpers/cql_results_helpers.js.coffee
> +  #     "Patient": { "raw": "???", "final": "NA", "pretty": "NA" },
Adding this pretty result generation to this function could have some serious performance impacts since this pretty data will be generated on every single calculation. Has the performance impact of this been analyzed? I expect the Opioid measure at least will become considerably slower as a result of this, but I bet the overall initial calculations run on page load will be noticeably affected.

The pretty formatted data isn't needed for every calculation. It is only used for excel export and potential debugging or hybrid measure result views. Perhaps a helper method could be called after calculation, only before the pretty format is needed, that will generate and add it to the existing structure.

2018-05-24 16:52 UTC, mayerm94 commented on app/assets/javascripts/helpers/cql_results_helpers.js.coffee
> +  #     "Patient": { "raw": "???", "final": "NA", "pretty": "NA" },
I ran profiler on a measure with 3 strats with 44 patients. Master = 4220.5 ms Scripting.  This branch 4830.2 ms scripting.

2018-05-24 16:55 UTC, hossenlopp commented on app/assets/javascripts/helpers/cql_results_helpers.js.coffee
> +  #     "Patient": { "raw": "???", "final": "NA", "pretty": "NA" },
Was that for loading an account with that single measure? Or just changing tabs on that measure?

2018-05-24 18:42 UTC, hossenlopp commented on app/assets/javascripts/helpers/cql_results_helpers.js.coffee
> +  @_prettyResult: (result) ->
This function should be public so it can be used to generate pretty results for other calculation results on demand.

2018-05-24 18:53 UTC, holmesie commented on app/assets/javascripts/helpers/cql_results_helpers.js.coffee
> +  @_prettyResult: (result) ->
Right

2018-05-24 19:34 UTC, mayerm94 approved these changes

2018-05-24 19:47 UTC, merged